import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "iceland-overview": {
    // identity sources: Hagstofa Íslands《Mannfjöldinn 1. janúar 2025》：389,444 人。https://hagstofa.is/utgafur/frettasafn/mannfjoldi/mannfjoldinn-1-januar-2025/
    //   核实日 2026-09-07，来源级别 1
    identity:
      "Iceland is an island nation in the North Atlantic, about 100,000 sq km, with a population of about 389,000 as of January 2025 (Statistics Iceland) — the least densely populated country in Europe, with over 60% living in the capital area. It sits exactly on the Mid-Atlantic Ridge, where the North American and Eurasian plates pull apart, and over a mantle hotspot, so volcanism and geothermal activity are intense: about thirty active volcanic systems, with geysers, hot springs and lava fields everywhere. At the same time about a tenth of the country is under ice, giving a landscape of 'fire and ice' together.",
    layout:
      "The centre of Iceland is an uninhabitable highland desert and ice cap, and people and roads are concentrated in a ring around the coast. Route 1, the Ring Road, is about 1,330 km and links most towns and sights. The south-west has the capital area and the geothermal belt; the south coast has waterfalls, black beaches and glacier tongues; the south-east has Vatnajökull, the largest glacier in Europe, and a glacier lagoon; the east and north are fjords and farmland; the north-western Westfjords are the most remote.",
    gettingAround:
      "Almost all international flights land at Keflavík Airport (KEF, about 50 km south-west of Reykjavík). Getting between towns is mainly by car (the Ring Road is paved; the interior 'F-roads' are gravel, need a 4x4 and are open only in summer); there are also a few domestic flights linking Reykjavík with the north, east and Westfjords. Public buses are limited. In winter roads ice over with strong wind — always check road and weather forecasts. Tap water is excellent and drinkable. Power is 230V with the European two-round-pin plug.",
    culture:
      "The official language is Icelandic, and almost everyone speaks fluent English. Society is strongly egalitarian, crime is low, and nature protection is taken seriously. Icelanders use patronymics: the surname is the father's name plus -son / -dóttir, so the phone book is ordered by first name. Bathing in geothermal pools is a national habit, and you must shower thoroughly without a swimsuit before entering a pool (this is clearly required). Tipping is not expected. Prices are very high.",
    seeAndDo:
      "The Golden Circle (the rift at Þingvellir National Park, the Geysir geothermal area, Gullfoss waterfall); on the south coast, Seljalandsfoss and Skógafoss, black beaches, the glacier lagoon and 'Diamond Beach'; the Snæfellsnes peninsula; in the north, the Mývatn geothermal area, Dettifoss, and whale watching at Húsavík; geothermal spas such as the Blue Lagoon. Northern lights in winter (September–March), midnight sun in summer. In recent years the Reykjanes Peninsula has had several eruptions — viewable from a distance but only under official guidance.",
    whenAndTips:
      "June–August has the longest daylight, open interior roads and the best conditions for a Ring Road trip; September–March is aurora season but with short days, poor weather and some roads closed. The weather changes many times a day — dress in layers and carry a windproof, waterproof jacket. When driving, mind the wind on car doors, gravel roads, single-lane bridges and sheep on the road. In volcanic and geothermal areas stay strictly on the paths and follow IMO (the Icelandic Met Office) and local notices. Most foreign visitors travel visa-free for short tourism in the Schengen area or follow Schengen rules.",
  },

  reykjavik: {
    // identity sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   雷克雅未克市镇 139,804（2026-01-01，占全国 394,324 的 35.5%），Hagstofa Íslands 官方稿，级别 1。
    //   https://hagstofa.is/utgafur/frettasafn/mannfjoldi/mannfjoldi-1-januar-2026/
    //   ⚠️ **首都区的合计总人口本轮没能核到一个自洽的官方数**：不同发布给出 244,536（2025-01-01）/ 约 247,000（推算）/ 251,900（正文旧值）/ 264,056（2026 Q1 估计）四个互相矛盾的数字，正文因此只写占比、不改总数，另开 issue，下一轮直接从 Hagstofa PxWeb 表 MAN02005 把 7 个市镇加总。
    identity:
      "Reykjavík is the capital of Iceland, and the northernmost capital of a sovereign state in the world, with a municipal population of about 140,000 at the start of 2026 and, together with the rest of the Capital Region, about 63 per cent of the country. The name means 'smoky bay' in Old Norse — the first settlers saw geothermal steam. The city is small and low-rise, heated by geothermal water, with almost no industrial chimneys.",
    // howItWorks sources: 首都区 251,912 / 全国 394,324（2026-01-01，Hagstofa MAN02005，1 级）。核实 2026-09-12
    howItWorks:
      "Reykjavík is Iceland's capital and a municipality, governed by a council of 23 members who appoint the mayor rather than electing one directly; it had about 140,000 people in 2026, more than a third of the country, while the Capital Region of seven municipalities — Kópavogur, Hafnarfjörður, Garðabær and the rest — held about 252,000 at the start of 2026 (Statistics Iceland), 64 per cent of Iceland, each neighbour with a council of its own. The city is divided into ten districts. The old centre lies at the tip of the peninsula: Laugavegur is the main shopping street, Parliament stands on Austurvöllur, Hallgrímskirkja on the hilltop and the old harbour to the north, and Laugardalur is the district of sports and thermal pools. Addresses give street, number and postcode, and the postcodes 101 to 113 are badges of identity — '101 Reykjavík' means the life of the centre. Iceland has no railway, public transport is Strætó buses alone, the car is daily life, and the whole city is heated by geothermal district heating. Keflavík International Airport lies about 50 km south-west. Newcomers most often go wrong by taking the city of Reykjavík for the whole Capital Region, when more than half its people live in the neighbouring municipalities.",
    layout:
      "Reykjavík is built on a peninsula, sea on three sides, with Mount Esja and distant snow peaks behind it. The old town and harbour are at the northern end of the peninsula, and the main street, Laugavegur, is for shopping and eating; the landmark Hallgrímskirkja church stands on a rise in the middle of the city, with a tower view over the coloured roofs. The city spreads south-east into suburbs.",
    gettingAround:
      "International flights land at Keflavík (KEF), with buses (Flybus, Airport Direct) about 45 minutes to town (there is no train). The city has buses (Strætó), but the centre is compact and walkable. Many people rent a car in Reykjavík and drive the Ring Road. The climate is temperate maritime, moderated by ocean currents: winters are not extremely cold (often around 0°C) but windy with rain and snow and short days; summers are cool with very long daylight.",
    culture:
      "Icelandic is the main language, with widespread English. The city's culture is active in music (several internationally known musicians are from here), literature (a very high number of books published per head) and design. Bathing in public warm pools is a way to socialise, and you must shower naked before entering. Restaurants do not require tipping. Prices are high, and eating out and alcohol are especially expensive.",
    seeAndDo:
      "The tower of Hallgrímskirkja; the Sun Voyager sculpture and the Harpa concert hall by the harbour; the National Museum and the Settlement Exhibition (871±2); shopping on Laugavegur; the Tjörnin pond and City Hall; whale and puffin trips from the old harbour; the city's geothermal beach and pools. Use it as a base for the Golden Circle, the south coast, or the Reykjanes volcanic activity.",
    whenAndTips:
      "June–August has long daylight and the best weather but the most visitors and expensive lodging; September–March you may see the aurora from the edge of the city. It is changeable and windy all year — carry a waterproof. The city is small and most sights are walkable — no need to rush into a rental car, rent it for the Ring Road. Downtown parking is paid and scarce.",
  },

  keflavik: {
    // identity sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   雷克雅内斯拜尔市镇 24,557（2026-07-01，国家登记处 Þjóðskrá 数据，经地方媒体转述，2 级）；凯夫拉维克 + 纳尔兹维克城镇聚落 22,377（2025，Hagstofa，级别 1）。
    //   https://www.vf.is/frettir/ibuathroun-a-sudurnesjum-haegir-a-vexti-og-faekkun-i-reykjanesbae
    //   https://hagstofa.is/utgafur/frettasafn/mannfjoldi/mannfjoldi-eftir-byggdakjornum-og-thettbylisstodum-2025/
    //   **这条是「市镇 vs 城镇聚落」混用的典型**：同一个地名在冰岛有两个官方数，差 2000 多人，不写明是哪一档就没法核。
    identity:
      "Keflavík is a port town on the Reykjanes Peninsula, officially named Reykjanesbær after merging with neighbouring towns, the municipality had about 25,000 people in mid-2026, of which the combined urban settlement of Keflavík and Njarðvík held about 22,000 in 2025. Iceland's international airport is next to it, and most visitors pass through on arrival and departure. The peninsula itself is almost entirely lava field and geothermal ground, and there have been several eruptions nearby since 2021.",
    // howItWorks sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   同 identity 注释。原文停在 2018 年的 15,930，落后四期以上。
    //   https://www.vf.is/frettir/ibuathroun-a-sudurnesjum-haegir-a-vexti-og-faekkun-i-reykjanesbae
    //   https://hagstofa.is/utgafur/frettasafn/mannfjoldi/mannfjoldi-eftir-byggdakjornum-og-thettbylisstodum-2025/
    howItWorks:
      "Keflavík is a town on the Reykjanes peninsula in south-western Iceland; in the mid-1990s it merged with Njarðvík and Hafnir to form the municipality of Reykjanesbær, the combined urban settlement of Keflavík and Njarðvík holding about 22,000 people in 2025 and the whole municipality about 25,000 in mid-2026; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. The name means driftwood bay, and the town grew from the sixteenth century on fishing and fish processing amid a country of basalt rubble and moss. During the Second World War the American military built the airport beside the town, and through the Cold War Naval Air Station Keflavik was an important base for watching the northern seas, the American forces withdrawing in 2006 and the base passing to civil and residential use. Keflavík International Airport lies at the town's edge as Iceland's international gateway, where nearly every flight in and out of the country lands, with Reykjavík about 50 km north-east. Many musicians came from here in the 1960s and 1970s, earning it the nickname of the Beatles town. Newcomers most often go wrong by treating the airport as part of Reykjavík, when it stands in another municipality nearly an hour from the city.",
    layout:
      "Keflavík is on the western coast of the peninsula, with the airport to its south-west. The whole Reykjanes Peninsula is a young black lava platform, almost treeless, with geothermal steam rising from the ground; the famous Blue Lagoon, in the middle of the peninsula, is warm mineral-rich water discharged from a geothermal power station. The southern coast has cliffs, lighthouses and the 'Bridge Between Continents' over a fissure between the American and Eurasian plates.",
    gettingAround:
      "From the airport it is about 45 minutes by bus to Reykjavík. Many people rent a car here to start the Ring Road. The town is walkable. The climate is temperate maritime, and the open peninsula terrain makes it especially windy. Recent volcanic activity has been concentrated in the eastern part of the peninsula (around Grindavík), and roads may close temporarily.",
    culture:
      "Icelandic is the main language, with widespread English. There was a US military base here (left in 2006), leaving some traces and an aviation museum. The town is quiet, based on fishing and airport-related industry. Restaurants do not require tipping.",
    seeAndDo:
      "The Blue Lagoon geothermal spa (book online in advance); the Reykjanes geopark: the bubbling mud pots and fumaroles at Gunnuhver, Lake Grænavatn, the Bridge Between Continents, the Valahnúkamöl cliffs and lighthouse; Lake Kleifarvatn; if there is a safely opened eruption viewpoint, watch from a distance under official guidance. The 'Giant' sculpture and the Viking World museum near the airport.",
    whenAndTips:
      "It is convenient as the first or last stop in Iceland, and the Blue Lagoon is often scheduled for the arrival or departure day. The wind on the peninsula is extreme — take care with car doors. During volcanic activity, follow IMO (the Icelandic Met Office) and civil-protection notices, never enter a closed area, and never approach lava on your own.",
  },

  vik: {
    identity:
      "Vík (in full, Vík í Mýrdal) is the southernmost town in Iceland, with a population of only a few hundred, but because it is right on the Ring Road and surrounded by dense sights it is a key tourist base on the south coast. The town is set between black sea cliffs, green mossy mountains, and the Mýrdalsjökull ice cap to the north, which sits over the Katla volcano.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Vík í Mýrdal (Iceland; village in Mýrdalshreppur municipality with about 750 inhabitants as of 2021, the southernmost village in Iceland, on the Ring Road about 180 km south-east of Reykjavík; the largest settlement for some 70 km around and the service centre for the coast between Skógar and Mýrdalssandur; the black sand beach named among the ten most beautiful beaches on earth by Islands Magazine in 1991, with the Reynisdrangar sea stacks offshore; the wettest coastal town in Iceland with about 2,250 mm of rain a year; the Katla volcano, which last erupted in 1918, with an evacuation plan giving residents little time to reach the hilltop church)
    howItWorks:
      "Vík í Mýrdal is a village on the south coast of Iceland in Mýrdalshreppur municipality with about 750 inhabitants as of 2021, the southernmost settlement in the country; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. Its function is service: along some 70 km of coast between Skógar and Mýrdalssandur this is the only place with fuel, a supermarket and hotels, so nearly everyone on the Ring Road stops here once. The black sand beach and the Reynisdrangar stacks offshore are its famous sight, listed among the ten most beautiful beaches on earth by an American magazine in 1991; but the surf here throws sudden sneaker waves far up the sand, warning signs stand along it, and people are swept out every year. It is the wettest coastal town in Iceland with about 2,250 mm of rain a year. North of the village the Katla volcano lies beneath the Mýrdalsjökull ice cap and last erupted in 1918; an eruption would send meltwater down in very little time, and the church on the hill is the village assembly point. Newcomers most often go wrong by turning their back to the sea for a photograph, which is exactly how people are taken.",
    layout:
      "Vík stretches along one main road, with a white hilltop church that is the landmark and the flood-refuge point. Both sides of the town have black beaches: to the west is the famous Reynisfjara black beach, with columnar basalt cliffs and sea stacks; the beach directly south of the town runs east. North over the pass are the Mýrdalsjökull ice cap and the Sólheimajökull glacier tongue.",
    gettingAround:
      "Vík has no airport with scheduled flights and no train; the Ring Road runs through it, and you arrive by car or tour bus. The town is walkable, but you need a car for the surrounding sights. The climate is temperate maritime, one of the wettest places in Iceland, foggy and windy. In winter roads ice over with strong wind, and the south coast road occasionally closes for wind.",
    culture:
      "Icelandic is the main language, and tourism is well developed, with food and lodging geared to passing visitors. The town's resources are limited, and lodging and restaurant tables are tight in peak season. Restaurants do not require tipping.",
    seeAndDo:
      "Reynisfjara black beach and its columnar basalt (the waves are extremely dangerous — stay well back from the waterline and never turn your back on the sea); the sea arch and lighthouse at Dyrhólaey; the hilltop church for the view; west to Skógafoss, Seljalandsfoss and the Sólheimajökull glacier (hike with a guide); east to the Fjaðrárgljúfur canyon and toward the glacier lagoon.",
    whenAndTips:
      "It can be visited year-round; June–September has relatively good weather and long days. The 'sneaker waves' at Reynisfjara sweep visitors out to sea every year — take the warning signs seriously, keep well back and watch the water. In winter check road.is and vedur.is (road conditions, weather, aurora forecast). The town is small — book lodging well ahead in peak season.",
  },

  hofn: {
    // identity sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   赫本镇（byggðakjarni）1,802（2025）；霍尔纳峡湾市镇（sveitarfélag）2,589（2025）—— **两档不要混用**。2026-09-09 核。
    //   瓦特纳冰原：按**体积**是欧洲最大的冰帽（与瓦特纳冰原国家公园管理局自身表述一致），按**面积**次于俄罗斯新地岛北岛冰帽。原文「欧洲最大的冰川」不带口径。
    //   https://en.wikipedia.org/wiki/Vatnaj%C3%B6kull
    //   **跨系统的不一致**：同一个事实在地形条目 vatnajokull 里带了「按体积算」的限定，在这个城市条目里没带 —— 两套内容各写各的，修一处要顺手搜另一套。
    identity:
      "Höfn (in full, Höfn í Hornafirði — 'höfn' is Icelandic for 'harbour') is a fishing town in south-east Iceland, with a town population of about 1,800 in 2025, on a spit at the mouth of a lagoon, backed by Vatnajökull — by volume the largest ice cap in Europe — and its glacier tongues reaching down between the mountains. It is known for langoustine.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Höfn (Iceland; town in Hornafjörður municipality in the south-east with 1,802 residents in 2025, on a peninsula surrounded by sea on three sides; the name means harbour; founded in 1897 by the merchant Ottó Tuliníus, who moved a trading post from Papós, with growth after the Hornafjarðarbrú bridge of 1961; fishing, particularly langoustine and saltfish, and tourism around Vatnajökull, Europe's largest ice cap by volume, and the nearby glaciers; the annual lobster festival in early July; on the Ring Road about 455 km from Reykjavík, the Almannaskarðsgöng tunnel of 2005 improving winter access; a regional airport with flights to Reykjavík)
    howItWorks:
      "Höfn is a town of Hornafjörður municipality in south-eastern Iceland with about 1,800 residents in 2025; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. The name simply means harbour, and the town stands on a small peninsula with sea on three sides. The merchant Ottó Tuliníus founded it in 1897 by moving a trading post from Papós, and it grew in earnest only after the Hornafjarðarbrú bridge opened in 1961. Fishing is the old trade, known especially for langoustine and saltfish, with a langoustine festival each July. Its other living comes from the ice behind it: Vatnajökull, the largest ice cap in Europe by volume, lies on the heights just north, the Jökulsárlón glacier lagoon about 80 km west, and glacier tourism has made this small town the base of the south-east coast. The Ring Road passes through, Reykjavík lying about 455 km west; the Almannaskarðsgöng tunnel of 2005 eased winter access, and a regional airport flies to Reykjavík. Newcomers most often go wrong by expecting the glacier lagoon beside the town, when it is more than an hour away by road.",
    layout:
      "Höfn is at the end of a low, flat spit, water on three sides, and in good weather you can see the white edge of Vatnajökull and several peaks under the ice caps (including Iceland's highest point, Hvannadalshnúkur) from the town. The Ring Road passes north of the town; between the town and the glacier is an outwash plain and lagoon.",
    gettingAround:
      "Höfn has a small airport (HFN) with a few flights to and from Reykjavík; most people arrive by car on the Ring Road (about 6 hours from Reykjavík, about 2.5 hours from Vík). The town is walkable, but you need a car or a tour for the glacier. The climate is temperate maritime and windy, and the ice cap creates its own local weather.",
    culture:
      "Icelandic is the main language, and the town lives on fishing and tourism. There is a 'Lobster Festival' in late summer. Restaurants do not require tipping. This is one of the sunnier corners of Iceland, though the weather is still changeable.",
    seeAndDo:
      "Use Höfn as a base for the Jökulsárlón glacier lagoon and 'Diamond Beach' (floes washed up on the black sand) and the Fjallsárlón lagoon; glacier hikes and blue ice caves in Vatnajökull National Park (winter, with a certified guide); hiking and basalt waterfalls at Skaftafell; the harbour and lagoon walk in town, and the langoustine.",
    whenAndTips:
      "May–September is best for the Ring Road and glacier hikes; blue ice caves are a November–March activity. For anything on the ice (caves, glacier walks) always go with a certified guide and never go onto the ice alone. The floes and tides at the lagoon are dangerous — do not stand on the ice or get too close to the water. In winter the south-east road closes for strong wind.",
  },

  egilsstadir: {
    // identity sources: 人口：**城镇聚落（byggðakjarni）口径**，不是市镇（Múlaþing）—— 这两档在冰岛差别很大，本库已因混用出过错。冰岛统计局 PxWeb MAN030101 代码 902：2025-01-01 = 2,711（正式发布 2025-10-07）；2026-01-01 数据库初步值 2,719，年度新闻稿未发。原文 2,632 与官方任一年都对不上。按城镇聚落发布的新闻稿通常在同年 10 月初，下一期预计 2026 年 10 月。
    identity:
      "Egilsstaðir is the largest town in eastern Iceland, with a settlement population of 2,711 as of 1 January 2025 (Statistics Iceland), and the transport, service and administrative centre of the eastern fjords region. It sits on Lagarfljót, Iceland's third-largest lake by area — long and thin, and said in local folklore to be home to a 'lake monster'. Around it is one of Iceland's rare large areas of woodland.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Egilsstaðir (Iceland; town in east Iceland on the banks of the Lagarfljót, 2,632 residents in 2024, the largest settlement in the eastern region; formally established only in 1947, though the farmer Jón Bergsson had begun developing the site earlier in the 20th century; growth during the 2004–2008 hydropower and aluminium boom; a crossroads where the main regional routes meet, the area's transport, service and administrative centre, with airport, gymnasium and health clinic; Hallormsstaðaskógur, the biggest forest in Iceland, plus Hengifoss and Skriðuklaustur nearby; subarctic climate with mild summers, a record 29.8 °C in August 2025)
    howItWorks:
      "Egilsstaðir is the largest town in eastern Iceland with 2,632 residents in 2024, on the banks of the Lagarfljót; Iceland has only the state and municipalities, this town belonging to Múlaþing, formed by merger in 2020, which runs schools, planning and local services while the state runs health care and police. It is a very young town: it was formally established only in 1947, before which there was a single farm here, the farmer Jón Bergsson having begun to build up the site early in the twentieth century, and the hydropower and aluminium works of 2004 to 2008 brought a further wave of growth. Its position explains its existence — the main roads of the east meet here, so the airport, the clinic, the secondary school and the government offices are all in this town and people from the fjords around come in to use them. Hallormsstaðaskógur, the largest forest in Iceland, stands on the south shore of the lake, with Hengifoss and the Skriðuklaustur house nearby. Over the pass lies Seyðisfjörður, from which the ferry sails to Denmark and the Faroes. Newcomers most often go wrong by looking for an old town, when this one is younger than many of its residents.",
    layout:
      "Egilsstaðir is on flat ground in a river valley in the eastern interior, with Lagarfljót stretching south-west from the edge of town. The Ring Road passes through; east over the mountains, about 25 minutes, is the fjord port town of Seyðisfjörður (known for its rainbow street and ferry terminal). The town itself is small and practical.",
    gettingAround:
      "Egilsstaðir Airport (EGS) has flights to and from Reykjavík (about 1 hour) and a few regional services to Akureyri. Most people arrive by car on the Ring Road. You need a car for the surrounding fjords and waterfalls. The climate is more continental: drier than the coast, warmer in summer and colder in winter.",
    culture:
      "Icelandic is the main language. The east is one of the most sparsely populated and 'remote'-feeling parts of Iceland, with a slow pace. Seyðisfjörður has an active arts community and an annual music festival. Restaurants do not require tipping.",
    seeAndDo:
      "Hengifoss (one of Iceland's higher waterfalls, with red bands in the rock wall); a drive around Lagarfljót and the Hallormsstaður woods; over the mountains to Seyðisfjörður for the rainbow street and the fjord; north to Dettifoss and Mývatn (about 2 hours); driving the eastern fjords for fishing villages and seabirds.",
    whenAndTips:
      "June–September is best, with snow-free passes and the woods at their greenest. Route 93 to Seyðisfjörður often has snow and fog in winter — check road conditions before setting out. Distances between eastern sights are long and petrol stations are few — keep an eye on the fuel gauge.",
  },

  akureyri: {
    // identity sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   阿克雷里市镇 20,284（2026-01-01，Hagstofa，级别 1 交叉确认）。
    //   埃亚峡湾：通行表述是「冰岛最长的峡湾**之一**」（约 60 公里），**查不到支持绝对「最长」的权威来源**，已降级。2026-09-09 核。
    //   https://en.wikipedia.org/wiki/Eyjafj%C3%B6r%C3%B0ur
    identity:
      "Akureyri is the largest town in northern Iceland, with a population of about 20,000 at the start of 2026, called the 'capital of the north', at the head of Eyjafjörður, one of Iceland's longest fjords, ringed by mountains on three sides. Although it is only about 100 km from the Arctic Circle, its position at the end of a long fjord and the ocean's moderating effect make the climate milder than you might expect, and trees grow well.",
    // howItWorks sources: Wikipedia (2026-09): Akureyri (municipality Akureyrarbær; 11-member council appoints mayor; 20,284 2026; largest outside Capital Region; university 1987; hospital; airport; Hrísey and Grímsey in municipality; Ring Road ~390 km)
    howItWorks:
      "Akureyri is the largest town in Iceland outside the Capital Region, with about 20,000 people in 2026, and is called the 'capital of North Iceland': the municipality is governed by an eleven-member council that appoints the mayor. It has one of the country's two main hospitals, the University of Akureyri founded in 1987, an airport with flights to Reykjavík and an ice-free port where cruise ships call in summer, and it is the service centre of the whole north. The town spreads along the west shore of Eyjafjörður: Hafnarstræti is the main street, the steps of Akureyri church are the point of reference, the botanical garden is among the northernmost in the world, and the Hlíðarfjall ski area lies in the mountains to the west. The islands of Hrísey and Grímsey, the latter on the Arctic Circle, belong to the municipality. The Ring Road to Reykjavík runs about 390 km and is often closed by winter storms, while the flight takes 45 minutes. Addresses give street, number and postcode, beginning with 600. The red traffic lights are heart-shaped, the town's small emblem. Newcomers most often go wrong by taking Akureyri for a small town, when it is the administrative, medical and educational centre of North Iceland.",
    layout:
      "Akureyri is built on the hillside on the west side of the fjord, with the centre and harbour low down and the residential areas climbing the slope. Snow mountains face the town across and at the head of the fjord. The town has the northernmost botanic garden in Iceland. South along the fjord and valley is farmland; east over the mountains is the Mývatn area.",
    gettingAround:
      "Akureyri Airport (AEY) is south of the town, with frequent flights to and from Reykjavík (about 45 minutes), plus a few international flights and regional services. Most people arrive by car on the Ring Road (about 5 hours from Reykjavík). The town has walking and buses. The climate is temperate maritime, drier than the south, with heavy winter snow — it is one of Iceland's ski centres.",
    culture:
      "Icelandic is the main language, with widespread English. Akureyrians identify strongly with the 'capital of the north', and the town has a theatre, a university and an active music scene. The red heart-shaped traffic lights are a local emblem. Restaurants do not require tipping.",
    seeAndDo:
      "The hillside Akureyri church, the botanic garden, the old wooden houses; whale watching from the fjord (humpback, minke); an hour east to the Mývatn geothermal area, Goðafoss and Dettifoss; skiing at Hlíðarfjall in winter; in summer, south to the Ásbyrgi canyon and the Diamond Circle.",
    whenAndTips:
      "June–September is best, with very long daylight. Winter has heavy snow but city life continues, and it is a good place for skiing and the aurora — mountain passes need winter tyres and a road check. Whale watching is possible from both Akureyri and Húsavík, with a higher success rate from Húsavík.",
  },

  husavik: {
    // identity sources: 「欧洲观鲸之都」经查证是当地旅游业的自我宣传口号（多家站点均写「bills itself as」），无官方或独立评选出处，已降级为「当地常自称」。3 级，2026-09-09 核。
    //   https://visitorsguide.is/husavik-the-whale-watching-capital-of-europe/
    //   人口 2,300–2,500 的区间表述本轮未找到更精确的单一官方数，保留区间。
    identity:
      "Húsavík is a fishing town in northern Iceland, with a population of about 2,300, known for whale watching and locally billed as the 'whale-watching capital of Europe' — the food-rich Skjálfandi Bay offshore gives reliable humpback sightings in summer, and sometimes blue whales. The town has an all-timber old church and a dedicated whale museum.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Húsavík (Iceland; town in Norðurþing municipality on the north coast with about 2,300–2,500 residents, on Skjálfandi bay; a centre of whale watching in Iceland because whales of several species enter the bay; the wooden church Húsavíkurkirkja of 1907 the chief landmark; the Húsavík Whale Museum, the Exploration Museum and a Eurovision museum opened in 2021; recorded as the first place in Iceland settled by a Norseman, the Swedish Viking Garðar Svavarsson wintering here around 870; the 2020 film Eurovision Song Contest: The Story of Fire Saga set here, its title song Oscar-nominated; Akureyri within an hour via the Vaðlaheiðargöng tunnel of 2019; flights ended in 2024)
    howItWorks:
      "Húsavík is a town on the north coast of Iceland in Norðurþing municipality with about 2,300 to 2,500 residents; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. The town faces Skjálfandi bay, which several species of whale enter to feed each summer, and this has made it the centre of whale watching in Iceland — the boats go out from the harbour, the whale museum stands on the quay, and the local economy has turned from fishing to tourism on that account. The wooden church of 1907 stands on the slope as the town's mark. By the records this is the first place in Iceland where a Norseman wintered: the Swede Garðar Svavarsson stayed here around 870. A 2020 film about the Eurovision Song Contest was set in the town and its title song was nominated for an Oscar, after which a small museum on the subject opened here. Since the Vaðlaheiðargöng tunnel opened in 2019 Akureyri is an hour away; scheduled flights from the local airport ended in 2024. Newcomers most often go wrong by treating whale watching as a year-round activity, when the boats sail by season and weather.",
    layout:
      "Húsavík is on the eastern shore of Skjálfandi Bay, backed by low hills, with the harbour as the centre of the town, where the whale-watching boats depart. In good weather you can see distant snow mountains across the bay. The town is very small — a few streets.",
    gettingAround:
      "Húsavík has a small airport (HZK) with very few flights; most people drive about an hour from Akureyri, or on the Diamond Circle. The town is walkable. The climate is temperate maritime, drier than the south, cold in winter, near the Arctic Circle but still moderated by the ocean.",
    culture:
      "Icelandic is the main language, and in the tourist season the town runs on whale watching and related services. The GeoSea geothermal sea-view baths on the cliff are popular. Restaurants do not require tipping. A film set in Húsavík has raised its profile in recent years.",
    seeAndDo:
      "Whale watching (several operators, with traditional oak boats and fast RIBs); the Whale Museum; the wooden church; the GeoSea cliff baths; south to Goðafoss, Mývatn, Dettifoss and the Ásbyrgi canyon (the Diamond Circle in a day).",
    whenAndTips:
      "The whale-watching high season is June–August; April and September are possible but rougher — bring a windproof, waterproof jacket, as it is cold on the boat. Take seasickness medication in advance if you are prone to it. In winter flights and some roads are limited, and most people come in summer.",
  },

  isafjordur: {
    // identity sources: 人口：城镇聚落（byggðakjarni）口径，冰岛统计局 MAN030101 代码 410 —— 2025-01-01 = 2,705（正式发布 2025-10-07）。⚠️ 原文的「2023 年 1 月约 2,744」**查不到出处**：官方同表 2023-01-01 是 2,653，用 þéttbýlisstaður 表交叉也是 2,653，所以不是口径差异而是数值本身有误。下一期预计 2026 年 10 月。
    identity:
      "Ísafjörður is the largest town in the Westfjords of Iceland, with a settlement population of 2,705 as of 1 January 2025 (Statistics Iceland). The Westfjords are the oldest and most remote corner of Iceland — a peninsula cut into pieces by countless deep fjords and steep flat-topped mountains, with few roads, many tunnels, and often snowed in during winter. Ísafjörður is its centre.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Ísafjörður (Iceland; the largest town in the Westfjords, in Ísafjarðarbær municipality, with about 2,744 residents in January 2023, on a sandy spit in Skutulsfjörður off Ísafjarðardjúp; settled in the 9th century according to the Landnámabók, a trading centre from the 1500s, granted municipal status in 1786; timber buildings surviving from the 1700s including Krambúð 1757, Faktorshús 1765, Tjöruhúsið 1781 and Turnhúsið 1784; the coolest area in Iceland at sea level with a tundra climate, high winds and few sunny days; fishing historically dominant, now also the University Centre of the Westfjords and a gateway to the Hornstrandir nature reserve; the Aldrei fór ég suður music festival)
    howItWorks:
      "Ísafjörður is the largest town of the Westfjords in Iceland with about 2,744 residents in January 2023, in Ísafjarðarbær municipality; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. The town is built on a sandy spit reaching into Skutulsfjörður, walls of rock hundreds of metres high on three sides and one narrow road out — and that ground governs everything in the Westfjords: avalanches and closed roads are ordinary in winter, so the town has built deflection dams above it and tunnels through the hills below. By the Landnámabók people settled here in the ninth century; it was a trading centre from the 1500s and received municipal status in 1786, and several timber houses from the eighteenth century still stand by the harbour, the oldest from 1757. This is the coolest part of Iceland at sea level, a tundra climate with high winds and few clear days. Fishing was once the whole living; now the University Centre of the Westfjords is here too, and the Hornstrandir nature reserve is reached from this town. Newcomers most often go wrong by planning around road distances, when in winter that road may close at any time.",
    layout:
      "Ísafjörður is built on an L-shaped spit reaching into a fjord, with near-vertical flat-topped mountains on three sides and a single road in and out. The old town has a cluster of 18th–19th-century timber houses. Smaller fishing villages and abandoned settlements are scattered around the fjords.",
    gettingAround:
      "Ísafjörður Airport (IFJ) is in the fjord, its approach notoriously difficult and cancelled in bad weather, with flights to and from Reykjavík (about 40 minutes). By road it is a long way on the winding Westfjords roads and tunnels (about 5–6 hours from Reykjavík). The climate is temperate maritime, with the heaviest snow, strong wind, high mountains and deep valleys, and extremely changeable weather.",
    culture:
      "Icelandic is the main language. Westfjords people are known for resilience and hospitality, with small, close-knit communities. Ísafjörður has a music school and an annual ski/music festival around Easter. Restaurants do not require tipping.",
    seeAndDo:
      "The old-town timber houses and the Westfjords Heritage Museum; boat or car trips to small fishing villages in nearby fjords; hiking in the Hornstrandir nature reserve (an uninhabited area, reached by boat, with a guide); the Látrabjarg cliffs for puffins (summer, the westernmost point of Iceland); the Dynjandi waterfall. Alpine skiing in winter.",
    whenAndTips:
      "June–September has reliable roads and is the hiking season; the rest of the year has a high risk of heavy snow and avalanches, passes may close for days, and the itinerary needs plenty of flexibility. Flying saves time over driving but is cancelled in bad weather — have a plan B. Puffins and Hornstrandir are summer only.",
  },
};
