import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "iceland-overview": {
    // identity sources: Hagstofa Íslands《Mannfjöldinn 1. janúar 2025》：389,444 人。https://hagstofa.is/utgafur/frettasafn/mannfjoldi/mannfjoldinn-1-januar-2025/
    //   核实日 2026-09-07，来源级别 1
    identity:
      "Iceland is an island nation in the North Atlantic, about 100,000 sq km, with a population of about 389,000 as of January 2025 (Statistics Iceland) — the least densely populated country in Europe, with over 60% living in the capital area. It sits exactly on the Mid-Atlantic Ridge, where the North American and Eurasian plates pull apart, and over a mantle hotspot, so volcanism and geothermal activity are intense: about thirty active volcanic systems, with geysers, hot springs and lava fields everywhere. At the same time about a tenth of the country is under ice, giving a landscape of 'fire and ice' together.",
    layout:
      "The centre of Iceland is an uninhabitable highland desert and ice cap, and people and roads are concentrated in a ring around the coast. Route 1, the Ring Road, is about 1,330 km and links most towns and sights. The south-west has the capital area and the geothermal belt; the south coast has waterfalls, black beaches and glacier tongues; the south-east has Vatnajökull, the largest glacier in Europe, and a glacier lagoon; the east and north are fjords and farmland; the north-western Westfjords are the most remote.",
    gettingAround:
      "Almost all international flights land at Keflavík Airport (KEF, about 50 km south-west of Reykjavík). Getting between towns is mainly by car (the Ring Road is paved; the interior 'F-roads' are gravel, need a 4x4 and are open only in summer); there are also a few domestic flights linking Reykjavík with the north, east and Westfjords. Public buses are limited. In winter roads ice over with strong wind — always check road and weather forecasts. Tap water is excellent and drinkable. Power is 230V with the European two-round-pin plug.",
    culture:
      "The official language is Icelandic, and almost everyone speaks fluent English. Society is strongly egalitarian, crime is low, and nature protection is taken seriously. Icelanders use patronymics: the surname is the father's name plus -son / -dóttir, so the phone book is ordered by first name. Bathing in geothermal pools is a national habit, and you must shower thoroughly without a swimsuit before entering a pool (this is clearly required). Tipping is not expected. Prices are very high.",
    seeAndDo:
      "The Golden Circle (the rift at Þingvellir National Park, the Geysir geothermal area, Gullfoss waterfall); on the south coast, Seljalandsfoss and Skógafoss, black beaches, the glacier lagoon and 'Diamond Beach'; the Snæfellsnes peninsula; in the north, the Mývatn geothermal area, Dettifoss, and whale watching at Húsavík; geothermal spas such as the Blue Lagoon. Northern lights in winter (September–March), midnight sun in summer. In recent years the Reykjanes Peninsula has had several eruptions — viewable from a distance but only under official guidance.",
    whenAndTips:
      "June–August has the longest daylight, open interior roads and the best conditions for a Ring Road trip; September–March is aurora season but with short days, poor weather and some roads closed. The weather changes many times a day — dress in layers and carry a windproof, waterproof jacket. When driving, mind the wind on car doors, gravel roads, single-lane bridges and sheep on the road. In volcanic and geothermal areas stay strictly on the paths and follow IMO (the Icelandic Met Office) and local notices. Most foreign visitors travel visa-free for short tourism in the Schengen area or follow Schengen rules.",
  },

  reykjavik: {
    // identity sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   雷克雅未克市镇 139,804（2026-01-01，占全国 394,324 的 35.5%），Hagstofa Íslands 官方稿，级别 1。
    //   https://hagstofa.is/utgafur/frettasafn/mannfjoldi/mannfjoldi-1-januar-2026/
    //   ⚠️ **首都区的合计总人口本轮没能核到一个自洽的官方数**：不同发布给出 244,536（2025-01-01）/ 约 247,000（推算）/ 251,900（正文旧值）/ 264,056（2026 Q1 估计）四个互相矛盾的数字，正文因此只写占比、不改总数，另开 issue，下一轮直接从 Hagstofa PxWeb 表 MAN02005 把 7 个市镇加总。
    identity:
      "Reykjavík is the capital of Iceland, and the northernmost capital of a sovereign state in the world, with a municipal population of about 140,000 at the start of 2026 and, together with the rest of the Capital Region, about 63 per cent of the country. The name means 'smoky bay' in Old Norse — the first settlers saw geothermal steam. The city is small and low-rise, heated by geothermal water, with almost no industrial chimneys.",
    // howItWorks sources: 首都区 251,912 / 全国 394,324（2026-01-01，Hagstofa MAN02005，1 级）。核实 2026-09-12
    howItWorks:
      "Reykjavík is Iceland's capital and a municipality, governed by a council of 23 members who appoint the mayor rather than electing one directly; it had about 140,000 people in 2026, more than a third of the country, while the Capital Region of seven municipalities — Kópavogur, Hafnarfjörður, Garðabær and the rest — held about 252,000 at the start of 2026 (Statistics Iceland), 64 per cent of Iceland, each neighbour with a council of its own. The city is divided into ten districts. The old centre lies at the tip of the peninsula: Laugavegur is the main shopping street, Parliament stands on Austurvöllur, Hallgrímskirkja on the hilltop and the old harbour to the north, and Laugardalur is the district of sports and thermal pools. Addresses give street, number and postcode, and the postcodes 101 to 113 are badges of identity — '101 Reykjavík' means the life of the centre. Iceland has no railway, public transport is Strætó buses alone, the car is daily life, and the whole city is heated by geothermal district heating. Keflavík International Airport lies about 50 km south-west. Newcomers most often go wrong by taking the city of Reykjavík for the whole Capital Region, when more than half its people live in the neighbouring municipalities.",
    layout:
      "Reykjavík is built on a peninsula, sea on three sides, with Mount Esja and distant snow peaks behind it. The old town and harbour are at the northern end of the peninsula, and the main street, Laugavegur, is for shopping and eating; the landmark Hallgrímskirkja church stands on a rise in the middle of the city, with a tower view over the coloured roofs. The city spreads south-east into suburbs.",
    gettingAround:
      "International flights land at Keflavík (KEF), with buses (Flybus, Airport Direct) about 45 minutes to town (there is no train). The city has buses (Strætó), but the centre is compact and walkable. Many people rent a car in Reykjavík and drive the Ring Road. The climate is temperate maritime, moderated by ocean currents: winters are not extremely cold (often around 0°C) but windy with rain and snow and short days; summers are cool with very long daylight.",
    culture:
      "Icelandic is the main language, with widespread English. The city's culture is active in music (several internationally known musicians are from here), literature (a very high number of books published per head) and design. Bathing in public warm pools is a way to socialise, and you must shower naked before entering. Restaurants do not require tipping. Prices are high, and eating out and alcohol are especially expensive.",
    seeAndDo:
      "The tower of Hallgrímskirkja; the Sun Voyager sculpture and the Harpa concert hall by the harbour; the National Museum and the Settlement Exhibition (871±2); shopping on Laugavegur; the Tjörnin pond and City Hall; whale and puffin trips from the old harbour; the city's geothermal beach and pools. Use it as a base for the Golden Circle, the south coast, or the Reykjanes volcanic activity.",
    whenAndTips:
      "June–August has long daylight and the best weather but the most visitors and expensive lodging; September–March you may see the aurora from the edge of the city. It is changeable and windy all year — carry a waterproof. The city is small and most sights are walkable — no need to rush into a rental car, rent it for the Ring Road. Downtown parking is paid and scarce.",
  },

  keflavik: {
    // identity sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   雷克雅内斯拜尔市镇 24,557（2026-07-01，国家登记处 Þjóðskrá 数据，经地方媒体转述，2 级）；凯夫拉维克 + 纳尔兹维克城镇聚落 22,377（2025，Hagstofa，级别 1）。
    //   https://www.vf.is/frettir/ibuathroun-a-sudurnesjum-haegir-a-vexti-og-faekkun-i-reykjanesbae
    //   https://hagstofa.is/utgafur/frettasafn/mannfjoldi/mannfjoldi-eftir-byggdakjornum-og-thettbylisstodum-2025/
    //   **这条是「市镇 vs 城镇聚落」混用的典型**：同一个地名在冰岛有两个官方数，差 2000 多人，不写明是哪一档就没法核。
    identity:
      "Keflavík is a port town on the Reykjanes Peninsula, officially named Reykjanesbær after merging with neighbouring towns, the municipality had about 25,000 people in mid-2026, of which the combined urban settlement of Keflavík and Njarðvík held about 22,000 in 2025. Iceland's international airport is next to it, and most visitors pass through on arrival and departure. The peninsula itself is almost entirely lava field and geothermal ground, and there have been several eruptions nearby since 2021.",
    // howItWorks sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   同 identity 注释。原文停在 2018 年的 15,930，落后四期以上。
    //   https://www.vf.is/frettir/ibuathroun-a-sudurnesjum-haegir-a-vexti-og-faekkun-i-reykjanesbae
    //   https://hagstofa.is/utgafur/frettasafn/mannfjoldi/mannfjoldi-eftir-byggdakjornum-og-thettbylisstodum-2025/
    howItWorks:
      "Keflavík is a town on the Reykjanes peninsula in south-western Iceland; in the mid-1990s it merged with Njarðvík and Hafnir to form the municipality of Reykjanesbær, the combined urban settlement of Keflavík and Njarðvík holding about 22,000 people in 2025 and the whole municipality about 25,000 in mid-2026; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. The name means driftwood bay, and the town grew from the sixteenth century on fishing and fish processing amid a country of basalt rubble and moss. During the Second World War the American military built the airport beside the town, and through the Cold War Naval Air Station Keflavik was an important base for watching the northern seas, the American forces withdrawing in 2006 and the base passing to civil and residential use. Keflavík International Airport lies at the town's edge as Iceland's international gateway, where nearly every flight in and out of the country lands, with Reykjavík about 50 km north-east. Many musicians came from here in the 1960s and 1970s, earning it the nickname of the Beatles town. Newcomers most often go wrong by treating the airport as part of Reykjavík, when it stands in another municipality nearly an hour from the city.",
    layout:
      "Keflavík is on the western coast of the peninsula, with the airport to its south-west. The whole Reykjanes Peninsula is a young black lava platform, almost treeless, with geothermal steam rising from the ground; the famous Blue Lagoon, in the middle of the peninsula, is warm mineral-rich water discharged from a geothermal power station. The southern coast has cliffs, lighthouses and the 'Bridge Between Continents' over a fissure between the American and Eurasian plates.",
    gettingAround:
      "From the airport it is about 45 minutes by bus to Reykjavík. Many people rent a car here to start the Ring Road. The town is walkable. The climate is temperate maritime, and the open peninsula terrain makes it especially windy. Recent volcanic activity has been concentrated in the eastern part of the peninsula (around Grindavík), and roads may close temporarily.",
    culture:
      "Icelandic is the main language, with widespread English. There was a US military base here (left in 2006), leaving some traces and an aviation museum. The town is quiet, based on fishing and airport-related industry. Restaurants do not require tipping.",
    seeAndDo:
      "The Blue Lagoon geothermal spa (book online in advance); the Reykjanes geopark: the bubbling mud pots and fumaroles at Gunnuhver, Lake Grænavatn, the Bridge Between Continents, the Valahnúkamöl cliffs and lighthouse; Lake Kleifarvatn; if there is a safely opened eruption viewpoint, watch from a distance under official guidance. The 'Giant' sculpture and the Viking World museum near the airport.",
    whenAndTips:
      "It is convenient as the first or last stop in Iceland, and the Blue Lagoon is often scheduled for the arrival or departure day. The wind on the peninsula is extreme — take care with car doors. During volcanic activity, follow IMO (the Icelandic Met Office) and civil-protection notices, never enter a closed area, and never approach lava on your own.",
  },

  vik: {
    identity:
      "Vík (in full, Vík í Mýrdal) is the southernmost town in Iceland, with a population of only a few hundred, but because it is right on the Ring Road and surrounded by dense sights it is a key tourist base on the south coast. The town is set between black sea cliffs, green mossy mountains, and the Mýrdalsjökull ice cap to the north, which sits over the Katla volcano.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Vík í Mýrdal (Iceland; village in Mýrdalshreppur municipality with about 750 inhabitants as of 2021, the southernmost village in Iceland, on the Ring Road about 180 km south-east of Reykjavík; the largest settlement for some 70 km around and the service centre for the coast between Skógar and Mýrdalssandur; the black sand beach named among the ten most beautiful beaches on earth by Islands Magazine in 1991, with the Reynisdrangar sea stacks offshore; the wettest coastal town in Iceland with about 2,250 mm of rain a year; the Katla volcano, which last erupted in 1918, with an evacuation plan giving residents little time to reach the hilltop church)
    howItWorks:
      "Vík í Mýrdal is a village on the south coast of Iceland in Mýrdalshreppur municipality with about 750 inhabitants as of 2021, the southernmost settlement in the country; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. Its function is service: along some 70 km of coast between Skógar and Mýrdalssandur this is the only place with fuel, a supermarket and hotels, so nearly everyone on the Ring Road stops here once. The black sand beach and the Reynisdrangar stacks offshore are its famous sight, listed among the ten most beautiful beaches on earth by an American magazine in 1991; but the surf here throws sudden sneaker waves far up the sand, warning signs stand along it, and people are swept out every year. It is the wettest coastal town in Iceland with about 2,250 mm of rain a year. North of the village the Katla volcano lies beneath the Mýrdalsjökull ice cap and last erupted in 1918; an eruption would send meltwater down in very little time, and the church on the hill is the village assembly point. Newcomers most often go wrong by turning their back to the sea for a photograph, which is exactly how people are taken.",
    layout:
      "Vík stretches along one main road, with a white hilltop church that is the landmark and the flood-refuge point. Both sides of the town have black beaches: to the west is the famous Reynisfjara black beach, with columnar basalt cliffs and sea stacks; the beach directly south of the town runs east. North over the pass are the Mýrdalsjökull ice cap and the Sólheimajökull glacier tongue.",
    gettingAround:
      "Vík has no airport with scheduled flights and no train; the Ring Road runs through it, and you arrive by car or tour bus. The town is walkable, but you need a car for the surrounding sights. The climate is temperate maritime, one of the wettest places in Iceland, foggy and windy. In winter roads ice over with strong wind, and the south coast road occasionally closes for wind.",
    culture:
      "Icelandic is the main language, and tourism is well developed, with food and lodging geared to passing visitors. The town's resources are limited, and lodging and restaurant tables are tight in peak season. Restaurants do not require tipping.",
    seeAndDo:
      "Reynisfjara black beach and its columnar basalt (the waves are extremely dangerous — stay well back from the waterline and never turn your back on the sea); the sea arch and lighthouse at Dyrhólaey; the hilltop church for the view; west to Skógafoss, Seljalandsfoss and the Sólheimajökull glacier (hike with a guide); east to the Fjaðrárgljúfur canyon and toward the glacier lagoon.",
    whenAndTips:
      "It can be visited year-round; June–September has relatively good weather and long days. The 'sneaker waves' at Reynisfjara sweep visitors out to sea every year — take the warning signs seriously, keep well back and watch the water. In winter check road.is and vedur.is (road conditions, weather, aurora forecast). The town is small — book lodging well ahead in peak season.",
  },

  hofn: {
    // identity sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   赫本镇（byggðakjarni）1,802（2025）；霍尔纳峡湾市镇（sveitarfélag）2,589（2025）—— **两档不要混用**。2026-09-09 核。
    //   瓦特纳冰原：按**体积**是欧洲最大的冰帽（与瓦特纳冰原国家公园管理局自身表述一致），按**面积**次于俄罗斯新地岛北岛冰帽。原文「欧洲最大的冰川」不带口径。
    //   https://en.wikipedia.org/wiki/Vatnaj%C3%B6kull
    //   **跨系统的不一致**：同一个事实在地形条目 vatnajokull 里带了「按体积算」的限定，在这个城市条目里没带 —— 两套内容各写各的，修一处要顺手搜另一套。
    identity:
      "Höfn (in full, Höfn í Hornafirði — 'höfn' is Icelandic for 'harbour') is a fishing town in south-east Iceland, with a town population of about 1,800 in 2025, on a spit at the mouth of a lagoon, backed by Vatnajökull — by volume the largest ice cap in Europe — and its glacier tongues reaching down between the mountains. It is known for langoustine.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Höfn (Iceland; town in Hornafjörður municipality in the south-east with 1,802 residents in 2025, on a peninsula surrounded by sea on three sides; the name means harbour; founded in 1897 by the merchant Ottó Tuliníus, who moved a trading post from Papós, with growth after the Hornafjarðarbrú bridge of 1961; fishing, particularly langoustine and saltfish, and tourism around Vatnajökull, Europe's largest ice cap by volume, and the nearby glaciers; the annual lobster festival in early July; on the Ring Road about 455 km from Reykjavík, the Almannaskarðsgöng tunnel of 2005 improving winter access; a regional airport with flights to Reykjavík)
    howItWorks:
      "Höfn is a town of Hornafjörður municipality in south-eastern Iceland with about 1,800 residents in 2025; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. The name simply means harbour, and the town stands on a small peninsula with sea on three sides. The merchant Ottó Tuliníus founded it in 1897 by moving a trading post from Papós, and it grew in earnest only after the Hornafjarðarbrú bridge opened in 1961. Fishing is the old trade, known especially for langoustine and saltfish, with a langoustine festival each July. Its other living comes from the ice behind it: Vatnajökull, the largest ice cap in Europe by volume, lies on the heights just north, the Jökulsárlón glacier lagoon about 80 km west, and glacier tourism has made this small town the base of the south-east coast. The Ring Road passes through, Reykjavík lying about 455 km west; the Almannaskarðsgöng tunnel of 2005 eased winter access, and a regional airport flies to Reykjavík. Newcomers most often go wrong by expecting the glacier lagoon beside the town, when it is more than an hour away by road.",
    layout:
      "Höfn is at the end of a low, flat spit, water on three sides, and in good weather you can see the white edge of Vatnajökull and several peaks under the ice caps (including Iceland's highest point, Hvannadalshnúkur) from the town. The Ring Road passes north of the town; between the town and the glacier is an outwash plain and lagoon.",
    gettingAround:
      "Höfn has a small airport (HFN) with a few flights to and from Reykjavík; most people arrive by car on the Ring Road (about 6 hours from Reykjavík, about 2.5 hours from Vík). The town is walkable, but you need a car or a tour for the glacier. The climate is temperate maritime and windy, and the ice cap creates its own local weather.",
    culture:
      "Icelandic is the main language, and the town lives on fishing and tourism. There is a 'Lobster Festival' in late summer. Restaurants do not require tipping. This is one of the sunnier corners of Iceland, though the weather is still changeable.",
    seeAndDo:
      "Use Höfn as a base for the Jökulsárlón glacier lagoon and 'Diamond Beach' (floes washed up on the black sand) and the Fjallsárlón lagoon; glacier hikes and blue ice caves in Vatnajökull National Park (winter, with a certified guide); hiking and basalt waterfalls at Skaftafell; the harbour and lagoon walk in town, and the langoustine.",
    whenAndTips:
      "May–September is best for the Ring Road and glacier hikes; blue ice caves are a November–March activity. For anything on the ice (caves, glacier walks) always go with a certified guide and never go onto the ice alone. The floes and tides at the lagoon are dangerous — do not stand on the ice or get too close to the water. In winter the south-east road closes for strong wind.",
  },

  egilsstadir: {
    // identity sources: 人口：**城镇聚落（byggðakjarni）口径**，不是市镇（Múlaþing）—— 这两档在冰岛差别很大，本库已因混用出过错。冰岛统计局 PxWeb MAN030101 代码 902：2025-01-01 = 2,711（正式发布 2025-10-07）；2026-01-01 数据库初步值 2,719，年度新闻稿未发。原文 2,632 与官方任一年都对不上。按城镇聚落发布的新闻稿通常在同年 10 月初，下一期预计 2026 年 10 月。
    identity:
      "Egilsstaðir is the largest town in eastern Iceland, with a settlement population of 2,711 as of 1 January 2025 (Statistics Iceland), and the transport, service and administrative centre of the eastern fjords region. It sits on Lagarfljót, Iceland's third-largest lake by area — long and thin, and said in local folklore to be home to a 'lake monster'. Around it is one of Iceland's rare large areas of woodland.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Egilsstaðir (Iceland; town in east Iceland on the banks of the Lagarfljót, 2,632 residents in 2024, the largest settlement in the eastern region; formally established only in 1947, though the farmer Jón Bergsson had begun developing the site earlier in the 20th century; growth during the 2004–2008 hydropower and aluminium boom; a crossroads where the main regional routes meet, the area's transport, service and administrative centre, with airport, gymnasium and health clinic; Hallormsstaðaskógur, the biggest forest in Iceland, plus Hengifoss and Skriðuklaustur nearby; subarctic climate with mild summers, a record 29.8 °C in August 2025)
    howItWorks:
      "Egilsstaðir is the largest town in eastern Iceland, with a settlement population of 2,711 as of 1 January 2025 (Statistics Iceland), on the banks of the Lagarfljót; Iceland has only the state and municipalities, this town belonging to Múlaþing, formed by merger in 2020, which runs schools, planning and local services while the state runs health care and police. It is a very young town: it was formally established only in 1947, before which there was a single farm here, the farmer Jón Bergsson having begun to build up the site early in the twentieth century, and the hydropower and aluminium works of 2004 to 2008 brought a further wave of growth. Its position explains its existence — the main roads of the east meet here, so the airport, the clinic, the secondary school and the government offices are all in this town and people from the fjords around come in to use them. Hallormsstaðaskógur, the largest forest in Iceland, stands on the south shore of the lake, with Hengifoss and the Skriðuklaustur house nearby. Over the pass lies Seyðisfjörður, from which the ferry sails to Denmark and the Faroes. Newcomers most often go wrong by looking for an old town, when this one is younger than many of its residents.",
    layout:
      "Egilsstaðir is on flat ground in a river valley in the eastern interior, with Lagarfljót stretching south-west from the edge of town. The Ring Road passes through; east over the mountains, about 25 minutes, is the fjord port town of Seyðisfjörður (known for its rainbow street and ferry terminal). The town itself is small and practical.",
    gettingAround:
      "Egilsstaðir Airport (EGS) has flights to and from Reykjavík (about 1 hour) and a few regional services to Akureyri. Most people arrive by car on the Ring Road. You need a car for the surrounding fjords and waterfalls. The climate is more continental: drier than the coast, warmer in summer and colder in winter.",
    culture:
      "Icelandic is the main language. The east is one of the most sparsely populated and 'remote'-feeling parts of Iceland, with a slow pace. Seyðisfjörður has an active arts community and an annual music festival. Restaurants do not require tipping.",
    seeAndDo:
      "Hengifoss (one of Iceland's higher waterfalls, with red bands in the rock wall); a drive around Lagarfljót and the Hallormsstaður woods; over the mountains to Seyðisfjörður for the rainbow street and the fjord; north to Dettifoss and Mývatn (about 2 hours); driving the eastern fjords for fishing villages and seabirds.",
    whenAndTips:
      "June–September is best, with snow-free passes and the woods at their greenest. Route 93 to Seyðisfjörður often has snow and fog in winter — check road conditions before setting out. Distances between eastern sights are long and petrol stations are few — keep an eye on the fuel gauge.",
  },

  akureyri: {
    // identity sources: **冰岛的官方人口口径**（冰岛统计局 Hagstofa Íslands，2026-09-09 核）：sveitarfélag（市镇）/ byggðakjarni · þéttbýlisstaður（城镇聚落）/ höfuðborgarsvæðið（首都区，7 个市镇的官方统计分组）。基准日为每年 1 月 1 日，1 月上旬由国家登记处（Þjóðskrá）先发市镇级快报、Hagstofa 随后发正式稿，另按季度更新。
    //   阿克雷里市镇 20,284（2026-01-01，Hagstofa，级别 1 交叉确认）。
    //   埃亚峡湾：通行表述是「冰岛最长的峡湾**之一**」（约 60 公里），**查不到支持绝对「最长」的权威来源**，已降级。2026-09-09 核。
    //   https://en.wikipedia.org/wiki/Eyjafj%C3%B6r%C3%B0ur
    identity:
      "Akureyri is the largest town in northern Iceland, with a population of about 20,000 at the start of 2026, called the 'capital of the north', at the head of Eyjafjörður, one of Iceland's longest fjords, ringed by mountains on three sides. Although it is only about 100 km from the Arctic Circle, its position at the end of a long fjord and the ocean's moderating effect make the climate milder than you might expect, and trees grow well.",
    // howItWorks sources: Wikipedia (2026-09): Akureyri (municipality Akureyrarbær; 11-member council appoints mayor; 20,284 2026; largest outside Capital Region; university 1987; hospital; airport; Hrísey and Grímsey in municipality; Ring Road ~390 km)
    howItWorks:
      "Akureyri is the largest town in Iceland outside the Capital Region, with about 20,000 people in 2026, and is called the 'capital of North Iceland': the municipality is governed by an eleven-member council that appoints the mayor. It has one of the country's two main hospitals, the University of Akureyri founded in 1987, an airport with flights to Reykjavík and an ice-free port where cruise ships call in summer, and it is the service centre of the whole north. The town spreads along the west shore of Eyjafjörður: Hafnarstræti is the main street, the steps of Akureyri church are the point of reference, the botanical garden is among the northernmost in the world, and the Hlíðarfjall ski area lies in the mountains to the west. The islands of Hrísey and Grímsey, the latter on the Arctic Circle, belong to the municipality. The Ring Road to Reykjavík runs about 390 km and is often closed by winter storms, while the flight takes 45 minutes. Addresses give street, number and postcode, beginning with 600. The red traffic lights are heart-shaped, the town's small emblem. Newcomers most often go wrong by taking Akureyri for a small town, when it is the administrative, medical and educational centre of North Iceland.",
    layout:
      "Akureyri is built on the hillside on the west side of the fjord, with the centre and harbour low down and the residential areas climbing the slope. Snow mountains face the town across and at the head of the fjord. The town has the northernmost botanic garden in Iceland. South along the fjord and valley is farmland; east over the mountains is the Mývatn area.",
    gettingAround:
      "Akureyri Airport (AEY) is south of the town, with frequent flights to and from Reykjavík (about 45 minutes), plus a few international flights and regional services. Most people arrive by car on the Ring Road (about 5 hours from Reykjavík). The town has walking and buses. The climate is temperate maritime, drier than the south, with heavy winter snow — it is one of Iceland's ski centres.",
    culture:
      "Icelandic is the main language, with widespread English. Akureyrians identify strongly with the 'capital of the north', and the town has a theatre, a university and an active music scene. The red heart-shaped traffic lights are a local emblem. Restaurants do not require tipping.",
    seeAndDo:
      "The hillside Akureyri church, the botanic garden, the old wooden houses; whale watching from the fjord (humpback, minke); an hour east to the Mývatn geothermal area, Goðafoss and Dettifoss; skiing at Hlíðarfjall in winter; in summer, south to the Ásbyrgi canyon and the Diamond Circle.",
    whenAndTips:
      "June–September is best, with very long daylight. Winter has heavy snow but city life continues, and it is a good place for skiing and the aurora — mountain passes need winter tyres and a road check. Whale watching is possible from both Akureyri and Húsavík, with a higher success rate from Húsavík.",
  },

  husavik: {
    // identity sources（2026-09-15 核实，update）: Hagstofa MAN030101，byggðakjarni Húsavík = 2,403（2026-01-01），1 级；下一期约 2027-03
    // identity sources: 「欧洲观鲸之都」经查证是当地旅游业的自我宣传口号（多家站点均写「bills itself as」），无官方或独立评选出处，已降级为「当地常自称」。3 级，2026-09-09 核。
    //   https://visitorsguide.is/husavik-the-whale-watching-capital-of-europe/
    //   人口 2,300–2,500 的区间表述本轮未找到更精确的单一官方数，保留区间。
    identity:
      "Húsavík is a fishing town in northern Iceland, with an urban-settlement population of 2,403 as of 1 January 2026 (Statistics Iceland), known for whale watching and locally billed as the 'whale-watching capital of Europe' — the food-rich Skjálfandi Bay offshore gives reliable humpback sightings in summer, and sometimes blue whales. The town has an all-timber old church and a dedicated whale museum.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Húsavík (Iceland; town in Norðurþing municipality on the north coast with about 2,300–2,500 residents, on Skjálfandi bay; a centre of whale watching in Iceland because whales of several species enter the bay; the wooden church Húsavíkurkirkja of 1907 the chief landmark; the Húsavík Whale Museum, the Exploration Museum and a Eurovision museum opened in 2021; recorded as the first place in Iceland settled by a Norseman, the Swedish Viking Garðar Svavarsson wintering here around 870; the 2020 film Eurovision Song Contest: The Story of Fire Saga set here, its title song Oscar-nominated; Akureyri within an hour via the Vaðlaheiðargöng tunnel of 2019; flights ended in 2024)
    howItWorks:
      "Húsavík is a town on the north coast of Iceland in Norðurþing municipality with 2,403 residents in the urban settlement on 1 January 2026 (Statistics Iceland); Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. The town faces Skjálfandi bay, which several species of whale enter to feed each summer, and this has made it the centre of whale watching in Iceland — the boats go out from the harbour, the whale museum stands on the quay, and the local economy has turned from fishing to tourism on that account. The wooden church of 1907 stands on the slope as the town's mark. By the records this is the first place in Iceland where a Norseman wintered: the Swede Garðar Svavarsson stayed here around 870. A 2020 film about the Eurovision Song Contest was set in the town and its title song was nominated for an Oscar, after which a small museum on the subject opened here. Since the Vaðlaheiðargöng tunnel opened in 2019 Akureyri is an hour away; scheduled flights from the local airport ended in 2024. Newcomers most often go wrong by treating whale watching as a year-round activity, when the boats sail by season and weather.",
    layout:
      "Húsavík is on the eastern shore of Skjálfandi Bay, backed by low hills, with the harbour as the centre of the town, where the whale-watching boats depart. In good weather you can see distant snow mountains across the bay. The town is very small — a few streets.",
    gettingAround:
      "Húsavík has an airport but no scheduled flights: the scheduled service to Reykjavík ended in 2024, a single subsidised winter season ran from late 2024 to March 2025, and there have been no scheduled departures since (as of September 2026). Most people drive about an hour from Akureyri, or arrive on the Diamond Circle. The town is walkable. The climate is temperate maritime, drier than the south and cold in winter, just south of the Arctic Circle at 66°33'N but still moderated by the ocean.",
    culture:
      "Icelandic is the main language, and in the tourist season the town runs on whale watching and related services. The GeoSea geothermal sea-view baths on the cliff are popular. Restaurants do not require tipping. A film set in Húsavík has raised its profile in recent years.",
    seeAndDo:
      "Whale watching (several operators, with traditional oak boats and fast RIBs); the Whale Museum; the wooden church; the GeoSea cliff baths; south to Goðafoss, Mývatn, Dettifoss and the Ásbyrgi canyon (the Diamond Circle in a day).",
    whenAndTips:
      "The whale-watching high season is June–August; April and September are possible but rougher — bring a windproof, waterproof jacket, as it is cold on the boat. Take seasickness medication in advance if you are prone to it. In winter flights and some roads are limited, and most people come in summer.",
  },

  isafjordur: {
    // identity sources: 人口：城镇聚落（byggðakjarni）口径，冰岛统计局 MAN030101 代码 410 —— 2025-01-01 = 2,705（正式发布 2025-10-07）。⚠️ 原文的「2023 年 1 月约 2,744」**查不到出处**：官方同表 2023-01-01 是 2,653，用 þéttbýlisstaður 表交叉也是 2,653，所以不是口径差异而是数值本身有误。下一期预计 2026 年 10 月。
    identity:
      "Ísafjörður is the largest town in the Westfjords of Iceland, with a settlement population of 2,705 as of 1 January 2025 (Statistics Iceland). The Westfjords are the oldest and most remote corner of Iceland — a peninsula cut into pieces by countless deep fjords and steep flat-topped mountains, with few roads, many tunnels, and often snowed in during winter. Ísafjörður is its centre.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Ísafjörður (Iceland; the largest town in the Westfjords, in Ísafjarðarbær municipality, with about 2,744 residents in January 2023, on a sandy spit in Skutulsfjörður off Ísafjarðardjúp; settled in the 9th century according to the Landnámabók, a trading centre from the 1500s, granted municipal status in 1786; timber buildings surviving from the 1700s including Krambúð 1757, Faktorshús 1765, Tjöruhúsið 1781 and Turnhúsið 1784; the coolest area in Iceland at sea level with a tundra climate, high winds and few sunny days; fishing historically dominant, now also the University Centre of the Westfjords and a gateway to the Hornstrandir nature reserve; the Aldrei fór ég suður music festival)
    howItWorks:
      "Ísafjörður is the largest town of the Westfjords in Iceland with about 2,744 residents in January 2023, in Ísafjarðarbær municipality; Iceland has only the state and municipalities, the municipality running schools, planning and local services while the state runs health care and police. The town is built on a sandy spit reaching into Skutulsfjörður, walls of rock hundreds of metres high on three sides and one narrow road out — and that ground governs everything in the Westfjords: avalanches and closed roads are ordinary in winter, so the town has built deflection dams above it and tunnels through the hills below. By the Landnámabók people settled here in the ninth century; it was a trading centre from the 1500s and received municipal status in 1786, and several timber houses from the eighteenth century still stand by the harbour, the oldest from 1757. This is the coolest part of Iceland at sea level, a tundra climate with high winds and few clear days. Fishing was once the whole living; now the University Centre of the Westfjords is here too, and the Hornstrandir nature reserve is reached from this town. Newcomers most often go wrong by planning around road distances, when in winter that road may close at any time.",
    layout:
      "Ísafjörður is built on an L-shaped spit reaching into a fjord, with near-vertical flat-topped mountains on three sides and a single road in and out. The old town has a cluster of 18th–19th-century timber houses. Smaller fishing villages and abandoned settlements are scattered around the fjords.",
    gettingAround:
      "Ísafjörður Airport (IFJ) is in the fjord, its approach notoriously difficult and cancelled in bad weather, with flights to and from Reykjavík (about 40 minutes). By road it is a long way on the winding Westfjords roads and tunnels (about 5–6 hours from Reykjavík). The climate is temperate maritime, with the heaviest snow, strong wind, high mountains and deep valleys, and extremely changeable weather.",
    culture:
      "Icelandic is the main language. Westfjords people are known for resilience and hospitality, with small, close-knit communities. Ísafjörður has a music school and an annual ski/music festival around Easter. Restaurants do not require tipping.",
    seeAndDo:
      "The old-town timber houses and the Westfjords Heritage Museum; boat or car trips to small fishing villages in nearby fjords; hiking in the Hornstrandir nature reserve (an uninhabited area, reached by boat, with a guide); the Látrabjarg cliffs for puffins (summer, the westernmost point of Iceland); the Dynjandi waterfall. Alpine skiing in winter.",
    whenAndTips:
      "June–September has reliable roads and is the hiking season; the rest of the year has a high risk of heavy snow and avalanches, passes may close for days, and the itinerary needs plenty of flexibility. Flying saves time over driving but is cancelled in bad weather — have a plan B. Puffins and Hornstrandir are summer only.",
  },
  selfoss: {
    // 全七段 sources: 同中文侧（Statistics Iceland MAN030101 / MAN02005, tier 1; Árborg municipality website, tier 1; Strætó 2026 network notice, tier 1; Vegagerðin / government news via search summary, tier 2; mbl.is / Vísir, tier 2; Icelandic Met Office 2008-05-29, tier 1; distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Selfoss is a town in south Iceland on the Ölfusá River, about 50 km from Reykjavík in a straight line, with the Ring Road running through its centre. By Statistics Iceland's urban-locality measure it is the most populous town in the south, with about 10,400 people on 1 January 2025. The town grew up around a bridge: in 1891 the first suspension bridge over the Ölfusá was built here.",
    howItWorks:
      "Selfoss has no government of its own: it belongs to the municipality of Árborg, formed in 1998 from the town of Selfoss and three rural districts, and the same council also runs the seaside villages of Eyrarbakki and Stokkseyri; the council has 11 members and appoints the mayor. The south Iceland comprehensive college and university bodies based in Selfoss serve almost the whole south but are not run by the municipality. The centre is the main street, Austurvegur, just across the bridge, with the town hall on it, and in 2021 a new town centre of reconstructed old Icelandic houses opened beside the bridgehead. Addresses give street, number and postcode 800. Daily life runs on roads and buses: route 51 goes straight to Reykjavík, the south's inter-town buses connect here, and the in-town bus is free. Outsiders often make two mistakes: thinking Selfoss is a municipality in its own right, and thinking the Selfoss waterfall in the north is here, when the two are about 300 km apart in a straight line.",
    layout:
      "The town centre is by the Ölfusá bridge, with the main street Austurvegur running east along the Ring Road, Tryggvaskáli at the bridgehead, the new town centre just south of the bridgehead and Selfoss Church to the west of it; Ingólfsfjall rises about 6 km north-west of town; a new Ölfusá bridge is under construction.",
    gettingAround:
      "Selfoss has no airport with scheduled flights; domestic flights use Reykjavík Airport (RKV, about 51 km in a straight line) and international flights Keflavík (KEF, about 79 km). Iceland has no railways, so travel is by road: bus 51 runs to and from Reykjavík, and for the ferry to the Westman Islands at Landeyjahöfn you change here to bus 53 (lines as in Strætó's network from 2026). The in-town Árborg bus is free. A new Ölfusá bridge is under construction, expected to be finished in 2028 (as of September 2026).",
    culture:
      "Icelandic is spoken locally, and English is widely understood. Inter-town buses accept bank cards. The town has indoor and outdoor pools, and soaking in a hot pool is part of everyday Icelandic life.",
    seeAndDo:
      "The Ölfusá bridge and riverside path; Tryggvaskáli; the new town centre of reconstructed old houses; Selfoss Church; a hike up Ingólfsfjall; Selfoss as a base for exploring the south.",
    whenAndTips:
      "June–August has the longest days and warmest weather; winter days are short and roads may be icy, so check road conditions before setting out. The epicentre of a magnitude 6.3 earthquake in 2008 was at Ingólfsfjall, about 5 km north-west of town.",
  },
  heimaey: {
    // 全七段 sources: 同中文侧（Vestmannaeyjar town website, tier 1; Statistics Iceland, tier 1; Herjólfur articles and FAQ, tier 1; Icelandic government news 2026-04-28 / 05-14, tier 1; Norlandair, tier 1; USGS Man Against Volcano, tier 1; UNESCO 1267, tier 1; Eldheimar, tier 1）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Heimaey is the only inhabited island of the Westman Islands off Iceland's south coast, and its town is the municipality of Vestmannaeyjar, with about 4,500 registered residents on 1 January 2026 (Statistics Iceland). In 1973 the east side of the island split open in an eruption; nearly 5,300 residents were evacuated to the mainland within hours, the lava crept towards the harbour, and once the town was saved people moved back. The volcano the eruption created, Eldfell, still stands right at the eastern edge of town.",
    howItWorks:
      "Vestmannaeyjar is an independent municipality with a single tier of administration, run by a nine-member town council that appoints the mayor, and all its registered residents live in this one town on Heimaey. The island's lifeline is the Herjólfur ferry, and the ferry company is wholly owned by the town. The town is squeezed around the harbour on the north of the island, with the 1973 lava right on its eastern side and the volcano museum built on streets once buried by tephra. Addresses give street, number and postcode 900. Daily life is set by the ferry: normally the crossing to Landeyjahöfn on the mainland takes 35 minutes, but when that harbour silts up or the weather is bad the ferry switches to Þorlákshöfn, a 2-hour-45-minute crossing; in early 2026 Landeyjahöfn was closed for months and the government subsidised extra flights. Outsiders often make two mistakes: assuming the 35-minute crossing holds all year, when in winter and spring the ferry often changes port, and assuming you can land on nearby Surtsey, which only scientists may visit.",
    layout:
      "The town lies around the harbour on the north side of the island, with Landakirkja church in the centre; east of town is the 1973 lava field, with Eldfell about 1 km south-east of the centre beside the older Helgafell and the Eldheimar volcano museum at the lava's edge; Skansinn is north-east of town; Herjólfsdalur is to the west; Stórhöfði is at the island's southern tip.",
    gettingAround:
      "Heimaey's airport only has government-subsidised flights in winter, so the usual way on and off is the Herjólfur ferry: 35 minutes to Landeyjahöfn, or 2 hours 45 minutes to Þorlákshöfn when Landeyjahöfn cannot be used; arrive 30 minutes before departure and book ahead. As of September 2026 Landeyjahöfn is sometimes closed because of insufficient water depth, so check the ferry company's notices before travelling. By bus from Reykjavík to Landeyjahöfn you change at Selfoss. On the island, walk or cycle.",
    culture:
      "Icelandic is spoken locally, and English is widely understood. On the first weekend of August each year the National Festival is held in Herjólfsdalur, a tradition dating back to 1874, and the island is very busy then. Vegetation on the lava fields and volcano slopes is fragile, so stay on the paths.",
    seeAndDo:
      "A climb up Eldfell to see the 1973 lava and crater; the Eldheimar volcano museum (a house dug out after more than 40 years under tephra, plus a Surtsey exhibition); Helgafell; Herjólfsdalur; Skansinn; Stórhöfði at the southern tip of the island.",
    whenAndTips:
      "June–August has long days and warmer weather; in winter and spring the seas are rough and the ferry often switches to Þorlákshöfn, so leave slack in your plans. The volcano museum is open daily from 11:00 to 17:00 (September 2026). Surtsey cannot be visited.",
  },

  stykkisholmur: {
    // 全七段 sources: 同中文侧（Statistics Iceland PxWeb MAN030101 / MAN02005, tier 1; stykkisholmur.is on the 2022 merger, the 2023 naming vote, the council and the appointed town manager, tier 1; ferja.is and the Icelandic Road and Coastal Administration on the Baldur ferry, tier 1; distances computed）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧：name comes from the rock Stykkið, corrected）。
    identity:
      "Stykkishólmur is a harbour town on the north coast of Iceland's Snæfellsnes peninsula, with a settlement population of 1,204 on 1 January 2025 (Statistics Iceland). The island of Súgandisey shelters the harbour on its north side, and the town exists because of that sheltered water; its name, though, comes from another rock in the harbour, Stykkið, on which the main breakwater now stands. From here a ferry crosses Breiðafjörður to the Westfjords.",
    howItWorks:
      "Iceland has only two tiers, the state and the municipality. This municipality was formed in 2022 by merging the town of Stykkishólmur with the rural district of Helgafellssveit — the very district the town had been separated from in the later 19th century — and the merged council then ran a naming competition, received 73 suggestions, and in January 2023 voted on the name Sveitarfélagið Stykkishólmur. The council has seven directly elected members, usually meets once a month, and its meetings are open to the public and streamed on the municipality's own channel; the town manager is hired by the council rather than elected, attends its meetings with the right to speak and to table proposals, but has no vote unless he is also an elected member. The centre of town is the harbour street: the town hall, the Norwegian House, the museum ticket desk and the ferry berth are all on the same Hafnargata. Its living radius is set by the fjord and by that ferry — by road it is a drive around the peninsula to Reykjavík, by sea a crossing to the Westfjords, so the town is both the end of the peninsula and the start of a route across the fjord; four municipalities on the peninsula also run a shared sustainability policy. The mistake newcomers make most often is to treat Stykkishólmur as just the town: of the municipality's 1,300 people on 1 January 2026, 1,218 live in the town and the rest on the farmland brought in by the merger.",
    layout:
      "The harbour and Hafnargata are the centre of town: the town hall and the Norwegian House are on that street, the Library of Water is west of it in the old library building on the highest point in town, and the church is to the south. Súgandisey lies on the north side of the harbour, with a lighthouse on it, reached on foot along the causeway.",
    gettingAround:
      "The town has an airport but no scheduled flights; the nearest airport with scheduled flights is Reykjavík's domestic airport, about 112 km away in a straight line, with Keflavík about 121 km away. Most people drive, turning off the ring road up into the Snæfellsnes peninsula. The ferry Baldur sails from here to the island of Flatey and to Brjánslækur on the far side of the fjord, a service the Road and Coastal Administration counts as public transport; sailings change with the season, so check with the operator. The town is small enough to walk. The climate is maritime — cool summers, winters that are not extreme, and a lot of wind.",
    culture:
      "Icelandic is spoken locally. The town has a regional museum and a contemporary art installation, and in summer boats run out among the islands of Breiðafjörður. Tipping in restaurants is not expected.",
    seeAndDo:
      "The Norwegian House — built in 1832 from prefabricated timber shipped from Norway, the first two-storey dwelling in Iceland, and now the regional museum; the Library of Water, whose 24 glass columns hold water taken from the country's main glaciers; the walk out along the causeway onto Súgandisey for the view over harbour and fjord; and the Baldur ferry across Breiðafjörður, calling at the island of Flatey.",
    whenAndTips:
      "June–August has the longest days and the most ferry and boat departures; winter is windy with short daylight. Ferry and boat schedules shift with the season, so check the operator's notices before you travel.",
  },

  seydisfjordur: {
    // 全七段 sources: 同中文侧（Statistics Iceland PxWeb, tier 1; mulathing.is on the 2020 merger and the heimastjórn, tier 1; Vegagerðin tunnel environmental report on the 620 m pass, tier 1; Minjastofnun on the Blue Church, tier 1; Icelandic Met Office 2020-12-22 on the landslide, tier 1; distances computed）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧：third member appointed by the council, corrected）。
    identity:
      "Seyðisfjörður is a town at the head of a fjord in eastern Iceland, with a settlement population of 655 on 1 January 2025 (Statistics Iceland). The fjord sides are steep, and a single road climbs over the 620-metre Fjarðarheiði pass to reach the outside world; at the other end, this is the only harbour in Iceland served by an international passenger ferry.",
    howItWorks:
      "The town has no municipality of its own: in 2020 four municipalities merged into Múlaþing, so it and Egilsstaðir over the pass now belong to the same one. The municipality left each former area a three-member local committee: two of its members are elected directly by local residents on the same day as the municipal council — everyone on the local electoral roll is automatically a candidate, and voters write names and addresses on the ballot — while the third is appointed by the council from among its own elected members. The committee handles detailed planning and environmental, cultural and agricultural matters, gives opinions on local issues and permits, and can put items on the council's agenda. Separately from the committee, a staff member serves as the town manager's representative locally, and there is a municipal office in town. The centre is the street at the head of the fjord: the municipal office and the technical museum are on Hafnargata, the art centre on Austurvegur, and the ferry berth is in the same stretch. The living radius is set by one road and one pass: the 620-metre Fjarðarheiði is the only land route out, closed between 29 and 56 days a year from 2015 to 2020 and often for several days at a time, so the secondary school, hospital, airport and most government offices are over the pass in Egilsstaðir — which is in the same municipality anyway. Newcomers often read \"the airport is only 19 km away\" as close, when that is a straight line, and often assume the town has its own council.",
    layout:
      "The town spreads along the head of the fjord: the municipal office and the Technical Museum of East Iceland are around Hafnargata, the Skaftfell art centre is on Austurvegur, and the Blue Church stands up the slope to the west, reached by a footway painted in rainbow colours. The Tvísöngur sound sculpture is on the hillside north-east of town, twenty to thirty minutes on foot. The ferry berth and harbour are in the same stretch.",
    gettingAround:
      "The town has no airport of its own; the nearest is Egilsstaðir, about 19 km away in a straight line — but the road has to climb the 620-metre Fjarðarheiði pass, which according to the Road and Coastal Administration is the highest mountain road among Iceland's towns served by a single road, closed between 29 and 56 days a year from 2015 to 2020; check the official road reports for winter conditions. The ferry Norröna sails from here to the Faroe Islands and Denmark, running only between spring and autumn, with dates published by the operator each year. The town is small enough to walk. The climate is maritime, with snow in winter and fog in the fjord.",
    culture:
      "Icelandic is spoken locally. The town has a resident artistic community and a visual art centre, with music and art events in summer. Tipping in restaurants is not expected.",
    seeAndDo:
      "The Blue Church — a timber church built in 1920–1922 and listed as a protected building in 2012; the Skaftfell Center for Visual Art; the Technical Museum of East Iceland, on how this stretch of coast has changed since 1880; and the walk up to the Tvísöngur sound sculpture on the hillside, where each of the five domes resonates at its own note.",
    whenAndTips:
      "June–August is the most comfortable and the season when the international ferry runs; in winter the pass may close, so check the day's road report before driving and leave room to change plans. Since the landslide of December 2020 the slopes above town have been divided into snow zones for evacuation planning, so follow local instructions when a warning is issued.",
  },

  // ── Iceland added-towns batch (2026-09-18): Siglufjörður / Sauðárkrókur / Reykjahlíð / Hveragerði ──
  // Shared sources and calibres (see the zh file for the full note): population = Statistics Iceland 1 Jan 2026,
  // locality table MAN030101 and municipality table MAN02005 (both updated 2026-03-12, published each March, level 1).
  // NOTE: Statistics Iceland changed its estimation method in March 2024 and revised the whole series back to 2011,
  // so figures published before 2024 must never be compared with current ones in the same sentence.
  // Municipal law nr. 138/2011: two tiers only (municipality + state); council size set by population bracket and always odd;
  // the mayor is hired by the council, never directly elected; a landshluti/region is not a tier of government.
  // Conventions: Icelandic consumer rules require the displayed price to be final, with every charge already included,
  // so no service charge is added at the till; the widely repeated "about 15% service included" has no official source and is not written.
  // Climate figures are the 1961-1990 thirty-year averages from the Icelandic Met Office (the 1991-2020 normals could not be obtained).

  siglufjordur: {
    identity:
      "Siglufjörður sits at the head of a narrow fjord on the eastern side of the Tröllaskagi peninsula in northern Iceland, hemmed in by mountains on three sides and open to the sea on the fourth. The locality had 1,159 residents on 1 January 2026 (Statistics Iceland). It received town rights in 1918 and became a separate judicial district at the same time; under that now-abolished category it was the northernmost such town in the country. In the first half of the twentieth century this was the centre of herring processing, and the old harbour buildings and wooden staging survive, three of them listed: Sæbyshús of 1886, Róaldsbrakki of 1907 and the Norwegian Seamen's Home of 1915. The Herring Era Museum occupies those buildings.",
    howItWorks:
      "The town is not itself a government. In 2006 it merged with Ólafsfjörður, on the other side of the mountains, into a municipality called Fjallabyggð; the new name was chosen by a vote held on the same day as that year's municipal election, from a shortlist of four. On 1 January 2026 the municipality had 1,969 residents, 1,159 of them here, 771 in Ólafsfjörður and the rest scattered. Iceland has only two tiers of government, municipality and state, with nothing in between; a region such as \"North Iceland\" is a statistical and voluntary-cooperation unit, not a tier. The council has seven seats, council size being set by population bracket and always an odd number, and the mayor is hired by the council rather than elected by voters. The meeting arrangement is the telling detail: this municipality holds its public council meetings alternately in the two towns, once in Tjarnarborg in Ólafsfjörður and once in the council chamber of the town hall here. The municipal offices are at Gránugata 24 in this town, and the organisational chart contains only municipality-wide bodies and standing committees, so neither town has a council of its own. The mistake newcomers make is to read this as a self-standing small town, when administratively it is one half of a municipality spanning two towns.",
    layout:
      "The whole town can be measured in metres. On a small shelf of flat ground on the western shore of the fjord, the church stands about 130 m north-west of the centre, the poetry centre about 100 m north, the folk music centre about 120 m east-south-east, an arts centre about 150 m east-north-east and the Herring Era Museum about 370 m south-south-west at the water; all of these are straight-line distances. Two mountains close in behind: Hafnarhyrna, about 687 m high, lies roughly 1.5 km west-north-west, and Strákar, about 625 m, roughly 2.8 km north-north-west, with the road into town running through a tunnel beneath the latter. Ólafsfjörður, the other town of the same municipality, is about 14.7 km south-east through a tunnel.",
    gettingAround:
      "Access is by Route 76. From the south the road passes through Strákagöng, a single-lane tunnel with a 50 km/h limit; Icelandic road-authority documents date its construction to 1965-1969 while the municipality says it opened in 1967 as the first large road tunnel in Iceland, and both statements are official. Eastwards the Héðinsfjörður tunnels, opened in 2010, lead to Ólafsfjörður; the road authority gives their lengths as 3.9 km and 7.1 km. The town has an airport but no scheduled flights; the nearest airport with scheduled service is Akureyri, about 67 km in a straight line, with a considerably longer road distance around the peninsula. Strætó route 78 runs to and from Akureyri and cards are accepted on board. Winter closures matter here: this road has winter maintenance seven days a week, but the stretch north through Almenningar is windy and snowy, and official figures for 2010-2022 give an average of just over nine full days of closure a year across about 21 closure events, while the Lágheiði pass towards Skagafjörður is usually shut for most of the year.",
    culture:
      "Icelandic is spoken and English is widely understood. Under Icelandic consumer rules the displayed price is the final price: VAT and any charge of any name must already be included, so restaurants do not add a service charge at the till. Cold tap water is drinkable and very low in minerals. The hot tap smells of sulphur, which is hydrogen sulphide from the geothermal water; it reacts with oxygen in the pipes and protects the steel, and the heating hot water is not meant for drinking or cooking, cold water being a separate system. Debit and credit cards are accepted on rural buses.",
    seeAndDo:
      "The Herring Era Museum is the main draw, housed in those listed harbour buildings, the oldest dating from 1886. Within a few minutes' walk of the centre there is also a poetry centre, a folk music centre and an arts centre. The church by the fjord is worth seeing from outside. Walkers can head uphill on either side of town, towards Hafnarhyrna or Strákar. The bathing facility here is the municipal swimming pool rather than a hot spring; there are none in this fjord.",
    whenAndTips:
      "Summer is the safe choice. A winter visit should budget for closures: the road here has maintenance all week, but the stretch to the north and the pass towards Skagafjörður can both shut, so check the day's road report before setting out. Daylight varies sharply: on the Met Office's 1961-1990 thirty-year averages the regional reference station at Akureyri records about 1,047 hours of sunshine a year, about 177 of them in June and none at all in December. Bring windproof and waterproof layers, because weather in the fjord changes quickly.",
  },

  saudarkrokur: {
    identity:
      "Sauðárkrókur lies on the eastern shore at the southern end of Skagafjörður in northern Iceland and is the service and commercial centre for the district. The locality had 2,672 residents on 1 January 2026 (Statistics Iceland), making it the largest locality within its municipality by that measure. The town spreads across flat ground at the head of the fjord with terraces behind it, and the coast to the north is farming country with surviving turf-house buildings, an area that appears often in Iceland's medieval sources.",
    howItWorks:
      "The name on the map is a town, but its life as a government ended in 1998. In that year eleven municipalities around Skagafjörður merged into one, the former town council here among them; in 2022 the last neighbour that had stayed out joined too, and the new government took the name Skagafjörður. So the government that runs this town is named after the fjord, not after the town. On 1 January 2026 the municipality had 4,361 residents, 2,672 of them here. The council has nine seats, council size being set by population bracket and always odd, and the mayor is hired by the council rather than elected. The municipal offices are in the town, while the municipality's own folk museum has its main site in a group of turf houses about 16 km outside it in a straight line. One more local peculiarity: the municipality's town bus runs only between 15 November and 28 February, free of charge and open to everyone, fourteen stops and about fifteen minutes a circuit, and it does not run on days when the school is closed, making it a bus line that exists only in winter. The mistake newcomers make is to assume this town has a council of its own.",
    layout:
      "The town is concentrated on a small patch of flat ground at the head of the fjord and is walkable in a few streets: the municipal swimming pool about 430 m west-north-west of the centre, the district library about 550 m north-west, the church about 820 m north-west and an experience exhibition on medieval history about 1.1 km north-north-west, all straight-line distances. What needs a car lies outside town: the turf-house museum about 16 km south-south-east, a natural hot pool about 16 km north-north-west, an emigration museum about 20 km east-north-east in another village, and the steep-sided island in the fjord about 22.6 km due north.",
    gettingAround:
      "You turn off the ring road: Route 75 branches from Route 1 and runs into town, while Route 76 passes along the eastern shore of the fjord on its way north around Tröllaskagi. The town has an airport but no scheduled flights; there was once a service to Reykjavík, but the airline that flew it ceased operating in 2024. The nearest airport with scheduled service is Akureyri, about 72 km east in a straight line. The long-distance coach route 57 between Reykjavík and Akureyri stops in the town, as it does at Varmahlíð, roughly once a day each way; apart from that mainline stop there is no rural route covering the district, so without a car the journey has to be planned around those times. The town's own free bus runs only in winter. For winter road conditions look at the region: Route 1 crosses the Öxnadalsheiði pass at about 540 m and is rarely closed because it is kept open as a priority, whereas the Lágheiði pass north towards Tröllaskagi is usually shut for most of the year.",
    culture:
      "Icelandic is spoken and English is widely understood. Under Icelandic consumer rules the displayed price is final, with VAT and any charge of any name already included, so no service charge is added at the till. Cold tap water is drinkable. The hot tap smells of sulphur, hydrogen sulphide from the geothermal water that reacts with oxygen in the pipes and protects the steel; heating hot water is not for drinking or cooking. This is farming and horse country, so expect horses near the road and slow down when passing them. Cards are accepted on rural buses.",
    seeAndDo:
      "The turf-house museum about 16 km outside town in a straight line is the largest single site in the district; it is run by the municipality and consists of a dozen or so connected buildings whose walls use almost no stone, because there is little stone locally, and it usually needs a fair amount of time. In town there is the medieval-history exhibition, the district library and the church. North along the coast is a natural hot pool on private farmland, worth asking about before setting out, and further north a village with an emigration museum. The steep island in the fjord is reached by boat, with sailings depending on season.",
    whenAndTips:
      "Summer suits driving, while winter is the season when the town bus runs. On the Met Office's 1961-1990 thirty-year averages the inland reference station in the fjord records an annual mean of about 2.4°C and about 469 mm of precipitation a year, far drier than the south coast. Check road conditions before setting out, particularly for journeys over a pass. Accommodation and supplies are on a small-town scale, and many people treat the town as a stop on the way around Tröllaskagi.",
  },

  reykjahlid: {
    identity:
      "Reykjahlíð stands on the north-eastern shore of Lake Mývatn in northern Iceland and is the main settlement in this stretch of geothermal and volcanic ground. The locality had 270 residents on 1 January 2026 (Statistics Iceland); that figure moved from 251 to 270 in three years, so numbers at this scale should always be read with their date. Within a few kilometres of the village there are fissures, pseudo-craters, an explosion crater, boiling mud pools and a lava formation, and the lake together with the river to its west forms one of Iceland's most important habitats for water birds. Local histories record that in a volcanic episode in 1729 a lava flow buried the farm here but parted around the church.",
    howItWorks:
      "Mývatn is known across the country, and the government that runs it has its offices more than forty kilometres away. In 2022 the former municipality here merged with its neighbour into the present Þingeyjarsveit, whose main office is at Laugar, about 43 km to the south-west; all that remains locally is a branch office, and the municipality's own website marks it as temporarily closed, with staff attending elsewhere at hours published online. The merger has left a plain trace: the website files its annual accounts in three parallel sets, one for the present municipality and one for each of the two predecessors. On 1 January 2026 the municipality had 1,471 residents, 270 of them in this village. The council has seven seats and the mayor is hired by the council, whose employment contract this municipality publishes on its website. More important on the ground, whoever manages the land is not whoever manages the water: the lake and the river to its west have been protected since 2004 under a law of their own, covering a 200-metre-wide strip along the whole shore of the lake and both banks of the river, and administered by the national conservation agency, while the field of pseudo-craters on the southern shore, protected as a natural monument since 1973, is stated officially to be managed by the local landowners. The mistake newcomers make is to treat Mývatn as one unified \"park\", when within a few kilometres you are dealing with different managers and different rules.",
    layout:
      "The village sits at the north-eastern corner of the lake with several features within walking distance or a short drive, all figures below being straight-line distances: a fissure you can climb down into about 370 m due south, the church about 570 m north-north-west, a second water-filled fissure cave about 2.1 km south-east and a geothermal bathing site about 3.1 km east-south-east. Further east lies the geothermal ground: a mountain of about 490 m roughly 4.1 km due east, and the boiling mud pools and steam vents at its foot about 4.6 km due east. To the south are the volcanic features: a 452 m explosion crater about 4.4 km south-south-east, the lava formation about 5.9 km due south, and the pseudo-crater field on the southern shore about 9.5 km south-west. A bird museum stands across the lake about 4.2 km west-south-west, and about 10.3 km north-north-east is another volcanic area that is still active.",
    gettingAround:
      "Route 1, the ring road, passes the village, so no detour is needed to get here, but the sights are spread over a radius of about ten kilometres and doing without a car is limiting. The village has an airport, Mývatn Airport, but no scheduled flights; the nearest airport with scheduled service is Akureyri, about 53 km due west in a straight line. Snow is heavy here in winter and access depends chiefly on the state of Route 1, so check the day's road report before setting out. The village is small, and accommodation, fuel and supplies are on the scale of a few hundred residents, so do not count on anything being open late.",
    culture:
      "Icelandic is spoken and English is widely understood. Under Icelandic consumer rules the displayed price is final, with VAT and any charge already included, so no service charge is added at the till. Cold tap water is drinkable; the sulphur smell from the hot tap is especially noticeable here, being hydrogen sulphide from the geothermal water, which reacts with oxygen in the pipes and protects the steel, and the heating hot water is not for drinking or cooking. On geothermal ground stay on the marked paths: this is both a protection rule and a matter of what may be boiling just under the surface. Cards are accepted on rural buses.",
    seeAndDo:
      "The geothermal field a few kilometres east of the village is the most immediate stop, with boiling mud and hissing steam vents; the official tourist material puts temperatures there above 200°C, and you must keep to the marked paths. To the south is a 452 m explosion crater, protected as a natural monument since 2011 over an area of 3.78 km², whose rim may be climbed only by the two paths on the north-western and southern sides. Further south the lava formation is brittle and fragile, and the official tourist material says not to climb on it. The pseudo-crater field on the southern shore covers about 70 hectares and was formed where a thin lava flow crossed wet ground and the trapped water burst out as steam; there are visitor facilities by the road. The fissure cave near the village is no longer used for bathing, the water having warmed between 1975 and 1984. For a warm soak there is the geothermal bathing site east of the village, formerly the Mývatn Nature Baths, or Jarðböðin, and now officially named Earth Lagoon Mývatn. A bird museum stands across the lake.",
    whenAndTips:
      "This is the drier side of Iceland. On the Met Office's 1961-1990 thirty-year averages the local station records an annual mean of about 1.4°C, about -4.8°C in January and about 9.9°C in July, with about 435 mm of precipitation a year; by comparison the south-coast reference station records 1,372.6 mm, more than three times as much. Summer brings long days, easier roads and the greatest numbers of water birds, while winter is snowy and plans have to follow the road report. For the northern lights, the Icelandic Met Office puts it plainly: they require dark and partly clear skies, and those two conditions do not coincide every night. Note also that the Arctic Circle lies at 66°33'N and this village is south of it, so there is no true midnight sun or polar night here.",
  },

  hveragerdi: {
    identity:
      "Hveragerði lies in the southern lowlands of south-west Iceland, about 45 km east of the capital, and had 3,342 residents in the locality on 1 January 2026 (Statistics Iceland). Its most distinctive feature is stated in the municipality's own description: the geothermal field is in the middle of the town. Steaming ground and vents sit between the blocks, the town took up geothermal greenhouse horticulture early, and that is what it is known for in Iceland. In the valley to the north runs a warm river that is a popular end point for a walk.",
    howItWorks:
      "Among two decades of Icelandic municipal mergers this place is the counter-example: it was neither absorbed nor did it absorb anyone. A village formed here from 1929, it separated from the surrounding rural district to stand on its own in 1946, and became a town in 1987, remaining a municipality of its own ever since. The result is a very clean contrast: on 1 January 2026 the locality had 3,342 residents and the whole municipality 3,344, a difference of two people, so this government's territory is almost exactly the town itself. Iceland has only two tiers, municipality and state, with no province in between, and a region such as \"South Iceland\" is only a statistical and voluntary-cooperation unit. The price of not merging is that services have to be bought jointly: this small municipality belongs to four inter-municipal bodies covering social services, district affairs, waste and health inspection. The council has seven seats, its size set by population bracket and always odd, and the mayor is hired by the council rather than elected. The council meets on the first Thursday of each month at five in the afternoon in the municipal building, and the website states that the meetings are open to the public. The municipality is marking its eightieth anniversary in 2026. The mistake newcomers make is to treat the town as a suburb of the capital; it is indeed only forty-odd kilometres from Reykjavík, but administratively it is a complete and separate municipality.",
    layout:
      "The town is small and the main things are within walking distance, the figures below being straight-line distances: the art museum about 160 m south-south-east of the centre, the library and visitor information about 270 m south-south-west in a building that also holds an exhibition on the 2008 earthquake, the geothermal park in the town centre about 340 m due north, the ornamental garden about 490 m north-north-east, the church about 520 m due north, the 50-metre open-air pool about 560 m north-east and a geothermal vent about 1.1 km north-north-east. For the hot-spring valley north of town two different figures must be kept apart: the trailhead at the mouth of the valley is about 2.9 km north-north-west in a straight line, and from there it is a walk of about 3 km along the valley, that second figure being trail length rather than straight-line distance, to reach the bathable warm stretch of the river. About 6 km east is the western end of Ingólfsfjall, a ridge some eight kilometres long whose summit lies further east again.",
    gettingAround:
      "Route 1, the ring road, passes the edge of town, about forty-odd minutes' drive from the capital. There is no airport with scheduled flights in the town: Keflavík, which handles international flights, is about 69 km away in a straight line, and the domestic airport at Reykjavík about 40 km. The town centre is walkable, and for the hot-spring valley you drive to the car park at the valley mouth and walk from there. The climate is that of the southern lowlands, far wetter than the north and relatively mild in winter but windy; in winter go by the day's road report.",
    culture:
      "Icelandic is spoken and English is widely understood. Under Icelandic consumer rules the displayed price is final, with VAT and any charge of any name already included, so no service charge is added at the till. Cold tap water is drinkable; the hot tap smells of sulphur, hydrogen sulphide from the geothermal water which reacts with oxygen in the pipes and protects the steel, and heating hot water is not for drinking or cooking. Horticulture and the use of geothermal heat are local industries, and geothermally heated greenhouses are visible around the town. Cards are accepted on rural buses.",
    seeAndDo:
      "The geothermal park in the town centre allows a close look at vents and steam, which is unusual inside an Icelandic town. The art museum and the exhibition on the 2008 earthquake are both within a few hundred metres of the centre, the latter in a building that also holds the library and visitor information. The 50-metre open-air pool is a local institution. The hot-spring valley to the north is the most popular walk: from the car park at the valley mouth it is about 3 km along the valley to the warm stretch of river, with little climb but real need for windproof and waterproof layers, and the ground beside the path is geothermal, so do not leave the path.",
    whenAndTips:
      "This is the wet side of Iceland. On the Met Office's 1961-1990 thirty-year averages the south-coast reference station about 20 km away in a straight line records 1,372.6 mm of precipitation a year and an annual mean of about 4.1°C, against 435 mm by Lake Mývatn in the north, a threefold difference within one country. Bring a waterproof jacket, in summer as well. The hot-spring valley can be walked year-round, but in winter the path ices up and darkness comes early, so start early. Pack a dry bag for your clothes before getting into the warm river, because there are no changing facilities in the valley.",
  },
};
