import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "latvia-overview": {
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; Law on Administrative Territories and Populated Areas, likumi.lv tier 1; ECB tier 1; Road Traffic Regulations §160 tier 1; LSM tier 2; vivi.lv tier 1, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，人口经 CSP API 直查，全部 ok）。
    identity:
      "Latvia is a country on the eastern shore of the Baltic Sea, bordered by Estonia to the north and facing the Baltic and the Gulf of Riga to the west; on 1 January 2026 its population was about 1.845 million (Central Statistical Bureau of Latvia). The land is low — its highest point is only about 312 m — with glacial hills and lakes in the east, plains in the centre, and long beaches and pine forest along the coast; the capital, Riga, stands at the head of the Gulf of Riga near the mouth of the Daugava.",
    howItWorks:
      "Latvia has a single tier of local government: after the 2021 reform the country was consolidated into 43 local governments, and after Varakļāni Municipality merged into Madona Municipality in July 2025 there are 42 — 7 are the governments of state cities (Riga, Daugavpils, Liepāja, Jelgava, Jūrmala, Ventspils and Rēzekne) and 35 are municipalities (novadi), each run by an elected council. There are also 5 planning regions responsible for regional development planning, but they are not a tier of government. Many municipalities have their administrative centre inside a state city while remaining separate governments: the city of Jelgava runs the town, and the surrounding Jelgava Municipality has a council of its own. Locals describe places by city and municipality, adding regional names such as Kurzeme, Zemgale, Vidzeme and Latgale. Riga sets the radius of life: international flights, railways and long-distance coaches all centre on it. Newcomers most often go wrong by assuming they can fly around the country — there are currently no scheduled domestic passenger flights, and cities are linked by train, coach and car.",
    layout:
      "Riga lies in the middle at the head of the Gulf of Riga, with Jūrmala stretching along the shore to its west; Kurzeme in the west faces the open Baltic and holds Liepāja, Ventspils and Kuldīga; Zemgale in the south-centre is plain country centred on Jelgava; Vidzeme in the north-east has the Gauja valley and hills, with Sigulda and Cēsis; Latgale in the south-east is lake country, and its largest city is Daugavpils.",
    gettingAround:
      "Riga International Airport is the only airport in the country with scheduled passenger flights, and it lies outside the Riga city boundary in Mārupe Municipality. There are no scheduled domestic passenger flights. Trains, run by Vivi, go from Riga to Jūrmala, Jelgava, Sigulda, Cēsis, Daugavpils and Liepāja; Ventspils and Kuldīga have no passenger railway and are reached by long-distance coach. Driving is on the right, and daytime running lights or dipped headlights are required in daylight all year round. Latvia has used the euro since 1 January 2014 and joined the Schengen Area in 2007.",
    culture:
      "The official language is Latvian, and English is widely spoken in tourism. The midsummer festival around 23–24 June (Līgo / Jāņi) is one of the most important folk festivals of the year, with flower wreaths, bonfires and staying up to greet the sunrise. Rye bread, smoked fish and grey peas with bacon are traditional foods. Tipping is not obligatory, and a service charge is sometimes already itemised on the bill, so check the receipt first. Electricity is 230 V with European two-pin round plugs.",
    seeAndDo:
      "Historic towns: Old Riga and its Art Nouveau district, Kuldīga Old Town, the medieval castles of Cēsis and Sigulda, Jelgava Palace and Rundāle Palace near Bauska, and Daugavpils Fortress. Nature: the sandstone valley of Gauja National Park, the bog boardwalk in Ķemeri National Park, the sea cliffs and Cape Kolka in Kurzeme, the lakes of Latgale and the Daugava Bends. Latvia has 3 World Heritage sites: the Historic Centre of Riga, survey points of the Struve Geodetic Arc and Kuldīga Old Town.",
    whenAndTips:
      "June to August has the longest days and the liveliest coast, and many shops and offices close around midsummer; May and September are quieter and cool, and the autumn colours of the Gauja valley in September–October are well known; winter is cold with short days, and Sigulda has a bobsleigh track. Allow time for coaches to Ventspils and Kuldīga in the west. Drivers going to Jūrmala pay an entry fee at the city entrance.",
  },
  riga: {
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; UNESCO whc 852 tier 1; latvia.travel tier 1; Riga International Airport and Rīgas satiksme tier 1; en.wikipedia tier 3 for council term and districts, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，人口经 CSP API 直查，全部 ok）。
    identity:
      "Riga, the capital of Latvia, stands at the head of the Gulf of Riga near the mouth of the Daugava; on 1 January 2026 it had about 589,000 people (Central Statistical Bureau of Latvia). Founded as a port town in 1201, it was an important Hanseatic centre in eastern Europe from the 13th to the 15th century, and its old town together with its Art Nouveau buildings of the 19th and early 20th centuries was inscribed on the World Heritage List in 1997 as the Historic Centre of Riga.",
    howItWorks:
      "Riga is a state city run by an elected city council, which is re-elected every four years and chooses the mayor. For administration the city is divided into 6 districts — the Central, Kurzeme and Northern districts, and the Latgale, Vidzeme and Zemgale suburbs — and for planning it is further divided into 58 neighbourhoods (apkaimes). The heart of the city is the old town on the right bank of the Daugava, with the central district that grew outwards from the 19th century right beside it; the railway station, coach station and Central Market are grouped at the south-east corner of the old town, while the left bank, known as Pārdaugava, holds the National Library. The radius of daily life is set by buses, trams and suburban trains. Newcomers most often go wrong by assuming the airport is in the city — it is actually in Mārupe Municipality outside the city boundary, about 8.8 km in a straight line from the centre, and bus 22 runs into town.",
    layout:
      "The old town lies on the right bank of the Daugava, with the castle, the cathedral, St Peter's Church and the House of the Blackheads packed into its streets; east of it is a belt of parks along the city canal with the Freedom Monument, and beyond that the central district built in the 19th century, where Art Nouveau buildings cluster around Alberta iela; south-east of the old town are the central railway station, the international coach station and the Central Market; across the river on the left bank are the National Library and residential areas; the airport is to the south-west in Mārupe Municipality.",
    gettingAround:
      "Riga International Airport is the only airport in the country with scheduled passenger flights, and bus 22 links it with the city centre. The city has buses, trolleybuses and trams, and the old town is best on foot. Trains from the central station go to Jūrmala, Sigulda, Cēsis, Jelgava, Daugavpils and Liepāja; for Ventspils and Kuldīga take a long-distance coach from the international coach station, about 500 m from the railway station.",
    culture:
      "Latvian is spoken, and English is widespread. The medieval lanes of the old town and the Art Nouveau facades of the central district are the city's two calling cards; St Peter's Church is a Gothic church begun in the 13th century, and its tower looks out over the old town. The Central Market was converted from several Zeppelin hangars and is the place to buy smoked fish, rye bread and seasonal produce.",
    seeAndDo:
      "Old town: Riga Cathedral, St Peter's Church, the House of the Blackheads and the exterior of Riga Castle. Central district: the Freedom Monument and canal parks, the Art Nouveau buildings around Alberta iela, and the Central Market. Across the river: the National Library of Latvia. Day trips: take the train to the beach at Jūrmala, or to the Gauja valley at Sigulda.",
    whenAndTips:
      "June to August has the longest days and the busiest outdoor cafés in the old town; December brings Christmas markets; winter is cold and pavements ice over. The old town is largely cobbled, so flat, non-slip shoes help. Tickets for bus 22 from the airport can be bought from the driver, but only by bank card.",
  },
  daugavpils: {
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; daugavpils.lv history tier 1; latvia.travel tier 1; vivi.lv tier 1; en.wikipedia tier 3 for the museum opening and the 19th-century plan, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Daugavpils lies in Latgale in south-eastern Latvia, with the Daugava flowing past the city; on 1 January 2026 it had about 77,000 people and, by city population in the figures of the Central Statistical Bureau of Latvia, it is the country's second-largest city. Its signature landmark is the fortress built in the 19th century; the painter Mark Rothko was born in the city, and a museum named after him now stands inside the fortress.",
    howItWorks:
      "Daugavpils is a state city run by an elected city council; it is also the administrative centre of the surrounding Augšdaugava Municipality, but the city and the municipality are separate governments. The city has two centres: one is the new town centre laid out in the 19th century south-east of the fortress, with a grid of streets, Unity House and the main shopping streets; the other, to the north-west, is the fortress itself, where the area inside the walls is still a district of streets and homes. The Daugava divides the city into two banks; the Grīva area on the left bank was later joined to the city, and the Unity Bridge links the two sides. The radius of daily life is set by trams and buses, and the city has a tram network. Newcomers most often go wrong by treating the fortress as just a sight — it is a neighbourhood where people still live.",
    layout:
      "The city centre is on the right bank of the Daugava, its grid of streets around Unity House; the fortress is north-west of the centre, also on the right bank, and the Rothko Museum occupies its artillery arsenal; the Unity Bridge crosses the Daugava southwards to Grīva on the left bank; lakes and forest surround the city, and the Daugava Bends Nature Park lies not far to the east.",
    gettingAround:
      "There is no airport with scheduled flights here; flights go through Riga International Airport, about 195 km away in a straight line. About 6 trains a day run from Riga to Daugavpils, taking about 2 h 48 min to 3 h 18 min, and there are also long-distance coaches. The city has trams and buses, and the fortress is about 2 km from the centre in a straight line.",
    culture:
      "Daugavpils is the cultural centre of Latgale; Unity House, completed in 1937, is a combined building with a theatre, a concert hall and a library. The Rothko Museum has a permanent display of original works by Mark Rothko and also holds contemporary art exhibitions. Latgale has a long tradition of ceramics.",
    seeAndDo:
      "The walls, gates and arsenal of Daugavpils Fortress; the Rothko Museum; Unity House and the pedestrian streets of the centre; the view of the Daugava from the Unity Bridge. Day trips: the Daugava Bends Nature Park to the east, looking over the Rozališķi meander from the Vasargelišķi tower; the Latgale lake district.",
    whenAndTips:
      "May to September is best for the fortress and the riverside; winter is cold. Most visitors from Riga come by train, so allow the better part of a day. For the Daugava Bends and the lakes, a car or hired driver is more convenient than public transport.",
  },
  liepaja: {
    // whenAndTips sources（2026-09-15 核实，fix）: 同上
    // gettingAround sources（2026-09-15 核实，fix）: vivi.lv 新闻「No Liepājas uz Rīgu un atpakaļ katru dienu」（1 级，2026-07：自 2026-07-31 起每日各方向 1 班、周日加开，约 3 h 04–3 h 07）与 vivi.lv 2026-09-02 生效的叶尔加瓦—利耶帕亚线时刻表 PDF（1 级，13.55→17.11、18.20→21.39 两个车次，周日班次标注未逐一核）并存；正文写「一两班、部分只在周日」并指向最新时刻表
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; liepaja2027.lv tier 1; latvia.travel tier 1; LSM tier 2; vivi.lv tier 1; 1188.lv tier 2; en.wikipedia tier 3 for the canal and Karosta dates, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，里加—利耶帕亚火车班次两份官方来源不一致，改为「一两班」并指向最新时刻表，其余 ok）。
    identity:
      "Liepāja is a port city on the Kurzeme coast of western Latvia, squeezed between the Baltic Sea and Lake Liepāja; on 1 January 2026 it had about 67,000 people (Central Statistical Bureau of Latvia). It is known for its sea wind, its music and its long beach — locals call it \"the city where the wind is born\" — and it will be a European Capital of Culture in 2027.",
    howItWorks:
      "Liepāja is a state city run by an elected city council; the land outside the city belongs to South Kurzeme Municipality, whose administrative centre is Grobiņa, not Liepāja. A trade canal splits the city in two: south of the canal is Old Liepāja, with the old town, the market, Holy Trinity Cathedral and the Great Amber concert hall; north of it is New Liepāja; and further north along the coast is Karosta, a naval port district built in the late 19th and early 20th centuries. Locals give directions by these three districts. The radius of daily life is set by trams, buses and bicycles, and the beach and Seaside Park are a walk west of the old town. Newcomers most often go wrong by assuming Liepāja's airport has flights — it has had no scheduled passenger flights since September 2020.",
    layout:
      "Old Liepāja lies south of the canal, its old-town streets bordered by Lake Liepāja to the east and Seaside Park and the beach to the west; the Great Amber concert hall stands on the south bank of the canal; New Liepāja is north of the canal; Karosta is at the northern end of the city, with buildings such as St Nicholas Naval Cathedral; the main body of Lake Liepāja lies south of the city in South Kurzeme Municipality.",
    gettingAround:
      "Liepāja Airport currently has no scheduled passenger flights. Riga International Airport is about 186 km away in a straight line; the nearest airport with scheduled flights is Palanga in Lithuania, about 60 km away in a straight line. Trains from Riga to Liepāja are few: as of September 2026 there are only one or two a day (some run on Sundays only), taking a little over 3 hours, so check the latest timetable from the rail operator Vivi before setting out; long-distance coaches take about 3 h to 3 h 45 min. Ferries sail several times a week to Travemünde in Germany. The city has trams and buses.",
    culture:
      "The Liepāja Symphony Orchestra is based at the Great Amber concert hall, whose amber-coloured glass facade has become a new city landmark; the city has more than 70 Art Nouveau buildings. A local saying runs: \"Warm up so you can go back out into the wind.\" Summer brings music festivals and beach events, and the 2027 European Capital of Culture will bring cultural projects throughout the year.",
    seeAndDo:
      "The Great Amber concert hall, Holy Trinity Cathedral, the wooden and Art Nouveau buildings of the old town, Seaside Park and the wide beach; St Nicholas Naval Cathedral and the coastal breakwater in Karosta to the north. Day trips: Pape Nature Park and Lake Pape to the south, and the Jūrkalne cliffs to the north.",
    whenAndTips:
      "June to August is the busiest time on the beach, but the wind is strong and the water cold; May and September are quieter. If coming by train, check that day's departures first, as there are very few. Wind is normal here, so bring a windproof jacket in any season.",
  },
  jelgava: {
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; latvia.travel Jelgava tier 1; vivi.lv tier 1; en.wikipedia and OSM tier 3 for the palace architect, riverside setting and Rundāle location, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Jelgava is a city on the Zemgale Plain in south-central Latvia, on the Lielupe about 40 km in a straight line from central Riga; on 1 January 2026 it had about 54,000 people (Central Statistical Bureau of Latvia). It was once the capital of the Duchy of Courland, and Jelgava Palace by the river, the former residence of the dukes, now houses the Latvia University of Life Sciences and Technologies.",
    howItWorks:
      "Jelgava is a state city run by an elected city council; it is also the administrative centre of the surrounding Jelgava Municipality, but the city and the municipality are separate governments, each with its own council. The centre lies on the right bank of the Lielupe: the palace stands on the castle-island side of the river, the old town lies south-west of it, and the tower of Holy Trinity Church and the Academia Petrina building are the old town's reference points. Jelgava is a university town, with the campus in the palace itself. The radius of daily life is tied closely to Riga, a little over forty minutes away by train. Newcomers most often go wrong by assuming that nearby Rundāle Palace is in Jelgava — it is in fact in Bauska Municipality to the south, about 32 km from Jelgava in a straight line.",
    layout:
      "The city sits on the flat Zemgale Plain, with the Lielupe running along its eastern side; Jelgava Palace is by the river, the old town is south-west of the palace with the Holy Trinity Church tower and Academia Petrina within it; the railway station is south of the old town; and wide farmland surrounds the city.",
    gettingAround:
      "Trains from Riga to Jelgava take about 42–48 minutes and run fairly often; Jelgava is also a stop on the train to Liepāja. Riga International Airport is about 33 km away in a straight line. Buses are the main transport in town, and the old town and palace are within walking distance of each other. Rundāle Palace can be reached by car or coach.",
    culture:
      "Jelgava Palace was the residence of the Dukes of Courland and still holds the ducal family crypt; the Academia Petrina building is now a museum of history and art, with a viewing balcony in its tower. The Holy Trinity Church tower has been turned into a lookout, with a platform 37 m high over the city and the plain. Every summer the city holds events such as a sand sculpture festival.",
    seeAndDo:
      "Jelgava Palace and the ducal crypt, the Holy Trinity Church tower lookout, Academia Petrina (the museum of history and art), and the Lielupe riverside promenade. Day trips: Rundāle Palace and Bauska Castle ruins in Bauska Municipality.",
    whenAndTips:
      "May to September is best for the riverside and palace gardens. Jelgava combines well with Rundāle Palace and Bauska as a day trip from Riga.",
  },
  jurmala: {
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; visitjurmala.lv tier 1; latvia.travel tier 1; Nature Conservation Agency tier 1; en.wikipedia and OSM tier 3 for the resort sequence and the boardwalk location, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Jūrmala is a seaside resort city west of Riga, stretching along the Gulf of Riga; on 1 January 2026 it had about 53,000 people (Central Statistical Bureau of Latvia). It is made up of more than a dozen resort villages strung along the coast, and Latvia's tourism agency speaks of nearly 25 km of white sand beach; Majori is the city centre, and the wooden villas and cafés of Jomas iela are its most familiar image.",
    howItWorks:
      "Jūrmala is a state city with its own elected council, not a district of Riga. The city is long and narrow, squeezed between the Gulf of Riga and the Lielupe, and from east to west runs through resorts such as Lielupe, Bulduri, Dzintari, Majori, Dubulti, Sloka and Ķemeri, whose names locals use to give directions. The railway ties it together: there are 14 stations within the city, and the train from Riga takes 20–50 minutes depending on the destination. Majori is the centre and home to the tourist information centre. Drivers should note that motor vehicles entering the special regime zone pay an entry fee, which in 2026 is 5 euros per vehicle per day. Newcomers most often go wrong by thinking Jūrmala is just a beach — it is a city in its own right, with neighbourhoods, sanatoriums and forest behind the sand.",
    layout:
      "The city stretches along the southern shore of the Gulf of Riga, with the beach to the north and the Lielupe to the south; Lielupe and Bulduri at the eastern end are closest to Riga, Dzintari and Majori in the middle are the busiest stretch, with Jomas iela in Majori; Ķemeri at the western end borders Ķemeri National Park and has old spa buildings and a water tower.",
    gettingAround:
      "Take a train from Riga Central Station towards Tukums; it takes about half an hour to Majori. Riga International Airport is about 12 km from Jūrmala in a straight line. Within the city it is easiest to move between railway stations, and the beach is good for walking or cycling. Drivers entering the special regime zone pay an entry fee at the entrance, 5 euros per vehicle per day in 2026.",
    culture:
      "Jūrmala grew into a seaside health resort from the nineteenth century and has kept many wooden villas; the Dzintari Concert Hall holds concerts in summer. The Ķemeri area has a tradition of sulphur springs and mud treatments. The beach is crowded in summer, but the Baltic is cool and the swimming season is short.",
    seeAndDo:
      "Jomas iela and the beach at Majori, the Dzintari Concert Hall, the Jūrmala Open-Air Museum at the eastern end, and the Ķemeri water tower and old spa quarter at the western end. Nearby: the Great Ķemeri Bog boardwalk in Ķemeri National Park, outside the Jūrmala city boundary in Tukums Municipality.",
    whenAndTips:
      "June to August is the busiest time, with crowded trains at weekends; May and September are quiet. The coast is windy and evenings cool noticeably. For the Ķemeri bog boardwalk, set out in the morning and bring insect repellent in summer.",
  },
  ventspils: {
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; latvia.travel tier 1; vivi.lv tier 1; 1188.lv tier 2; Ventspils airport history page tier 1; en.wikipedia tier 3 for the castle museum, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Ventspils is a port city in north-western Latvia at the mouth of the Venta on the Baltic Sea; on 1 January 2026 it had about 32,000 people (Central Statistical Bureau of Latvia). It combines a port and a beach: port areas line both banks of the river mouth, a long sandy beach runs to the west, and the old town gathers around a medieval castle of the Livonian Order.",
    howItWorks:
      "Ventspils is a state city run by an elected city council; it is also the administrative centre of the surrounding Ventspils Municipality, but the city and the municipality are separate governments. The city's structure follows the river mouth: the port lines both banks, the old town and castle are on the south bank with the port promenade running along the river beside the castle, and south-west of the old town is the seaside district with the Seaside Open-Air Museum and the beach. Locals give directions by old town, port and seaside. The radius of daily life is set by walking, cycling and buses in a compact city. Newcomers most often go wrong by expecting to arrive by train or plane — there is no passenger railway and the airport has no scheduled passenger flights, so from Riga it is about three hours by coach or car.",
    layout:
      "The Venta flows in from the south-east and reaches the sea on the north side of the city, with port areas on both banks of the mouth; the old town is on the south bank, with Ventspils Castle right by the river; south-west of the old town are the seaside district and the beach, with the breakwaters and lighthouse at the north-western end by the river mouth; forest surrounds the city.",
    gettingAround:
      "Ventspils has no passenger railway, and its airport has no scheduled passenger flights. Long-distance coaches from Riga take about 2 h 40 min to 3 h 50 min, most about 3 hours; Riga International Airport is about 154 km away in a straight line. The city is compact enough for walking and cycling; in summer a narrow-gauge sightseeing train runs in the seaside park.",
    culture:
      "The castle dates from the time of the Livonian Order and is now a museum. Twenty-eight painted \"Cow Parade\" sculptures are scattered around the city, and buoys and an old pilot boat are displayed along the port promenade. The beach has held Blue Flag status since 1999.",
    seeAndDo:
      "Ventspils Castle museum, the port promenade, the Seaside Open-Air Museum and narrow-gauge train, the Blue Flag beach and the breakwaters at the river mouth. Nearby: the Irbene radio telescope in Ventspils Municipality; to the north, Slītere National Park and Cape Kolka.",
    whenAndTips:
      "June to August is the liveliest time on the beach and in the seaside park; the rest of the year is windy. Coaches are not very frequent, so check return times in advance. Ventspils fits well into a Kurzeme loop with Kuldīga and Cape Kolka.",
  },
  sigulda: {
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; MK Nr. 418 tier 1; Nature Conservation Agency tier 1; latvia.travel tier 1; vivi.lv tier 1; en.wikipedia tier 3 for castle dates and town extent, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Sigulda is a small town about 50 km in a straight line north-east of Riga, beside the Gauja valley in the western part of Gauja National Park; on 1 January 2026 the town had about 15,000 people and Sigulda Municipality about 32,000 (Central Statistical Bureau of Latvia). The sandstone cliffs of the valley, its medieval castles and its autumn colours make it one of the most common day trips from Riga.",
    howItWorks:
      "Sigulda is the administrative centre of Sigulda Municipality, and the town and the surrounding countryside are governed together by an elected municipal council; for planning purposes it belongs to the Riga Planning Region. The Gauja valley splits the town in two: on the south-eastern bank are the town itself, the railway station and Sigulda Medieval Castle; on the north-western bank are Turaida Castle and Krimulda Manor, and the two sides are linked by a road bridge and a cable car across the valley. Locals give directions by Turaida, Krimulda and the town. Daily life is linked to Riga, a little over forty minutes away by train. Newcomers most often go wrong by assuming the castles, caves and bobsleigh track are all packed into a small town centre — they are spread across both sides of the valley, with real climbs and distances between them.",
    layout:
      "The town stands on high ground on the south-eastern side of the Gauja valley, where the railway station and Sigulda Medieval Castle are, with the bobsleigh track on the valley slope west of the town; the Gauja flows from north-east to south-west along the valley floor, with Gūtmaņala below the slope on the north-western bank; Turaida Castle and Krimulda Manor stand on the high ground of the north-western bank.",
    gettingAround:
      "Trains from Riga to Sigulda take about 43 minutes to 1 hour 8 minutes; Riga International Airport is about 59 km away in a straight line. The town can be walked; to reach Turaida across the river take a bus, or ride the cable car across the valley and continue on foot. The valley sides are steep, so allow time for hiking.",
    culture:
      "Sigulda is one of the gateways to Gauja National Park, established in 1973 as Latvia's first national park. The town's bobsleigh track is 1,420 m long with 16 bends and is open to visitors for rides in both winter and summer. The museum reserve around Turaida Castle preserves the castle, a church and manor buildings.",
    seeAndDo:
      "Turaida Castle and museum reserve, Sigulda Medieval Castle, Gūtmaņala cave, Krimulda Manor, the bobsleigh track, the cable car across the valley, and the trails along the Gauja valley.",
    whenAndTips:
      "Late September to mid-October brings the best autumn colour in the valley and crowds at weekends; summer suits hiking and canoeing; winter offers rides on the bobsleigh track. Valley trails are slippery after rain, so wear non-slip shoes.",
  },
  cesis: {
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; MK Nr. 418 tier 1; latvia.travel tier 1; vivi.lv tier 1; en.wikipedia tier 3 for the chronicle date, Hanseatic membership and old-town layout, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Cēsis is a small town in the Vidzeme region of north-eastern Latvia, in the eastern part of Gauja National Park; on 1 January 2026 the town had about 15,000 people and Cēsis Municipality about 41,000 (Central Statistical Bureau of Latvia). Latvia's tourism agency describes it as more than 800 years old and one of the best-preserved medieval towns in the Baltic region; its castle ruins and old-town lanes are its core.",
    howItWorks:
      "Cēsis is the administrative centre of Cēsis Municipality, and the town and the surrounding countryside are governed together by an elected municipal council. The heart of the town is the old town: the castle ruins and castle park are on its western side, St John's Church is in the middle, and Unity Square on its eastern edge is where the old town meets the newer town. The old town keeps its medieval street pattern, and locals give directions by the castle, the square and the church. The radius of daily life is set by walking and buses, and the old town can be walked in an hour or two. Newcomers most often go wrong by taking the population of \"Cēsis\" as that of one town — on 1 January 2026 the town itself had about 15,000 people, while about 41,000 was the whole of Cēsis Municipality including the surrounding countryside and small towns.",
    layout:
      "The old town stands on high ground by the Gauja valley, with the castle ruins and castle park on its western side next to an ancient hillfort; St John's Church is in the middle of the old town and Unity Square on its eastern edge; the Gauja and its sandstone cliffs lie to the north-west of the town; about 7 km south of the town, a reconstructed wooden lake fortress stands on Lake Āraiši.",
    gettingAround:
      "Cēsis is on the Riga–Valga railway, and trains from Riga take about 1 h 11 min to 1 h 52 min; Riga International Airport is about 90 km away in a straight line. The old town is walkable; for the Āraiši Lake Fortress and the Gauja valley trails a car or bicycle is more convenient.",
    culture:
      "Cēsis Castle is the ruin of a stone castle from the time of the Livonian Order, and from May to October the castle hosts demonstrations of medieval crafts and a vegetable garden. The Āraiši Lake Fortress is a wooden lake settlement reconstructed from archaeological finds. In summer the old town often hosts art festival events.",
    seeAndDo:
      "Cēsis Castle ruins and castle park, St John's Church, the old-town lanes and Unity Square, and the sandstone cliff trails along the Gauja. Nearby: the Āraiši Lake Fortress archaeological park.",
    whenAndTips:
      "May to October offers the most at the castle; late September to October brings good autumn colour in the valley. Cēsis pairs well with Sigulda for two days in the Gauja valley, by train from Riga.",
  },
  kuldiga: {
    // seeAndDo sources（2026-09-15 核实，fix）: latvia.travel Riežupe Sand Caves page (1级，2026-09-15访问："a 2-kilometer-long underground labyrinth created by human hands... the maze 460 meters long" 官方口径就是「2公里」，没有「多」)
    // 全七段 sources: 同中文侧（CSP IRS031 tier 1; Ministry of Foreign Affairs of Latvia tier 1; UNESCO whc 1658 tier 1; vivi.lv tier 1; 1188.lv tier 2; latvia.travel tier 1, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，里耶祖佩沙洞「2 公里多」改为约 2 公里，其余 ok）。
    identity:
      "Kuldīga is a small town in the Kurzeme region of western Latvia, at the confluence of the Venta and the Alekšupīte stream; on 1 January 2026 the town had about 9,900 people and Kuldīga Municipality about 26,000 (Central Statistical Bureau of Latvia). In 2023 Kuldīga Old Town was inscribed on the World Heritage List as Latvia's third World Heritage site, and the Venta Rapid, a broad fall stretching across the Venta beside the town, is its most familiar image.",
    howItWorks:
      "Kuldīga is the administrative centre of Kuldīga Municipality, and the town and the surrounding countryside are governed together by an elected municipal council; the World Heritage old town is managed jointly by the municipality and the Kuldīga Restoration Centre. As UNESCO describes it, the old town is built up in layers: the castle hill terrace with 13th-century origins, the medieval Kalnamiests quarter whose oval outline can still be traced, and the town that grew in the time of the Duchy of Courland — this was the main residence and administrative centre of the duchy's first duke. The Alekšupīte runs through the middle of the old town, flowing along the walls of houses towards the Venta, and Town Hall Square is where locals take their bearings. Daily life is compact, and the old town can be walked end to end. Newcomers most often go wrong by expecting to arrive by train — there is no passenger railway, and the coach from Riga takes about two and a half to three and a half hours.",
    layout:
      "The old town lies on the west bank of the Venta, with Town Hall Square at its centre and the Alekšupīte running through it to join the Venta near the rapid; the Venta Rapid is on the Venta to the east, with the brick bridge built in the second half of the 19th century a short way downstream; the castle hill stands on the high bank beside the rapid; the Riežupe Sand Caves are about 4 km north of the town.",
    gettingAround:
      "Kuldīga has no passenger railway; long-distance coaches from Riga take about 2 h 30 min to 3 h 27 min, and Riga International Airport is about 122 km away in a straight line. The old town and the rapid are within walking distance; for the Riežupe Sand Caves, Ventspils or the coast, a car is most convenient.",
    culture:
      "The old town keeps its wooden and masonry houses, red-tiled roofs and a street pattern going back to the Middle Ages; UNESCO notes that the Venta Rapid was crucial to Kuldīga's development as a trading centre. In summer people often wade along the shallow rock step at the edge of the rapid, and in spring the sight of fish leaping up the falls is a seasonal feature of the town.",
    seeAndDo:
      "The Venta Rapid and brick bridge, Town Hall Square and the old-town lanes, the houses along the Alekšupīte and the Alekšupīte waterfall, and the castle hill park. Nearby: the Riežupe Sand Caves, with about 2 km of underground passages, and the Venta valley nature reserve.",
    whenAndTips:
      "May to September is best, with crowds at summer weekends; the rapid is widest in spring when the water is high. Coaches are limited, so drive or stay a night in town and combine it with Ventspils and the Jūrkalne cliffs on a Kurzeme trip.",
  },
  valmiera: {
    // 全七段 sources: 同中文侧（CSP IRS031 2026-01-01, tier 1; Law on Administrative Territories and Populated Areas, likumi.lv, tier 1; Valmiera municipality website history, theatre and train news, tier 1; Central Finance and Contracting Agency, tier 1; distances computed）。 核实 2026-09-16 当批（content-verifier 独立检索，老城与火车站的东西岸方位疑写反，改为不写方位的「隔河相对」，其余 ok）。
    identity:
      "Valmiera is a town in Vidzeme in northern Latvia, divided by the Gauja river, with about 22,700 people in the town itself and about 50,300 in Valmiera Municipality on 1 January 2026 (Central Statistical Bureau of Latvia). First mentioned in writing in 1323, it had a castle of the Livonian Order and belonged to the Hanseatic League in the Middle Ages, and today it is one of Vidzeme's centres for transport and education.",
    howItWorks:
      "In law Valmiera is one of Latvia's ten 'state cities', yet it has no government of its own: since 2021 it has been merged with seven former municipalities around it into Valmiera Municipality, governed by an elected municipal council, whose territory also includes four other towns and more than twenty rural parishes over nearly 3,000 km². That is the key difference from state cities such as Liepāja and Daugavpils, which have their own governments. The centre is the old town beside the Gauja, where St Simon's Church, the castle ruins and museum and the theatre stand close together, the castle built on high ground between the Gauja and the deep valley of a tributary. Locals find their way by the church, the river and the railway station. Daily life stretches along the Gauja valley and the railway, with Cēsis twenty-odd kilometres to the south. Newcomers often assume a 'state city' must govern itself like Riga, or count the whole municipality's population as the town's.",
    layout:
      "The old town stands on high ground beside the Gauja, grouping St Simon's Church, the ruins of the Livonian Order castle, Valmiera Museum and the theatre; the Gauja runs through the town with parks and paths along its banks. Newer districts spread along both sides of the river, with the railway station on the other side of the river from the old town. South along the Gauja valley are Cēsis and Sigulda, and to the north lie the farmland and forests of Vidzeme.",
    gettingAround:
      "There is no airport with scheduled flights here; scheduled flights go through Riga International Airport (RIX), about 111 km away in a straight line. Valmiera is on the Riga–Valga railway, and since January 2026 the Tallinn–Tartu–Riga international train also stops here. Buses and walking cover the town, and the old town is walkable.",
    culture:
      "Latvian is spoken, and English is widely used among younger people. Valmiera Theatre counts 1923, when regular professional performances began, as its founding year, and it reopened after major renovation in 2024. The renovated tower of St Simon's Church has a viewing platform over the Gauja valley and the town.",
    seeAndDo:
      "St Simon's Church and its tower viewing platform; the ruins of the Order castle and Valmiera Museum; a walk along the Gauja riverside paths; a performance at Valmiera Theatre; and a trip south along the Gauja valley to Cēsis and Sigulda.",
    whenAndTips:
      "May–September is the most comfortable, with boating on the Gauja in summer; winters are cold with short days. International trains run only a few times a day, so check the operator's timetable before travelling.",
  },

  rezekne: {
    // 全七段 sources: 同中文侧（Central Statistical Bureau IRS031 at 1 January 2026, tier 1; National Encyclopaedia of Latvia on the two governments in the city, the landscape and the river, tier 2; city tourism site on the castle, tier 1; Vivi timetable effective 2 September 2026, tier 1; OurAirports; distances computed）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧）。
    identity:
      "Rēzekne stands on the northern edge of the Latgale upland in eastern Latvia, with 25,978 people in the city at the start of 2026 (Central Statistical Bureau) — seventh among Latvian cities on that same table. The city sits in the hollow of the Rēzekne river, ringed by hills, with the river splitting it roughly in two; that 116-kilometre river links Latvia's two largest lakes, Rāzna and Lubāns.",
    howItWorks:
      "The striking thing here is that two governments sit in the same city. Rēzekne is one of Latvia's ten state cities and one of the seven that have their own local government and council; at the same time the administration of Rēzekne municipality is based in the city, though what it governs is the ring of rural parishes outside it. After the 2021 reform the country's local governments are the seven self-governing state cities plus thirty-five municipalities, and this arrangement is not unusual — Jelgava and Daugavpils work the same way, while Valmiera, also a state city, has no government of its own and sits inside a municipality. The terrain is worth noticing too: the lowest ground in the city, in the river valley, is around 130 m while nearby hilltops reach into the 180s, several hills stand more than thirty metres above their surroundings, and according to the National Encyclopaedia this makes Rēzekne one of the most interesting Latvian cities in landscape terms — locals call it the city of seven hills. Newcomers take \"Rēzekne municipality\" for the city's own government, when the two govern different places.",
    layout:
      "The old core is on the east bank around the castle mound, with the castle ruins and the Zeimuļs creative centre there. The GORS concert hall is a few hundred metres south-west of the centre and the Latgale Culture and History Museum a short way north. Kovšu Lake lies about 1 km south-west of the centre, with a park along its shore, and the two railway stations are at the west and north-east ends of the city.",
    gettingAround:
      "Rēzekne has no airport with scheduled flights; the nearest with them is Riga, about 210 km away in a straight line. Passenger trains run towards Riga, coaches serve Riga, Daugavpils and the surrounding municipalities, city buses run locally, and the old core is walkable. The climate is temperate continental, with cold snowy winters.",
    culture:
      "Latvian is spoken, alongside the written tradition of Latgalian — the creative centre's name, Zeimuļs, is Latgalian for \"pencil\". Latgalian pottery is the old craft of this region, with a permanent display at the culture and history museum. Restaurant bills sometimes include a service charge, so check the receipt before paying; tap water is drinkable according to the utilities. The supply is 230 V with two-round-pin continental sockets.",
    seeAndDo:
      "The castle mound and ruins; a performance at the GORS concert hall; the architecture of the Zeimuļs centre; the pottery display at the culture and history museum; a walk around Kovšu Lake; and trips out to Lake Rāzna to the south-east and Lake Lubāns to the north-east.",
    whenAndTips:
      "May to September is the most comfortable; winters are cold with short days. Both lakes need a car or a coach, services are infrequent, so check return times first.",
  },

  madona: {
    // 全七段 sources: 同中文侧（CSB IRS031 at 1 January 2026 — note the two AREA codes before and after the 1 July 2025 merger, tier 1; National Encyclopaedia of Latvia on the administrator arrangement and the town's layout, tier 2; Vivi timetable, tier 1; the Gaiziņkalns tower deliberately omitted as its status is unknown）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧）。
    identity:
      "Madona lies on the edge of the Vidzeme upland in central Latvia, with 6,502 people in the town and 29,466 in Madona municipality at the start of 2026 (Central Statistical Bureau). Gaiziņkalns, the country's highest point at 311.94 m, is about 16 km west, and the great bog of Teiči about 30 km south; the town itself straddles a morainic ridge, with more than sixty metres between its highest and lowest ground.",
    howItWorks:
      "Madona is not a state city, and it does not even have a council of its own: it had a town government until 2009, and since Madona municipality was formed in 2021 the town has been run by an administrator appointed by the municipality — the only arrangement of its kind among the Latvian towns in this library. The municipality itself is still changing: on 1 July 2025 Varakļāni municipality was merged into Madona municipality, taking effect with the first sitting of the council elected that year; after the reform the country's local governments are seven self-governing state cities and thirty-five municipalities. The railway divides the town: the centre, the shops and most of the residents are north of the line, while south of it are detached houses, the sports ground and the recreation area by the water. Two things set the living radius — the railway to Riga, and the upland outside town, where the country's highest point, a cross-country skiing and biathlon centre and a large protected bog all lie within half an hour to an hour by car. Newcomers take the municipality for the town, when the municipality is far larger.",
    layout:
      "The centre is north of the railway, with the museum of local history and art in it and the railway and coach stations a few hundred metres to the south-east. The Smeceres sils sports centre is about 3.7 km south-west of town, Gaiziņkalns about 16 km west in a straight line, Cesvaine Castle about 14 km north-east, and the Teiči bog about 30 km south.",
    gettingAround:
      "Madona has no airport with scheduled flights; the nearest with them is Riga, about 137 km away in a straight line. Passenger trains run towards Riga; the town itself has only two bus routes, sealed roads link the municipality's parishes, and reaching the upland or the bog needs a car. The climate is temperate continental with cold snowy winters, which is why this area is a centre for cross-country skiing.",
    culture:
      "Latvian is spoken. A potato festival has been held in town each autumn since 1999. Restaurant bills sometimes include a service charge, so check the receipt before paying; tap water is drinkable according to the utilities. The supply is 230 V with two-round-pin continental sockets.",
    seeAndDo:
      "The museum of local history and art; the ski and cycle trails at Smeceres sils; the drive up to Gaiziņkalns to stand on the country's highest point; Cesvaine Castle; and the edge of the protected bog at Teiči to the south.",
    whenAndTips:
      "June to September suits walking on the upland and around the bog, and December to March is the snow season. There are no visitor facilities on the summit of Gaiziņkalns, and the view depends on the weather; the bog reserve has access restrictions, so visits go through its management.",
  },
};
