import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "kyrgyzstan-overview": {
    // 全七段 sources: 同中文侧（National Statistical Committee tables 769 / 825, tier 1; "Environment 2020–2024", tier 1; UK FCDO travel advice 2026-09-14, tier 1; 24.kg on the service-charge ban, tier 2; airport.kg on the BSZ code, tier 1; UNESCO ICH 2012, tier 1）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Kyrgyzstan is a landlocked mountain country in Central Asia, about 199,900 km² in area, with around nine-tenths of it above 1,500 m and the Tian Shan running across it. According to the National Statistical Committee, the resident population on 1 January 2026 was about 7.4 million, roughly 42% of it urban. Its towns are squeezed into valleys and basins between the mountains: the capital, Bishkek, lies in the Chüy Valley in the north, and Issyk-Kul, ringed by snow mountains, lies to the north-east.",
    howItWorks:
      "Kyrgyzstan's first-level divisions are seven regions plus two cities of republican status, Bishkek and Osh — Bishkek ranks alongside the regions and is not part of the surrounding Chüy Region. Each region has a plenipotentiary representative of the president. Population is highly concentrated: by resident population at the start of 2026, Bishkek alone holds about 18% of the country, while Naryn and Talas regions each have only one town with city status, with more than 80% of people living in villages, and many district centres are administratively villages too. Daily life is shaped by the mountains: valleys and basins are linked by roads over passes, and stretches are often closed by snow in winter. The most common misunderstanding is to picture a flat steppe country with easy travel between towns, when getting from the capital to most regional centres means crossing passes thousands of metres high.",
    layout:
      "The Chüy Valley in the north is the lowland where Bishkek lies; east through the Boom Gorge is the Issyk-Kul basin, with the junction town of Balykchy at its western end, the lakeside resort of Cholpon-Ata on the north shore and the regional centre Karakol at the eastern end; south of the basin, over the mountains, lies the inner Tian Shan, where Naryn is the regional centre in the Naryn valley and Kochkor is the gateway to Song-Köl; the Talas valley in the north-west is home to Talas.",
    gettingAround:
      "Manas International Airport (BSZ, the code that replaced FRU in 2025) is the main gateway, with scheduled direct flights from Beijing, Guangzhou and other Chinese cities. Several regional centres, including Karakol, Naryn and Talas, have domestic scheduled flights to Bishkek, with only a few flights a week. Long-distance travel is mostly by road: shared taxis and minibuses are the usual way, so keep an eye on your belongings; roads outside Bishkek are often closed by snow in winter. The currency is the som; Visa works in most places, Mastercard is sometimes refused, QR-code payments are common, and you need cash in the countryside.",
    culture:
      "The state language is Kyrgyz, and Russian is also an official language and widely used. You must carry your passport or a notarised copy; e-cigarettes may not be brought into the country; drinking alcohol in public places is illegal; don't photograph police stations, border checkpoints or military sites. From 2026 restaurants may no longer add a separate service charge to the bill — it is built into menu prices — and tipping is voluntary. The traditional felt carpets ala-kiyiz and shyrdak were inscribed on UNESCO's List of Intangible Cultural Heritage in Need of Urgent Safeguarding in 2012.",
    seeAndDo:
      "Hiking in the valleys around Issyk-Kul and Karakol at its eastern end; the high pastures around Song-Köl; Ala-Archa National Park south of Bishkek; the Boom Gorge and the Jeti-Ögüz rocks on the lake's southern side; the Naryn valley and the mountain landscapes of the inner Tian Shan; Ala-Too Square, the National Historical Museum and Osh Bazaar in Bishkek.",
    whenAndTips:
      "June to September is the main season for the mountains and the lake, when high pastures and hiking routes open; winters are cold, Bishkek's air quality is poor, power cuts are frequent across the country, and roads outside Bishkek are often blocked by snow. Avalanches and landslides often cut mountain roads in spring, and high-altitude hikers should watch for altitude sickness. Longer stays must be registered as required; follow the latest official announcements for entry rules.",
  },
  bishkek: {
    // 全七段 sources: 同中文侧（National Statistical Committee table 825, tier 1; 24.kg on municipal territorial administrations 2025, tier 2; bulak.kg on the 2021 law, tier 2; UK FCDO 2026-09-14, tier 1; economist.kg / 24.kg on the summer train, tier 2; coordinates from Wikidata / OSM, distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok，人口据统计委员会 xls 复核）。
    identity:
      "Bishkek is the capital of Kyrgyzstan, in the Chüy Valley in the north at the northern foot of the Kyrgyz Ala-Too, with snow mountains visible south of the city. According to the National Statistical Committee, the city's resident population on 1 January 2026 was about 1.359 million, around 18% of the country. It is the national political, economic and transport centre and the starting point for trips to Issyk-Kul and the mountains.",
    howItWorks:
      "Bishkek is a city of republican status, on a par with the regions, and its mayor is appointed by the president; it is surrounded on three sides by districts of Chüy Region yet is not part of it. Under the law on the status of the capital the city has no more than four districts; the 2024–2025 administrative reform brought a number of suburban villages into the city, not as new districts but under eight municipal territorial administrations, so former village names still appear in addresses. The centre is Ala-Too Square, with the National Historical Museum, Erkindik Boulevard and several theatres and galleries within walking distance. Daily life follows a grid of streets and north–south boulevards, with mountains to the south and the airport to the north. The most common misunderstanding is to assume the airport is on the edge of town, when Manas International Airport is north of the city, about 23 km from the centre in a straight line.",
    layout:
      "Ala-Too Square is the city centre, with the National Historical Museum right on its north side; Erkindik Boulevard runs south from the square towards Bishkek-2 railway station; the Museum of Fine Arts is east of the square and the National Philharmonic to the west; Osh Bazaar is about 3 km west of the centre. South of the city rises the Kyrgyz Ala-Too, and Ala-Archa National Park lies in a valley about 38 km south of the city in a straight line.",
    gettingAround:
      "Manas International Airport (BSZ) is north of the city, about 23 km from the centre in a straight line, with international and domestic scheduled flights. Bishkek-2 railway station is close to the centre; in summer (early June to mid-September in 2026) a tourist train runs to Balykchy at the western end of Issyk-Kul, taking about 4 hours. Getting around the city is by taxi, bus and minibus; use a booked taxi service rather than flagging cars in the street. Trips to Issyk-Kul and the regions are mostly by shared taxi and long-distance bus.",
    culture:
      "Kyrgyz and Russian are both in everyday use, and signs are often in both. Osh Bazaar is a lively traditional market, but pickpockets target tourists there, so watch your belongings. There are government buildings around the square, so follow local rules when taking photos. Winter air quality is poor and power cuts are frequent. From 2026 restaurant bills no longer carry a separate service charge; tipping is voluntary.",
    seeAndDo:
      "Ala-Too Square and the National Historical Museum; a walk along Erkindik Boulevard; the Museum of Fine Arts; the National Philharmonic and the Manas sculpture group in front of it; Osh Bazaar; hiking in Ala-Archa National Park south of the city.",
    whenAndTips:
      "May–June and September–October are the most comfortable months in the city; July–August is hot and the season for the mountains and the lake; winter is cold with poor air quality. Issyk-Kul and Ala-Archa can be reached the same day; mountain weather changes fast, so bring warm layers.",
  },
  karakol: {
    // 全七段 sources: 同中文侧（National Statistical Committee table 825, tier 1; gov.kg Issyk-Kul Region page, tier 1; Asman Airlines API, tier 1; "Environment" table 4.15, tier 1; ru/en Wikipedia for the wooden buildings, tier 3; distances computed from coordinates）。 核实 2026-09-15 当批（content-verifier 独立检索，本条改 1 处：徒步起点「在山口」改为谷口保护区入口；航班每周五、周日据航司接口复核）。
    identity:
      "Karakol is the regional centre of Issyk-Kul Region, near the eastern end of Issyk-Kul at the northern foot of the Terskey Ala-Too, at about 1,700 m. According to the National Statistical Committee, its resident population on 1 January 2026 was about 91,500. The town has a wooden church and mosque and old wooden houses with carved porches, and the valleys south of town are for hiking and skiing.",
    howItWorks:
      "Karakol is a city of regional status where the region's administration, hospitals and long-distance transport are concentrated; about 70% of the region's people live in villages. Its structure can be summed up as \"the town is the supply base, the scenery is in the mountains\": the Altyn-Arashan valley, Jeti-Ögüz, Ala-Kul lake and the ski base that visitors come for all lie ten to twenty-odd kilometres away in the Terskey Ala-Too, and the town is where you set out, sleep and shop. Locals give directions by the market, bus stations, church and mosque. The most common misunderstanding is to think you can walk from town to the mountain scenery, when every valley needs its own transport and high hikes need time to acclimatise.",
    layout:
      "The town centre has a central park and the regional museum, with the wooden Holy Trinity Cathedral nearby and the Ibrahim Haji Mosque less than a kilometre to the north; the main bazaar is west of the centre. Karakol airport is a short way north of town. South of town rises the Terskey Ala-Too: the Karakol ski base is about 11 km to the south-east in a straight line, the Altyn-Arashan valley about 22 km south-east, the Jeti-Ögüz rocks about 22 km south-west, and Ala-Kul lake about 22 km south-east high in the mountains.",
    gettingAround:
      "Karakol International Airport (IKG) is north of town, about 2.3 km from the centre in a straight line, with domestic scheduled flights to Bishkek but only a few a week (two a week in autumn 2026). By road from Bishkek it is about 313 km in a straight line, through the Boom Gorge and east along the lake shore. Valleys are reached by taxi or hired car, and hiking routes mostly start at the protected-area entrances at their mouths. The climate is continental, with cold winters and cool summer mornings and evenings in the mountains.",
    culture:
      "Kyrgyz and Russian are both in use. The wooden church and mosque are active places of worship: dress modestly, keep quiet and follow the opening rules on site. Hiking in protected areas means following the rules and carrying out your rubbish. From 2026 restaurant bills no longer carry a separate service charge; tipping is voluntary.",
    seeAndDo:
      "The wooden Holy Trinity Cathedral and Ibrahim Haji Mosque; the regional museum; the main bazaar; hiking and hot springs in the Altyn-Arashan valley; the Jeti-Ögüz rocks; high-mountain hiking to Ala-Kul lake; the Karakol ski base in winter.",
    whenAndTips:
      "June to September suits hiking; high routes such as around Ala-Kul lake, above 3,500 m, call for caution over altitude sickness and sudden weather changes; winter is for skiing. Avalanches and landslides are common in the mountains in spring, so check conditions before setting out. The Issyk-Kul regional tourist police can be contacted in English or Russian; use the latest locally published number.",
  },
  "cholpon-ata": {
    // 全七段 sources: 同中文侧（National Statistical Committee table 825, tier 1; Asman Airlines network, tier 1; economist.kg / 24.kg on summer flights, tier 2; ru.wikipedia on the petroglyph museum and Rukh Ordo, tier 3; distances computed from coordinates）。 核实 2026-09-15 当批（content-verifier 独立检索，本条改 1 处：岩画区「不要触摸攀爬」无规章来源改写）。
    identity:
      "Cholpon-Ata lies on the middle of Issyk-Kul's north shore at the southern foot of the Kungey Ala-Too; it is the centre of Issyk-Kul District and a resort on the north shore. According to the National Statistical Committee, its resident population on 1 January 2026 was about 27,000. In summer the lakeside is busy, and across the water rise the snow peaks of the Terskey Ala-Too.",
    howItWorks:
      "Cholpon-Ata has two identities: it is the seat of Issyk-Kul District and a quiet small town in winter, and in summer it turns into a lakeside resort whose crowds are mainly holidaymakers. The town's boundaries were extended eastwards in a recent redistricting, so many addresses bearing the names of lakeside resorts are administratively part of Cholpon-Ata. Accommodation ranges from resorts and hotels to private rooms, which are commonly rented out in summer. Locals give directions by the lake shore, the main road and the bus station. The most common misunderstanding is to assume the nearby Issyk-Kul International Airport has flights all year, when it mainly has seasonal flights in summer, and the rest of the time most people come by road from Bishkek.",
    layout:
      "The town stretches east–west along the main road on the north shore of Issyk-Kul, with a lakeside park on the shore south of the centre and the bus station near the centre; the Rukh Ordo cultural centre is about 1 km east of the centre by the lake; the open-air petroglyph field lies on a boulder-strewn slope about 2.4 km north-west of town. The Kungey Ala-Too rises to the north, and Issyk-Kul International Airport is at Tamchy, about 32 km west in a straight line.",
    gettingAround:
      "By road from Bishkek it is about 204 km in a straight line, via the Boom Gorge and Balykchy then east along the north shore, usually by shared taxi or minibus. Issyk-Kul International Airport at Tamchy is about 32 km away in a straight line and mainly has seasonal flights in summer (it was not in the domestic network in autumn 2026). Karakol is further east along the shore, about 109 km in a straight line. Summers by the lake are pleasantly cool.",
    culture:
      "Kyrgyz and Russian are both in use. The open-air petroglyph field is part of a museum reserve, so treat the carvings with care. Drinking alcohol in public places, including the lakeside, is illegal. From 2026 restaurant bills no longer carry a separate service charge; tipping is voluntary.",
    seeAndDo:
      "The open-air petroglyph field; the Rukh Ordo cultural centre; the lakeside park and swimming in the lake; views across the lake to the snow peaks of the Terskey Ala-Too; summer water activities.",
    whenAndTips:
      "July–August is the high season for the lake, so book accommodation early; June and September are quieter with pleasant weather; in winter there are very few visitors. Issyk-Kul's water is slightly salty and the lake surface lies at about 1,600 m, so protect yourself from the sun.",
  },
  balykchy: {
    // 全七段 sources: 同中文侧（National Statistical Committee tables 769 / 825, tier 1; ru.wikipedia on the road junction and railway terminus, tier 3; economist.kg / 24.kg on the summer train, tier 2; OurAirports / airport.kg, tier 3 / 1; distances computed from coordinates）。 核实 2026-09-15 当批（content-verifier 独立检索，本条断言全部 ok）。
    identity:
      "Balykchy lies on the north shore at the western end of Issyk-Kul, a city of regional status in Issyk-Kul Region whose name means \"fisherman\" in Kyrgyz. According to the National Statistical Committee, its resident population on 1 January 2026 was about 57,800. The road and railway from Bishkek both arrive here, making it the gateway to the Issyk-Kul area.",
    howItWorks:
      "Balykchy is Issyk-Kul's \"western gate\": the road from Bishkek, after passing through the Boom Gorge, divides here, one branch following the north shore to Cholpon-Ata, one the south shore, and another heading south to Kochkor and Naryn; the railway from Bishkek also ends here. So it is first a road junction and transfer point, and only second a lakeside town. Locals give directions by the bus station, markets and railway station. The most common misunderstanding is to take it for a lakeside resort, when the resort areas lie further east along the north shore and Balykchy's role is as a transport hub where many people simply change vehicles.",
    layout:
      "The town spreads along the north shore at the western end of the lake, with the bus station in the south-west of town and the fish market and honey fair in the west; the railway station is also in the south-west, and the Balykchy Beach station, terminus of the summer tourist train, is by the lake on the east side of town. To the west, the road and railway from Bishkek enter the basin, with the Boom Gorge about 34 km to the north-west in a straight line.",
    gettingAround:
      "Balykchy has no airport with scheduled flights (the local airfield is closed); the nearest, Issyk-Kul International Airport at Tamchy, is about 44 km away in a straight line and has only seasonal summer flights. By road from Bishkek it is about 137 km in a straight line, through the Boom Gorge; in summer (early June to mid-September in 2026) a tourist train runs from Bishkek, taking about 4 hours. Connections to Cholpon-Ata, Karakol, Kochkor and Naryn all change at the bus station here.",
    culture:
      "Kyrgyz and Russian are both in use. There is a fish market and a honey fair on the west side of town. Drinking alcohol in public places is illegal. From 2026 restaurant bills no longer carry a separate service charge; tipping is voluntary.",
    seeAndDo:
      "The lakeside fish market and fairs; the summer tourist train through the Boom Gorge to the lake; the shore at the western end of Issyk-Kul; onward trips from here to Song-Köl, Naryn or the north and south shores.",
    whenAndTips:
      "The tourist train runs only in summer; the rest of the year it's the road. The western end of the lake is drier and windier than the east. It is a transfer point, so there is no need to linger — just arrange onward transport for your destination.",
  },
  naryn: {
    // 全七段 sources: 同中文侧（National Statistical Committee tables 769 / 825, tier 1; Asman Airlines API and Manas airport board, tier 1; Great Soviet Encyclopedia on the Naryn basin climate, tier 2; en.wikipedia on the town along the river, tier 3; "Environment" table 4.15, tier 1; distances computed from coordinates）。 核实 2026-09-15 当批（content-verifier 独立检索，本条删 1 处无来源提示（路上畜群））。
    identity:
      "Naryn is the regional centre of Naryn Region, in the Naryn valley of the inner Tian Shan at about 2,000 m, stretched along both banks of the Naryn River. According to the National Statistical Committee, its resident population on 1 January 2026 was about 42,500. It is the region's only town with city status and the starting point for the high plateaus and mountain pastures of the inner Tian Shan.",
    howItWorks:
      "Naryn is a case of \"one region, one town\": of Naryn Region's roughly 316,000 residents, only Naryn lives in a town with city status and everyone else lives in villages, so the urban population is only about 13%. That is why the regional and district administration, theatre, museum, hospitals and schools are all concentrated in this valley. The town is hemmed in by the river and the slopes on either side, stretching east–west in a narrow ribbon, with the bus station and museum at the eastern end and the market and theatre in the middle. Herding is the backbone of the region's economy, and pastures begin just outside town. The most common misunderstanding is to picture Naryn as a town on a plain, when it sits at about 2,000 m, has very cold winters, and any trip out of town crosses mountains.",
    layout:
      "The Naryn River runs east to west through town, with the town stretched in a narrow strip along both banks: the historical and ethnographic museum is in the east, and the music and drama theatre and city market are in the centre; several bridges link the two banks. Naryn airport is about 11 km east of town in a straight line, and Salkyn-Tor Nature Park lies in a valley about 15 km east of town.",
    gettingAround:
      "Naryn airport is east of town, about 11 km from the centre in a straight line, with domestic scheduled flights to Bishkek twice a week. By road from Bishkek it is about 198 km in a straight line, south over the mountains via Balykchy and Kochkor, usually by shared taxi or minibus; mountain roads may be blocked by snow in winter. The town is small and taxis are easy. Winters in the Naryn basin are severe, with average January temperatures of about −15 to −18 °C, and summers are cool, with July averaging about 15–17 °C.",
    culture:
      "Kyrgyz is the main language, and Russian is also often used. Outside town is herding country. Avoid photographing sensitive places such as police stations. Drinking alcohol in public places is illegal. From 2026 restaurant bills no longer carry a separate service charge; tipping is voluntary.",
    seeAndDo:
      "The Naryn historical and ethnographic museum; the town and valley scenery along both banks of the Naryn River; the city market; the valleys and forest of Salkyn-Tor Nature Park; using Naryn as a base for high mountain pastures of the inner Tian Shan.",
    whenAndTips:
      "June to September is the best time to travel, when the mountain pastures are at their liveliest; winters are long and harsh, so bring heavy clothing. At about 2,000 m you may feel slightly unwell on arrival, so take the first day easy. Mountain roads are long and filling stations are few, so fill up before driving.",
  },
  talas: {
    // 全七段 sources: 同中文侧（National Statistical Committee tables 769 / 825, tier 1; gov.kg Talas Region page, tier 1; Asman Airlines API and Manas airport board, tier 1; en.wikipedia on the passes, tier 3; "Environment" table 4.15, tier 1; distances computed from coordinates）。 核实 2026-09-15 当批（content-verifier 独立检索，本条改 1 处：初稿把奥特莫克山口写成吐阿舒山口、终点写成楚河谷地，已改正）。
    identity:
      "Talas is the regional centre of Talas Region, in the Talas valley in north-western Kyrgyzstan at about 1,300 m, with the Talas Ala-Too to the south. According to the National Statistical Committee, its resident population on 1 January 2026 was about 43,900. It is the region's only town with city status, surrounded by valley farmland and foothill pastures.",
    howItWorks:
      "Talas Region is a valley region enclosed by mountains: of its roughly 283,000 residents, only Talas lives in a town with city status, and the urban population is about 15%. It is separated from the capital by mountains — driving from Bishkek on domestic roads means first crossing the Too-Ashuu Pass over the Kyrgyz Ala-Too, above 3,000 m, into the Suusamyr Valley, then the Ötmök Pass down to the Talas valley — so domestic scheduled flights between the regional centre and the capital matter locally. The administration, theatre, market and bus station are all near the centre, which is compact. The most common misunderstanding is to see that the two cities are less than 200 km apart in a straight line and expect a drive of an hour or two, when the road winds over mountains and may close in winter.",
    layout:
      "The town lies in the Talas valley, with the central bazaar and bus station in the centre and the music and drama theatre to the north-east; Talas airport is a short way east of town. To the south rises the northern slope of the Talas Ala-Too, with Besh-Tash Nature Park in a valley about 26 km south-east of town in a straight line. The valley extends east and west, with pastures on the slopes on either side.",
    gettingAround:
      "Talas airport is east of town, about 2.7 km from the centre in a straight line, with domestic scheduled flights to Bishkek twice a week. Driving from Bishkek on domestic roads means crossing two passes above 3,000 m via the Suusamyr Valley; the straight-line distance is about 198 km, but the road is much longer and may close in winter. In town, walk or take a taxi. The climate is continental, cold in winter and hot in summer, with dry summers in the valley.",
    culture:
      "Kyrgyz is the main language, and Russian is also often used. Drinking alcohol in public places is illegal. From 2026 restaurant bills no longer carry a separate service charge; tipping is voluntary.",
    seeAndDo:
      "The central bazaar; the music and drama theatre; gorges and hiking in Besh-Tash Nature Park south-east of town; the farmland and foothill pastures of the Talas valley; the high pastures of the Suusamyr Valley crossed on the road over the mountains.",
    whenAndTips:
      "June to September is best, when the mountain roads are in good condition; in winter the passes may be snowbound and flying is more reliable. For a day trip to Besh-Tash or other valleys, start early, as mountain weather changes quickly.",
  },
  kochkor: {
    // 全七段 sources: 同中文侧（National Statistical Committee tables 769 / 825 (village government figure), tier 1; en.wikipedia / Wikidata for elevation and roads, tier 3; "Environment" 2025 on Song-Köl area, tier 1; Great Soviet Encyclopedia on Song-Köl, tier 2; UNESCO ICH 2012, tier 1; distances computed from coordinates）。 核实 2026-09-15 当批（content-verifier 独立检索，本条软化 1 处无来源提示）。
    identity:
      "Kochkor is the centre of Kochkor District in Naryn Region, in a mountain basin at about 1,800 m, and administratively a village. According to the village government's figures for early 2026, it has about 11,200 people. It lies on the road from Bishkek to Naryn, is the gateway to Song-Köl, and traditional felt carpets are made in the village.",
    howItWorks:
      "Kochkor has two roles: it is the centre of Kochkor District, whose roughly 71,000 residents are all counted as rural and which is run by a village government rather than a city government; and it is the transfer point for the high lake of Song-Köl, where many people arrange vehicles and stock up before heading into the mountains. It sits on the main road from Bishkek towards Naryn, with another road heading west towards the Jumgal basin. Locals give directions by the main street, the market and the museum. The most common misunderstanding is to think Song-Köl is right next to the village, when it lies about 64 km to the south-west in a straight line, on a plateau at around 3,000 m, reached by road over the mountains, and begins freezing around the end of September each year.",
    layout:
      "The village runs along its main street, with the regional museum and house of culture in the centre and the livestock market to the west. The road to the north-east leads to Balykchy and Issyk-Kul, the road south to Naryn, and a road west to the Jumgal basin. Song-Köl lies behind the mountains to the south-west.",
    gettingAround:
      "Kochkor has no airport with scheduled flights; the nearest with scheduled flights are Naryn airport (about 89 km away in a straight line) and Manas International Airport in Bishkek. By road from Bishkek it is about 120 km in a straight line, usually changing at Balykchy, by shared taxi or minibus; trips to Song-Köl are usually by hired car, on mountain roads open in summer and unsuitable in winter. The climate is continental and mountainous, with cold winters and cool summer mornings and evenings.",
    culture:
      "Kyrgyz is the main language. The traditional felt carpets ala-kiyiz and shyrdak are part of nomadic life and were inscribed on UNESCO's List of Intangible Cultural Heritage in Need of Urgent Safeguarding in 2012; you can see them being made and sold in the village. When visiting herders' homes, follow your hosts' lead. Drinking alcohol in public places is illegal. From 2026 restaurant bills no longer carry a separate service charge; tipping is voluntary.",
    seeAndDo:
      "Felt carpet workshops and handmade carpets; the regional museum; the livestock market; trips from Kochkor to the high pastures of Song-Köl; the mountain scenery west towards the Jumgal basin.",
    whenAndTips:
      "June to September is the season for Song-Köl; the lake lies at about 3,000 m and is cold even in summer, so bring plenty of warm clothing and watch for altitude sickness; the lake starts freezing around the end of September. Transport to Song-Köl can be arranged in Kochkor.",
  },
  bokonbayevo: {
    // 全七段 sources: 同中文侧（National Statistical Committee tables 825 and 769, tier 1; airport.kg airport list, tier 1; UNESCO tentative list 5518 and MAB, tier 1; UNESCO national commission on falconry, tier 1; distances computed）。 核实 2026-09-16 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Bokonbayevo is a large village on the south shore of Issyk-Kul in Kyrgyzstan, in Ton District of Issyk-Kul Region, with about 13,400 people at the start of 2026 according to the village government. It lies on the road along the south shore, with the lake to the north and valleys of the Tian Shan to the south; ruins of a medieval town near the Ton river nearby are on the World Heritage tentative list.",
    howItWorks:
      "Administratively Bokonbayevo is a village run by its rural district (aiyl aimak) government, not a city government, and the roughly 58,000 residents of Ton District are all classed as rural. Its daily radius is set by a single lakeshore road running west to Balykchy and east to Karakol, stringing the villages of the south shore together, with roads into the southern valleys branching off it. The village stretches along the road, with a park and a community tourism information point in the centre. Locals find their way by the road, the park and the lakeshore. Newcomers most often assume the south shore has an airport and resort strip like Cholpon-Ata on the north shore — there is no airport with scheduled flights here, and the airport at Tamchy on the north shore has only seasonal flights — and that the red sandstone canyon beside the lakeshore road is on the village's doorstep, when it is about 30 km east.",
    layout:
      "The village sits on the south side of Issyk-Kul, stretched along the east–west lakeshore road with a park in the centre; the lake lies to the north, and the Ton and other valleys lead south into the Tian Shan. About 30 km east along the road, by the lakeshore, is the red sandstone canyon popularly called Fairy Tale Canyon; Balykchy lies to the west and Karakol to the east.",
    gettingAround:
      "Bokonbayevo has no airport with scheduled flights; the nearest, Issyk-Kul International Airport at Tamchy on the north shore, has only seasonal flights and is about 57 km away across the lake in a straight line, and year-round scheduled flights mean going to Bishkek. From Bishkek most people travel via Balykchy and along the south-shore road by shared taxi or minibus; in summer a tourist train also runs from Bishkek to Balykchy, where you change. Driving or hiring a car is easiest between the lakeside villages.",
    culture:
      "Kyrgyz is the main language. Falconry is part of Kyrgyz nomadic tradition, and Kyrgyzstan joined UNESCO's listing of falconry as intangible cultural heritage of humanity in 2021; the traditional felt carpets ala-kiyiz and shyrdak are common too. The whole Issyk-Kul area is a UNESCO biosphere reserve. Drinking alcohol in public places is illegal.",
    seeAndDo:
      "The park and lakeshore in the village; the red sandstone canyon beside the lakeshore road about 30 km east; the villages and beaches of the south shore; high pastures in the valleys to the south; and learning about nomadic traditions such as falconry and felt-making.",
    whenAndTips:
      "June–September is best for the lake and valleys; winters are cold, and in the summer peak it is worth booking accommodation and transport ahead.",
  },
  "at-bashy": {
    // 全七段 sources: 同中文侧（National Statistical Committee tables 825 and 769, tier 1; airport.kg, tier 1; UNESCO tentative list 5518 (2010), tier 1; distances computed）。 核实 2026-09-16 当批（content-verifier 独立检索，本条 ok；盆地南北格局沿用仓库地形条目）。
    identity:
      "At-Bashy is a large village in At-Bashy District of Naryn Region, Kyrgyzstan, in the At-Bashy basin at a little over 2,000 metres, with about 15,300 people at the start of 2026 according to the village government. Outside the village are two Silk Road sites on the World Heritage tentative list: the walls of Koshoy-Korgon about 11 km away in a straight line, and the stone caravanserai of Tash-Rabat in a high valley to the south-west at about 3,200 metres.",
    howItWorks:
      "Administratively At-Bashy is a village run by the At-Bashy rural district (aiyl aimak) government; the roughly 63,000 residents of At-Bashy District are all classed as rural, and in the whole of Naryn Region only the regional capital, Naryn, counts as urban. The village stretches along its main street, with the market and cultural centre together in one area. Daily life is shaped by the basin: irrigated farmland to the north, the At-Bashy range to the south, and for longer trips a drive of about 30 km north to Naryn, whose airport also has the flights to Bishkek. Locals find their way by the main street, the market and the road to Naryn. Newcomers most often assume Tash-Rabat is next to the village, when it lies about 58 km south-west in a straight line, in a side valley at about 3,200 metres, and needs a hired car; they also imagine Koshoy-Korgon as a complete fortress, when it is the ruin of mud-brick walls, with a site museum built beside it in 2007.",
    layout:
      "The village lies in the At-Bashy basin, stretched along its main street with the market and cultural centre in the middle; across the basin to the south is the At-Bashy range. About 11 km west are the Koshoy-Korgon ruins and museum, about 58 km south-west into the mountains is Tash-Rabat, and about 30 km north is the town of Naryn.",
    gettingAround:
      "At-Bashy has no airport with scheduled flights; the nearest is Naryn Airport, about 40 km away in a straight line, with scheduled flights to Bishkek, and more flights go through Manas International Airport in Bishkek. By road, come from Bishkek via Naryn by shared taxi or minibus; Koshoy-Korgon and Tash-Rabat need a hired car, and road conditions and access requirements for Tash-Rabat should be checked with a local tour operator before setting off. The climate is continental and alpine, with severe winters.",
    culture:
      "Kyrgyz is the main language. Tash-Rabat is a square building of slate slabs with one large dome and nineteen small domes inside; according to the World Heritage tentative list it dates from the 11th–12th centuries and was restored in the late 1970s. When visiting herders' homes, follow the host's lead; drinking alcohol in public places is illegal.",
    seeAndDo:
      "The Koshoy-Korgon walls and site museum; the stone caravanserai of Tash-Rabat; the pastures of the At-Bashy basin and views of the At-Bashy range; the village market; and an inner Tian Shan route combined with Naryn and Kochkor.",
    whenAndTips:
      "June–September is the time to go; Tash-Rabat is at about 3,200 metres and cold even in summer, so watch for altitude sickness and bring warm clothes; mountain roads may be difficult in winter.",
  },

  "kara-balta": {
    // 全七段 sources: 同中文侧（National Statistical Committee table 825 at 1 January 2026, tier 1, digit-checked against Bishkek in the repo; the same table's ordering shows it ranked alongside the districts rather than inside one; OurAirports for the closed airfields and the Manas flight board, tier 1/3; distances computed from this entry's own coordinates）。 核实 2026-09-16 当批。
    identity:
      "Kara-Balta stands in the western Chuy valley of northern Kyrgyzstan, at the northern foot of the Kyrgyz Range, with 61,364 residents at the start of 2026 (National Statistical Committee). Its position is the whole point of it: the Bishkek-Osh road leaves the valley here and climbs south along the Kara-Balta river towards the Töö-Ashuu pass — coming up from the flat country, this is the last town of any size before the mountains.",
    howItWorks:
      "A Kyrgyz \"city\" is not one tier but two, and Kara-Balta is a specimen of the first. The statistical tables list it alongside Tokmok and Kant ahead of the districts, level with them — a city of regional status, counted inside no district at all. Yet the administration of Jaiyl district sits in this very town: two governments in one place, one running the town, the other running the countryside around it but not the town, counted separately in the tables. Toktogul, written in the same batch, is the mirror image — a city listed inside its district. None of this is visible on a map, but it decides which door you go to. The town itself is a long strip along the road and the railway: the road towards the pass is the spine, the town hall stands on it, the station is a kilometre or so north, and the housing is north of that again. The living radius is set by that road — an hour north to the capital, and straight into the mountains as soon as you turn south.",
    layout:
      "The town hall stands on the main axis, with the monument at the town entrance right in front of it. The railway station is about 1.7 km north, with the housing beyond it. Manas International Airport is about 59 km north-east, and the Suusamyr valley about 76 km south over the Töö-Ashuu pass.",
    gettingAround:
      "Kara-Balta has no airport with scheduled flights — the airfield and helipads within the town are closed, and the nearest airport with scheduled service is Manas International, about 59 km away in a straight line. Getting in and out means the Bishkek-Osh road or the commuter train to Bishkek. The climate is temperate continental with cold winters, and the pass to the south is often closed in winter, so check road conditions before setting out.",
    culture:
      "Kyrgyz and Russian are spoken. Since 1 January 2026 restaurants in Kyrgyzstan may no longer add a separate service charge.",
    seeAndDo:
      "The town has few built sights of its own; what it is good for is as a gateway — south over the Töö-Ashuu pass into the Suusamyr valley, or north into the Chuy valley and towards the capital. In town, the streets and markets along the main axis are what there is.",
    whenAndTips:
      "May to September suits going south into the mountains. The pass can close or be restricted for snow in winter and spring, so check road conditions whatever the season; lodging and supplies in town are limited, and most people treat this as a stop on the way.",
  },

  toktogul: {
    // 全七段 sources: 同中文侧（table 825, Jalal-Abad page, at 1 January 2026, tier 1 — the town's own website still carries an older, pre-boundary-reform figure and the two are deliberately not compared in one sentence; both the town and the district administration websites for the two seats, tier 1; OurAirports, tier 3; distances computed from this entry's own coordinates）。 核实 2026-09-16 当批。
    identity:
      "Toktogul lies in western Kyrgyzstan in the Ketmen-Töbö basin on the upper Naryn, with 37,869 residents at the start of 2026 (National Statistical Committee, on the post-reform boundaries). The Bishkek-Osh road drops into the basin here after crossing the Ala-Bel pass and threading the Chychkan gorge; the low ground of the basin holds the large reservoir of the same name.",
    howItWorks:
      "Kara-Balta, written in the same batch, is a city of regional status; Toktogul is the opposite — the tables list it inside Toktogul district, a district-level town. So this town of thirty-odd thousand also has two governments, but the relationship is reversed: the town administration runs the town, while the district's state administration runs the villages of the whole district, and that district was itself formed in 1998 by merging two others, with its seat here. A Kyrgyz \"city\" therefore has to be read two ways, depending on whether the table puts it before its district or inside it. The shape of the town is set by the basin and the road: houses on the gentle slope on the northern side, the road entering from the gorge mouth to the north-east and running through towards the south-west. The living radius is almost entirely that road — it is the only through route into the basin, north over the passes towards the capital, south and down towards the edge of the Fergana valley.",
    layout:
      "The town administration is in the centre. The Chychkan joins from the west (two sources put its mouth several kilometres apart, so no exact distance is given here), the centre of the Ketmen-Töbö basin is about 4.5 km south-west, and the near shore of the Toktogul Reservoir about 9 km south-west. The Alatai State Nature Park is about 63 km west-north-west.",
    gettingAround:
      "Toktogul has no airport with scheduled flights — there is an airfield about 6.5 km west of the town, but nothing scheduled uses it. Getting in and out is almost entirely the Bishkek-Osh road: north over the Ala-Bel and Töö-Ashuu passes, or south down through the gorge. The climate is temperate continental, hot in the basin in summer and cold in winter, with the passes often closed by snow.",
    culture:
      "Kyrgyz and Russian are spoken. Since 1 January 2026 restaurants in Kyrgyzstan may no longer add a separate service charge.",
    seeAndDo:
      "There are no built antiquities here; what there is to look at is landscape — the basin and the mountains around it, the water of the reservoir, and the Chychkan gorge on the way in. The Alatai State Nature Park lies to the west-north-west.",
    whenAndTips:
      "May to September is the most comfortable; both passes can close in winter, so checking road conditions before setting out is not optional. Expect small-town lodging and supplies — this is a staging point on a long road, where most people spend a night or restock and move on.",
  },

  kazarman: {
    // 全七段 sources: 同中文侧（National Statistical Committee table 825 at 1 January 2026, tier 1, digit-checked 5/5 against Toktogul, Kara-Balta, Bishkek, Naryn and Talas already in the repo; the country's list of 33 cities from the state registration service's structure table, tier 1, which is what makes the "still a village" point checkable; UNESCO Tentative List ref 1512 for the petroglyphs, tier 1 — only the archaeology and dating are written, not the beliefs the listing text mentions; distances computed from this entry's own coordinates. The airfield has scheduled flights but no `airport` field is filled, because the IATA codes the airline's own API returns for it, Naryn and Talas are absent from OurAirports and the conflict is unresolved）。 核实 2026-09-17 当批。
    identity:
      "Kazarman lies in western Kyrgyzstan in the Naryn valley on the eastern slope of the Fergana range, with 11,892 residents at the start of 2026 (National Statistical Committee). It is the administrative centre of Toguz-Toro district, ringed by mountains — north over a pass towards Naryn, west down towards Jalal-Abad — and an airfield with scheduled flights sits just outside the village.",
    howItWorks:
      "In Kyrgyzstan a \"city\" is an act of legislation, not a population threshold. Kazarman has nearly twelve thousand people, an airfield and a district to administer, and is still officially a village; meanwhile Kok-Jangak in the same region, with about thirteen thousand, is a city, and Shopokov over in Chuy, with three hundred fewer people than here, is a city too. The country's thirty-three cities are listed one by one in the state registration service's structure table, and this place is not among them. So the question of whether somewhere counts as a city is answered by that list, not by the population column. It also explains what is unusual here: a village that is a district seat, with the village administration and the district's own offices on the same street. The living radius is set by the mountains — the pass to the north is often closed by snow in winter, and then the flight is how people come and go, which is rare for a settlement of this size.",
    layout:
      "The village administration is in the middle with the bazaar about 0.2 km west of it. Kazarman airfield is about 1.8 km east-north-east. The Saimaly-Tash petroglyphs are about 30 km south-west up in the mountains, and the national nature park of the same name about 31 km south-south-west.",
    gettingAround:
      "Kazarman has an airfield with scheduled flights about 1.8 km north-east of the village — unusual for a settlement of ten thousand or so. Overland access means mountain roads: north over the passes towards Naryn, west down towards Jalal-Abad, with the passes often snowed in during winter, so check conditions before setting out. The climate is temperate continental, hot in the valley in summer and cold in winter.",
    culture:
      "Kyrgyz and Russian are spoken. Since 1 January 2026 restaurants in Kyrgyzstan may no longer add a separate service charge.",
    seeAndDo:
      "The village itself is a mountain settlement and what there is to see is up in the hills: according to the UNESCO Tentative List text, some ten thousand stones bearing images have been identified at Saimaly-Tash, the earliest dating to the third and early second millennia BC, and a national nature park covers the area around them. Going up needs a guide and the right season.",
    whenAndTips:
      "June to September is the season for the mountains; at other times the passes and the track up are often impassable. The petroglyph area is high with no supplies, so a local guide is essential and worth asking whether the route is open on the day; lodging in the village is family-run and very limited.",
  },

  "kyzyl-suu": {
    // 全七段 sources: 同中文侧（table 825 at 1 January 2026, tier 1, same digit check; the district's own website confirms the administration's address here, tier 1; the region's city list from the state registration service's structure table, tier 1, which is what makes "the largest district with no city in it" checkable; distances computed from this entry's own coordinates — the Jeti-Ögüz rocks POI shares its coordinates digit-for-digit with the terrain entry's anchor. OurAirports flags Tamga as having scheduled service while the airline's own route list does not include it, so that row is not used）。 核实 2026-09-17 当批。
    identity:
      "Kyzyl-Suu stands on the southern shore of Issyk-Kul where the rivers come out of the Terskey Ala-Too, with 15,716 residents at the start of 2026 (National Statistical Committee). It is the administrative centre of Jeti-Ögüz district; some eighteen kilometres east, red sandstone has been cut into a row of standing forms — the place known as the Seven Bulls.",
    howItWorks:
      "Jeti-Ögüz is the most populous district in the Issyk-Kul region, with over a hundred thousand people, more than any of the other four; and it is also the only district in the region with no city inside it at all — the region's three cities are all in other districts. So the largest district is administered from a village of fifteen thousand. There is a further layer that confuses people: within this district the name Jeti-Ögüz refers to three different places — the district itself, a village of about 3,900 that shares the name, and a separately counted resort settlement of about 280 — and the district administration is in none of them, but here, eighteen kilometres away. So \"going to Jeti-Ögüz\" always needs saying which one. The village itself is simple in plan: the district offices, the bazaar and a few main streets together, the road into the mountains heading east and the road down to the lake heading north.",
    layout:
      "The district administration is in the middle of the village, the bazaar about 0.2 km west of it and the destination information centre about 0.7 km north-east. The Jeti-Ögüz rocks and the Broken Heart are about 18.7 km due east and the red rocks viewpoint about 19.3 km due east; the administration of Jeti-Ögüz village is about 20 km east-north-east.",
    gettingAround:
      "Kyzyl-Suu has no airport with scheduled flights; the nearest that does is Karakol, about 38 km east-north-east. The road along the southern shore is the main route, east to Karakol and west towards Balykchy, while the roads into the mountains are strongly seasonal. The climate is temperate continental, milder by the lake than up the valleys.",
    culture:
      "Kyrgyz and Russian are spoken. Since 1 January 2026 restaurants in Kyrgyzstan may no longer add a separate service charge.",
    seeAndDo:
      "The drive east into the valley for the red rock forms of the Seven Bulls and the Broken Heart, with the red rocks viewpoint beside them; the bazaar in the village; and the southern shore road, using the village as a base.",
    whenAndTips:
      "June to September suits the mountains, and the valley roads can be hard going under snow in winter. The valley floods easily after rain and during the melt, so ask locally about the day's conditions; lodging in the village is family-run.",
  },
};
