import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  // ============ Singapore ============
  "singapore-overview": {
    // identity sources: SingStat《Population Trends, 2025》：2025 年 6 月末总人口 6.11 百万，其中常住人口 420 万、非居民 191 万。https://www.singstat.gov.sg/publication-resources/population-trends-2025
    //   本批唯一一条数字与官方完全吻合的。核实日 2026-09-07，来源级别 1
    identity:
      "The Republic of Singapore is a city-state island nation in Southeast Asia, covering about 735 km² with a total population of about 6.11 million as of end-June 2025 (Singapore Department of Statistics) — one of the most densely populated independent countries in the world after Monaco. Its capital is Singapore itself; the official languages are Malay (the national language), English, Mandarin and Tamil, and its currency is the Singapore dollar (SGD).",
    layout:
      "The country is highly urbanised with no traditional multi-city division: Marina Bay and the city centre form the political and economic core, Sentosa is the well-known resort island to the south, outlying islands such as Pulau Ubin and St John's Island preserve natural and historical landscapes, and the Central Catchment and Bukit Timah reserves are mainland Singapore's only remaining large tracts of forest.",
    gettingAround:
      "Changi Airport is the international air hub, about 20 km from the city centre, reachable by MRT in 40–45 minutes; the island's public transport network is extensive, with MRT, buses and ride-hailing (Grab) covering the whole island. As a single city-state, Singapore has no domestic flights. Visa-free arrangements for short-term visitors vary by nationality — check Singapore's official current announcements.",
    culture:
      "The official languages are Malay (national language), English (the language of administration and business), Mandarin and Tamil, spoken alongside each other; society is composed of Malay, Chinese, Indian and Eurasian communities among others. Singapore is known for strict management of public order and cleanliness (such as bans on spitting and smoking in most public places). Bringing chewing gum into the country is banned (except for medicinal gum), and littering or eating/drinking on the MRT can draw fines; Singapore has extremely severe drug penalties, with trafficking punishable by death — know and follow local law. Restaurant bills often already include service, and tipping is not a mandatory tradition. The voltage is 230V, with British-style three-pin plugs.",
    seeAndDo:
      "Natural landforms: primary rainforest at Bukit Timah and the Central Catchment, the wetlands of Pulau Ubin and Chek Jawa, the mangroves of Sungei Buloh, the rocky shore at Labrador. Island leisure: Sentosa's beaches and theme parks, diving at Sisters' Islands Marine Park. History and culture: the multiethnic districts of Chinatown, Kampong Glam and Little India; the historical sites of St John's Island and Kusu Island.",
    whenAndTips:
      "Lying near the equator, Singapore is hot and humid year-round with no distinct seasons; rainfall is comparatively heavier from November to January (the northeast monsoon season), and afternoon showers are common in other months too — carry rain gear year-round, and a light layer is useful given strong indoor air-conditioning.",
  },
  "singapore-city": {
    identity:
      "Singapore city is the urban core of the entire country, on the south coast of Singapore Island where the Singapore River meets the sea — the country's political, economic and cultural centre and one of the world's major international financial and trade hubs, its urban form built up in layers from what began as a trading port on a strait.",
    // howItWorks sources: Wikipedia (2026-09): Singapore (city-state, no local tier; 5 CDC districts; town councils; ~744 km²; 6.11 million 2025, ~4.2 million residents; 55 URA planning areas; ~78% HDB; MRT 6 lines; COE; 4 official languages; 6-digit postcode)
    howItWorks:
      "Singapore is a city-state with no local government tier: one national government runs everything from planning and housing to transport and police. The country is divided into five Community Development Council districts, the day-to-day management of public housing estates falls to town councils chaired by Members of Parliament, and the unit of planning is the 55 planning areas drawn by the Urban Redevelopment Authority — Downtown Core, Orchard, Toa Payoh — which are also the language in which locals place things. The territory covers about 744 km² and is still growing by reclamation, with about 6.11 million people in 2025, of whom about 4.2 million are residents. About 78 per cent of residents live in Housing and Development Board flats, planned in estates around MRT stations, the basic cell of the city. Six MRT lines and buses run on one card, and owning a car requires bidding for a costly Certificate of Entitlement. English, Malay, Mandarin and Tamil are official, with English the working language. Addresses give block, street, floor-unit and a six-digit postcode unique to each building. Newcomers most often go wrong by treating Singapore as a 'city', when it is a country with no city government at all.",
    layout:
      "Around the mouth of the Singapore River, the Raffles Landing Site and colonial-era buildings such as City Hall and the old Parliament House mark the city's original administrative and commercial core; further out, Chinatown, Kampong Glam and Little India are the traditional enclaves shaped by Chinese, Malay-Muslim and Indian immigration respectively, and Marina Bay, built on land reclaimed in the late 20th century, is the modern financial and landmark core, with Orchard Road as Singapore's main shopping street.",
    gettingAround:
      "Changi Airport is about 20 km from the city centre, with the airport MRT line taking about 35–45 minutes into town; the city's MRT network is extensive, with buses and Grab ride-hailing covering the whole island as the main way to explore its different districts.",
    culture:
      "The official languages — Malay, English, Mandarin and Tamil — are spoken alongside each other, and the society is known for its coexistence of diverse ethnicities and religions. Singapore is known for its strict management of public order and clean cityscape; chewing gum (other than medicinal) is banned on entry, and littering or eating/drinking on the MRT can mean a fine — drug laws carry severe penalties, so don't take the risk. Restaurant bills typically already include service, and tipping is not a mandatory tradition.",
    seeAndDo:
      "Merlion Park (at the mouth of the Singapore River, the city's signature viewpoint, with the historic civic district and the Marina Bay skyline visible in the same frame); Boat Quay and Clarke Quay along the river (former trading-port wharves, now a dining and nightlife district); the historic buildings around City Hall and the old Parliament House; Gardens by the Bay and Marina Bay Sands; Chinatown and the Buddha Tooth Relic Temple; Kampong Glam and the Sultan Mosque; Little India; the Singapore Botanic Gardens (a UNESCO World Heritage Site).",
    whenAndTips:
      "Hot and humid year-round — carry rain gear for afternoon showers; the city centre's sights are concentrated and the MRT is convenient, making it well suited to an itinerary combining walking with metro rides.",
  },
  sentosa: {
    identity:
      "Sentosa is a resort island of about 500 ha off Singapore's south coast, originally named Pulau Blakang Mati (\"the island behind which lies death\") and renamed Sentosa (Malay for \"peace and tranquility\") in 1972; it is today Singapore's foremost island resort and theme-park destination.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Sentosa (Singapore; an island of about 4.71 km² off the southern coast across Keppel Harbour, the fourth-largest island apart from the main island; formerly Pulau Blakang Mati, a British military fortress and a Japanese prisoner-of-war camp in the Second World War, renamed Sentosa in 1972, the name from Sanskrit for peace and tranquillity; developed and managed by the Sentosa Development Corporation, a statutory board established in 1972, rather than as an ordinary planning area; about 25 million visitors a year; Resorts World Sentosa and Universal Studios Singapore; the artificial beaches Palawan, Siloso and Tanjong; the cable car, the Sentosa Express monorail and the boardwalk; Fort Siloso)
    howItWorks:
      "Sentosa is an island of about 4.71 km² off Singapore's southern coast across Keppel Harbour, the fourth-largest island apart from the mainland by area. Singapore has no tier of local government and the whole island state is run directly by the national government, but this island is more particular still: it is developed and managed by the Sentosa Development Corporation, a statutory board created in 1972, which holds planning, operations and facilities in one body rather than dividing them among the Urban Redevelopment Authority and other agencies as in an ordinary planning area. It was formerly Pulau Blakang Mati, long a British coastal fortress and used as a prisoner-of-war camp during the Second World War, and was renamed Sentosa in 1972 after a Sanskrit word for peace. It has been rebuilt whole as a resort island since: Resorts World Sentosa and Universal Studios Singapore stand at its centre, the beaches at Siloso, Palawan and Tanjong were made by reclamation, and Fort Siloso keeps the military remains. Three ways lead across — the cable car, the Sentosa Express monorail and a boardwalk — and about twenty-five million visits are made a year. Newcomers most often go wrong by taking it for a natural island, when its beaches and much of its ground were built.",
    layout:
      "Nearly 70% of the island remains natural rainforest; its south shore holds several beaches and resorts, while Resorts World Sentosa (home to Universal Studios) sits on the island's north side, linked to mainland Singapore by cable car, monorail and a causeway.",
    gettingAround:
      "Sentosa has no airport of its own and is reached via Changi Airport (about 30 km from the island); it connects to mainland Singapore by cable car, the Sentosa Express monorail, or on foot across the Sentosa Boardwalk causeway, with buses and a beach tram available for getting around the island.",
    culture:
      "The official languages — Malay, English, Mandarin and Tamil — are spoken alongside each other. Sentosa has been developed by the Sentosa Development Corporation since 1972, transforming from a disused military site into an internationally known leisure and resort island; the opening of Resorts World Sentosa in 2010 was a major milestone in its development.",
    seeAndDo:
      "Resorts World Sentosa (Universal Studios Singapore); Siloso Beach and other south-shore beaches; cable-car views across the strait; the Skyline Luge and other outdoor adventure activities.",
    whenAndTips:
      "Hot and humid year-round — plan beach and outdoor activities to avoid the midday heat; rainfall is heavier from November to January, so check the weather before visiting.",
  },
  "chinatown-singapore": {
    identity:
      "Chinatown is one of Singapore's oldest Chinese settlement areas; its Chinese name, Niu Che Shui (\"bullock cart water\"), recalls how water was once carted in by ox-drawn cart to supply residents — the district has grown from a 19th-century immigrant foothold into today's heritage quarter of shophouses and temples.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Chinatown, Singapore (a subzone and historic enclave within the Outram planning area of the Central Area, made up of five precincts developed between the 1820s and 1920s; under the Raffles Town Plan of 1822 areas were designated for different communities, the Chinese allotted land south-west of the Singapore River; the Chinese and Malay names, Kreta Ayer, come from the bullock water-carts that carried the district's water supply in the 19th century; the Buddha Tooth Relic Temple, Sri Mariamman Temple and Thian Hock Keng; the Chinatown Complex hawker centre; MRT connections; debate over conservation and commercialisation; spans the Tanjong Pagar and Jalan Besar constituencies)
    howItWorks:
      "Chinatown is a subzone and historic enclave within the Outram planning area of Singapore's Central Area, made up of five precincts that took shape between the 1820s and the 1920s. Singapore has no tier of local government and the whole island state is run directly by the national government, with the Urban Redevelopment Authority handling planning and conservation; since 1989 the shophouses here have been gazetted as a conservation area, so facades, windows and roofs are governed by rule and alterations may only be made within that frame. The district began as an administrative division: the Raffles Town Plan of 1822 allotted the land south-west of the Singapore River to Chinese settlers, setting the pattern of communities by quarter. Its Chinese and Malay names, Kreta Ayer, both mean bullock water-cart and refer to the carts that hauled water into this district in the nineteenth century, when there was no piped supply. It is not only Chinese temples today: the Buddha Tooth Relic Temple, the Sri Mariamman Hindu temple, Thian Hock Keng and the Jamae Mosque stand within a few streets of each other, and that mixture is the ordinary condition of the old town. The Chinatown Complex is among the largest hawker centres in the country. Newcomers most often go wrong by reading Chinatown as where Singapore's Chinese live, when Chinese are more than seventy per cent of the whole country and this is a historic quarter, not an enclave.",
    layout:
      "The district is built around a handful of old streets — Smith Street, Pagoda Street, Trengganu Street — lined with dense rows of two- and three-storey Nanyang shophouses; historically the area was subdivided by dialect group (Hokkien, Teochew, Cantonese, Hainanese, Hakka, Henghua and Foochow), a pattern still traceable in street names and temple locations today. The Buddha Tooth Relic Temple and the Sri Mariamman Temple stand only a few hundred metres apart, a direct illustration of Chinese and Indian faiths coexisting within the same quarter.",
    gettingAround:
      "Chinatown MRT station (EW/NE line interchange) sits right in the district's centre; Chinatown has no airport of its own and is reached via Changi Airport (about 20 km from the city centre); the district is compact and best explored on foot.",
    culture:
      "Sri Mariamman Temple, built in 1827, is Singapore's oldest Hindu temple, its gopuram tower densely covered in colourful deity sculptures; the Buddha Tooth Relic Temple, completed in 2007, is built in a Tang-dynasty-inspired style and houses what is said to be an actual tooth relic of the Buddha. Shoes come off before entering either temple, and some inner halls of the Hindu temple may be restricted to worshippers — follow posted signage.",
    seeAndDo:
      "Sri Mariamman Temple (1827, Singapore's oldest Hindu temple); the Buddha Tooth Relic Temple and Museum (Tang-style architecture and the Buddha tooth relic); the shophouse streets and night market along Smith Street and Trengganu Street; the Chinatown Heritage Centre (early immigrant life); Chinatown Complex (hawker centre and wet market).",
    whenAndTips:
      "In the weeks around Lunar New Year the district is strung with lanterns and hosts a festive market — its liveliest but also its most crowded stretch; a weekday evening of temple-hopping and street food is a more relaxed way to see it.",
  },
  "kampong-glam": {
    identity:
      "Kampong Glam is Singapore's historic Malay-Muslim quarter; Raffles' 1822 town plan allotted this area to the Malay, Bugis and Arab communities, and in 1823 the British East India Company formally granted part of it to Sultan Hussein Shah of Johor as a royal seat, making it one of the few districts in Singapore that preserves a continuous royal-historical thread.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Kampong Glam (Singapore; a neighbourhood in the Rochor planning area known as the Muslim quarter; the name from the gelam tree, a Melaleuca species; home to Malay aristocracy before 1819, and under the Raffles Plan of 1822 designated for the Sultan and his household and for the Malay and Arab communities; the Sultan Mosque and Istana Kampong Glam, now the Malay Heritage Centre; restored shophouses along Arab Street, Haji Lane and Bussorah Street; traditional textile, blacksmith and religious-goods trades alongside galleries, cafes and design firms; the One Kampong Gelam association formed in 2014)
    howItWorks:
      "Kampong Glam is a neighbourhood in the Rochor planning area of Singapore, often called the Muslim quarter. Singapore has no tier of local government and the whole island state is run directly by the national government, with the Urban Redevelopment Authority handling planning and conservation; the district has been gazetted for conservation since 1989 and its shophouse facades and structures are restored under rule, so the look of the whole quarter is fixed by policy. The name comes from the gelam tree, a local melaleuca. Before 1819 this was where Malay aristocracy lived, and the Raffles Plan of 1822 assigned it to the Sultan and his household and to the Malay and Arab communities — the clearest case of that division by quarter. The golden dome of the Sultan Mosque is the landmark of the district, and Istana Kampong Glam beside it is now the Malay Heritage Centre. Arab Street and the lanes around it were the trade in textiles, gold, spices and goods for the hajj, and journeys to Mecca were long arranged from here; Haji Lane is now small shops and galleries. Newcomers most often go wrong by reading it as a street of restaurants and photographs, when it remains a religious and commercial centre for the Malay Muslim community.",
    layout:
      "The Sultan Mosque forms the district's geographic and visual centre; the old shophouses along Haji Lane and Arab Street have been reinvented as cafés, indie boutiques and a hub of street murals, while textile, perfume and carpet shops persist around the mosque — a blend of old and new woven into the same streetscape. The old Istana (palace) complex is the core site for understanding this local royal history.",
    gettingAround:
      "Bugis MRT station (EW/DT line interchange) is a short walk away; Kampong Glam has no airport of its own and is reached via Changi Airport (about 20 km from the city centre); the district is compact and best explored on foot.",
    culture:
      "Sultan Mosque was first built in 1824 by Sultan Hussein Shah, Singapore's first sultan; the current building dates to a 1932 reconstruction, its golden domes the district's landmark, with carpeting inside donated by a Saudi Arabian prince. Shoes come off before entering, and women should carry a headscarf and dress modestly. Haji Lane takes its name from the boarding houses that once sheltered pilgrims travelling to and from Mecca.",
    seeAndDo:
      "Sultan Mosque (first built 1824, present building from 1932); the old Istana Kampong Glam (Malay Heritage Centre, tracing this local royal history); the murals and indie shops of Haji Lane; the Middle Eastern-inflected shops and carpet stores of Arab Street; Middle Eastern and Turkish restaurants nearby.",
    whenAndTips:
      "Some shops adjust their hours during Ramadan, but it's also a good time to experience the local Muslim community's iftar bazaar atmosphere; weekday evenings offer softer light for photographing the Sultan Mosque and Haji Lane's murals.",
  },
  "little-india-singapore": {
    identity:
      "Little India is Singapore's historic Indian quarter; Indian labourers were drawn here in the 19th century by the area's lime kilns and brick-making industry, gradually forming an Indian residential and trading district centred on Serangoon Road, gazetted as a conservation area in 1989.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Little India, Singapore (a district in the Rochor planning area east of the Singapore River, across from Chinatown and north of Kampong Glam, known within the Indian Singaporean community as Tekka; it grew from 19th-century cattle trading rather than from an allocation in the 1822 Raffles Town Plan, Indian migrant workers finding work in cattle rearing along the Serangoon River and settling permanently as Europeans left and the swamps were drained; gazetted as a conservation area on 7 July 1989; the Sri Veeramakaliamman Temple, the Tekka Centre market, Mustafa Centre and several mosques and temples; Deepavali and Thaipusam; served by the North East and Downtown MRT lines)
    howItWorks:
      "Little India is a district in the Rochor planning area of Singapore, east of the Singapore River across from Chinatown with Kampong Glam to its south, and known within the Indian Singaporean community as Tekka. Singapore has no tier of local government and the whole island state is run directly by the national government, with the Urban Redevelopment Authority handling planning and conservation, and the district was gazetted for conservation on 7 July 1989. Its origin differs from Chinatown's and Kampong Glam's: the Raffles Town Plan of 1822 did not allot this ground to Indians — it grew of itself, because cattle trading and brick kilns along the Serangoon River in the nineteenth century needed labour, Indian migrants gathered here for that work, and settled permanently as the European traders moved away and the swamps were drained. So the district's spine is Serangoon Road, lined by the Sri Veeramakaliamman temple, mosques and the Tekka market, with the Mustafa Centre trading almost around the clock. The streets are lit for Deepavali and Thaipusam, and Sunday is when migrant workers gather here. Newcomers most often go wrong by assuming the three ethnic quarters were made the same way, when Little India was not planned.",
    layout:
      "Serangoon Road is the district's main artery, densely lined with spice shops, goldsmiths, sari stores and Hindu temples; Tekka Centre (its predecessor Tekka Market opened in 1915; the present building dates from 1982) is one of Singapore's largest wet markets and a core spot for Indian food, while the district's colourful Nanyang shophouse façades echo the equally colourful temple towers nearby.",
    gettingAround:
      "Little India MRT station (NE/DT line interchange) sits at the heart of the district; Little India has no airport of its own and is reached via Changi Airport (about 20 km from the city centre); the district is compact and best combined with a short MRT ride.",
    culture:
      "Sri Veeramakaliamman Temple, whose shrine dates from 1855 (the temple itself was built in 1881), is among Singapore's earliest temples dedicated to the Hindu goddess Kali, its gopuram tower densely and elaborately sculpted; shoes come off before entering, and women should dress modestly. During Deepavali and Thaipusam the district is elaborately lit and hosts major processions.",
    seeAndDo:
      "Sri Veeramakaliamman Temple (shrine from 1855, temple built 1881, dedicated to the goddess Kali); Tekka Centre (original market 1915, present building 1982, one of Singapore's largest wet markets and food centres); the spice and sari shops along Serangoon Road; nearby Indian restaurants and sweet shops.",
    whenAndTips:
      "Deepavali (October–November, dates vary by year) and Thaipusam (January–February) bring elaborate lighting and processions to the district — its liveliest but also busiest stretch; weekday afternoons offer a more unhurried pace for temples and Tekka Centre.",
  },
};
