import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "slovenia-overview": {
    // 全七段 sources: 同中文侧。Population 2,135,107 on 1 Jan 2026 (SURS, released 2026-04-24)；212 municipalities incl. 12 urban municipalities (gov.si)；
    // Slovene official, Italian/Hungarian also official in municipalities where those national communities live (Constitution Art. 11)；euro from 1 Jan 2007；Schengen 2007；e-vinjeta。
    // ⚠️ tipping line 3 级，当批核实。2026-09-13 首写。零争议：不写南缘邻国国名、不写海岸线长度与海域划界。
    identity:
      "Slovenia sits where the Alps, the Dinaric mountains, the Pannonian plain and the Adriatic meet, with a population of about 2.135 million on 1 January 2026 (Statistical Office of the Republic of Slovenia). The country is small, but within short distances it packs four utterly different landscapes: limestone peaks and glacial lakes in the north-west, karst plateaus and caves in the south-west, flat river plains in the north-east, and a short stretch of coast in the south-western corner.",
    howItWorks:
      "Slovenia has no self-governing regions or provinces; local government has a single tier of 212 municipalities (občine), twelve of them urban municipalities, each run by an elected mayor and council. Twelve statistical regions exist for statistics only and are not administrative bodies. Ljubljana is the country's political, transport and university centre, where the main railway lines and motorways converge. Locals describe where they are by historical region — Upper Carniola, Styria, the Littoral, Lower Carniola, Prekmurje — names that remain part of everyday speech. Daily life is shaped by valleys: towns follow river valleys and basins, and crossing a ridge often takes far longer than the straight-line distance suggests. The commonest misunderstanding among newcomers is that a small country can be seen in a day, when the drive between the mountains and the coast often takes a good part of one.",
    layout:
      "Broadly: the Ljubljana Basin and the capital in the centre; the Julian Alps with Lakes Bled and Bohinj in the north-west, and the Kamnik–Savinja Alps and the Karawanks along the north; the Soča valley and the Brda hills in the west; the Kras plateau, the Škocjan Caves and the inland karst fields in the south-west, with the short coast of Koper and Piran beyond; and Maribor, Ptuj and the Mura Plain in the north-east. The Sava crosses the middle of the country from north-west to south-east.",
    gettingAround:
      "Ljubljana Jože Pučnik Airport is the main air gateway; there are no year-round scheduled domestic flights between Slovenian cities, so travel is by rail, intercity coach and car. The rail network radiates from Ljubljana, but some mountain and coastal lines run infrequently and coaches are often more convenient. Traffic drives on the right, and motorways and expressways require an electronic vignette (e-vinjeta). Slovenia has used the euro since 1 January 2007 and joined the Schengen Area in 2007.",
    culture:
      "Slovene is the official language; in municipalities where the Italian and Hungarian national communities live, Italian or Hungarian is also official and signs are bilingual. English is widely spoken among younger people and in tourism. Alpine dairy pastures and cheese, air-dried ham and wine on the karst plateau, and spa culture in the north-east are among the country's most distinctive local traditions. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy. Mains power is 230 V with standard two-pin European plugs.",
    seeAndDo:
      "Landscapes: Triglav and the Julian Alps, Lakes Bled and Bohinj, Vintgar Gorge, the Soča valley, the Škocjan Caves, intermittent Lake Cerknica and the Logar Valley. Towns and heritage: Ljubljana's old town and Plečnik's architecture, Maribor's Drava riverfront, Ptuj's old town and carnival tradition, Piran's Tartini Square and Koper's Venetian-style old town.",
    whenAndTips:
      "May–June and September are the most comfortable months nationwide; July–August brings the biggest crowds to the coast and lakes and peak season on mountain trails; December–March is ski season in the Alps, and high trails depend on weather and snow. Before heading into the high mountains, check trail and weather information from Triglav National Park and the Alpine Association; some high routes are unsuitable for ordinary hikers in winter and spring.",
  },
  ljubljana: {
    // 全七段 sources: 同中文侧。Municipality population 302,826 on 1 Jan 2026 (SURS SiStat 05E1022S, 2026H1)；17 districts with district councils；LJU at Brnik ~26 km by road；LPP buses, Urbana card also valid for the castle funicular；Plečnik's works inscribed 2021。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Ljubljana is the capital of Slovenia, with a municipal population of about 303,000 on 1 January 2026 (Statistical Office of the Republic of Slovenia). It lies in the Ljubljana Basin, with Castle Hill rising in the middle of the city and the Ljubljanica curving around the old town at its foot; many of the old town's bridges, embankments and market arcades are the work of the architect Jože Plečnik, inscribed on the World Heritage List in 2021 as an example of 'human centred urban design'.",
    howItWorks:
      "Ljubljana is an urban municipality run by an elected mayor and city council, and it is divided into 17 districts, each with its own district council handling neighbourhood matters. The city's centre is the old town along the Ljubljanica at the foot of Castle Hill, with government offices, the university and the main cultural institutions all within walking distance. Addresses read street and number, and locals orient by the castle, the river, the Triple Bridge and Prešeren Square. Daily life runs on the city bus network operated by Ljubljana Passenger Transport, and a single Urbana card covers both the buses and the castle funicular. The commonest misunderstanding among newcomers is to take the small old town for the whole city — most homes and workplaces lie beyond it, out towards the ring road.",
    layout:
      "The city's framework is Castle Hill and the Ljubljanica. The old town lines both banks of the river on the western side of the hill, with Prešeren Square and the Triple Bridge as its hub and the Central Market running along the river to the Dragon Bridge. West of the river lies the city centre that took shape from the nineteenth century, with its government buildings, and beyond it to the north-west is Tivoli Park. The railway and bus stations are north of the centre. To the south lies the flat Ljubljana Marsh, and to the north the Sava and the plain leading to Upper Carniola.",
    gettingAround:
      "Jože Pučnik Airport is at Brnik north of the city, about 26 km by road, served by airport shuttles and city buses. Getting around town is mainly by bus, and the Urbana card works on buses and the castle funicular; the heart of the old town is largely pedestrian. The railway station is the hub of the national network, with trains for Bled, Maribor and the coast. The old town is small and its main sights are walkable; you can walk up to the castle or take the funicular.",
    culture:
      "Slovene is spoken, and English is widely understood. Riverside cafés and the open-air market are part of everyday life in the old town, and the area around the Central Market is where local produce is most concentrated. Plečnik's bridges, colonnades and public spaces are the city's most distinctive heritage. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy.",
    seeAndDo:
      "Ljubljana Castle and the view over the city; the Triple Bridge, Prešeren Square and the Ljubljanica embankments; Plečnik's Central Market colonnade; the Dragon Bridge; Tivoli Park; the wetland trails of the Ljubljana Marsh on the southern edge of the city; and, as a base, day trips to Bled, Bohinj and the karst region.",
    whenAndTips:
      "May–June and September–October are the most comfortable; summer evenings along the river are lively; the old town holds Christmas markets in December. Fog is common in the basin in winter. The paths up Castle Hill are steep, so wear good walking shoes.",
  },
  maribor: {
    // 全七段 sources: 同中文侧。Municipality population 114,872 on 1 Jan 2026, second-largest by municipal population (SURS)；on the Drava；the Old Vine on the Lent riverfront, Guinness World Records 2004 (slovenia.info)；Pohorje cable car lower station ~5 km from the old town (Visit Maribor)；MBX has no stable scheduled passenger flights。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Maribor stands on the Drava in north-eastern Slovenia, with a municipal population of about 115,000 on 1 January 2026 (Statistical Office of the Republic of Slovenia), making it the country's second-largest city by municipal population. It has the forested Pohorje massif at its back and the Drava Plain in front of it, and the Lent riverfront of its old town is its most recognisable stretch.",
    howItWorks:
      "Maribor is an urban municipality run by an elected mayor and city council, and it is divided into city districts, each with its own district council. The city's centre is the old town on the north bank of the Drava, which contains the main square, the town hall and the Lent riverfront; the south bank holds residential and industrial districts that grew up from the nineteenth century. Addresses read street and number, and locals orient by the Drava, its bridges and the main square. Daily life is framed by river and mountain: everyday routines stay in the districts on either bank, while weekends mean skiing or hiking up on Pohorje. The commonest misunderstanding among newcomers is to treat the city as a mere stopover on the way to the mountains, when the old town and riverfront deserve a day of their own.",
    layout:
      "The Drava flows west to east through the city, dividing the old town on the north bank from the newer districts on the south. The old town centres on the main square and drops south to the river at Lent, where the Old Vine House stands on the embankment. Pohorje rises to the south-west, with the cable car's lower station about 5 km from the old town; to the east and south stretches the flat Drava Plain, running on towards Ptuj.",
    gettingAround:
      "The local Edvard Rusjan Airport has no stable scheduled passenger flights; the nearest airports with scheduled services are Graz in Austria and Ljubljana. Maribor is a railway hub with lines to Ljubljana and towards Austria. The city has a bus network; the old town is walkable, and buses run to the Pohorje cable car station.",
    culture:
      "Slovene is spoken, with English usable in tourism. The Styrian region around Maribor has a deep vine-growing and winemaking tradition, and the Old Vine on the Lent riverfront, recognised by Guinness World Records, is still harvested every year. In winter Pohorje is the city's ski slope. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy.",
    seeAndDo:
      "The Lent riverfront and the Old Vine House; the main square and town hall; a walk along the Drava; the cable car up Pohorje for hiking or skiing; and, as a base, Ptuj's old town and the wine country of the Slovene Hills.",
    whenAndTips:
      "May–June and September–October are the most comfortable; summer brings outdoor events and festivals to the riverfront; winter is ski season on Pohorje. Around the autumn grape harvest the surrounding wine estates are at their liveliest.",
  },
  celje: {
    // 全七段 sources: 同中文侧。Municipality population 49,802 on 1 Jan 2026 (SURS)；on the Savinja, ~56 km NE of Ljubljana (Britannica)；Roman Claudia Celeia under Claudius, 1st century (Britannica)；Old Castle of Celje built in the 12th century on hills SE of the town；seat of the Counts of Celje 1333–1456 (Britannica)。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Celje lies on the Savinja in east-central Slovenia, with a municipal population of about 50,000 on 1 January 2026 (Statistical Office of the Republic of Slovenia). It is a city with deep layers of history: known to the Romans as Celeia, it was the seat of the Counts of Celje in the Middle Ages, and the Old Castle of Celje still looks down on the valley from the hills south-east of town.",
    howItWorks:
      "Celje is an urban municipality run by an elected mayor and city council, and it is the central city of the Savinja statistical region. The city's centre is the compact old town on the Savinja, beneath which lie the remains of the Roman town of Celeia, some of them preserved in the underground galleries of the regional museum. Addresses read street and number, and locals orient by the old town, the river and Castle Hill. Daily life is bounded by the valley: the city spreads along the Savinja, with hills and forest all around. The commonest misunderstanding among newcomers is to see it only as a railway stop between Ljubljana and Maribor, when the old town and castle can be covered in half a day — ideal for breaking the journey.",
    layout:
      "The old town lies on the Savinja, a pedestrian area of narrow streets and small squares that holds the regional museum and its Roman galleries, with the railway station right beside it. The castle stands on the hills to the south-east, where the Savinja meanders on towards the Laško valley to the south. Newer districts spread across the flat valley floor.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest one is Ljubljana. Celje is on the Ljubljana–Maribor main line, with frequent trains. The old town is entirely walkable; the Old Castle can be reached on foot by trail or by car to near the top.",
    culture:
      "Slovene is spoken, with English usable among younger people. The story of the Counts of Celje is at the heart of local heritage, and the castle often hosts medieval-themed events. The surrounding Savinja valley is known for growing hops. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy.",
    seeAndDo:
      "The Old Castle of Celje and the view of the Savinja valley from its walls; the old town and the Roman remains in the regional museum; riverside paths along the Savinja; and, as a base, the Laško valley to the south and nearby spa towns.",
    whenAndTips:
      "May–October is the most comfortable; in summer the castle and old town host outdoor events. The trail up to the castle is steep and exposed at midday in peak season, so mornings and evenings are more pleasant.",
  },
  kranj: {
    // 全七段 sources: 同中文侧。Municipality population 57,491 on 1 Jan 2026 (SURS)；old town on a ~30 m high promontory between the Sava and the Kokra, protected as a cultural monument (City of Kranj / Visit Kranj)；Kokra canyon below；Prešeren Grove with the poet's grave (City of Kranj)；LJU not within the municipality。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Kranj is in Upper Carniola in north-western Slovenia, with a municipal population of about 57,500 on 1 January 2026 (Statistical Office of the Republic of Slovenia). Its old town stands on a rock promontory about 30 m high between the Sava and the Kokra, with the green canyon cut by the Kokra right at its foot and, on clear days, a view of the high mountains to the north.",
    howItWorks:
      "Kranj is an urban municipality run by an elected mayor and city council, and it is the central city of Upper Carniola. Its centre is the old town on the promontory, protected as a whole as cultural heritage; modern commercial and industrial areas spread across the flat ground beyond. Addresses read street and number, and locals orient by the old town, the two rivers and the canyon. Daily life is measured against Ljubljana: Kranj is close to both the capital and the international airport, and many people live here and commute to work in Ljubljana. The commonest misunderstanding among newcomers is to treat it as a town to pass through on the way to the airport or the mountains, when the old town and canyon trail are only minutes apart on foot.",
    layout:
      "The old town occupies a triangular rock promontory with the Kokra canyon on its eastern side and the Sava to the south-west, the two rivers meeting near its southern tip. The main street runs north–south along the promontory, and Prešeren Grove lies on the northern edge of the old town. Beyond the promontory the city spreads north and west across the open Sava plain, with the Kamnik–Savinja Alps and the Karawanks in the distance to the north.",
    gettingAround:
      "The city has no airport of its own; Ljubljana Jože Pučnik Airport lies about 9.5 km east of town, in the municipality of Cerklje na Gorenjskem rather than in Kranj. Kranj is on the railway and motorway from Ljubljana towards Upper Carniola and the north-western mountains, with frequent trains and coaches to the capital. The old town and the canyon trail are walkable.",
    culture:
      "Slovene is spoken, with English usable among younger people. The Slovene poet France Prešeren spent his last years in Kranj and is buried here, and the grove around his grave is an important place of remembrance. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy.",
    seeAndDo:
      "The old town and its main street on the promontory; the Kokra canyon trail; Prešeren Grove; views of the high mountains from the edge of the old town; and, as a base, Bled, Bohinj and the Kamnik–Savinja Alps.",
    whenAndTips:
      "May–October is the most comfortable; the canyon trail is slippery after rain. Being close to the airport, it makes a convenient base for arrival or departure days.",
  },
  koper: {
    // 全七段 sources: 同中文侧。Municipality population 54,795 on 1 Jan 2026 (SURS)；bilingual municipality, Koper / Capodistria both official (Culture.si)；Port of Koper Slovenia's only international cargo port (gov.si)；Praetorian Palace 13th c., present appearance mid-15th c., on the south side of the central square (Visit Koper)。零争议：central square not named。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Koper is on the northern part of Slovenia's coast, with a municipal population of about 54,800 on 1 January 2026 (Statistical Office of the Republic of Slovenia). It has two faces: the old town is a Venetian-style quarter of stone streets, while beyond it lies Slovenia's only international cargo port. The municipality is officially bilingual, and both its Slovene name, Koper, and its Italian name, Capodistria, are official.",
    howItWorks:
      "Koper is an urban municipality run by an elected mayor and city council; the Italian national community lives within the municipality, Italian and Slovene are both official, and signs and notices are bilingual. The city's centre is the old town's central square, home to the Praetorian Palace and the cathedral, while its economic centre of gravity is the port outside the old town, through which large volumes of goods move to and from inland central Europe. Addresses read street and number, and street names in the bilingual area appear in two forms. Daily life follows the shoreline: the city spreads along the coast and the hills behind it, where vineyards and small villages sit. The commonest misunderstanding among newcomers is to assume a port city's old town must have been swallowed by industry, when the old town and the port area are clearly separate.",
    layout:
      "The old town sits on a rise projecting into the sea, with the central square, the Praetorian Palace and the cathedral at its highest point and narrow streets running down to the water on every side. The port lies to the north-east and east of the old town, a broad expanse of quays, storage yards and railway tracks; newer districts extend south and east onto the coastal flats. Hills rise gently behind the city, and westward along the coast lie Izola and Piran.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest one is Trieste in Italy, followed by Ljubljana. Koper has a railway line to Ljubljana and convenient coaches, and local buses run along the coast to Izola and Piran. The old town is entirely walkable, with few slopes.",
    culture:
      "Slovene and Italian are both official, with English usable in tourism. The old town's Venetian-style architecture, seaside seafood and olive oil, and wine from the hills behind are at the core of local heritage and food. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy.",
    seeAndDo:
      "The old town's central square and the Praetorian Palace; the cathedral and its bell tower; the old town's narrow streets and small squares; the coastal path towards Izola; and the wine villages in the hills behind the city.",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August is hot and crowded by the sea. The old town stands on a rise and its paving gets hot at midday in summer, so mornings and evenings are better for walking.",
  },
  piran: {
    // 全七段 sources: 同中文侧。Municipality population 18,206 on 1 Jan 2026 (SURS)；Piran settlement >5,300 residents per km², the most densely populated urban settlement (SURS settlements release 2026-06-11)；Tartini Square named after Giuseppe Tartini (1692–1770)；tram Piran–Portorož–Lucija 1912–1953 shaped the elliptical square；old town closed to non-resident traffic, Fornače (Amfora) garage ~838 spaces with minibus to the square (Portorož & Piran tourism)。零争议：no bay / maritime issues。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Piran, at the western end of Slovenia's coast, is an old town crowded onto the tip of a narrow peninsula, with a municipal population of about 18,200 on 1 January 2026 (Statistical Office of the Republic of Slovenia). According to the statistical office's settlement data for the same date, the town of Piran has more than 5,300 residents per square kilometre, the highest density of any urban settlement in the country — something you can feel in the streets, where houses stand wall to wall and lanes are wide enough only for people on foot.",
    howItWorks:
      "Piran is a municipality run by an elected mayor and municipal council, and the municipality also includes the neighbouring resort town of Portorož; it is an officially bilingual area where Slovene and Italian are used side by side. The centre of the old town is Tartini Square, named after the composer and violinist Giuseppe Tartini, who was born here; in the first half of the twentieth century trams ran from here to Portorož. Addresses read street and number, with bilingual street names. Motor vehicles other than residents' are barred from the old town, so visitors park in the garage outside it and walk or take a minibus in. The commonest misunderstanding among newcomers is to expect to drive up to the square — there is nowhere on the peninsula to do that.",
    layout:
      "The old town fills the tip of the peninsula, with Tartini Square on the seaward side, narrow lanes and small squares climbing from it, a church and bell tower on the highest point of the peninsula, and a stretch of the old town walls on the landward side beyond. At the root of the peninsula are the parking garage and the seafront road to Portorož, the resort of hotels and bathing beaches in the bay to the south-east.",
    gettingAround:
      "There is no airport with stable scheduled passenger flights here; the nearest with scheduled services is Trieste in Italy, followed by Ljubljana. There is no railway, so coaches serve Ljubljana and Koper, and local buses link Piran and Portorož within the municipality. The old town is closed to cars: park in the garage outside town and take the minibus to the square.",
    culture:
      "Slovene and Italian are both official, and English is widely spoken in tourism. The old town's Venetian-style architecture, seafood and sea salt from the saltpans are at the core of local heritage and food; Tartini's birthplace and statue are the focus of the square. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy.",
    seeAndDo:
      "Tartini Square and Tartini's birthplace; the bell tower of the church at the top of the peninsula for a view over the town; a stretch of the old town walls; the seafront walk to Portorož; and a slow wander through the old town's lanes.",
    whenAndTips:
      "May–June and September–October are the most comfortable; in July–August the town is crowded and the garage often full, so arrive early or come by coach. The old town has many slopes and steps, so wear good walking shoes.",
  },
  bled: {
    // 全七段 sources: 同中文侧。Municipality population 8,103 on 1 Jan 2026 (SURS)；Bled Castle on a cliff ~130 m above the lake, first mentioned in a deed of 22 May 1011 by Emperor Henry II to the Bishops of Brixen (Bled Castle official site / Bled tourism)；~35 km from LJU and ~55 km from Ljubljana (Bled tourism)；Bled cream cake。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Bled is a small town on the shore of Lake Bled at the eastern foot of the Julian Alps, with a municipal population of about 8,100 on 1 January 2026 (Statistical Office of the Republic of Slovenia). Its image is practically a single picture: the church on the island in the lake, the castle on the cliff above the northern shore and the high mountains behind — the castle stands on a clifftop about 130 m above the water, and its earliest documentary mention dates from 1011.",
    howItWorks:
      "Bled is a municipality run by an elected mayor and municipal council, and the town's daily workings revolve almost entirely around the lake and tourism. The town centre is on the eastern shore, where hotels, shops and the bus station cluster; a path circles the lake, with the castle, the island and a few lakeside villages all strung along it. Addresses read street and number, and locals orient by the lake, the castle and the island. Daily life has a small radius — one walk around the lake is the scale of the whole town — while residents commute or shop in larger towns and Ljubljana. The commonest misunderstanding among newcomers is to assume you can park or get into the water anywhere around the lake; parking is tight in peak season, and traffic and visiting around the lake are regulated.",
    layout:
      "The lake is roughly oval, with the town centre on the eastern shore, the castle on the cliff to the north and the island near the western end. Forest and small villages line the western and southern shores, and the lakeside path can be walked all the way round. Vintgar Gorge lies a short distance north of town, and south-west along the valley of the Sava Bohinjka lies the way to Lake Bohinj.",
    gettingAround:
      "There is no airport with scheduled flights here; Bled's tourist board puts it about 35 km from Ljubljana Airport and about 55 km from Ljubljana, both with direct coaches. There is a railway station nearby on lines towards Ljubljana and towards Bohinj. The town and the lake circuit are entirely walkable; the traditional pletna boats go to the island, and coaches or a car take you to Vintgar Gorge and Bohinj.",
    culture:
      "Slovene is spoken, and English is widely spoken in tourism. Bled cream cake is the town's signature sweet, and the pletna boats on the lake, rowed by hand, are a traditional livelihood that has been kept alive. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy.",
    seeAndDo:
      "A full circuit of the lake path; a pletna boat to the island; Bled Castle and its view of the lake; Vintgar Gorge to the north; Lake Bohinj and the Savica waterfall to the west; and cream cake by the lake.",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August and weekends are crowded and parking is tight, so arrive early or come by coach. The lake is quiet in winter and occasionally freezes over, but the ice is not safe to walk on.",
  },
  ptuj: {
    // 全七段 sources: 同中文侧。Municipality population 23,898 on 1 Jan 2026 (SURS)；on the Drava between the Haloze and Slovene Hills；Roman Poetovio (slovenia.info)；Door-to-door rounds of Kurenti inscribed on UNESCO's Representative List of the Intangible Cultural Heritage of Humanity in December 2017 (slovenia.info)；Ptuj Castle on the hill above the old town。No 'oldest town' claim。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Ptuj lies on the Drava in north-eastern Slovenia, with a municipal population of about 23,900 on 1 January 2026 (Statistical Office of the Republic of Slovenia). Set between two wine districts, the Haloze hills and the Slovene Hills, it was known in Roman times as Poetovio; its old town runs along the river beneath a castle on the hill above, and the Kurent rounds at the end of each winter are its most distinctive folk tradition.",
    howItWorks:
      "Ptuj is an urban municipality run by an elected mayor and city council, and it is the central town for the surrounding countryside. Its centre is the compact old town on the north bank of the Drava, where squares, monasteries and churches sit at the foot of Castle Hill. Addresses read street and number, and locals orient by the castle, the river and the main square. Daily life is shaped by plain and hills: farmland of the Drava Plain surrounds the town, vineyards cover the hills to the north and south, and people from nearby villages come to Ptuj for errands and markets. The commonest misunderstanding among newcomers is that it is worth visiting only during carnival, when the old town, the castle and the wine country can be enjoyed for most of the year.",
    layout:
      "The Drava flows past the south of the town, with the old town on its north bank, a pedestrian quarter of narrow streets, small squares and monasteries; the castle stands on the hill north of the old town, looking over the whole valley. Newer residential districts and a spa area lie on the south bank. The Slovene Hills rise to the north, the Haloze hills to the south, and the open Drava Plain stretches east and west.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest ones are Graz in Austria and Ljubljana. Ptuj has a railway line towards Maribor and can also be reached by coach. The old town is entirely walkable, and the castle is a short walk up the trail.",
    culture:
      "Slovene is spoken, with English usable among younger people. At the end of winter, during carnival, the Kurenti — figures dressed in sheepskins and masks with bells at their waists — go from door to door to drive winter away, a tradition inscribed in 2017 on UNESCO's Representative List of the Intangible Cultural Heritage of Humanity. Wine from the two surrounding hill districts is an important part of local food. Restaurant bills usually do not include a service charge; about ten per cent, or rounding up, is customary if you are happy.",
    seeAndDo:
      "Ptuj Castle and its museum; the old town's squares, monasteries and churches; a walk along the Drava; the Kurent rounds and carnival at the end of winter; and the wine villages of the Haloze hills to the south and the Slovene Hills to the north.",
    whenAndTips:
      "May–October is the most comfortable; carnival falls at the end of winter (its dates move with the pre-Easter season), when beds are scarce and need booking ahead. During the autumn grape harvest the surrounding wine estates are at their liveliest.",
  },
};
