import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "slovenia-overview": {
    // 全七段 sources: 同中文侧。Population 2,135,107 on 1 Jan 2026 (SURS, released 2026-04-24)；212 municipalities incl. 12 urban municipalities (gov.si)；
    // Slovene official, Italian/Hungarian also official in municipalities where those national communities live (Constitution Art. 11)；euro from 1 Jan 2007；Schengen 2007；e-vinjeta。
    // ⚠️ tipping line 3 级，当批核实。2026-09-13 首写。零争议：不写南缘邻国国名、不写海岸线长度与海域划界。
    identity:
      "Slovenia sits where the Alps, the Dinaric mountains, the Pannonian plain and the Adriatic meet, with a population of about 2.135 million on 1 January 2026 (Statistical Office of the Republic of Slovenia). The country is small, but within short distances it packs four utterly different landscapes: limestone peaks and glacial lakes in the north-west, karst plateaus and caves in the south-west, flat river plains in the north-east, and a short stretch of coast in the south-western corner.",
    howItWorks:
      "Slovenia has no self-governing regions or provinces; local government has a single tier of 212 municipalities (občine), twelve of them urban municipalities, each run by an elected mayor and council. Twelve statistical regions exist for statistics only and are not administrative bodies. Ljubljana is the country's political, transport and university centre, where the main railway lines and motorways converge. Locals describe where they are by historical region — Upper Carniola, Styria, the Littoral, Lower Carniola, Prekmurje — names that remain part of everyday speech. Daily life is shaped by valleys: towns follow river valleys and basins, and crossing a ridge often takes far longer than the straight-line distance suggests. The commonest misunderstanding among newcomers is that a small country can be seen in a day, when the drive between the mountains and the coast often takes a good part of one.",
    layout:
      "Broadly: the Ljubljana Basin and the capital in the centre; the Julian Alps with Lakes Bled and Bohinj in the north-west, and the Kamnik–Savinja Alps and the Karawanks along the north; the Soča valley and the Brda hills in the west; the Kras plateau, the Škocjan Caves and the inland karst fields in the south-west, with the short coast of Koper and Piran beyond; and Maribor, Ptuj and the Mura Plain in the north-east. The Sava crosses the middle of the country from north-west to south-east.",
    gettingAround:
      "Ljubljana Jože Pučnik Airport is the main air gateway; there are no year-round scheduled domestic flights between Slovenian cities, so travel is by rail, intercity coach and car. The rail network radiates from Ljubljana, but some mountain and coastal lines run infrequently and coaches are often more convenient. Traffic drives on the right, and motorways and expressways require an electronic vignette (e-vinjeta). Slovenia has used the euro since 1 January 2007 and joined the Schengen Area in 2007.",
    culture:
      "Slovene is the official language; in municipalities where the Italian and Hungarian national communities live, Italian or Hungarian is also official and signs are bilingual. English is widely spoken among younger people and in tourism. Alpine dairy pastures and cheese, air-dried ham and wine on the karst plateau, and spa culture in the north-east are among the country's most distinctive local traditions. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill. Mains power is 230 V with standard two-pin European plugs.",
    seeAndDo:
      "Landscapes: Triglav and the Julian Alps, Lakes Bled and Bohinj, Vintgar Gorge, the Soča valley, the Škocjan Caves, intermittent Lake Cerknica and the Logar Valley. Towns and heritage: Ljubljana's old town and Plečnik's architecture, Maribor's Drava riverfront, Ptuj's old town and carnival tradition, Piran's Tartini Square and Koper's Venetian-style old town.",
    whenAndTips:
      "May–June and September are the most comfortable months nationwide; July–August brings the biggest crowds to the coast and lakes and peak season on mountain trails; December–March is ski season in the Alps, and high trails depend on weather and snow. Before heading into the high mountains, check trail and weather information from Triglav National Park and the Alpine Association; some high routes are unsuitable for ordinary hikers in winter and spring.",
  },
  ljubljana: {
    // 全七段 sources: 同中文侧。Municipality population 302,826 on 1 Jan 2026 (SURS SiStat 05E1022S, 2026H1)；17 districts with district councils；LJU at Brnik ~26 km by road；LPP buses, Urbana card also valid for the castle funicular；Plečnik's works inscribed 2021。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Ljubljana is the capital of Slovenia, with a municipal population of about 303,000 on 1 January 2026 (Statistical Office of the Republic of Slovenia). It lies in the Ljubljana Basin, with Castle Hill rising in the middle of the city and the Ljubljanica curving around the old town at its foot; many of the old town's bridges, embankments and market arcades are the work of the architect Jože Plečnik, inscribed on the World Heritage List in 2021 as an example of 'human centred urban design'.",
    howItWorks:
      "Ljubljana is an urban municipality run by an elected mayor and city council, and it is divided into 17 districts, each with its own district council handling neighbourhood matters. The city's centre is the old town along the Ljubljanica at the foot of Castle Hill, with government offices, the university and the main cultural institutions all within walking distance. Addresses read street and number, and locals orient by the castle, the river, the Triple Bridge and Prešeren Square. Daily life runs on the city bus network operated by Ljubljana Passenger Transport, and a single Urbana card covers both the buses and the castle funicular. The commonest misunderstanding among newcomers is to take the small old town for the whole city — most homes and workplaces lie beyond it, out towards the ring road.",
    layout:
      "The city's framework is Castle Hill and the Ljubljanica. The old town lines both banks of the river on the western side of the hill, with Prešeren Square and the Triple Bridge as its hub and the Central Market running along the river to the Dragon Bridge. West of the river lies the city centre that took shape from the nineteenth century, with its government buildings, and beyond it to the north-west is Tivoli Park. The railway and bus stations are north of the centre. To the south lies the flat Ljubljana Marsh, and to the north the Sava and the plain leading to Upper Carniola.",
    gettingAround:
      "Jože Pučnik Airport is at Brnik north of the city, about 26 km by road, served by airport shuttles and city buses. Getting around town is mainly by bus, and the Urbana card works on buses and the castle funicular; the heart of the old town is largely pedestrian. The railway station is the hub of the national network, with trains for Bled, Maribor and the coast. The old town is small and its main sights are walkable; you can walk up to the castle or take the funicular.",
    culture:
      "Slovene is spoken, and English is widely understood. Riverside cafés and the open-air market are part of everyday life in the old town, and the area around the Central Market is where local produce is most concentrated. Plečnik's bridges, colonnades and public spaces are the city's most distinctive heritage. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "Ljubljana Castle and the view over the city; the Triple Bridge, Prešeren Square and the Ljubljanica embankments; Plečnik's Central Market colonnade; the Dragon Bridge; Tivoli Park; the wetland trails of the Ljubljana Marsh on the southern edge of the city; and, as a base, day trips to Bled, Bohinj and the karst region.",
    whenAndTips:
      "May–June and September–October are the most comfortable; summer evenings along the river are lively; the old town holds Christmas markets in December. Fog is common in the basin in winter. The paths up Castle Hill are steep, so wear good walking shoes.",
  },
  maribor: {
    // 全七段 sources: 同中文侧。Municipality population 114,872 on 1 Jan 2026, second-largest by municipal population (SURS)；on the Drava；the Old Vine on the Lent riverfront, Guinness World Records 2004 (slovenia.info)；Pohorje cable car lower station ~5 km from the old town (Visit Maribor)；MBX has no stable scheduled passenger flights。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Maribor stands on the Drava in north-eastern Slovenia, with a municipal population of about 115,000 on 1 January 2026 (Statistical Office of the Republic of Slovenia), making it the country's second-largest city by municipal population. It has the forested Pohorje massif at its back and the Drava Plain in front of it, and the Lent riverfront of its old town is its most recognisable stretch.",
    howItWorks:
      "Maribor is an urban municipality run by an elected mayor and city council, and it is divided into city districts, each with its own district council. The city's centre is the old town on the north bank of the Drava, which contains the main square, the town hall and the Lent riverfront; the south bank holds residential and industrial districts that grew up from the nineteenth century. Addresses read street and number, and locals orient by the Drava, its bridges and the main square. Daily life is framed by river and mountain: everyday routines stay in the districts on either bank, while weekends mean skiing or hiking up on Pohorje. The commonest misunderstanding among newcomers is to treat the city as a mere stopover on the way to the mountains, when the old town and riverfront deserve a day of their own.",
    layout:
      "The Drava flows west to east through the city, dividing the old town on the north bank from the newer districts on the south. The old town centres on the main square and drops south to the river at Lent, where the Old Vine House stands on the embankment. Pohorje rises to the south-west, with the cable car's lower station about 5 km from the old town; to the east and south stretches the flat Drava Plain, running on towards Ptuj.",
    gettingAround:
      "The local Edvard Rusjan Airport has no stable scheduled passenger flights; the nearest airports with scheduled services are Graz in Austria and Ljubljana. Maribor is a railway hub with lines to Ljubljana and towards Austria. The city has a bus network; the old town is walkable, and buses run to the Pohorje cable car station.",
    culture:
      "Slovene is spoken, with English usable in tourism. The Styrian region around Maribor has a deep vine-growing and winemaking tradition, and the Old Vine on the Lent riverfront, recognised by Guinness World Records, is still harvested every year. In winter Pohorje is the city's ski slope. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "The Lent riverfront and the Old Vine House; the main square and town hall; a walk along the Drava; the cable car up Pohorje for hiking or skiing; and, as a base, Ptuj's old town and the wine country of the Slovene Hills.",
    whenAndTips:
      "May–June and September–October are the most comfortable; summer brings outdoor events and festivals to the riverfront; winter is ski season on Pohorje. Around the autumn grape harvest the surrounding wine estates are at their liveliest.",
  },
  celje: {
    // 全七段 sources: 同中文侧。Municipality population 49,802 on 1 Jan 2026 (SURS)；on the Savinja, ~56 km NE of Ljubljana (Britannica)；Roman Claudia Celeia under Claudius, 1st century (Britannica)；Old Castle of Celje built in the 12th century on hills SE of the town；seat of the Counts of Celje 1333–1456 (Britannica)。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Celje lies on the Savinja in east-central Slovenia, with a municipal population of about 50,000 on 1 January 2026 (Statistical Office of the Republic of Slovenia). It is a city with deep layers of history: known to the Romans as Celeia, it was the seat of the Counts of Celje in the Middle Ages, and the Old Castle of Celje still looks down on the valley from the hills south-east of town.",
    howItWorks:
      "Celje is an urban municipality run by an elected mayor and city council, and it is the central city of the Savinja statistical region. The city's centre is the compact old town on the Savinja, beneath which lie the remains of the Roman town of Celeia, some of them preserved in the underground galleries of the regional museum. Addresses read street and number, and locals orient by the old town, the river and Castle Hill. Daily life is bounded by the valley: the city spreads along the Savinja, with hills and forest all around. The commonest misunderstanding among newcomers is to see it only as a railway stop between Ljubljana and Maribor, when the old town and castle can be covered in half a day — ideal for breaking the journey.",
    layout:
      "The old town lies on the Savinja, a pedestrian area of narrow streets and small squares that holds the regional museum and its Roman galleries, with the railway station right beside it. The castle stands on the hills to the south-east, where the Savinja meanders on towards the Laško valley to the south. Newer districts spread across the flat valley floor.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest one is Ljubljana. Celje is on the Ljubljana–Maribor main line, with frequent trains. The old town is entirely walkable; the Old Castle can be reached on foot by trail or by car to near the top.",
    culture:
      "Slovene is spoken, with English usable among younger people. The story of the Counts of Celje is at the heart of local heritage, and the castle often hosts medieval-themed events. The surrounding Savinja valley is known for growing hops. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "The Old Castle of Celje and the view of the Savinja valley from its walls; the old town and the Roman remains in the regional museum; riverside paths along the Savinja; and, as a base, the Laško valley to the south and nearby spa towns.",
    whenAndTips:
      "May–October is the most comfortable; in summer the castle and old town host outdoor events. The trail up to the castle is steep and exposed at midday in peak season, so mornings and evenings are more pleasant.",
  },
  kranj: {
    // 全七段 sources: 同中文侧。Municipality population 57,491 on 1 Jan 2026 (SURS)；old town on a ~30 m high promontory between the Sava and the Kokra, protected as a cultural monument (City of Kranj / Visit Kranj)；Kokra canyon below；Prešeren Grove with the poet's grave (City of Kranj)；LJU not within the municipality。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Kranj is in Upper Carniola in north-western Slovenia, with a municipal population of about 57,500 on 1 January 2026 (Statistical Office of the Republic of Slovenia). Its old town stands on a rock promontory about 30 m high between the Sava and the Kokra, with the green canyon cut by the Kokra right at its foot and, on clear days, a view of the high mountains to the north.",
    howItWorks:
      "Kranj is an urban municipality run by an elected mayor and city council, and it is the central city of Upper Carniola. Its centre is the old town on the promontory, protected as a whole as cultural heritage; modern commercial and industrial areas spread across the flat ground beyond. Addresses read street and number, and locals orient by the old town, the two rivers and the canyon. Daily life is measured against Ljubljana: Kranj is close to both the capital and the international airport, and many people live here and commute to work in Ljubljana. The commonest misunderstanding among newcomers is to treat it as a town to pass through on the way to the airport or the mountains, when the old town and canyon trail are only minutes apart on foot.",
    layout:
      "The old town occupies a triangular rock promontory with the Kokra canyon on its eastern side and the Sava to the south-west, the two rivers meeting near its southern tip. The main street runs north–south along the promontory, and Prešeren Grove lies on the northern edge of the old town. Beyond the promontory the city spreads north and west across the open Sava plain, with the Kamnik–Savinja Alps and the Karawanks in the distance to the north.",
    gettingAround:
      "The city has no airport of its own; Ljubljana Jože Pučnik Airport lies about 9.5 km east of town, in the municipality of Cerklje na Gorenjskem rather than in Kranj. Kranj is on the railway and motorway from Ljubljana towards Upper Carniola and the north-western mountains, with frequent trains and coaches to the capital. The old town and the canyon trail are walkable.",
    culture:
      "Slovene is spoken, with English usable among younger people. The Slovene poet France Prešeren spent his last years in Kranj and is buried here, and the grove around his grave is an important place of remembrance. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "The old town and its main street on the promontory; the Kokra canyon trail; Prešeren Grove; views of the high mountains from the edge of the old town; and, as a base, Bled, Bohinj and the Kamnik–Savinja Alps.",
    whenAndTips:
      "May–October is the most comfortable; the canyon trail is slippery after rain. Being close to the airport, it makes a convenient base for arrival or departure days.",
  },
  koper: {
    // 全七段 sources: 同中文侧。Municipality population 54,795 on 1 Jan 2026 (SURS)；bilingual municipality, Koper / Capodistria both official (Culture.si)；Port of Koper Slovenia's only international cargo port (gov.si)；Praetorian Palace 13th c., present appearance mid-15th c., on the south side of the central square (Visit Koper)。零争议：central square not named。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Koper is on the northern part of Slovenia's coast, with a municipal population of about 54,800 on 1 January 2026 (Statistical Office of the Republic of Slovenia). It has two faces: the old town is a Venetian-style quarter of stone streets, while beyond it lies Slovenia's only international cargo port. The municipality is officially bilingual, and both its Slovene name, Koper, and its Italian name, Capodistria, are official.",
    howItWorks:
      "Koper is an urban municipality run by an elected mayor and city council; the Italian national community lives within the municipality, Italian and Slovene are both official, and signs and notices are bilingual. The city's centre is the old town's central square, home to the Praetorian Palace and the cathedral, while its economic centre of gravity is the port outside the old town, through which large volumes of goods move to and from inland central Europe. Addresses read street and number, and street names in the bilingual area appear in two forms. Daily life follows the shoreline: the city spreads along the coast and the hills behind it, where vineyards and small villages sit. The commonest misunderstanding among newcomers is to assume a port city's old town must have been swallowed by industry, when the old town and the port area are clearly separate.",
    layout:
      "The old town sits on a rise projecting into the sea, with the central square, the Praetorian Palace and the cathedral at its highest point and narrow streets running down to the water on every side. The port lies to the north-east and east of the old town, a broad expanse of quays, storage yards and railway tracks; newer districts extend south and east onto the coastal flats. Hills rise gently behind the city, and westward along the coast lie Izola and Piran.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest one is Trieste in Italy, followed by Ljubljana. Koper has a railway line to Ljubljana and convenient coaches, and local buses run along the coast to Izola and Piran. The old town is entirely walkable, with few slopes.",
    culture:
      "Slovene and Italian are both official, with English usable in tourism. The old town's Venetian-style architecture, seaside seafood and olive oil, and wine from the hills behind are at the core of local heritage and food. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "The old town's central square and the Praetorian Palace; the cathedral and its bell tower; the old town's narrow streets and small squares; the coastal path towards Izola; and the wine villages in the hills behind the city.",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August is hot and crowded by the sea. The old town stands on a rise and its paving gets hot at midday in summer, so mornings and evenings are better for walking.",
  },
  piran: {
    // 全七段 sources: 同中文侧。Municipality population 18,206 on 1 Jan 2026 (SURS)；Piran settlement >5,300 residents per km², the most densely populated urban settlement (SURS settlements release 2026-06-11)；Tartini Square named after Giuseppe Tartini (1692–1770)；tram Piran–Portorož–Lucija 1912–1953 shaped the elliptical square；old town closed to non-resident traffic, Fornače (Amfora) garage ~838 spaces with minibus to the square (Portorož & Piran tourism)。零争议：no bay / maritime issues。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Piran, at the western end of Slovenia's coast, is an old town crowded onto the tip of a narrow peninsula, with a municipal population of about 18,200 on 1 January 2026 (Statistical Office of the Republic of Slovenia). According to the statistical office's settlement data for the same date, the town of Piran has more than 5,300 residents per square kilometre, the highest density of any urban settlement in the country — something you can feel in the streets, where houses stand wall to wall and lanes are wide enough only for people on foot.",
    howItWorks:
      "Piran is a municipality run by an elected mayor and municipal council, and the municipality also includes the neighbouring resort town of Portorož; it is an officially bilingual area where Slovene and Italian are used side by side. The centre of the old town is Tartini Square, named after the composer and violinist Giuseppe Tartini, who was born here; in the first half of the twentieth century trams ran from here to Portorož. Addresses read street and number, with bilingual street names. Motor vehicles other than residents' are barred from the old town, so visitors park in the garage outside it and walk or take a minibus in. The commonest misunderstanding among newcomers is to expect to drive up to the square — there is nowhere on the peninsula to do that.",
    layout:
      "The old town fills the tip of the peninsula, with Tartini Square on the seaward side, narrow lanes and small squares climbing from it, a church and bell tower on the highest point of the peninsula, and a stretch of the old town walls on the landward side beyond. At the root of the peninsula are the parking garage and the seafront road to Portorož, the resort of hotels and bathing beaches in the bay to the south-east.",
    gettingAround:
      "There is no airport with stable scheduled passenger flights here; the nearest with scheduled services is Trieste in Italy, followed by Ljubljana. There is no railway, so coaches serve Ljubljana and Koper, and local buses link Piran and Portorož within the municipality. The old town is closed to cars: park in the garage outside town and take the minibus to the square.",
    culture:
      "Slovene and Italian are both official, and English is widely spoken in tourism. The old town's Venetian-style architecture, seafood and sea salt from the saltpans are at the core of local heritage and food; Tartini's birthplace and statue are the focus of the square. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "Tartini Square and Tartini's birthplace; the bell tower of the church at the top of the peninsula for a view over the town; a stretch of the old town walls; the seafront walk to Portorož; and a slow wander through the old town's lanes.",
    whenAndTips:
      "May–June and September–October are the most comfortable; in July–August the town is crowded and the garage often full, so arrive early or come by coach. The old town has many slopes and steps, so wear good walking shoes.",
  },
  bled: {
    // 全七段 sources: 同中文侧。Municipality population 8,103 on 1 Jan 2026 (SURS)；Bled Castle on a cliff ~130 m above the lake, first mentioned in a deed of 22 May 1011 by Emperor Henry II to the Bishops of Brixen (Bled Castle official site / Bled tourism)；~35 km from LJU and ~55 km from Ljubljana (Bled tourism)；Bled cream cake。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Bled is a small town on the shore of Lake Bled at the eastern foot of the Julian Alps, with a municipal population of about 8,100 on 1 January 2026 (Statistical Office of the Republic of Slovenia). Its image is practically a single picture: the church on the island in the lake, the castle on the cliff above the northern shore and the high mountains behind — the castle stands on a clifftop about 130 m above the water, and its earliest documentary mention dates from 1011.",
    howItWorks:
      "Bled is a municipality run by an elected mayor and municipal council, and the town's daily workings revolve almost entirely around the lake and tourism. The town centre is on the eastern shore, where hotels, shops and the bus station cluster; a path circles the lake, with the castle, the island and a few lakeside villages all strung along it. Addresses read street and number, and locals orient by the lake, the castle and the island. Daily life has a small radius — one walk around the lake is the scale of the whole town — while residents commute or shop in larger towns and Ljubljana. The commonest misunderstanding among newcomers is to assume you can park or get into the water anywhere around the lake; parking is tight in peak season, and traffic and visiting around the lake are regulated.",
    layout:
      "The lake is roughly oval, with the town centre on the eastern shore, the castle on the cliff to the north and the island near the western end. Forest and small villages line the western and southern shores, and the lakeside path can be walked all the way round. Vintgar Gorge lies a short distance north of town, and south-west along the valley of the Sava Bohinjka lies the way to Lake Bohinj.",
    gettingAround:
      "There is no airport with scheduled flights here; Bled's tourist board puts it about 35 km from Ljubljana Airport and about 55 km from Ljubljana, both with direct coaches. There is a railway station nearby on lines towards Ljubljana and towards Bohinj. The town and the lake circuit are entirely walkable; the traditional pletna boats go to the island, and coaches or a car take you to Vintgar Gorge and Bohinj.",
    culture:
      "Slovene is spoken, and English is widely spoken in tourism. Bled cream cake is the town's signature sweet, and the pletna boats on the lake, rowed by hand, are a traditional livelihood that has been kept alive. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "A full circuit of the lake path; a pletna boat to the island; Bled Castle and its view of the lake; Vintgar Gorge to the north; Lake Bohinj and the Savica waterfall to the west; and cream cake by the lake.",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August and weekends are crowded and parking is tight, so arrive early or come by coach. The lake is quiet in winter and occasionally freezes over, but the ice is not safe to walk on.",
  },
  ptuj: {
    // 全七段 sources: 同中文侧。Municipality population 23,898 on 1 Jan 2026 (SURS)；on the Drava between the Haloze and Slovene Hills；Roman Poetovio (slovenia.info)；Door-to-door rounds of Kurenti inscribed on UNESCO's Representative List of the Intangible Cultural Heritage of Humanity in December 2017 (slovenia.info)；Ptuj Castle on the hill above the old town。No 'oldest town' claim。⚠️ 当批核实。2026-09-13 首写。
    identity:
      "Ptuj lies on the Drava in north-eastern Slovenia, with a municipal population of about 23,900 on 1 January 2026 (Statistical Office of the Republic of Slovenia). Set between two wine districts, the Haloze hills and the Slovene Hills, it was known in Roman times as Poetovio; its old town runs along the river beneath a castle on the hill above, and the Kurent rounds at the end of each winter are its most distinctive folk tradition.",
    howItWorks:
      "Ptuj is an urban municipality run by an elected mayor and city council, and it is the central town for the surrounding countryside. Its centre is the compact old town on the north bank of the Drava, where squares, monasteries and churches sit at the foot of Castle Hill. Addresses read street and number, and locals orient by the castle, the river and the main square. Daily life is shaped by plain and hills: farmland of the Drava Plain surrounds the town, vineyards cover the hills to the north and south, and people from nearby villages come to Ptuj for errands and markets. The commonest misunderstanding among newcomers is that it is worth visiting only during carnival, when the old town, the castle and the wine country can be enjoyed for most of the year.",
    layout:
      "The Drava flows past the south of the town, with the old town on its north bank, a pedestrian quarter of narrow streets, small squares and monasteries; the castle stands on the hill north of the old town, looking over the whole valley. Newer residential districts and a spa area lie on the south bank. The Slovene Hills rise to the north, the Haloze hills to the south, and the open Drava Plain stretches east and west.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest ones are Graz in Austria and Ljubljana. Ptuj has a railway line towards Maribor and can also be reached by coach. The old town is entirely walkable, and the castle is a short walk up the trail.",
    culture:
      "Slovene is spoken, with English usable among younger people. At the end of winter, during carnival, the Kurenti — figures dressed in sheepskins and masks with bells at their waists — go from door to door to drive winter away, a tradition inscribed in 2017 on UNESCO's Representative List of the Intangible Cultural Heritage of Humanity. Wine from the two surrounding hill districts is an important part of local food. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "Ptuj Castle and its museum; the old town's squares, monasteries and churches; a walk along the Drava; the Kurent rounds and carnival at the end of winter; and the wine villages of the Haloze hills to the south and the Slovene Hills to the north.",
    whenAndTips:
      "May–October is the most comfortable; carnival falls at the end of winter (its dates move with the pre-Easter season), when beds are scarce and need booking ahead. During the autumn grape harvest the surrounding wine estates are at their liveliest.",
  },
  idrija: {
    // 全七段 sources: 同中文侧（SURS SiStat 05E1022S 2026H1 and 05C5006S, tier 1; gov.si municipality list, tier 1; idrija.si, tier 1; UNESCO 1313, tier 1; Idrija Geopark and CUDHg, tier 1 managers; Idrija tourist board, tier 1; distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Idrija is a mining town in a valley in western Slovenia; on 1 January 2026 the town itself had about 5,700 people and the Municipality of Idrija about 11,500 (Statistical Office of Slovenia). Mercury was first found here in 1490, and for the next five hundred years the town revolved around the mine; in 2012 Idrija and Almadén in Spain were inscribed together on the World Heritage list as the Heritage of Mercury.",
    howItWorks:
      "Idrija is an ordinary municipality run by a directly elected mayor and a municipal council, divided into 10 local communities whose councils are elected by their residents. The name covers two things: an old town of just over five thousand people, and a mountain municipality of about 293 km² with more than thirty settlements, the whole of which is also the Idrija UNESCO Global Geopark. The town's layout was shaped by the mine: shaft entrances, a castle built to store mercury and house the mine's management, a miners' theatre and the smelting plant are all in town, and timber was once flushed down to it by releasing water from dams in the hills. The smelter shut down in 1995, and since 2016 a public institution has looked after the mine and monitored the area. Locals find their way by the castle, the main square and the smelter. Daily life follows the valley: there is no railway, so reaching Ljubljana means a bus or a change onto the train at Logatec. Newcomers often take it for an Alpine resort, when what it offers is underground and industrial heritage.",
    layout:
      "The town runs along the Idrijca valley, with the old main square and the municipal offices on the valley floor and Gewerkenegg Castle on the slope just west of the square; the entrance to Anthony's Main Road is about 500 m south of the square, the Kamšt water wheel is in the south-east of town and the smelting plant is by the river to the north-east. Wild Lake is about 2 km south of town, and the old timber-floating dams sit higher up in the hills along the upper Idrijca.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest is Ljubljana (LJU), about 42 km away in a straight line. Idrija has no railway: coming by train from the Ljubljana, Postojna or Koper direction, get off at Logatec and change to a bus, and there are also direct buses between Idrija and Ljubljana. By car, leave the A1 motorway at Logatec. The town is walkable.",
    culture:
      "Slovene is spoken, with English usable at the sights. Idrija lace is a craft handed down in miners' families and the town has a lace school; bobbin lacemaking in Slovenia is on UNESCO's Representative List of the Intangible Cultural Heritage of Humanity. Idrijski žlikrofi, small potato-filled dumplings, are registered as an EU Traditional Speciality Guaranteed. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "Put on protective gear and go down Anthony's Main Road; the smelting plant visitor centre; the municipal museum in Gewerkenegg Castle, with exhibitions on the mercury mine and lace; the Kamšt wooden water wheel; the mining machinery at the Frančiška Shaft; Wild Lake south of town; and a plate of žlikrofi.",
    whenAndTips:
      "May–October is the most comfortable. The mine is cool all year, so bring a jacket even in summer and wear suitable shoes. Mine tours run at set times, so check the operator's opening hours. With no railway station in town, check bus times in advance if you are short of time.",
  },
  postojna: {
    // 全七段 sources: 同中文侧（SURS SiStat 05E1022S 2026H1 and 05C5006S, tier 1; gov.si and postojna.si, tier 1; cave operator, tier 1 operator figures; Postojna regional tourist board, tier 1; distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Postojna is a small town in the Inner Carniola karst of south-western Slovenia; on 1 January 2026 the town had about 10,000 people and the municipality about 17,200 (Statistical Office of Slovenia). It is known for Postojna Cave on its edge — according to the operator, the cave system is about 24 km long, and visitors ride a small train into it.",
    howItWorks:
      "Postojna is an ordinary municipality run by a directly elected mayor and a municipal council, with 15 local communities and 40 settlements. To visitors 'Postojna' means a group of sights; to residents it is a municipality of about 270 km². The cave entrance is about 1 km north-west of the town centre, Predjama Castle, set into the mouth of a cave in a cliff face, is about 8 km away in a straight line, and Planina Cave lies north of town — and the villages where the castle and Planina Cave stand belong to the same municipality. The cave is part of the state's natural heritage and guided tours are run by a company under a state concession contract, with combined tickets for the cave and the castle. Locals find their way by the cave, the railway station and the town centre. Daily life stretches along the railway and the motorway, with trains and buses to Ljubljana passing through. Newcomers often assume the castle is right next to the cave, when getting between them needs transport.",
    layout:
      "The town centre sits at the edge of a karst basin, with the railway station on the east side of town and the cave entrance, the olm vivarium and the karst exhibition grouped by the Pivka river to the north-west. Pivka Cave and Black Cave lie north of town, with Planina Cave further north; Predjama Castle stands at the head of a valley to the north-west, built into the mouth of a cave in a cliff.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest is Ljubljana (LJU), about 53 km away in a straight line. Postojna is on the railway from Ljubljana towards the coast, with the station close to the town centre; walking from the station to the cave entrance takes a little over 20 minutes. From 27 June to 30 September 2026 a shuttle bus runs between Postojna Cave and Predjama Castle for visitors holding tickets to both, taking about 20 minutes; at other times you need a car or a hired driver to reach the castle.",
    culture:
      "Slovene is spoken, and English is widely used at the sights. The caves are home to the olm, an eyeless amphibian you can see in the vivarium; Postojna Cave, Planina Cave and the surrounding karst are the landscape locals think of as home. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill.",
    seeAndDo:
      "Ride the train into Postojna Cave; the olm vivarium and the karst exhibition; Predjama Castle, built into a cliff; the underground river in Planina Cave; the Notranjska Museum in town; and further afield, the Škocjan Caves and the intermittent Lake Cerknica.",
    whenAndTips:
      "The cave is open all year and cool inside, so bring a jacket even in summer. July–August and public holidays are busy, so buy tickets in advance and pick an early tour. The shuttle bus season and timetable are announced each year by the regional tourist board, so check before you go.",
  },

  kamnik: {
    // 全七段 sources: 同中文侧（SURS SiStat at 1 January 2026 for the municipality and the settlement, tier 1; kamnik.si on the 22 local communities with SURS-sourced population as of 1 July 2025, tier 1; SURS on area and rankings, tier 1; slovenia.info for voltage and sockets, tier 1; distances computed）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧）。
    identity:
      "Kamnik stands at the mouth of the Kamniška Bistrica valley in central Slovenia, with 29,830 people in the municipality and 13,745 in the town itself at the start of 2026 (Statistical Office). The old town is anchored by the rock of Mali grad, which carries a two-storey Romanesque chapel, and the road north leads up to the high pastures of Velika planina and into the Kamnik-Savinja Alps.",
    howItWorks:
      "Kamnik is an ordinary municipality rather than an urban municipality — only twelve of Slovenia's two-hundred-odd municipalities are the latter — even though the town itself has been a town historically. The municipality covers 266 km² and is divided into twenty-two local and village communities, whose populations the municipality publishes one by one; those figures show where the weight of the place really lies: the largest is Duplica in the south, with over 4,400 people, more than the central community that holds the old town, with about 3,200. Industry and housing are to the south, the old town to the north, and that is the line people use when giving addresses. There is also a second, easily confused structure: the state's administrative unit is also called Kamnik, but it is an arm of the state rather than the elected municipality, and its boundaries need not match. The living radius is set by the valley: the town sits at its mouth, one road leads north into the mountains, and the capital and its airport are twenty kilometres south, so many people live here and work in Ljubljana. Newcomers plan by straight-line distance — the Logar valley looks a dozen kilometres away, but it lies in another municipality with a long road around, and is not part of the same valley system.",
    layout:
      "Glavni trg and Šutna form the north–south axis of the old town, with the rock of Mali grad closing off the old town on its southern side, right beside the street. Zaprice Castle is about 600 m south-west of the old town and Mekinje Monastery about 1 km north. The Volčji Potok arboretum is about 4.2 km south, the herdsmen's settlement on Velika planina about 8 km north-east, and the head of the Kamniška Bistrica valley about 9.7 km north.",
    gettingAround:
      "Ljubljana Airport is about 12 km west in a straight line, though it lies in another municipality; Kamnik has a branch railway towards Ljubljana, and the capital is about twenty kilometres away by road. Reaching the mountains means driving or taking a bus to the valley and changing to the cable car. The climate is temperate, with snow in the mountains in winter.",
    culture:
      "Slovene is spoken. Šutna in the old town is pedestrianised, with markets and events through the summer. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill. The supply is 230 V with two-round-pin continental sockets.",
    seeAndDo:
      "The rock of Mali grad and its two-storey chapel; Šutna and Glavni trg; the museum in Zaprice Castle; Mekinje Monastery; the Volčji Potok arboretum to the south; and the cable car up to the high pastures of Velika planina.",
    whenAndTips:
      "May to September suits the mountains and the arboretum, and winter is the snow season up top. Cable cars and mountain facilities run to season and weather, so check operating notices; do not plan the Logar valley by straight-line distance, as the road goes a long way round.",
  },

  bohinj: {
    // 全七段 sources: 同中文侧（SURS SiStat at 1 January 2026 for the municipality and settlements, tier 1; municipal statute on the four local communities, tier 1; SURS on the administrative unit being at Radovljica, tier 1; bohinj.si for the lake and Savica figures, tier 1; vogel.si on the cable car closure from 21 September 2026, tier 1; the national park's area and founding year deliberately omitted as only tier 2 was available）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧）。
    identity:
      "Bohinj lies in the Julian Alps of north-western Slovenia, with 5,216 people in the municipality at the start of 2026 (Statistical Office). On the map the name covers a municipality of 334 km², sixth largest in the country by area; in visitors' usage it usually means the small settlement at the eastern end of the lake, Ribčev Laz, home to 217 people. Lake Bohinj is about four kilometres long and some 45 m deep, and up the valley beyond its western end the Savica waterfall drops 78 m.",
    howItWorks:
      "Start with what \"Bohinj\" means: it is a municipality of twenty-four settlements scattered around the lake and the valleys, the largest of them, Bohinjska Bistrica, holding barely 1,700 people out of just over five thousand in all, while what visitors call Bohinj is usually Ribčev Laz at the lake's eastern end, with a couple of hundred. So people here do not give Bohinj as an address; they say Ribčev Laz, Stara Fužina, Ukanc or Bohinjska Bistrica. Nor is there only one authority: the municipality is self-governing with four local communities beneath it, while the state's administrative unit for this area sits outside the municipality at Radovljica, and over the same mountains and water lies the authority of Triglav National Park, the country's only one. The administrative centre and the visitor centre are not in the same place either: the municipal offices and the railway station are at Bohinjska Bistrica, while the church, the stone bridge and the tourist office are five kilometres away at the lake. There are only two ways out of the valley: east towards Bled and the capital, or south-west by train through a tunnel of more than six kilometres to the Soča side, which by road is a long detour.",
    layout:
      "Ribčev Laz is at the eastern end of the lake, with the church of St John the Baptist and the stone bridge there. The Savica waterfall is beyond the western end, about 7.3 km from the eastern end in a straight line, and the Vogel cable car base station is at Ukanc on the south-western shore, about 4 km away. The Mostnica gorge is about 2.4 km north and the alpine dairy museum at Stara Fužina about 1.5 km; Bohinjska Bistrica, the municipal seat, and the railway station are about 5 km east.",
    gettingAround:
      "Bohinj has no airport with scheduled flights; the nearest with them is Ljubljana, about 44 km away in a straight line. The railway is the Bohinj line, with the station at Bohinjska Bistrica, and a car-carrying train runs south-west through the tunnel to the Soča side, its times published by Slovenian Railways for each period. Buses and cars serve the valley, and parking by the lake is tight in summer. The climate is alpine, with snowy winters.",
    culture:
      "Slovene is spoken. Hay racks and herdsmen's huts are the vernacular architecture of these valleys, and Stara Fužina has a museum of alpine dairying. Tipping is not obligatory; rounding up or about ten per cent is usual if you are pleased, and whether a service charge is itemised is shown on the bill. The supply is 230 V with two-round-pin continental sockets.",
    seeAndDo:
      "The church of St John the Baptist and the stone bridge at the eastern end of the lake; the walk around the shore; the Savica waterfall beyond the western end; the path into the Mostnica gorge; the alpine dairy museum at Stara Fužina; and the cable car up Vogel for the view over lake and mountains — it is scheduled to close for major maintenance from 21 September to about 30 November 2026 and runs normally the rest of the year, so check operating notices.",
    whenAndTips:
      "June to September suits walking and the lake, and winter is the snow season. Parking by the lake is tight in summer, so buses and walking are easier; mountain weather changes fast, so take wind- and waterproof layers.",
  },
};
