import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "sri-lanka-overview": {
    // 全七段 sources: 同中文侧（Department of Census and Statistics, Census of Population and Housing 2024 final report, tier 1; Statistical Abstract ch. 1 climate, tier 1; Parliament of Sri Lanka news 2022-04-29, tier 1; Sri Jayawardenepura Kotte MC website, tier 1; PUCSL plug standard, tier 1; UK FCDO travel advice 2026-05-26, tier 1; Excise Department dry days via Daily Mirror / The Morning, tier 2; UNESCO open data, tier 1; AASL weekly schedule 2026-09-15, tier 1）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok，全国与分县城镇比例据普查终报表 3.5/3.6 复核）。
    identity:
      "Sri Lanka is an island country in the Indian Ocean, with mountains in the south-central interior, low plains all around them and a ring of beaches and lagoons along the coast. According to the Department of Census and Statistics' 2024 Census of Population and Housing, the resident population is about 21.78 million. Parliament sits in Sri Jayawardenepura Kotte, and Colombo, right next to it, is the commercial centre and international gateway. The country has eight World Heritage sites, including the ancient cities and fortifications of Anuradhapura, Sigiriya, Kandy and Galle, and the Central Highlands.",
    howItWorks:
      "Sri Lanka has two parallel sets of boundaries. The central government's set is 9 provinces, 25 districts and 340 Divisional Secretariat divisions, with more than 14,000 Grama Niladhari divisions at the bottom, whose village officers issue certificates and help carry out government programmes; the census publishes population on this set. The other set is local government: municipal councils, urban councils and Pradeshiya Sabhas, which handle rubbish, roads and building approvals. The two sets of boundaries do not match. Statistically only municipal and urban council areas count as urban, so in the 2024 census the urban sector held only about 17.5% of the population, and large continuous built-up areas around Colombo count as rural because they fall under Pradeshiya Sabhas. The most common misunderstanding is that Colombo is the capital: Parliament moved to neighbouring Sri Jayawardenepura Kotte in 1982, and Kotte was declared the capital from 1985.",
    layout:
      "The west coast holds Colombo, Sri Jayawardenepura Kotte and the Negombo area where the airport is; south along the coast are Galle's old town and beaches; the centre is mountainous, with Kandy on the northern edge of the hills, Nuwara Eliya high among the tea estates and Ella in Uva Province on the eastern slopes; north of the hills is the dry plain of the North Central region, home to the ancient capital Anuradhapura, the Dambulla cave temple and Sigiriya Rock.",
    gettingAround:
      "Bandaranaike International Airport (CMB), just south-east of Negombo, is the main international gateway, and several Chinese cities have scheduled direct flights to Colombo. Travel around the island is mainly by road: long-distance buses, hired cars and tuk-tuks are all common, and with tuk-tuks agree the fare first or choose one with a meter. The railway links Colombo, the coast and the hill country; the cyclone of November 2025 cut several sections, which have been reopening in stages, so check the latest Sri Lanka Railways notices before travelling. There are also seasonal small domestic flights. The currency is the Sri Lankan rupee; main towns have ATMs, but not all accept foreign cards.",
    culture:
      "In temples cover your shoulders and legs, take off shoes and hats, and don't pose for photos with your back to a Buddha statue. The full-moon Poya day each month is a public holiday, and alcohol sales stop nationwide. Nude and topless sunbathing are not allowed. Don't photograph or fly drones near military sites and government buildings. Carry your passport; a copy is usually fine. Restaurant and hotel bills usually already include a service charge, and tipping is voluntary. The standard socket is the British three-square-pin type (Type G), though older buildings may still have round-pin sockets. Don't drink tap water straight; use bottled or boiled water.",
    seeAndDo:
      "The Sacred City of Anuradhapura and Sigiriya Rock; the Dambulla cave temple; the Temple of the Sacred Tooth Relic and Kandy Lake; the ramparts and lighthouse of Galle's old town; the tea estates and Horton Plains around Nuwara Eliya; the Nine Arch Bridge and hill walks at Ella; Galle Face Green and the National Museum in Colombo; the lagoon and beach at Negombo.",
    whenAndTips:
      "Sri Lanka has four rainfall seasons: the south-west monsoon from May to September brings rain mainly to the south-west; October–November is the wettest period for the island as a whole; the north-east monsoon from December to February mainly affects the eastern half; March–April is the second inter-monsoon period. In the rainy season watch for landslides and road closures in the hills, and many beaches have dangerous swells and rip currents at certain times of year. You must apply online for an Electronic Travel Authorisation (ETA) before arrival; follow the latest announcements of Sri Lanka's Department of Immigration and Emigration. The tourism hotline 1912 runs 24 hours.",
  },
  "sri-jayawardenepura-kotte": {
    // 全七段 sources: 同中文侧（DCS 2024 census GN-level xlsx, tier 1 data; Sri Jayawardenepura Kotte MC website, tier 1; Parliament of Sri Lanka news, tier 1; UK FCDO 2026-05-26, tier 1; distances computed from coordinates）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Sri Jayawardenepura Kotte, usually shortened to Kotte, is Sri Lanka's capital and the seat of Parliament, about 7 km south-east of central Colombo in a straight line. The new Parliament building stands on an island in Diyawanna Oya lake; designed under the architect Geoffrey Bawa, it opened in 1982. According to the 2024 Census of Population and Housing, the 20 Grama Niladhari divisions of the city area have about 96,000 people.",
    howItWorks:
      "Kotte is run by the Sri Jayawardenepura Kotte Municipal Council, which was upgraded from an urban council only in 1997, and its land area is about 1,674 hectares. Parliament moved here in 1982 and Kotte was declared the capital from 1985, yet it and Colombo remain two separate municipal councils, and many government bodies and businesses are still in Colombo. The city has about 230 hectares of wetland, mostly along both banks of Diyawanna Oya, and when Parliament was built the land around it was designed as open water. Locally \"Kotte\" often means the old-town area, while the Parliament island and the commercial districts of Nugegoda and Rajagiriya all lie within the same council area, which has a service office in Nugegoda. The most common misunderstanding is to expect a compact government quarter, when Kotte and Colombo form one continuous city, with Parliament, shopping streets and housing spread across it.",
    layout:
      "Diyawanna Oya runs through the city, with Parliament on its island and Diyawanna Oya Park on the shore, and Beddagana Wetland Park on the lakeside near Parliament; remains of the old city wall survive along Rampart Road in the Ethul Kotte old-town area; the commercial district of Nugegoda is in the south-west of the city.",
    gettingAround:
      "Kotte and Colombo form one built-up area, with frequent buses and tuk-tuks between them; central Colombo is about 7 km away in a straight line. International flights use Bandaranaike International Airport to the north, about 31 km from Kotte in a straight line.",
    culture:
      "Parliament is a government building, so don't take photos or fly drones nearby; view it from the lakeside parks. The wetland park has walking trails good for birdwatching. The area with the old city wall remains has been declared an archaeological reserve.",
    seeAndDo:
      "The lakeside paths of Diyawanna Oya Park; Beddagana Wetland Park; the old city wall remains along Rampart Road; the shopping streets of Nugegoda.",
    whenAndTips:
      "The climate is the same as Colombo's: the south-west monsoon runs from May to September and October–November is wettest, when wetlands and low-lying roads flood easily in heavy rain. Visit the wetland park early or late in the day to avoid the midday heat.",
  },
  colombo: {
    // 全七段 sources: 同中文侧（DCS 2024 census GN-level xlsx, tier 1 data; Colombo Municipal Council website, tier 1; AASL / OurAirports coordinates, distances computed; RDA via search summary, tier 2; UK FCDO 2026-05-26, tier 1）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Colombo is Sri Lanka's commercial centre and international gateway, on the south-west coast just south of the mouth of the Kelani River. According to the 2024 Census of Population and Housing, the two Divisional Secretariat divisions covering the city area have about 509,000 people. The name comes from the Sinhala \"Kolamba\", meaning a port or ferry; the city has colonial-era buildings, the busy Pettah market district and the seafront Galle Face Green.",
    howItWorks:
      "Colombo is run by the Colombo Municipal Council, which first met in early 1866; the city covers about 37 km² and is divided for administration into 6 districts and 47 wards. Parliament and the title of capital have moved to neighbouring Sri Jayawardenepura Kotte to the south-east; the two are separate municipal councils, but their built-up areas run together. Locals give addresses by postal zone number, such as \"Colombo 03\", and the number is used more than street names to place a location. The census publishes population by Divisional Secretariat division, and much of Colombo's outer suburbs falls under Pradeshiya Sabhas and counts as rural. The most common misunderstanding is that the international airport is on the edge of Colombo: Bandaranaike International Airport is actually north near Negombo, about 28 km from central Colombo in a straight line.",
    layout:
      "The Fort district is by the sea, with Colombo Fort railway station and the Old Dutch Hospital; the Pettah market district adjoins it to the east; south of Fort along the sea is Galle Face Green, with Beira Lake inland; further south is the Cinnamon Gardens area, home to Viharamahadevi Park and the National Museum; residential and commercial districts continue south along the coast. The Kelani River reaches the sea north of the city.",
    gettingAround:
      "Bandaranaike International Airport (CMB) is north of the city, about 28 km from the centre in a straight line, linked by the Colombo–Katunayake Expressway. Colombo Fort station is the rail hub; lines have been reopening in stages since the November 2025 cyclone, so check Sri Lanka Railways notices before travelling. Getting around the city is by bus, tuk-tuk and ride-hailing; with tuk-tuks agree the fare first or choose one with a meter.",
    culture:
      "When visiting temples and mosques around Pettah, cover shoulders and legs and take off your shoes, and in Buddhist temples don't pose with your back to a Buddha statue. Don't take photos or fly drones near government buildings. Restaurant bills usually include a service charge, and tipping is voluntary. Alcohol sales stop on the monthly full-moon Poya day, when bars and liquor shops close.",
    seeAndDo:
      "The sea at Galle Face Green in the evening; the Colombo National Museum; Viharamahadevi Park; Beira Lake; wandering the Pettah market district; the Old Dutch Hospital, now a dining quarter.",
    whenAndTips:
      "The south-west monsoon from May to September brings rain mainly to the south-west, and October–November is the wettest period island-wide; from December to February the north-east monsoon mainly affects the eastern half, and Colombo is relatively drier. It is hot and humid all year with frequent afternoon showers; stay out of the sea when the surf is high.",
  },
  kandy: {
    // 全七段 sources: 同中文侧（DCS 2024 census GN-level xlsx and final report, tier 1; Kandy Municipal Council website, tier 1; UNESCO 450, tier 1; Sri Dalada Maligawa FAQ, tier 1; Statistical Abstract ch. 1, tier 1; Cinnamon Air, tier 1; Sri Lanka Railways restoration notice 2025-12-29, tier 1; distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条改 1 处：铁路「分段恢复」改为科伦坡—康提截至 2026-09 仍未复运）。
    identity:
      "Kandy sits on the northern edge of Sri Lanka's central hills at about 490 m and is the main city of Central Province. It was the last capital of the Sinhala kings, until 1815, and the Sacred City of Kandy, centred on the Temple of the Sacred Tooth Relic, was inscribed as a World Heritage site in 1988. The city is laid out around an artificial lake, with wooded hills on every side.",
    howItWorks:
      "Kandy is run by the Kandy Municipal Council, set up under an 1865 ordinance and working from 1866, but for a long time supervised by a government agent sent by the central administration; it had its first elected mayor only in 1939, and today it is divided into 22 wards. The census publishes population by Divisional Secretariat division: the division containing Kandy had about 153,000 people in the 2024 census, but it also takes in outlying villages such as Peradeniya, so it is not the city itself. The centre is compact, with the Temple of the Tooth less than 1 km from Kandy Lake in a straight line and the market, bus station and railway station west of the lake. The most common misunderstanding is to picture Kandy District as urbanised, when only about 12% of the district's people live in areas counted as urban, and outside the city it is hill villages and plantations.",
    layout:
      "Kandy Lake is on the east side of the centre, with the Temple of the Tooth on its northern shore; the hillside north of the lake is the Udawatta Kele Sanctuary; west of the lake are the shopping streets, market, bus station and Kandy railway station; south-west of the city, by the Mahaweli River, are the Royal Botanic Gardens at Peradeniya; the Ceylon Tea Museum is on a hillside to the south.",
    gettingAround:
      "Kandy has no airport with regular scheduled flights; international flights use Bandaranaike International Airport, about 84 km away in a straight line, and most people come by bus or hired car. The Colombo–Kandy railway has been out of service since the November 2025 cyclone and, as of September 2026, passenger services had not resumed; check Sri Lanka Railways notices for when they restart. The centre is small enough to walk around the lake and the temple, and buses or tuk-tuks go to the botanic gardens and the tea museum.",
    culture:
      "The Temple of the Tooth is open daily from 5:30 to 20:00, with three offering ceremonies a day. Leave shoes and large bags at the deposit counters, and everyone goes through a security check; pets are not allowed. Visitors in shorts, sleeveless or revealing clothes are not admitted, but suitable clothing is available at the entrance. Foreign visitors' tickets are issued only by the machines inside the temple, and tickets sold by anyone else are invalid. Don't pose with your back to a Buddha statue. Each year the temple holds a grand perahera procession, with dates set by the Buddhist calendar.",
    seeAndDo:
      "The Temple of the Sacred Tooth Relic; a walk around Kandy Lake; the forest trails of Udawatta Kele Sanctuary; the Royal Botanic Gardens at Peradeniya; the Ceylon Tea Museum.",
    whenAndTips:
      "Kandy's average temperature is about 24.5 °C, cooler than the coast. The south-west monsoon (June–August) brings heavy rain to the hills and October–November is the wettest period island-wide, so watch for landslides on mountain roads. The temple is crowded at the early-morning and evening ceremonies; visit between them for a quieter look.",
  },
  galle: {
    // 全七段 sources: 同中文侧（DCS 2024 census GN-level xlsx, tier 1 data; Galle Municipal Council website, tier 1; UNESCO 451, tier 1; Cinnamon Air, tier 1; RDA via search summary, tier 2; Sri Lanka Railways 2025-12-29, tier 1; distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Galle lies on the coast at Sri Lanka's south-western corner and is the main city of Southern Province. The old town on its headland is enclosed by ramparts and bastions, and the Old Town of Galle and its Fortifications became a World Heritage site in 1988: first built by the Portuguese in the 16th century, it reached its height before the British arrived in the 18th century, and its streets and buildings show the interplay of European architecture and South Asian traditions. According to the 2024 Census of Population and Housing, the Galle Four Gravets Divisional Secretariat division has about 108,000 people.",
    howItWorks:
      "Galle is run by the Galle Municipal Council, set up in 1867 with just 5 wards and expanded to 15 by 1944; it has had a mayor-and-council system since 1939. The city's land area is about 16.5 km², bordered by the sea to the south and south-west. The city comes in two parts: the old town on the headland, inside the walls, with lanes, old buildings, museums and small guesthouses; and the modern town outside the walls, where the railway station, bus station, market and cricket ground are. The most common misunderstanding is to think the old town is all of Galle, or that nearby Unawatuna beach is part of it, when the beach is about 4 km south-east of the old town in a straight line and needs a separate ride.",
    layout:
      "Galle's old town sits on the headland with ramparts all around the sea side; at its southern end are Galle Lighthouse and Flag Rock Bastion, and the National Maritime Museum is just inside the walls; north of the gates are Galle International Stadium, the bus station and Galle railway station; the modern town spreads north and east; about 4 km south-east in a straight line is Unawatuna beach.",
    gettingAround:
      "Galle has no airport with regular scheduled flights, and Koggala, about 12 km to the east, has only seasonal small flights in winter; international flights use Bandaranaike International Airport, about 133 km away in a straight line, via the Southern Expressway. The coastal railway links Colombo and Galle and resumed passenger services in December 2025; check Sri Lanka Railways notices for trains. The old town is best on foot, and buses or tuk-tuks go to the beaches.",
    culture:
      "The old town has churches and other religious buildings; dress modestly when entering places of worship, and in Buddhist temples take off your shoes and don't pose with your back to a Buddha statue. Nude and topless sunbathing are not allowed. The ramparts are crowded at sunset, so mind the drops. Restaurant bills usually include a service charge, and tipping is voluntary.",
    seeAndDo:
      "A walk along the old-town ramparts by the sea; Galle Lighthouse and Flag Rock Bastion; the National Maritime Museum; the old buildings in the lanes of the old town; Galle International Stadium; Unawatuna beach.",
    whenAndTips:
      "Galle gets 1,500 to 1,900 mm of rain a year; the south-west monsoon (May–September) brings rain and big seas and October–November is wettest; during the north-east monsoon (December–February) the rain falls mainly on the eastern half and the south-west coast is relatively drier. Many beaches have dangerous rip currents in some months, so check the warnings before swimming.",
  },
  "nuwara-eliya": {
    // 全七段 sources: 同中文侧（Statistical Abstract ch. 1, tier 1; DCS 2024 census GN-level xlsx and final report, tier 1; Sri Lanka Railways seat-reservation station list, tier 1; The Sunday Times 2026-06-21, tier 2; terrain registry horton-plains, tier 1; Cinnamon Air, tier 1; distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条改 1 处：县城镇部门 5% 改为约 5.8%）。
    identity:
      "Nuwara Eliya lies in Sri Lanka's Central Highlands at about 1,900 m, with an average annual temperature of only about 15.8 °C and hillsides covered in tea estates. With a lake and a park at the edge of town, it is the starting point for Horton Plains National Park and the highland tea estates.",
    howItWorks:
      "Nuwara Eliya is run by a municipal council, the only one in its district, while the Divisional Secretariat division the census uses is far larger, stretching from the town out to highland villages such as Nanu Oya, Pattipola and Ambewela, with about 88,000 people in the 2024 census. Life in the district is shaped by tea: in the 2024 census more than half the district's population lived in the estate sector and only about 5.8% in the urban sector, and the town is the market and service centre for the surrounding estates and farms. The most common misunderstanding is that you can take the train straight to Nuwara Eliya: the town itself has no station, and the nearest one is at Nanu Oya, about 3.7 km away in a straight line, from where you still need a ride into town.",
    layout:
      "The town centre is around Victoria Park; Gregory Lake, with a lakeside path, is south-east of the centre; Nanu Oya station lies to the south-west; Pedro Tea Estate is on the hillside to the east; Horton Plains National Park is on the plateau about 21 km south in a straight line.",
    gettingAround:
      "Nuwara Eliya has no airport with regular scheduled flights; international flights use Bandaranaike International Airport, about 100 km away in a straight line, but a long drive on mountain roads. Trains stop at Nanu Oya; passenger services on the Nanu Oya–Badulla section (through Ella) resumed in June 2026, and for the Kandy direction check Sri Lanka Railways notices. Horton Plains is usually reached by hired car or tuk-tuk. Don't lean out of train doors or windows while the train is moving.",
    culture:
      "Visit tea estates through factories open to visitors and their marked routes. Mornings and evenings are cold at this altitude, so bring a jacket. When visiting temples, cover shoulders and legs and take off your shoes.",
    seeAndDo:
      "Victoria Park; a walk around Gregory Lake; a factory visit at Pedro Tea Estate; the hike to the World's End escarpment in Horton Plains National Park.",
    whenAndTips:
      "Parts of the district get more than 5,000 mm of rain a year: the south-west monsoon (June–August) brings heavy rain to the hills and October–November is wettest island-wide, so in the rainy season watch for landslides and road closures. Highland weather changes quickly, so take rain gear and a jacket for Horton Plains.",
  },
  ella: {
    // 全七段 sources: 同中文侧（Ella Pradeshiya Sabha website, tier 1; DCS census definitions and 2024 GN-level xlsx, tier 1; The Sunday Times 2026-06-21, tier 2; UK FCDO 2026-05-26, tier 1; coordinates from Wikidata / OSM, distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Ella is a small town in the hills of Sri Lanka's Uva Province, beside a gap on the eastern slopes of the Central Highlands, surrounded by tea estates, waterfalls and peaks you can hike up. The hill-country railway runs past the town, and nearby Nine Arch Bridge is a stone railway viaduct spanning a valley.",
    howItWorks:
      "Ella is administered by the Ella Pradeshiya Sabha, and in Sri Lankan statistics every Pradeshiya Sabha area counts as rural, so this \"town\" familiar to visitors is statistically rural. In the 2024 census the Ella Divisional Secretariat division had about 49,000 people, but the Grama Niladhari division actually called Ella had only about 1,500, the rest being a string of hill villages around it. The layout is simple: hotels, restaurants and the station sit along one main street, and Nine Arch Bridge, Little Adam's Peak and Ella Rock are all within 3 km in a straight line, reachable on foot. The most common misunderstanding is to picture a busy hill town from the photos, when it is a hill village with very few permanent residents.",
    layout:
      "The main street runs along the road, with Ella railway station near the centre; Nine Arch Bridge is in a valley about 2.5 km east of town; Little Adam's Peak is about 3 km to the south-east; Ella Rock is about 2.7 km to the south; Ravana Falls is about 3.5 km north of town.",
    gettingAround:
      "Ella has no airport with scheduled flights; international flights use Bandaranaike International Airport, about 132 km away in a straight line, over mountain roads. The hill-country railway's Nanu Oya–Badulla section passes through Ella and had resumed passenger services as of September 2026; check Sri Lanka Railways notices for trains. Don't lean out of train doors or windows while the train is moving. The town is walkable, and tuk-tuks go to the sights further out.",
    culture:
      "When walking beside the tracks watch for trains, and don't stop on railway bridges for photos. When visiting hill temples, cover shoulders and legs and take off your shoes. Guesthouse and restaurant bills usually include a service charge, and tipping is voluntary.",
    seeAndDo:
      "Nine Arch Bridge; a sunrise hike up Little Adam's Peak; the climb to Ella Rock; Ravana Falls; the surrounding tea estates.",
    whenAndTips:
      "The south-west monsoon runs from May to September and the north-east monsoon from December to February, and October–November is the wettest period island-wide. After rain, hill paths and trackside trails are slippery, so wear non-slip shoes and watch for landslides in the rainy season.",
  },
  negombo: {
    // 全七段 sources: 同中文侧（DCS 2024 census GN-level xlsx and final report, tier 1; OurAirports / Wikidata coordinates, distances computed; Sri Lanka Railways 2025-12-29, tier 1; terrain registry negombo-lagoon; OSM coordinates）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok；机场方位由「南」改为「东南」（按坐标方位角约 124°））。
    identity:
      "Negombo is on Sri Lanka's west coast, and Bandaranaike International Airport is only about 6 km south-east of town in a straight line, so many travellers spend a night here on arrival or before leaving. South of town is Negombo Lagoon and to the north a long stretch of beach, and fishing boats and the fish market are part of everyday life. According to the 2024 Census of Population and Housing, the Negombo Divisional Secretariat division has about 138,000 people.",
    howItWorks:
      "Negombo is run by the Negombo Municipal Council, one of two municipal councils in Gampaha District. Gampaha is the country's most populous district, yet only about 14% of its people count as urban, because large built-up areas fall under Pradeshiya Sabhas and count as rural; Negombo is one of the few places in the district that counts as urban. The town sits between the sea and the lagoon: the old town and market are near the lagoon mouth, fishing revolves around the lagoon and harbour, and hotels cluster along the coast to the north. The most common misunderstanding is that the airport is in Negombo, when it is at Katunayake to the south-east, outside the Negombo council area, just very close.",
    layout:
      "The old town is near the lagoon mouth, with the ruins of the Dutch fort; the railway station is east of the old town; beaches and the hotel area run north along the coast, with the beach park about 3.5 km north of the centre; Negombo Lagoon lies south of town, and the international airport is about 6 km south-east of the centre in a straight line.",
    gettingAround:
      "Bandaranaike International Airport (CMB) is south-east of town, about 6 km away in a straight line and a quick taxi or tuk-tuk ride. The coastal railway from Colombo passes through Negombo and resumed passenger services in December 2025; check Sri Lanka Railways notices for trains. Colombo can also be reached by expressway. In town, tuk-tuks are the main transport; agree the fare first.",
    culture:
      "The fish market and fishing harbour are workplaces, so ask before taking photos and keep out of the way of people carrying loads. Nude and topless sunbathing are not allowed. Restaurant bills usually include a service charge, and tipping is voluntary.",
    seeAndDo:
      "A boat trip on Negombo Lagoon; a walk along the beach; the Dutch fort ruins in the old town; the early-morning fish market.",
    whenAndTips:
      "The south-west monsoon (May–September) brings rain and big seas, so stay out of the water when swells are dangerous; October–November is wettest island-wide; seas are usually calmer from December to March. For an early flight, staying near the airport is the safer choice.",
  },
  anuradhapura: {
    // 全七段 sources: 同中文侧（UNESCO 200, tier 1; DCS 2024 census GN-level xlsx and final report, tier 1; Cinnamon Air, tier 1; Statistical Abstract ch. 1, tier 1; UK FCDO 2026-05-26, tier 1; coordinates from Wikidata / OSM, distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Anuradhapura lies on the dry plain of Sri Lanka's North Central region, with great ancient reservoirs at the edge of town. The Sacred City of Anuradhapura became a World Heritage site in 1982: the city grew up around a cutting of a Bodhi tree brought in the 3rd century BC, remained a political and religious centre for about 1,300 years, and after the late 10th century was abandoned and long hidden in jungle. Today the site holds huge brick stupas, ancient ponds and monastery ruins.",
    howItWorks:
      "Anuradhapura is run by a municipal council, the only one in its district, but the Divisional Secretariat divisions the census uses do not match it: the city spans two divisions, both of which include large rural areas. The ancient site and the residential town are separate: the Grama Niladhari division containing the sacred city had only about 970 people in the 2024 census, and residents live mainly in the new town to the east, whose divisions are numbered \"Step\". Only about 5.5% of the district's people count as urban, and beyond the city are rice fields and villages irrigated by reservoirs. The most common misunderstanding is to expect the monuments among the streets of the city centre, when the ruins are spread over several square kilometres, with the Kuttam Pokuna twin ponds about 3 km from the Bodhi tree, so you need a bicycle or a ride to go between them.",
    layout:
      "The ancient site is north-west of the city: Jaya Sri Maha Bodhi, Ruwanwelisaya and Thuparamaya run from south to north, Jetavanaramaya is to the east and the Kuttam Pokuna twin ponds further north; Tissa Wewa reservoir is south-west of the site; the residential new town and the railway station are to the east; Mihintale is about 12 km east of the city in a straight line.",
    gettingAround:
      "Anuradhapura's airport has no scheduled flights; international flights use Bandaranaike International Airport, about 141 km away in a straight line, and most people come by bus or hired car. The northern railway line has been reopening in stages since the November 2025 cyclone, so check Sri Lanka Railways notices. The site is large; renting a bicycle or hiring a tuk-tuk for the day is the easiest way round.",
    culture:
      "The stupas and the Bodhi tree are active religious sites: cover shoulders and legs, take off shoes and hats, don't pose with your back to a Buddha statue, and don't climb stupas or ruins. Stone paving gets very hot underfoot, so early morning and late afternoon are more comfortable. Pilgrims crowd the sites on the monthly full-moon Poya day, when alcohol sales also stop.",
    seeAndDo:
      "Jaya Sri Maha Bodhi; Ruwanwelisaya; Thuparamaya; Jetavanaramaya; the Kuttam Pokuna twin ponds; sunset by Tissa Wewa; Mihintale east of the city.",
    whenAndTips:
      "The North Central region is hotter than the south-west coast and the hills, with fierce midday sun, so plan visits for early and late in the day. The north-east monsoon (December–February) mainly brings rain to the eastern half, and October–November is the wettest period island-wide. Bring plenty of water, sun protection and shoes that are easy to slip off.",
  },
  dambulla: {
    // 全七段 sources: 同中文侧（DCS 2024 census GN-level xlsx, tier 1 data; UNESCO 561 / 202, tier 1; Cinnamon Air, tier 1; terrain registry minneriya-tank (Department of Wildlife Conservation), tier 1; UK FCDO 2026-05-26, tier 1; coordinates from Wikidata / OSM, distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok，村官区人口据统计局 xlsx 复核）。
    identity:
      "Dambulla lies on the northern edge of Sri Lanka's Central Province, at the margin of the dry plain, and is the base for two World Heritage sites: the Dambulla cave temple at the edge of town (inscribed in 1991 as the Rangiri Dambulla Cave Temple) has been a place of pilgrimage for 22 centuries, with about 2,100 m² of Buddhist murals and 157 statues in its five cave sanctuaries; about 16.5 km north-east in a straight line, Sigiriya Rock holds the ruins of the capital built by Kassapa I in the 5th century, inscribed in 1982.",
    howItWorks:
      "Dambulla is run by the Dambulla Municipal Council; the Dambulla Divisional Secretariat division that the census uses had about 81,000 people in 2024, but the Grama Niladhari division called Dambulla Town had only about 4,100, the rest being dozens of surrounding villages. Sigiriya, familiar to visitors, is in the same division, as a Grama Niladhari division of only about 720 people. So the two World Heritage sites sit at opposite ends of the same administrative division, about 16.5 km apart in a straight line: Dambulla is a market town where roads meet, and Sigiriya is a village beside the ruins. The most common misunderstanding is to think Sigiriya is a town where you can get everything, when shops, banks and long-distance buses are mostly in Dambulla.",
    layout:
      "Dambulla town spreads out where several roads meet, and the cave temple is on a rock hill on the north-western side of town, less than 1 km from the centre in a straight line; about 16.5 km to the north-east is Sigiriya Rock, with Pidurangala Rock just to its north and the Sigiriya Museum below; further east is Minneriya National Park.",
    gettingAround:
      "Dambulla has no airport with regular scheduled flights, and the airport near Sigiriya has only seasonal small domestic flights; international flights use Bandaranaike International Airport, about 113 km away in a straight line. Travel in the area is by road: long-distance buses meet in Dambulla, and tuk-tuks or hired cars go to Sigiriya and the national park.",
    culture:
      "The cave temple is an active monastery: cover shoulders and legs, take off shoes and hats, and don't pose with your back to a Buddha statue. There is also a temple on Pidurangala Rock, where the same etiquette applies. Climbing Sigiriya Rock involves many steps, so carry enough water.",
    seeAndDo:
      "The Dambulla cave temple; Sigiriya Rock and the ruins on and below it; the Sigiriya Museum; climbing Pidurangala Rock for a view of Sigiriya; watching wild elephants in Minneriya National Park.",
    whenAndTips:
      "It is hotter here than on the coast or in the hills, so start the Sigiriya climb early. The north-east monsoon (December–February) brings rain, and October–November is the wettest period island-wide. Wild elephants occasionally attack people, so in the national park stay with your guide and don't get out of the vehicle.",
  },
  polonnaruwa: {
    // 全七段 sources: 同中文侧（Department of Census and Statistics 2024 census GN-level table and final report, tier 1; Urban Development Authority Polonnaruwa plan 2021–2030, tier 1; UNESCO 201, tier 1; Central Cultural Fund, tier 1; distances computed）。 核实 2026-09-16 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Polonnaruwa is a city in Sri Lanka's North Central Province whose ruins were inscribed on the World Heritage list in 1982 as the Ancient City of Polonnaruwa, the garden city and religious buildings of the 12th-century reign of Parakramabahu I. In the 2024 census the Thamankaduwa Divisional Secretariat in which the city lies had about 92,000 people, about 37,000 of them classed as urban (Department of Census and Statistics).",
    howItWorks:
      "Polonnaruwa has two names for two sets of boundaries: the divisional secretariat used for population statistics is called Thamankaduwa, while the municipal council is called Polonnaruwa — and that council was only split off from the former rural council at the end of 2016, making it the only municipal council in the district. The ancient city is not run by the municipal council; the state's Central Cultural Fund has been responsible for its conservation, management and archaeology since 1980. The city really falls into three parts: the ancient city along the east shore of Parakrama Samudra, with the museum, the royal palace ruins and the Sacred Quadrangle in the south and the rock-cut Buddhas of Gal Vihara a few kilometres north; the New Town, where the municipal council sits, south-east of the reservoir; and Kaduruwela further east, with the railway station and the roadside commercial strip. Only this one municipal area counts as urban in the whole district, and beyond it lie rice fields and villages irrigated by reservoirs. Locals find their way by the ancient city, New Town and Kaduruwela. Newcomers often assume the ancient city is the town centre, when the railway station is in Kaduruwela about 4 km in a straight line from the archaeological museum, and underestimate how far the ruins stretch, several kilometres from south to north.",
    layout:
      "Parakrama Samudra lies to the west, with the ancient city running north–south along its east shore: the archaeological museum and royal palace ruins at the southern end, the Sacred Quadrangle and the Vatadage in the middle, and Rankoth Vehera and then Gal Vihara to the north. New Town is south-east of the reservoir, and Kaduruwela, with the railway station, further east. About 27 km west in a straight line is Sigiriya, and about 39 km is Dambulla.",
    gettingAround:
      "Polonnaruwa has no airport with scheduled flights; international flights use Bandaranaike International Airport, about 149 km away in a straight line, and most visitors come by car or hired driver. Trains run to Colombo; the line was restored in stages after the 2025 cyclone, so follow Sri Lanka Railways' announcements. The ruins are spread out north to south, so hiring a bicycle or a tuk-tuk to go from site to site is easiest.",
    culture:
      "The Buddha images and shrines in the ruins are religious sites: cover shoulders and legs and remove shoes and hats to enter; the Central Cultural Fund forbids photographs taken with your back to a Buddha image and touching religious statues, and plastic bags are not allowed in the site. On each full-moon Poya day many people come to worship and alcohol sales stop.",
    seeAndDo:
      "The archaeological museum; the Sacred Quadrangle and the Vatadage; Rankoth Vehera; the rock-cut Buddhas of Gal Vihara; sunset along the shore of Parakrama Samudra; and further afield, Minneriya National Park, Sigiriya and Dambulla.",
    whenAndTips:
      "The ruins are very exposed in the daytime, so visit early or late and carry plenty of water. Tickets and opening hours are as announced by the Central Cultural Fund; the stone paving gets hot to walk on barefoot, so a pair of socks helps.",
  },

  ratnapura: {
    // 全七段 sources: 同中文侧（DCS Census of Population and Housing 2024 at 19 December 2024, DS-division level, tier 1, digit-checked against Colombo and Kotte in the repo; the municipal council's own history page for the 1877/1922/1940/1967 sequence and the 22.18 km² area, tier 1; NGJA licensing page, tier 1; distances computed from this entry's own coordinates — note the council's own "101 km to Colombo" is by road, about 66 km straight-line）。 核实 2026-09-16 当批。
    identity:
      "Ratnapura lies in the wet-zone hills at the south-western foot of Sri Lanka's central highlands, with 121,166 people in the divisional secretariat at the 2024 census (Department of Census and Statistics) — a wider area than the town itself, only about two fifths of it counted as urban. The name means \"city of gems\": the gravels the Kalu Ganga and its tributaries bring down off the mountains carry them, and the town is built on that valley floor.",
    howItWorks:
      "The industry this town is famous for is the one thing its own government does not control. Where a gem pit may be dug and how deep is written on a mining licence issued by the National Gem and Jewellery Authority, a central body — not the municipal council, and not the province. What the council does run is a different set of things: it began as a local board in 1877, became an urban council in 1922, a municipal body in 1940 and a maha municipal council in 1967, over an area of just over twenty-two square kilometres. And one fact is the other side of the gem trade: by the council's own account about thirteen per cent of that area is liable to flood — the valleys the gems come from and the valleys that flood are the same valleys, and the water level in the wet season decides whether a pit can be worked. The living radius is set by two mountain roads: the Sri Pada trailhead to the north-east and the rainforest entrance to the south, each an hour or two away, with the town as the supply point for both.",
    layout:
      "The clock tower and the public market are in the centre. The national museum is about 0.5 km north-west, the Katugas Ella falls about 0.8 km north-north-west, and the Sabaragamu Maha Saman Devalaya about 2.7 km west-north-west. Bopath Ella is about 14 km north-north-west, the Palabaddala Sri Pada trailhead about 16 km north-north-east, and the Kudawa entrance to the Sinharaja rainforest about 26 km due south.",
    gettingAround:
      "Ratnapura has no airport with scheduled flights; international flights go through Bandaranaike International outside Colombo, about 80 km away in a straight line. There is no railway — only an old rail bridge east of town — so roads carry everything; Colombo is about 101 km by road and about 66 km in a straight line. The climate is tropical and hot all year, with heavy rain in both monsoons, May to September and November to January.",
    culture:
      "Sinhala is spoken, with English in tourist settings. The gem trade is part of daily life here, with dealers and brokers along the streets. Restaurant bills usually include a service charge. Alcohol is not sold on Poya (full-moon) days. Play safe with tap water and drink bottled or boiled water. Sockets are type G, the British three-pin.",
    seeAndDo:
      "The national museum and the market in town; the Maha Saman Devalaya and Katugas Ella to the north-west; Bopath Ella to the north; the Sri Pada climb from the Palabaddala trailhead; and the Kudawa entrance into the Sinharaja rainforest to the south.",
    whenAndTips:
      "December to March is the drier stretch and suits walking and the rainforest; in the monsoons the mountain roads slip and the valleys flood, so check conditions first. The Sri Pada pilgrimage season runs from December to May — outside it the path has neither lights nor stalls; the rainforest needs a guide and a ticket under the reserve's rules.",
  },

  kurunegala: {
    // 全七段 sources: 同中文侧（DCS Census 2024, DS-division level, tier 1, same table and same digit check; the urban-sector share is from the same census; distances computed from this entry's own coordinates. ⚠️ the city's own .mc.gov.lk domain is now occupied by an unrelated third-party site and is never used as a source, so the council's founding year, ward count and area — tier 3 only — are not written at all）。 核实 2026-09-16 当批。
    identity:
      "Kurunegala stands on the plains of north-western Sri Lanka, with 88,999 people in the divisional secretariat at the 2024 census (Department of Census and Statistics). A ring of bare rock hills encloses the town, the largest of them Athugala — locally explained as the \"elephant rock\", gala being Sinhala for rock — and at their foot lies a tank, the town spread over the flat ground between water and stone.",
    howItWorks:
      "This is a good place to see what Sri Lanka's \"urban\" figure actually counts. The 2024 census gives the Kurunegala divisional secretariat 89,000 people, but under the national definition — only municipal and urban council areas count as urban — just 26,000 of them are urban, and the remaining two thirds are statistically rural. In other words, \"how many people live in Kurunegala\" has answers that differ threefold depending on which layer you ask about. That is general in Sri Lanka, where the national urban share is about 17.5 per cent, not because most people live in fields but because much continuous built-up area falls under village councils. The town's shape is set by the rock hills: flat land is limited, so the market, the station and the government offices are packed between the tank and the rock while housing runs outward along a few radial roads — and people give directions by the hills and the water rather than by street names.",
    layout:
      "The clock tower and the central market are in the centre. Rajapihilla Park is about 0.2 km south-south-east, the Athugala Buddha statue about 0.6 km east-south-east, the Ethkanda temple about 0.6 km south-east, Athugala itself about 0.7 km east-north-east and the tank about 0.9 km north-north-west. The railway station is about 1.5 km south-east. The rock fortress of Yapahuwa is about 37 km due north.",
    gettingAround:
      "Kurunegala has no airport with scheduled flights; international flights go through Bandaranaike International, about 63 km away in a straight line. As of September 2026 the northern main line through the town is running again, while the Colombo-Kandy main line has still not reopened, so that journey has to go round. Roads carry the rest, with the town at a junction of several trunk routes. The climate is tropical and hot all year.",
    culture:
      "Sinhala is spoken, with English in tourist settings. Restaurant bills usually include a service charge. Alcohol is not sold on Poya (full-moon) days. Play safe with tap water and drink bottled or boiled water. Sockets are type G, the British three-pin.",
    seeAndDo:
      "The climb up Athugala for the view over town and tank; the Buddha statue on the rock; the walk around the tank; the viewpoint in Rajapihilla Park; the central market and the Ethkanda temple; and, within an hour's drive, the rock fortress of Yapahuwa.",
    whenAndTips:
      "Any time of year works, with rain in both monsoons, May to September and November to January. The rock is slippery after rain and the stone is fierce at midday, so climb early or late; temples mean bare feet and covered knees.",
  },
};
