import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "malta-overview": {
    // 全七段 sources: 同中文侧。Population 588,254 at end-2025（NSO NR 120/2026, tier 1）；68 local councils (54 Malta, 14 Gozo) since 1993, six regional councils since October 2021（EU CoR, OECD SNG-WOFI, tier 2）；regions per vca.gov.mt（tier 1）；free bus travel for residents with a personalised tallinja card since October 2022（infrastructure.gov.mt, tier 1）；Ċirkewwa–Mġarr ferry ~25 min, 24 hours; no scheduled Malta–Gozo flights. 2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "Malta is an island nation in the central Mediterranean, made up of three inhabited islands — Malta, Gozo and Comino — and several uninhabited islets, with a population of about 588,000 at the end of 2025 (National Statistics Office). The country is tiny, yet it packs in thousands of years of history: Neolithic megalithic temples, harbour fortress cities built by the Knights, and the fortifications and language habits left by British rule.",
    howItWorks:
      "Malta has no city tier of government. The country is divided into 68 local council areas — 54 on Malta and 14 on Gozo — each run by an elected local council that handles a limited set of matters such as street cleaning and local road upkeep, while schools, hospitals, police and buses belong to central government. Since 2021 six regional councils have also existed, mainly to coordinate cross-boundary matters such as waste. So the 'towns' that sit shoulder to shoulder on the map are administrative areas, often separated by nothing more than a street. Locals give directions using these area names, and addresses are written as street, locality and postcode. Everyday life is shaped by the harbours: people and towns are concentrated around the two harbours on Malta's east coast, while the south-west and the north are far emptier. Newcomers most often assume that Valletta is the largest city — at the end of 2025 Valletta had only about 5,200 residents, and the most populous council area was St Paul's Bay in the north, with about 43,000.",
    layout:
      "The north-east coast of Malta is the most densely populated part: the Grand Harbour and Marsamxett Harbour flank the Valletta peninsula, the Three Cities including Birgu face it across the Grand Harbour, and Sliema and St Julian's line the north shore of Marsamxett. Towards the centre-west of the island are the old city of Mdina and Rabat; the north, with its ridges and valleys, holds Mellieħa and St Paul's Bay; the south-east coast has the fishing harbour of Marsaxlokk; the south-west coast has the Dingli Cliffs. Across a channel to the north-west lie Comino and Gozo, whose centre is Victoria.",
    gettingAround:
      "Malta International Airport at Luqa is the country's only civil airport, about 8 km by road from Valletta, with the TD4 airport express running direct to Valletta (it replaced the old X4 in April 2025); there are currently no scheduled flights between Malta and Gozo. There is no railway, so public transport means buses, with the island network hubbed on the terminus just outside Valletta's City Gate; residents with a personal card ride free, while visitors buy tickets. For Gozo, take the ferry from Ċirkewwa at Malta's northern tip to Mġarr harbour, about 25 minutes; it runs 24 hours a day all year and carries vehicles, and passenger-only fast ferries also run from Valletta to Mġarr. Traffic drives on the left.",
    culture:
      "The official languages are Maltese and English; road signs, menus and government documents are widely bilingual, and English is enough to get by. Catholic feasts matter in every locality, and in summer each area's patron-saint feast brings processions, bands and fireworks. Food blends Mediterranean and Italian influences, with rabbit, Maltese cheese pastries and many kinds of fish among the common local dishes. Tipping is not compulsory: check whether the bill already lists a service charge — if it does, no tip is needed; if not, 5–10% or rounding up is appreciated for good service. Voltage is 230 V with British-style three-pin plugs.",
    seeAndDo:
      "Historic towns: Valletta and St John's Co-Cathedral, Birgu and the Three Cities, the old city of Mdina and the catacombs of Rabat, the citadel of Victoria on Gozo. Prehistoric sites: the temples of Ħaġar Qim and Mnajdra, and Ġgantija on Gozo. Coast and nature: the Dingli Cliffs, the Blue Grotto, Comino's Blue Lagoon, Dwejra and Ramla Bay on Gozo.",
    whenAndTips:
      "April–June and September–October are mild and the sea is already warm enough to swim; July–August is hot and dry with strong sun, and beaches and ferries are crowded; winter is mild and windy with occasional downpours, a good time for the historic towns. Carry plenty of water and sun protection at open-air sites in summer. Queues for the Gozo ferry are longest at weekends and on public holidays, so travel off-peak where possible.",
  },
  valletta: {
    // 全七段 sources: 同中文侧。Population 5,189 at 31 Dec 2025（NSO, tier 1）；Port Region（vca.gov.mt）；founded after the 1565 siege by the Knights, inscribed 1980, 320 monuments within 55 ha, late-Renaissance grid plan（UNESCO, tier 1）；bus terminus outside City Gate, ferries to Sliema and the Three Cities（publictransport.com.mt, tier 1）; X4 withdrawn 2025-04-20, airport–Valletta now TD4; Saluting Battery fires Monday–Saturday at noon and 4 pm（当批核实改正）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "Valletta is the capital of Malta, with a population of about 5,200 at the end of 2025 (National Statistics Office). It stands on the Sceberras peninsula between the Grand Harbour and Marsamxett Harbour, a new city built by the Knights Hospitaller after the Great Siege of 1565, and was inscribed on the World Heritage List in 1980 — 320 monuments within 55 hectares, its streets laid out in the regular grid of a late-Renaissance ideal city.",
    howItWorks:
      "Valletta is one of Malta's 68 local council areas, with an elected local council for street cleaning and local matters, and it is also the national political centre — the President's office, Parliament and several ministries are inside the walls. Its centre is Republic Street, which runs straight through the peninsula from City Gate; the main streets run parallel or at right angles to it, so if you get lost, returning to this axis puts you right. Locals orient themselves by City Gate, the Upper Barrakka Gardens and Fort St Elmo. Daily life reaches beyond the walls: few people live in Valletta, but far more come each day to work, do business and sightsee, the bus terminus sits just outside City Gate, and ferries leave from below the walls for Sliema and the Three Cities. Newcomers most often assume the capital must be Malta's largest city — Valletta had only about 5,200 residents at the end of 2025; it is an old city of government, churches and museums, not a population centre.",
    layout:
      "The peninsula runs north-east from City Gate out into the sea, with Republic Street as the spine of the city and parallel Merchants Street as the other main street. Near City Gate are the Parliament building and the ruins of the opera house; mid-city are St John's Co-Cathedral and the Grandmaster's Palace; the Upper Barrakka Gardens on the southern bastions look over the Grand Harbour to the Three Cities; Fort St Elmo holds the tip of the peninsula. Outside the walls to the south-west are Floriana and the bus terminus.",
    gettingAround:
      "The airport at Luqa is about 8 km by road, and the TD4 airport express runs direct to Valletta. Inside the city you walk; the streets are steep with many steps, and a lift below the Upper Barrakka Gardens runs down to the waterfront. Ferries go to Sliema and the Three Cities, and most buses to the rest of the island leave from outside City Gate. Vehicle access to the old city is restricted, so driving in is not recommended.",
    culture:
      "Maltese and English are both spoken. Most churches, palaces and museums keep set hours and dress codes, and shoulders and knees should be covered in churches. The Saluting Battery below the Upper Barrakka Gardens fires its guns at noon and 4 pm, Monday to Saturday. Cafés and wine bars cluster in the side streets off Republic Street and Merchants Street. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "St John's Co-Cathedral; the Upper Barrakka Gardens and the Saluting Battery; the Grandmaster's Palace; Fort St Elmo and the National War Museum; Republic Street and Merchants Street; the waterfront promenade below the walls; a ferry ride for views of the Grand Harbour and the Three Cities.",
    whenAndTips:
      "April–June and September–October are the most comfortable; July–August is hot and the streets have little shade, so sightsee in the morning and early evening. The city gets busy on days when cruise ships are in port. There are many slopes and steps, so wear good walking shoes.",
  },
  sliema: {
    // 全七段 sources: 同中文侧。Population 23,570 at 31 Dec 2025; density about 18,186 per km², the highest of any locality（NSO NR 120/2026 tables 11–12, tier 1）；Eastern Region（vca.gov.mt）；Sliema–Valletta ferry（publictransport.com.mt）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "Sliema lies on the north shore of Marsamxett Harbour, facing Valletta across the water, with a population of about 23,600 at the end of 2025 (National Statistics Office); by official figures it is the most densely populated local council area in the country, at about 18,000 people per square kilometre. It is one of Malta's main residential, shopping and hotel districts, with a seafront promenade running for several kilometres along the rocky shore.",
    howItWorks:
      "Sliema is a local council area with an elected local council for streets and local matters, while schools, health care and buses belong to central government. It runs seamlessly into St Julian's to the west and Gżira to the south, the boundaries all but invisible on the street, and locals place themselves by names such as Tigné Point, the Ferries and Tower Road. Its centre is not a square but two waterfronts: on the harbour side facing Valletta are the ferry landing and shopping malls, and on the open-sea side a long promenade and rock-cut bathing areas. Daily life fits in a small radius — shops, restaurants, swimming and the ferry to Valletta are all within walking distance, while parking a car is the hard part. Newcomers most often assume Sliema has sandy beaches — its shore is flat rock shelving, so you swim from the rocks or from purpose-built lidos, and sand means heading north or to Gozo.",
    layout:
      "The council area occupies a small peninsula jutting into the sea: along Marsamxett Harbour on the south-east side are the ferry landing and shopping streets, the tip is the new development and old fort at Tigné Point, the north-east side faces the open sea with Tower Road and the promenade, and the north-west side meets St Julian's.",
    gettingAround:
      "The airport is about 6.5 km in a straight line, with bus connections. The quickest way to Valletta is the ferry across Marsamxett Harbour, just a few minutes; buses also link Sliema with Valletta and the north. Within Sliema you walk, and the promenade continues all the way to St Julian's. Roads are congested at peak hours and parking is difficult.",
    culture:
      "Maltese and English are both spoken, and restaurants, hotels and language schools are concentrated here. The promenade is where residents take their evening walk, and in summer the rock-cut bathing areas along the shelving are busy. Dress modestly in churches. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "The seafront promenade and Tower Road; Tigné Point and its view of Valletta; the ferry to Valletta; swimming from the rock shelving; walking along the coast to Spinola Bay in St Julian's.",
    whenAndTips:
      "May–October is swimming season; the rocks can be slippery and the swell strong where you enter the water. When winter winds are strong, waves wash over the promenade. Staying in Sliema, the ferry to Valletta is more convenient than the bus.",
  },
  "st-julians": {
    // 全七段 sources: 同中文侧。Population 15,594 at 31 Dec 2025（NSO, tier 1）；Eastern Region（vca.gov.mt）；Spinola Bay, Paceville, Balluta Bay, St George's Bay（public sources, tier 3, 当批核实 ok）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "St Julian's is on Malta's north-east coast next to Sliema, with a population of about 15,600 at the end of 2025 (National Statistics Office). The old fishing cove of Spinola Bay still has brightly painted boats moored in it, while Paceville, just north of the bay, is where Malta's bars and nightclubs are most concentrated — the two are only a few streets apart.",
    howItWorks:
      "St Julian's is a local council area with an elected local council for streets, rubbish collection and local matters, while buses, schools and health care belong to central government. It merges with neighbouring areas such as Sliema and Swieqi, the boundaries invisible on the street. The area actually has two quite different centres: to the south, Spinola Bay, an old fishing harbour lined with restaurants; to the north, Paceville, an entertainment district of hotels, a casino and nightclubs, with the small beach of St George's Bay beyond it. When locals say 'St Julian's' they usually mean one specific part. Daily life follows the shoreline, and it is only a twenty- or thirty-minute walk from Sliema. Newcomers most often take the whole area for a nightlife district — Paceville is just a small part of the north, while the bays are quiet streets of homes and restaurants.",
    layout:
      "From south to north the shoreline runs from Balluta Bay to Spinola Bay to St George's Bay. Spinola Bay is the old fishing harbour with restaurants around it; the high ground north of the bay holds Paceville's streets and hotels; St George's Bay is a small sandy beach. Inland the area meets Swieqi and Sliema.",
    gettingAround:
      "The airport is about 6.9 km in a straight line, with bus connections. For Valletta take the bus, or walk to Sliema for the ferry. Within the area you walk; at night Paceville is crowded with people and traffic, so take care.",
    culture:
      "Maltese and English are both spoken. Spinola Bay is for seafood and strolling, while Paceville's bars and clubs stay open late, especially at weekends and in summer. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "The fishing boats and waterfront restaurants of Spinola Bay; the square and church at Balluta Bay; the small beach at St George's Bay; the coastal walk to Sliema; Paceville's nightlife.",
    whenAndTips:
      "May–October is the seaside season; on summer weekend nights Paceville is very crowded and noisy, so for quieter accommodation choose the Spinola Bay or Sliema side.",
  },
  mdina: {
    // 全七段 sources: 同中文侧。Population Mdina 201, Rabat 12,463 at 31 Dec 2025（NSO, tier 1）；both Western Region（vca.gov.mt）；capital until the Knights arrived in 1530, 'Silent City'; Arab-period walls reducing the city, the area outside becoming Rabat ('suburb'); St Paul's Cathedral; St Paul's Catacombs in Rabat（mdinamalta.com, National Geographic, tier 2–3, 当批核实 ok）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "Mdina is a walled old city on high ground in central-western Malta, the island's capital until the Knights Hospitaller arrived in 1530; Rabat, directly outside its walls, was originally its suburb. At the end of 2025 only about 200 people lived inside Mdina, while Rabat had about 12,500 (National Statistics Office).",
    howItWorks:
      "Mdina and Rabat are two separate local council areas, both in the Western Region, each with its own elected local council; buses, schools and health care belong to central government. They were once a single city: under Arab rule the city was reduced in size and walls were built on the high ground, the part inside becoming Mdina and the part outside becoming Rabat — a name meaning 'suburb' in Arabic. The division of roles today is clear: Mdina is an old city of palaces, churches and noble houses with very few residents, while Rabat is an everyday town with a market, schools and housing. Vehicle access inside the walls is restricted; Mdina's centre is the cathedral square, and Rabat's is its parish church and the streets around it. Newcomers most often go through Mdina's gate and never reach Rabat — yet the catacombs and the Roman town house remains lie outside the walls.",
    layout:
      "Mdina sits on the edge of the high ground, its northern walls looking out over the north of the island towards the harbours of the north-east coast; the main gate is on the south-west side, and inside are winding narrow lanes and St Paul's Cathedral. South of the gate lie the streets of Rabat, with St Paul's Catacombs and the Roman town house remains near the boundary between the two.",
    gettingAround:
      "The airport is about 7.4 km in a straight line, with bus connections; from Valletta the bus takes about half an hour to the gate. Mdina can only be explored on foot, and Rabat's main sights are also within walking distance. For the Dingli Cliffs, continue from Rabat by bus or taxi.",
    culture:
      "Mdina is known for its quiet, and residents ask visitors to keep their voices down and not disturb homes. Churches and museums expect modest dress covering shoulders and knees. Rabat's bakeries and snack shops are the place to try everyday Maltese food. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "Mdina's main gate and walls; St Paul's Cathedral and the Cathedral Museum; the viewpoints on the bastions; St Paul's Catacombs in Rabat; the Roman town house remains; Rabat's parish church and old streets.",
    whenAndTips:
      "Early morning and early evening are quieter with better light; tour groups peak around midday. At summer noon the stone walls reflect a lot of heat, so carry water and sun protection. Mdina at night is especially quiet and good for a stroll.",
  },
  birgu: {
    // 全七段 sources: 同中文侧。Population Birgu 2,262, Senglea 2,407, Cospicua 4,785 at 31 Dec 2025（NSO, tier 1）；all Port Region（vca.gov.mt）；Knights' first base 1530; renamed Vittoriosa after the 1565 siege; Fort St Angelo; Inquisitor's Palace seat of the Inquisition 1574–1798; the Three Cities enclosed by about 5 km of late-17th-century Cottonera walls（birgulc.gov.mt, Heritage Malta and others, tier 1–3, 当批核实 ok）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "Birgu stands on a headland on the south side of the Grand Harbour and, with Senglea and Cospicua, forms the Three Cities. When the Knights Hospitaller came to Malta in 1530 they first made Birgu their base; after the Great Siege of 1565 it was renamed the 'Victorious City'. At the end of 2025 Birgu had about 2,300 residents and the Three Cities together about 9,500 (National Statistics Office).",
    howItWorks:
      "The 'Three Cities' are not an administrative unit: Birgu, Senglea and Cospicua are three separate local council areas, each with its own elected local council, all in the Port Region; buses, schools and health care belong to central government. Each town holds a headland or creek head: Birgu and Senglea face each other across a dockyard creek, and Cospicua, at the head of the creek behind them, joins them together. Walls enclose all three, and locals orient themselves by Fort St Angelo, the dockyard creek and each town's parish church. Life runs along the water: from Birgu's waterfront a ferry crosses straight to Valletta, much faster than going round by road. Newcomers most often assume the history of the Grand Harbour is all in Valletta — yet the Knights' first headquarters and the fiercest defence of the Great Siege were across the water in Birgu.",
    layout:
      "Birgu occupies a narrow headland with Fort St Angelo at its tip; the waterfront on the west side of the headland has the marina and the Maritime Museum, and inside are narrow lanes, the Inquisitor's Palace and the parish church. Across the dockyard creek to the west is Senglea, whose watchtower garden at the tip looks straight at Valletta; at the head of the creek to the south is Cospicua.",
    gettingAround:
      "The airport is about 5.3 km in a straight line, with bus connections. For Valletta, take the ferry across the Grand Harbour from the waterfront, or the bus. The Three Cities are walkable from one to another, and Birgu's streets are narrow but not steep.",
    culture:
      "Maltese and English are both spoken. The Three Cities keep a strong community life, with processions and fireworks for summer patron-saint feasts and solemn religious rites around Easter. Churches expect modest dress. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "Fort St Angelo; the Inquisitor's Palace; the Malta Maritime Museum; Birgu's old streets and squares; the watchtower garden at Senglea's tip; a walk along the waterfront and a ferry ride for a sea-level view of Valletta's walls.",
    whenAndTips:
      "April–June and September–October are the most comfortable; much quieter than busy Valletta, it suits a slow half-day. The waterfront is fully exposed to the sun at summer noon, and early evening is the best time to watch Valletta's lights across the water.",
  },
  "victoria-gozo": {
    // 全七段 sources: 同中文侧。Population Victoria (Ir-Rabat, Għawdex) 7,671; Gozo and Comino district 41,793 at 31 Dec 2025（NSO, tier 1）；Gozo Region（vca.gov.mt）；Cittadella restoration and visitor centre co-funded by the ERDF（European Commission Inforegio, tier 1）；Ċirkewwa–Mġarr ferry ~25 min; Valletta–Mġarr fast ferry; Ġgantija part of the Megalithic Temples WHS（UNESCO）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "Victoria is Gozo's central town, called Rabat in Maltese, built at the foot of a hill in the middle of the island with the citadel on top. At the end of 2025 Victoria had about 7,700 residents, and Gozo and Comino together about 41,800 (National Statistics Office). The island's bus routes, market and government offices all centre on it.",
    howItWorks:
      "Victoria is one of the 14 local council areas of the Gozo Region, with an elected local council for streets and local matters; buses, schools and health care belong to central government. There is no local government for Gozo as a whole — the 14 council areas are each independent, and Victoria is simply the most populous and the one with the most institutions. Directions on the island radiate from Victoria: buses fan out from its terminus to the villages, and getting between villages often means returning to Victoria to change. Life is framed by the ferry — there is no bridge and no scheduled flight between Gozo and Malta, so working, seeing a specialist or catching a plane on Malta all begin with the boat from Mġarr harbour. Newcomers most often treat Gozo as a suburb of Malta that can be seen on a day trip — its villages, coast and sites are scattered, and with ferry queues a single day is usually a rush.",
    layout:
      "The citadel crowns the hilltop, its walls looking out over the whole island; below it is Victoria's old town, with the market and cafés around Independence Square and Republic Street as the main shopping street. Mġarr harbour is on the island's south-east coast, Dwejra at its western end, Marsalforn on the north coast and Xlendi on the south-west coast.",
    gettingAround:
      "Gozo has no airport with scheduled flights; the nearest is Malta International Airport. The ferry from Ċirkewwa at Malta's northern tip to Mġarr harbour takes about 25 minutes, runs 24 hours a day all year and carries vehicles; passenger-only fast ferries also run from Valletta to Mġarr. Buses link Mġarr with Victoria, and the island network is hubbed on Victoria with fewer services than on Malta; a hire car or driver gives more flexibility. Traffic drives on the left.",
    culture:
      "Maltese and English are both spoken, and the pace is slower than on Malta. Each village's patron-saint feast is the big event of summer, and Victoria's opera houses and band traditions are well known in Malta. Gozitan cheese and honey are common local products. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "The citadel and its visitor centre; the morning market in Independence Square; the Ġgantija temples; the Inland Sea and Fungus Rock at Dwejra; the red sand of Ramla Bay; Xlendi Bay; the Ta' Pinu basilica; the salt pans and wave-cut rocks along the north coast.",
    whenAndTips:
      "April–June and September–October are best for walking and swimming; in July–August ferry queues are long, so avoid setting off at weekends and on public holidays. Plan at least one night on Gozo — it is far more relaxed than a same-day return.",
  },
  marsaxlokk: {
    // 全七段 sources: 同中文侧。Population 4,327 at 31 Dec 2025（NSO, tier 1）；Southern Region（vca.gov.mt）；painted luzzu boats with an eye on the bow, Sunday fish market, St Peter's Pool（several tier-3 sources, 当批核实; "dates back to the Phoenicians" is tier-3 only and not used）；Marsaxlokk Bay a ria（Gauci 2025, tier 2）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "Marsaxlokk is a fishing village on Malta's south-east coast, with a population of about 4,300 at the end of 2025 (National Statistics Office). Its harbour is full of traditional luzzu fishing boats painted red, yellow, blue and green, each with an eye painted on the bow, and on Sundays a fish market and general market spread along the waterfront.",
    howItWorks:
      "Marsaxlokk is a local council area in the Southern Region, with an elected local council for streets, the waterfront and local matters; port management, buses, schools and health care belong to central government. The village stretches along the head of Marsaxlokk Bay, and its centre is the waterfront and the square in front of the parish church, with restaurants, the market and the boats all on that one shoreline. Locals give directions by the waterfront, the church and the headlands on either side of the bay mouth. The bay sets the limits of daily life: the village's routine revolves around fishing and waterfront dining, while across the bay and around its mouth are harbour and industrial facilities of a quite different kind. Newcomers most often assume the Sunday market is all locally caught fish and runs all day — there are many stalls of household goods and souvenirs too, and the fish stalls are busiest in the morning and start packing up after midday.",
    layout:
      "The village follows the curving shore at the head of the bay, with restaurants and the Sunday market along the waterfront promenade and fishing boats moored in the bay. East of the bay the Delimara peninsula runs south, and on its east coast is the rock pool of St Peter's Pool.",
    gettingAround:
      "The airport is about 6.3 km in a straight line, with bus connections, and buses run from Valletta. The village is walkable. There is no direct bus to St Peter's Pool; people usually walk, take a taxi or drive, and parking is hard on summer weekends.",
    culture:
      "Maltese and English are both spoken. Waterfront restaurants focus on fish and seafood, and Sunday lunch is family time for locals, so restaurants are often full. The eye painted on the bow is a traditional decoration of Maltese fishing boats. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "The painted fishing boats in the harbour; the Sunday fish market and general market; a fish lunch at a waterfront restaurant; the rock pool of St Peter's Pool on the Delimara peninsula; a walk around the bay.",
    whenAndTips:
      "Sunday morning is the liveliest, so go early for the fish market; on weekdays the village is quiet and better for photographing the boats. At St Peter's Pool the rocks are slippery, and in rough seas it is not safe to swim.",
  },
  mellieha: {
    // 全七段 sources: 同中文侧。Population 14,541 at 31 Dec 2025（NSO, tier 1）；Northern Region（vca.gov.mt）；Mellieħa (Għadira) Bay beach and Għadira Nature Reserve; Sanctuary of Our Lady of Mellieħa; Popeye Village built as the set for the 1980 film Popeye at Anchor Bay（Popeye Village official site, Wikipedia, tier 3）；Red Tower on Marfa Ridge; Ċirkewwa ferry terminal（public sources, 当批核实 ok）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "Mellieħa is in the north of Malta, built along a ridge above Mellieħa Bay, with a population of about 14,500 at the end of 2025 (National Statistics Office). The bay below has one of the larger sandy beaches on the island of Malta, with the Għadira wetland reserve behind it, and to the west, at Anchor Bay, stands the village built as the set for the 1980 film Popeye and kept ever since.",
    howItWorks:
      "Mellieħa is a local council area in the Northern Region, with an elected local council for streets and local matters, while buses, schools and health care belong to central government. The council area is large: besides the main town on the ridge it takes in Mellieħa Bay below, Anchor Bay to the west, and Marfa Ridge in the far north with the Ċirkewwa ferry terminal for Gozo. So when locals say 'Mellieħa' they may mean the town centre or the whole northern coast. The town's centre is the parish church and main street on the ridge, while the beaches and the ferry terminal are down below, reached by steep roads or by bus. The ridges and valleys shape daily life: northern Malta alternates ridge and valley, with towns on the ridges and beaches at the valley mouths. Newcomers most often assume that staying in Mellieħa town means staying by the sea — the town centre is well above Mellieħa Bay and some distance from it, a hard climb on foot.",
    layout:
      "The main town runs along the crest of Mellieħa Ridge, with the parish church and the Sanctuary of Our Lady of Mellieħa at its south-eastern end; below to the north are the beach of Mellieħa Bay and the Għadira wetland; further north is Marfa Ridge with the Red Tower, and at its western end the Ċirkewwa ferry terminal; on the west coast are Anchor Bay and Popeye Village.",
    gettingAround:
      "The airport is about 15 km in a straight line, with bus connections. The Ċirkewwa ferry terminal and Gozo are close; Valletta is about an hour by bus depending on traffic. The slope between the town centre and the beach is steep, so the bus is the easier option.",
    culture:
      "Maltese and English are both spoken. In summer Mellieħa Bay is a busy beach for local families and visitors, with full facilities. The Sanctuary of Our Lady of Mellieħa is an important Marian pilgrimage site in Malta. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "The beach at Mellieħa Bay; the Għadira Nature Reserve; the Sanctuary of Our Lady of Mellieħa; Anchor Bay and Popeye Village; the Red Tower on Marfa Ridge; the ferry from Ċirkewwa to Gozo and Comino.",
    whenAndTips:
      "May–October is beach season, and the shallow water of Mellieħa Bay suits families; summer weekends in July–August are crowded. The Għadira reserve opens seasonally, so check its opening times before going.",
  },
  "st-pauls-bay": {
    // 全七段 sources: 同中文侧。Population 43,095 at 31 Dec 2025, the largest local council area in the table（NSO NR 120/2026 table 11, tier 1）；Northern Region（vca.gov.mt）；council area includes Buġibba, Qawra, Xemxija, Burmarrad and others（sanpawlilbaharlc.gov.mt, tier 1）；St Paul's shipwreck tradition from the Acts of the Apostles, traditionally placed at St Paul's Islands（written as tradition）；statue on St Paul's Islands inaugurated 1845（Wikipedia, tier 3, 当批核实 ok）。2026-09-13 首写；核实 2026-09-13 当批（content-verifier 独立检索 17 组：15 ok / 2 wrong 已改；分地方人口它取不到 NSO 表，由写入者在浏览器里直接解析 NR 120/2026 官方 xlsx 表 11 取得，1 级）。
    identity:
      "St Paul's Bay is in the north of Malta and, with a population of about 43,100 at the end of 2025, is the most populous local council area in Malta (National Statistics Office). Its name comes from the shipwreck of St Paul recorded in the Acts of the Apostles — by tradition, the wreck happened around St Paul's Islands off the mouth of the bay. Today Buġibba and Qawra, on the bay, are among Malta's main seaside resort areas.",
    howItWorks:
      "St Paul's Bay is a local council area in the Northern Region, with an elected local council for streets and local matters, while buses, schools and health care belong to central government. The council area takes in several settlements — Buġibba, Qawra, Xemxija, Burmarrad and others — and locals usually give the settlement name in addresses rather than 'St Paul's Bay'. There is no single centre: Buġibba's square and seafront are the heart of the resort, the old St Paul's Bay area has the fishing harbour and church, and Burmarrad in the valley still keeps its farmland. Daily life follows the bay, with the resort's hotels, restaurants and promenade all within walking distance. Newcomers most often assume the most populous place must be near the capital — Malta's most populous council area is on this northern bay, not among the harbour towns around Valletta.",
    layout:
      "The bay runs south-west from its mouth; on its east side is the peninsula of Buġibba and Qawra, ending at Qawra Point; at the head of the bay are old St Paul's Bay and Xemxija; St Paul's Islands lie off the bay mouth. Inland are the Pwales valley and the Is-Simar wetland reserve.",
    gettingAround:
      "The airport is about 12 km in a straight line, with bus connections. Buġibba is a major bus stop for the north, with easy connections to Valletta, Mellieħa and the Ċirkewwa ferry terminal. The resort is walkable. St Paul's Islands can be seen from the sea on a boat trip.",
    culture:
      "Maltese and English are both spoken, and restaurants, bars and hotels are concentrated in the resort. The annual feast of St Paul's Shipwreck is a public holiday in Malta, with religious celebrations across the islands. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "The promenades of Buġibba and Qawra; Qawra Point; a boat trip to see St Paul's Islands and the statue of St Paul on them; the Is-Simar wetland reserve; the bay and footpaths at Xemxija.",
    whenAndTips:
      "May–October is the holiday season, busy and lively at night in summer; in winter many resort facilities cut back their hours. Swimming is mostly from rock shelving, so watch for slippery rocks and swell.",
  },
  qrendi: {
    // 全七段 sources: 同中文侧（NSO NR 120/2026 table 11, tier 1; Western Regional Council website, tier 1; Qrendi Local Council, tier 1; Heritage Malta, tier 1; Malta Public Transport route 74, tier 1; distances computed）。 核实 2026-09-16 当批（content-verifier 独立检索，本条 ok；2025 年末人口 NSO 官网对脚本 403，研究阶段在浏览器取表、与既有条目同表自检一致）。
    identity:
      "Qrendi is a village in the south-west of the island of Malta, with about 3,400 people at the end of 2025 (National Statistics Office). The village sits on inland high ground, but its territory runs down to the sea: the Ħaġar Qim and Mnajdra temples, more than five thousand years old, stand on the clifftop outside the village and were inscribed on the World Heritage list in 1992 as part of the Megalithic Temples of Malta, and the fishing inlet of Wied iż-Żurrieq and the Blue Grotto on the coast also come under Qrendi.",
    howItWorks:
      "Qrendi is a local council locality, with an elected local council looking after streets and local matters, and belongs to the Western Region, whose regional council is made up of the mayors of its local councils. The two temples themselves are managed by the national heritage agency Heritage Malta, not the local council. There is a mismatch in names here: the fishing inlet of Wied iż-Żurrieq and the Blue Grotto sound as if they belong to the neighbouring town of Żurrieq, and the bus stops carry Żurrieq's name, but the 1993 Local Councils Act placed them within Qrendi's locality. More confusingly, the National Statistics Office counts Qrendi in the 'South Eastern' statistical district while its regional council is the Western Region — statistical and administrative groupings are two different systems. The centre of the village is around the parish church, and the sights are on the clifftops and shore a kilometre or two away. Locals find their way by the village centre, the temples and Wied iż-Żurrieq. Daily life happens within a small radius: the airport is about 3 km away in a straight line, and route 74 buses link the village, the temples and the Blue Grotto. The commonest mistake newcomers make is assuming the Blue Grotto belongs to Żurrieq.",
    layout:
      "The village is on high ground in the south-west of Malta, with the parish church at its centre and a large collapse sinkhole, il-Maqluba, just outside. About 2 km south-west on the clifftop by the sea is Ħaġar Qim, with Mnajdra about 500 m downhill; south towards the sea is the fishing inlet of Wied iż-Żurrieq, with the Blue Grotto's sea arch on the nearby cliffs.",
    gettingAround:
      "Malta International Airport (MLA) is about 3 km away in a straight line. Route 74 buses from Valletta serve Qrendi village, the temples and the Blue Grotto area, and the temples are a few minutes' walk from the nearest stop. To see the Blue Grotto's sea arch, take a small boat from Wied iż-Żurrieq; whether boats run depends on the sea.",
    culture:
      "Maltese and English are spoken. The doorway of Mnajdra's South Temple aligns with sunrise at the spring and autumn equinoxes. The temple sites are covered by protective shelters; do not climb on the stones. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "Ħaġar Qim temple and visitor centre; Mnajdra temple downhill; a boat trip from Wied iż-Żurrieq to the Blue Grotto; clifftop walks above the sea; and the il-Maqluba sinkhole at the edge of the village.",
    whenAndTips:
      "Spring and autumn are the most comfortable; in summer the clifftops have no shade and the midday sun is fierce, so go early or late in the day. Blue Grotto boats depend on the wind and waves and stop when it is rough. Temple opening hours and tickets are as announced by Heritage Malta.",
  },

  xaghra: {
    // 全七段 sources: 同中文侧（NSO NR 120/2026 table 11 at 31 December 2025, tier 1; Heritage Malta on Ġgantija and the Ta' Kola windmill, tier 1; Gozo Channel on the ferry, tier 1; MTA on tipping and drinking water, tier 1; distances computed）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧）。
    identity:
      "Xagħra stands on a plateau in the middle of Gozo, with 5,386 residents at the end of 2025 (National Statistics Office) — on that same release the second most populous of the fourteen local council areas of Gozo and Comino. Within its boundaries are the Ġgantija temples, the Gozo component of the Megalithic Temples of Malta World Heritage site, and below the plateau to the north lies the red sand of Ramla Bay.",
    howItWorks:
      "Malta has no tier of city government: there are 68 local councils, 54 on Malta and 14 on Gozo, and Xagħra is one of them, with council size set by population; since 2021 a layer of six regional councils sits above them, and Xagħra belongs to the Gozo region. Gozo also has a layer Malta lacks — a ministry for Gozo, set up in 1987, which handles most Gozitan business. So counting who runs Xagħra takes three layers: the local council, the regional council and that ministry. The locality itself is a raised plateau: the village sits on top, Ġgantija stands at its edge, and the plateau drops away northwards to Ramla Bay. There is also something rarely found elsewhere: two caves beneath private houses in the village, opened to visitors by the householders themselves, so whether they are open depends on the day. Newcomers often assume everything on Gozo is in Victoria, when this World Heritage component is here; many also take the neighbouring village of Marsalforn for part of Xagħra, when it belongs to another locality.",
    layout:
      "The square with the basilica is the centre of the village, the Ta' Kola windmill about 200 m to its east, and the Ġgantija temples about 400 m to its south-east. Ninu Cave is under a house just north of the square. Ramla Bay lies about 1.6 km north-east in a straight line, down off the edge of the plateau.",
    gettingAround:
      "Gozo has no scheduled flights; the nearest airport with them is Malta International, about 29 km away in a straight line. Reaching the island means the ferry: the state-owned operator runs across to Malta all year, with sailings adjusted by season, so check the notices before travelling. Buses run from Victoria to Xagħra and to Ramla Bay. The village is walkable, and the beach is downhill going and uphill coming back. The climate is Mediterranean, hot and dry in summer, mild and wet in winter.",
    culture:
      "Maltese is spoken and English is also official. The basilica and the parish feast are part of local life, so dress modestly when visiting churches. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "The Ġgantija temples and their interpretation centre; the Ta' Kola windmill; the basilica on the village square; the caves beneath village houses, opened by their owners at irregular hours; and the walk down off the plateau to the red sand of Ramla Bay.",
    whenAndTips:
      "April–June and September–October are the most comfortable; high summer is fierce. There is a real height difference between the village and the beach, so the return is a climb, and ferry sailings change with the season, so leave time for the trip back.",
  },

  mosta: {
    // 全七段 sources: 同中文侧（NSO NR 120/2026 table 11, tier 1; Northern Region council self-description, tier 1; Heritage Malta on the Ta' Bistra catacombs, tier 1; the Rotunda's dome diameter and basilica date deliberately omitted because sources disagree; distances computed）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧）。
    identity:
      "Mosta lies in the middle of Malta, with 25,845 residents at the end of 2025 (National Statistics Office) — on that release the third most populous of the country's 68 local council areas, while the capital, Valletta, had just 5,189. Its centre is the 19th-century domed church, and the locality reaches north to the top of the fault escarpment that runs across the island.",
    howItWorks:
      "Malta has no tier of city government: Mosta is one of the 68 local council areas, with a regional council layer added in 2021, and it belongs to the Northern Region. The distribution of people is the key to this country: the capital has barely five thousand residents while Mosta has over twenty-five thousand — the political centre and the population centre parted company long ago. The shape of the locality is worth noticing too: dense town at the southern end, rising ground northwards to the top of the fault escarpment, where the forts and the continuous infantry wall built by the British in the 19th century run along the crest; Fort Mosta's address falls within this locality, though it is not open to visitors. The domed church in the centre was begun in 1833 and finished in 1860 on the site of a church of about 1614, built largely by volunteer labour from the parish; on 9 April 1942 a bomb pierced the dome without exploding. West of the town lies a group of ancient catacombs which, according to the heritage agency, is as far as is known the largest set of tombs and catacombs beyond the confines of the ancient city. Newcomers take Mosta for a place with one church, when it is among the most populous localities in the country.",
    layout:
      "The square in front of the domed church is the centre, with the Ta' Bistra catacombs about 1 km north-west. Wied il-Għasel cuts into the escarpment north of town, its mouth a few hundred metres from the square, and Speranza Valley lies about 1.5 km to the south-west. Fort Mosta is about 1.4 km due north on the crest, and is not open to visitors.",
    gettingAround:
      "Malta International Airport is about 7.5 km south-east in a straight line and Valletta about 8 km south-east. Buses and cars do the work on the island, Mosta sits where several main routes meet, and the town itself is walkable. The climate is Mediterranean, hot and dry in summer, mild and wet in winter.",
    culture:
      "Maltese is spoken and English is also official. The domed church is a working parish church, so dress modestly and avoid visiting during Mass. Tipping is common here, unless a service charge is already on the bill. For drinking water, bottled or filtered water is advised.",
    seeAndDo:
      "The domed church and its displays; the Ta' Bistra catacombs; a walk into Wied il-Għasel where it cuts the escarpment; the paths in Speranza Valley; and the line of the Victoria Lines along the crest.",
    whenAndTips:
      "April–June and September–October are the most comfortable. The church is in daily parish use and closed to visitors during Mass; the valley paths have no shade in summer, so take water and a hat.",
  },
};
