import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "new-zealand-overview": {
    // identity sources: Stats NZ《National population estimates: At 31 December 2025》：估计常住人口 5,342,000 人（临时值）。https://www.stats.govt.nz/information-releases/national-population-estimates-at-31-december-2025/
    //   核实日 2026-09-07，来源级别 1
    identity:
      "New Zealand lies in the south-west Pacific, made up of the North Island, the South Island and some smaller islands, with an estimated resident population of about 5.34 million at the end of 2025, provisional (Stats NZ), most of it on the North Island. In Māori the country is called Aotearoa (\"land of the long white cloud\"). The official languages are English, Māori and New Zealand Sign Language. It sits on a plate boundary — mountainous, with volcanoes, geothermal areas and earthquakes — and faces Australia across the Tasman Sea.",
    layout:
      "The North Island is comparatively gentle, with large areas of pasture, the central volcanic plateau (Ruapehu, Lake Taupō) and the geothermal country around Rotorua; the largest city, Auckland, and the capital, Wellington, are both here. The South Island is split lengthwise by the Southern Alps, with fiords and glaciers on the west, the Canterbury Plains on the east, the largest city being Christchurch, and Queenstown as the tourism centre of the south. Cook Strait separates the islands, with a car ferry across it.",
    gettingAround:
      "Distances between towns are not huge but the roads are winding; travel is mainly by air (Air New Zealand, Jetstar and others) and by car. Self-drive is common — drive on the left, expect winding roads and many one-lane bridges, and in winter parts of the South Island need care for ice and snow. Intercity coaches and scenic trains are limited. The climate is temperate maritime; in the southern hemisphere the seasons are reversed (December–February is summer); the weather changes fast, you can get \"four seasons in one day\", and windproof, waterproof clothing is worth carrying year-round. UV is strong — sun protection is basic sense.",
    culture:
      "English is universal; Māori language and culture (the marae meeting house, the haka, the hāngī earth-oven meal) are part of the national identity, and many place names are Māori or dual English–Māori (per the New Zealand Geographic Board, NZGB). The pace is relaxed, with a strong value on the outdoors and on conservation. Border checks on food, soil, and camping and hiking gear are very strict (to keep out biosecurity threats), so declare honestly and clean your boot soles. Tipping is not customary.",
    seeAndDo:
      "On the South Island, the Southern Alps, the fiords, the glaciers and the night sky (the Tekapo area is a dark-sky reserve); adventure sports at Queenstown; on the North Island, the volcanoes and geothermal areas, the Waitomo glow-worm caves and the Bay of Islands. Hiking (the \"Great Walks\"), whale watching, penguins and albatross, and Lord of the Rings locations are common themes. The seasons are distinct, and skiing is July–September.",
    whenAndTips:
      "December–March is the summer high season with the best weather and long daylight; June–August is winter, with skiing on the South Island and a milder North Island. Citizens of most countries need to apply online for an NZeTA and pay a visitor levy before arrival, which cannot be arranged on arrival. Popular tracks (such as the Milford Track) need booking far ahead in peak season. The weather is changeable — check forecasts for mountain hikes and leave your plans with the authorities.",
  },

  auckland: {
    // identity sources: 新西兰统计局（Stats NZ）《Subnational population estimates》**年度**发布，覆盖截至当年 6 月 30 日的估计，
    //   最近一期 2025-10-29 发布（基准 2025-06-30），下一期预计 2026-10。region / territorial authority / urban area
    //   三档口径都在同一份里。2026-09-08 核。
    //   **新西兰官方没有与美国 MSA 对等的「都会区」口径** —— 本项目今后统一用「城区人口（Stats NZ urban area）」、
    //   「XX 市议会辖区人口（territorial authority）」、「XX 大区人口（region）」三种可追溯到官方分类的说法。
    //   奥克兰大区（Auckland Council 统一辖区，2010 年合并）2025-06-30 ERP **1,816,000**；
    //   同期全国 5,324,700 —— 182/532 ≈ **34.1%**，「约三分之一」成立（1 级，2026-09-08 核）。
    identity:
      "Auckland is the largest city in New Zealand, where the Auckland region — coterminous with Auckland Council — had an estimated resident population of about 1.82 million in June 2025 (Stats NZ), about a third of the country. It is built on a narrow isthmus with a harbour on each side and dozens of low extinct volcanic cones scattered through it, hence \"City of Sails\". It is not the capital — that is Wellington. The city is named after the Earl of Auckland, a 19th-century British politician.",
    // howItWorks sources: Wikipedia (2026-09): Auckland (unitary Auckland Council since 2010 merger of 7 territorial authorities + regional council; 21 local boards; ~4,900 km² region; ~1.7 million 2024–25 ≈ one-third of NZ; Harbour Bridge 1959; AT HOP); Local government in New Zealand
    howItWorks:
      "The Auckland people speak of is, administratively, a 'super city' created only in 2010: seven territorial councils and a regional council were merged into one Auckland Council, whose elected mayor and governing body run transport, water, planning and waste for the whole region, while 21 local boards beneath it run parks, libraries and community affairs in their own areas; police, schools and hospitals belong to central government. The Auckland region covers about 4,900 km², the urban area about 1,100 km², with about 1.82 million people in June 2025, close to a third of the country, and the largest Pacific and Asian communities of any New Zealand city. The city sits on the isthmus between the Waitematā and Manukau harbours: the central business district lies on the Waitematā, the North Shore across the Harbour Bridge of 1959, South Auckland around Manukau, and West Auckland as another quarter. Addresses give number, street, suburb and four-digit postcode, and locals place things by suburb. Trains, buses and ferries run on one AT HOP card, yet the car remains most people's daily life. The Māori name Tāmaki Makaurau is used alongside the English. Newcomers most often go wrong by taking the central business district for Auckland, when it is one point in a metropolitan area spanning two harbours.",
    layout:
      "Auckland straddles the isthmus between the Waitematā Harbour (east) and the Manukau Harbour (west); the city centre and the Sky Tower are on the eastern harbour. The whole city sits on the Auckland Volcanic Field — about 50 extinct cones through the suburbs, and Maungawhau (Mt Eden) and Maungakiekie (One Tree Hill) can both be climbed for a panorama. North over the Harbour Bridge is the North Shore and the way to the Bay of Islands; east are the Hauraki Gulf islands such as Waiheke; south is the Waikato farm country.",
    // gettingAround sources（2026-09-13 回扫改）：原「也在修城铁连接线 / a rail link is under construction」—— City Rail Link 2026-06 实质完工、2026-09-13 开通（OurAuckland 奥克兰市议会官方新闻，1 级）；且 CRL 在市中心地下、并不连机场，原句把两件事混在一起。核实 2026-09-13
    gettingAround:
      "Auckland Airport is south of the city, with airport buses (SkyDrive/SkyBus) and public buses into town; the City Rail Link under central Auckland opened on 13 September 2026. The city has buses, trains and ferries with a single AT HOP card; ferries go to Devonport and Waiheke. The city is spread out and many people hire a car (drive on the left). The climate is temperate maritime, mild and humid all year — about 23°C in summer (December–February), about 14°C in winter — with rain possible in any season and often windy.",
    culture:
      "English is universal. Auckland has one of the largest Pacific Islander populations of any city (sometimes called the largest Polynesian city in the world), with big Māori, Samoan, Tongan and Asian communities and very diverse food and markets. The pace is slower than a European or American big city, and weekends centre on the coast and the outdoors. Tipping is not expected.",
    seeAndDo:
      "The Sky Tower for the city and harbour; Mt Eden and One Tree Hill for the volcanic landforms; the Viaduct waterfront and the old streets of Parnell; the Auckland War Memorial Museum (Māori and Pacific taonga, war remembrance — a solemn place) and the Maritime Museum; ferries to Devonport for the coastal forts, and to Waiheke for the wineries and beaches. An hour west are the black-sand beaches such as Piha and the Waitākere rainforest (parts are managed to slow kauri dieback disease).",
    whenAndTips:
      "November–April has the best weather. Auckland is known for \"four seasons in one day\", so carry a windproof, waterproof layer. The black-sand beaches (Piha, Bethells) have big surf and rip currents — swim only between the flags where there are lifeguards. Border checks on hiking boots, tents and food are very strict, so clean and declare.",
  },

  wellington: {
    // identity sources: 新西兰统计局（Stats NZ）《Subnational population estimates》**年度**发布，覆盖截至当年 6 月 30 日的估计，
    //   最近一期 2025-10-29 发布（基准 2025-06-30），下一期预计 2026-10。region / territorial authority / urban area
    //   三档口径都在同一份里。2026-09-08 核。
    //   **新西兰官方没有与美国 MSA 对等的「都会区」口径** —— 本项目今后统一用「城区人口（Stats NZ urban area）」、
    //   「XX 市议会辖区人口（territorial authority）」、「XX 大区人口（region）」三种可追溯到官方分类的说法。
    //   惠灵顿市 + 下哈特 + 上哈特 + 波里鲁阿四个 territorial authority 相加，2025-06-30 约 **433,900**
    //   （3 级汇总，**不是 Stats NZ 的单一统计单元**）；
    //   Stats NZ 官方 **Wellington Region 2025-06-30 为 543,400**，范围大得多（含凯皮蒂、怀拉拉帕等乡村地区）。
    //   **两个数字都对，指的却是完全不同的范围** —— 原文用同一批「都会区／XX 区」措辞，读者会以为在说同一件事。
    identity:
      "Wellington is the capital of New Zealand, at the southern tip of the North Island on Cook Strait; Wellington City together with Lower Hutt, Upper Hutt and Porirua had a combined estimated population of about 434,000 in June 2025 — the sum of four councils, not a single official Stats NZ unit. Hills on three sides and the sea on the fourth make the centre compact — it is called one of the smallest capitals in the world — and it is famously windy (\"Windy Wellington\"). The city is named after the Duke of Wellington, who defeated Napoleon; there is also a Wellington in Somerset, England, and one in New South Wales, Australia.",
    // howItWorks sources: Wikipedia (2026-09): Wellington (Wellington City Council ~290 km²; ~210,800 June 2025; region ~550,000 with Lower Hutt/Upper Hutt/Porirua; Greater Wellington Regional Council; capital since 1865; Wellington Fault); Local government in New Zealand
    howItWorks:
      "Wellington has been New Zealand's capital since 1865 — a status resting on constitutional convention rather than statute — with Parliament, the ministries and the Supreme Court in the central business district. Wellington City Council governs about 290 km² with about 210,000 people in 2025, while the Wellington Region holds about 550,000, with Lower Hutt, Upper Hutt and Porirua as cities with councils of their own, the Greater Wellington Regional Council running public transport and environment, and police, schools and hospitals under central government. The city is squeezed between harbour and hills, much of its business district built on land raised by the 1855 earthquake and then reclaimed, with residential suburbs climbing the slopes and the cable car as the old way up; the Wellington Fault runs through the centre, and earthquake risk is the city's constant background. Addresses give number, street, suburb and four-digit postcode. Metlink trains and buses run on one Snapper card, and the Cook Strait ferries leave from here for the South Island. Wind is Wellington's calling card. Newcomers most often go wrong by taking Wellington city for the whole capital region, when the Hutt Valley and Porirua are other cities.",
    layout:
      "Wellington is built on the steep western shore of an almost enclosed harbour (Lambton Harbour), with little flat land — houses climb the slopes in layers, linked by a cable car and steep steps. The centre and Parliament (the \"Beehive\") are by the harbour; south are the Botanic Garden at the top of the cable car and the Zealandia sanctuary; at the harbour mouth to the north is the ferry terminal (the South Island ferries leave from here).",
    gettingAround:
      "Wellington Airport is just south of the city, close to the centre, with an airport bus. The city has buses and a commuter rail network, paid with a Snapper card or bank card. The Cable Car links the centre with the Botanic Garden on the hill. For the South Island, take the inter-island ferry (about 3–3.5 hours to Picton). The climate is temperate maritime, mild all year but very windy, especially in spring, and the weather changes fast — always carry a windproof jacket.",
    culture:
      "Wellington is New Zealand's political, cultural and film centre (Wētā Workshop, and the post-production for the Lord of the Rings and Avatar films is done here), with a high density of cafés and small theatres — it is called the \"coffee capital\". The pace is unhurried and the centre is walkable. Tipping is not expected.",
    seeAndDo:
      "Te Papa, the national museum (free, Māori and natural history — a solemn place); the cable car up to the Botanic Garden; Zealandia, an urban ecosanctuary for native birds; the independent shops and restaurants of Cuba Street and the surrounding quarter; the harbour waterfront walk; the Mount Victoria lookout by cable car or car. The ferry across Cook Strait into the Marlborough Sounds is a classic piece of scenery.",
    whenAndTips:
      "December–March has the most settled weather. Wind is normal in Wellington, especially in spring, and stronger by the sea and up high — hats and light items blow away easily. The Cook Strait ferry is delayed or cancelled in high wind and swell, so leave flexibility if you have a South Island connection. Border checks on outdoor gear and food are strict.",
  },

  rotorua: {
    // howItWorks sources（2026-09-15 核实，add-year）: Stats NZ 2025-06-30 估计（1 级）；下一期约 2026-10
    // identity sources（2026-09-15 核实，update）: Stats NZ Subnational population estimates at 30 June 2025（1 级；分区数经维基转引核对）；下一期约 2026-10
    identity:
      "Rotorua is in the volcanic country of the central North Island, on the shore of Lake Rotorua, with an urban-area population of about 58,500 in June 2025 (Stats NZ). It sits in an old caldera with strong geothermal activity — geysers, boiling mud pools and coloured hot springs are everywhere, and the air often smells of sulphur. It is also one of the centres of Māori culture, especially that of the Te Arawa people.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Rotorua (Rotorua Lakes Council, Bay of Plenty; urban area ~58,500, 13th largest in NZ; southern shore of Lake Rotorua in the Rotorua Caldera; Pōhutu Geyser at Whakarewarewa; hydrogen sulfide smell, "Sulphur City"; Te Arawa settled from the 14th century, Ohinemutu; 46% Māori (2023 census; not the national highest — Gisborne is higher); health care and hospitality the largest employers)
    // howItWorks sources（2026-09-13 回扫改）：删「新西兰毛利人比例最高的城市」—— 2023 年普查吉斯伯恩约 55–56% 更高（Te Ao Māori News 引 Stats NZ，2 级）；46% 本身保留。核实 2026-09-13
    howItWorks:
      "Rotorua is a city of the Bay of Plenty region of New Zealand, governed by the Rotorua Lakes Council, its urban area holding about 58,500 people in June 2025 (Stats NZ), the thirteenth largest in the country; the council runs waste, roads and planning, while police, schools and hospitals belong to central government. The city stands on the southern shore of Lake Rotorua inside the Rotorua Caldera, and the geothermal field comes up beneath it: the Pōhutu Geyser at Whakarewarewa, the steaming mud pools and the smell of hydrogen sulfide are daily life, and 'Sulphur City' is its nickname. The Te Arawa people settled here from the fourteenth century, the village of Ohinemutu stands on the lake shore, and about 46 per cent of residents are Māori, with Māori cultural performance and the geothermal ground its tourist mainstay and the mountain bike trails of the redwoods to the east. Auckland lies about 220 km north-west, Taupō about 80 km south, the airport north-east of town and there is no passenger railway. Newcomers most often go wrong by expecting the geothermal ground outside town, when it steams in the parks and beside the streets.",
    layout:
      "The town is on the southern shore of Lake Rotorua, around the Government Gardens. Geothermal areas are in and around it: Kuirau Park is in town, while Wai-O-Tapu (\"thermal wonderland\"), Te Puia and Waimangu are to the south; the Whakarewarewa Forest (the Redwoods) to the south-east is for cycling and running. There are a dozen or so volcanic lakes around.",
    gettingAround:
      "Rotorua Airport is on the eastern shore of the lake, with scheduled domestic flights. Most people drive from Auckland (about 3 hours). The town is small and walkable; the surrounding geothermal areas and the Redwoods need a car or a tour. The climate is temperate maritime — mild summers, cool winters, rain year-round, and high humidity near the geothermal areas.",
    culture:
      "English is universal, and Māori culture is part of daily life here: you can visit a marae, see kapa haka performance, and try hāngī (an earth-oven meal). At geothermal areas and Māori villages, stay on the paths and follow instructions — the ground crust is thin and scalding, and leaving the path is dangerous. Tipping is not customary.",
    seeAndDo:
      "The Wai-O-Tapu geothermal area (the Champagne Pool, the Artist's Palette, the Lady Knox Geyser, which erupts at a set time each day); Te Puia for geysers and the Māori arts institute; walking or cycling the Redwoods and the treewalk (lit at night); the lake-view hot pools of the Polynesian Spa; the mud baths of Hell's Gate; nearby Mount Tarawera and the Blue and Green lakes.",
    whenAndTips:
      "It is a year-round destination, most comfortable December–March. The sulphur smell tarnishes silver jewellery, so sensitive people can take it off. The geothermal crust is dangerous — stay on the paths and mind children. Geysers erupt at set times, so plan around them. It is rainy, so bring an umbrella and waterproof shoes.",
  },

  christchurch: {
    // identity sources: 新西兰统计局（Stats NZ）《Subnational population estimates》**年度**发布，覆盖截至当年 6 月 30 日的估计，
    //   最近一期 2025-10-29 发布（基准 2025-06-30），下一期预计 2026-10。region / territorial authority / urban area
    //   三档口径都在同一份里。2026-09-08 核。
    //   **新西兰官方没有与美国 MSA 对等的「都会区」口径** —— 本项目今后统一用「城区人口（Stats NZ urban area）」、
    //   「XX 市议会辖区人口（territorial authority）」、「XX 大区人口（region）」三种可追溯到官方分类的说法。
    //   基督城市（territorial authority，含班克斯半岛）2025-06 ERP **419,200**；
    //   Stats NZ 官方城区（urban area）**407,800**；含塞尔文、怀马卡里里两区的都会范围约 **556,500**
    //   （3 级转引 Stats NZ，2026-09-08 核）。
    //   **原文里「都会区」一个词在同一条目里指了两个不同的数**（identity 40 万 ≈ urban area，
    //   howItWorks 56 万 = 含两区）。
    identity:
      "Christchurch is the largest city on the South Island and the centre of the Canterbury region; Christchurch City (including Banks Peninsula) had an estimated population of about 419,000 in June 2025, its official urban area about 408,000, and the wider metropolitan area including the Selwyn and Waimakariri districts about 556,000 (Stats NZ). It is built on the eastern edge of the Canterbury Plains at the foot of Banks Peninsula; it began as a planned Church of England settlement, laid out on a grid around a cathedral, and is named after Christ Church, a college of Oxford — there is also a Christchurch in Dorset, England. The 2010–2011 earthquakes badly damaged the centre, which has been rebuilding since.",
    // howItWorks sources: Wikipedia (2026-09): Christchurch (Christchurch City Council ~1,415 km² incl. Banks Peninsula; ~419,200 June 2025; metro ~556,500; Four Avenues grid 1850; Lyttelton tunnel 1964; 2010–11 earthquakes; Environment Canterbury); Local government in New Zealand
    howItWorks:
      "Christchurch is the largest city of the South Island, and Christchurch City Council governs about 1,415 km² — since Banks Peninsula joined in 2006 — with about 419,000 people in 2025 and about 556,000 across the built-up area together with the Selwyn and Waimakariri districts — Stats NZ publishes no metropolitan-area tier — in the wider area; Environment Canterbury is the regional council for public transport and environment, and police, schools and hospitals belong to central government. The city was laid out on the plain to the Canterbury Association's plan of 1850, a square centre within the Four Avenues with Cathedral Square as the point of reference, the Avon and Hagley Park running through it, the Port Hills to the south and the port of Lyttelton through the tunnel of 1964. The earthquake sequence of 2010–2011 rewrote the city: most of the centre was demolished and rebuilt, more than 8,000 homes in the east were red-zoned, and the Cardboard Cathedral and the new convention centre are the emblems of the rebuild. Rangiora to the north and Rolleston to the south-west lie in two other district councils and are the fastest-growing commuter belt. Addresses give number, street, suburb and four-digit postcode. Public transport is buses only, on the Metro card. The Māori name Ōtautahi is used alongside the English. Newcomers most often go wrong by taking the rebuilt centre for the whole of Christchurch, when the city's life is spread through the suburbs on the plain.",
    layout:
      "Christchurch is built on the flat Canterbury Plains, with the Avon River winding through the grid of the centre and Cathedral Square at the heart. South-east are the port of Lyttelton and Banks Peninsula (an old extinct volcano with a broken coast of small bays); the Port Hills on the peninsula's edge give views over Lyttelton Harbour. West are the plains and the foot of the Southern Alps.",
    gettingAround:
      "Christchurch Airport is north-west of the city, with an airport bus and public buses into town. Christchurch is the main gateway to the South Island: west over Arthur's Pass to the West Coast (with the TranzAlpine scenic train), south to Tekapo, Aoraki/Mount Cook and Queenstown, north to Kaikōura for whales. The city has buses (Metrocard); the centre is flat and good for cycling (there are public bikes). The climate is temperate maritime, with dry summers, frosty winters, and occasional hot, dry föhn winds (\"norwesters\").",
    culture:
      "English is universal; Christchurch is called the most English of New Zealand's cities, with large parks, cricket grounds and Edwardian buildings. Since the earthquakes, the centre has filled with transitional spaces made of shipping containers and street art, and feels younger than before. The pace is slow. Tipping is not expected.",
    seeAndDo:
      "Punting on the Avon, the Botanic Gardens and Hagley Park; Cathedral Square (reinstatement of the cathedral stalled in 2024 over a funding gap and was re-planned in 2025 as a staged rebuild), the Cardboard Cathedral and the earthquake memorial wall (a solemn place); the Canterbury Museum and the Bridge of Remembrance; the gondola up the Port Hills for the view over Lyttelton Harbour; the International Antarctic Centre. Drive out to Akaroa (a French-flavoured town on Banks Peninsula), Tekapo for the night sky, and Aoraki/Mount Cook.",
    whenAndTips:
      "December–March has the best weather. On norwester days (dry, hot north-west wind) the temperature jumps and fire risk is high. The TranzAlpine train and the routes to Aoraki/Mount Cook and Tekapo need booking in high season. The inland South Island has snow in winter — check road conditions and carry chains. Border checks on outdoor gear and food are very strict.",
  },

  queenstown: {
    // identity sources: 新西兰统计局（Stats NZ）《Subnational population estimates》**年度**发布，覆盖截至当年 6 月 30 日的估计，
    //   最近一期 2025-10-29 发布（基准 2025-06-30），下一期预计 2026-10。region / territorial authority / urban area
    //   三档口径都在同一份里。2026-09-08 核。
    //   **新西兰官方没有与美国 MSA 对等的「都会区」口径** —— 本项目今后统一用「城区人口（Stats NZ urban area）」、
    //   「XX 市议会辖区人口（territorial authority）」、「XX 大区人口（region）」三种可追溯到官方分类的说法。
    //   皇后镇湖区议会辖区（Queenstown-Lakes District）2025-06-30 ERP **53,800**（3 级转引 Stats NZ，2026-09-08 核）；
    //   镇区约 2.9 万与 howItWorks 一致。**该区年增长率一度高达约 8%，人口数过期得特别快**，下一轮必刷。
    identity:
      "Queenstown is in the south of the South Island on the shore of Lake Wakatipu, ringed by mountains including The Remarkables, with an urban-area population of under 30,000 (about 54,000 in the wider Queenstown-Lakes District in June 2025, Stats NZ) but serving as the tourism and outdoor-sports centre of New Zealand. It is known as the \"adventure capital\" — bungy jumping (the first commercial bungy site is nearby), skydiving, jetboating and skiing are all here. The origin of the name is uncertain, with several accounts.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Queenstown (largest town of Queenstown-Lakes District, Otago; urban population ~29,000 June 2025; north-eastern shore of Lake Wakatipu at 310 m; The Remarkables and Coronet Peak; bungy jumping; Skyline gondola on Bob's Peak; Arrowtown and Wānaka in the same district; least affordable housing in NZ, average price over NZ$1.7 million by late 2022; airport)
    howItWorks:
      "Queenstown is a resort town of the Otago region of New Zealand and the largest town of the Queenstown-Lakes District, with an urban population of about 29,000 in June 2025; the council runs waste, roads and planning, while police, schools and hospitals belong to central government. The town lies on the north-eastern shore of Lake Wakatipu at 310 m with mountains on every side: the ski fields of The Remarkables and Coronet Peak open in winter, the Skyline gondola climbs from the centre to Bob's Peak, and bungy jumping became a business at the Kawarau bridge; Arrowtown and Wānaka lie in the same district and Milford Sound is the end of a long day trip. Tourism is the whole of its economy, housing is the least affordable in the country with an average price over NZ$1.7 million by late 2022, and the shortage of housing is a standing local problem; the airport lies east of town, while Christchurch and Dunedin are each hundreds of kilometres away. Newcomers most often go wrong by taking Queenstown for a city, when it is a town of under thirty thousand priced like an international resort.",
    layout:
      "Queenstown is built on a bay at a Z-shaped bend in Lake Wakatipu; the centre is compact and walkable, and the Skyline Gondola runs straight from town to a hilltop lookout. Across the lake are The Remarkables; the lake's north-west arm leads to Glenorchy and the valleys used for Lord of the Rings. North-east over the hills are Arrowtown (an old gold-rush town) and Wānaka; south are Te Anau and the fiords.",
    gettingAround:
      "Queenstown Airport is at Frankton, east of town, about 10 minutes from the centre, with scheduled domestic flights and flights to Australia. There are buses in town and to the airport, but most sights, tracks and ski fields need a car or a tour. In winter, mountain roads need care for ice and snow and may require chains. The climate is temperate semi-arid (in the mountains' rain shadow): warm, dry summers, cold, snowy winters, and a wide day-to-night range.",
    culture:
      "English is universal; Queenstown has one of the highest shares of international visitors in New Zealand, with a well-developed service industry and high prices. Life revolves around the outdoors and the lake and mountains. Tipping is not expected.",
    seeAndDo:
      "The Skyline Gondola for the view over Lake Wakatipu and The Remarkables, plus the summit luge; a cruise on the historic steamship TSS Earnslaw; bungy, skydiving and jetboating (choose licensed operators); drives to Glenorchy, Arrowtown and Wānaka; a long day trip or overnight to Milford Sound (a long, winding drive, mostly done by tour or with a stay). Skiing in winter at Coronet Peak and The Remarkables.",
    whenAndTips:
      "December–February is the summer high season (hiking, water activities); June–August is the ski season; both are expensive for accommodation and need early booking. The Milford Sound day trip is about a 4-hour drive each way, on a winding road with changeable weather. For adventure activities, use licensed operators and read the insurance and safety briefings.",
  },

  dunedin: {
    // identity sources: 新西兰统计局（Stats NZ）《Subnational population estimates》**年度**发布，覆盖截至当年 6 月 30 日的估计，
    //   最近一期 2025-10-29 发布（基准 2025-06-30），下一期预计 2026-10。region / territorial authority / urban area
    //   三档口径都在同一份里。2026-09-08 核。
    //   **新西兰官方没有与美国 MSA 对等的「都会区」口径** —— 本项目今后统一用「城区人口（Stats NZ urban area）」、
    //   「XX 市议会辖区人口（territorial authority）」、「XX 大区人口（region）」三种可追溯到官方分类的说法。
    //   达尼丁市议会辖区（territorial authority，约 3,286 km²，绝大部分是农村）2025 年约 **133,000**；
    //   **Stats NZ 官方城区（urban area）只有约 104,000**（3 级转引 Stats NZ，2026-09-08 核）。
    //   **原文把辖区人口当成了「都会区」人口** —— 这类辖区面积极大、含大片农村的城市尤其要分开写，
    //   不然会明显高估建成区规模。「南岛人口第二多」按两档口径都成立。
    identity:
      "Dunedin is on the south-eastern coast of the South Island at the base of the Otago Peninsula; the Dunedin City territorial authority (about 3,286 km², much of it rural) had an estimated population of about 133,000 in 2025, of which about 104,000 live in the official urban area (Stats NZ) — the second-largest city on the South Island. It was founded by Scottish Presbyterian settlers in the mid-19th century, and the name Dunedin is the old Scots Gaelic name for Edinburgh (Dùn Èideann); the street names, churches and university carry a strong Scottish stamp. The wildlife nearby — albatross, yellow-eyed penguins, sea lions — is a major draw.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Dunedin (second city of the South Island, Otago; territorial authority ~3,286 km², larger than Rhode Island; ~132,800 June 2025; founded 1848 by Scottish settlers, name from Gaelic for Edinburgh; 1860s gold rush briefly made it NZ's largest city; University of Otago 1869, oldest in NZ, "Scarfies"; Baldwin Street the world's steepest residential street; Otago Peninsula albatross and penguins; Dunedin sound)
    howItWorks:
      "Dunedin is the second city of New Zealand's South Island in the Otago region, governed by the Dunedin City Council over about 3,286 km², larger than the American state of Rhode Island, with about 132,800 people in June 2025; the council runs waste, roads and planning, while police, schools and hospitals belong to central government. Settlers of the Free Church of Scotland founded the city in 1848 and named it from the Gaelic for Edinburgh, and the Octagon and the Victorian railway station are of that time; the Otago gold rush of the 1860s briefly made it the largest city in New Zealand, and the stone buildings are what that money left. The University of Otago, founded in 1869, is the oldest in the country, its students' 'Scarfie' culture and the Dunedin sound of the 1980s the city's other face; Baldwin Street is the steepest residential street in the world, the Otago Peninsula holds royal albatross and yellow-eyed penguin colonies, and the airport lies south at Momona. Newcomers most often go wrong by taking Dunedin for a small city, when its territory is larger than some countries' provinces and farms and coastline lie beyond the town.",
    layout:
      "Dunedin is built in a valley and on steep slopes at the head of a long harbour (Otago Harbour), with The Octagon as the centre. The University of Otago (the oldest in New Zealand) is just north of the centre. East along the harbour is the Otago Peninsula — a hilly peninsula whose tip, Taiaroa Head, has the only mainland breeding colony of royal albatross in the world. Baldwin Street, in the suburbs, was long considered one of the steepest streets in the world.",
    gettingAround:
      "Dunedin Airport is about 30 km south-west of the city, with an airport bus. Intercity travel is by car or coach. The city has buses; the centre is walkable but hilly. Seeing the Otago Peninsula wildlife needs a car or a tour (the peninsula road is narrow and winding). The climate is temperate maritime — cooler than the North Island, with four clear seasons, frosts and occasional snow in winter, and fast-changing weather.",
    culture:
      "English is universal, with a strong Scottish heritage (a Scottish festival, bagpipes, a statue of Robert Burns). It is a university city, young and lively in term time. The pace is slow. Tipping is not expected.",
    seeAndDo:
      "The Octagon and the surrounding Edwardian buildings, and the Dunedin Railway Station (one of the most-photographed buildings in New Zealand); the Otago Museum and the Toitū Otago Settlers Museum; Taiaroa Head on the Otago Peninsula for the royal albatross, and a penguin reserve for yellow-eyed penguins (they come ashore in the evening — go with a licensed guide and keep quiet); Larnach Castle; Baldwin Street. North are the Moeraki Boulders.",
    whenAndTips:
      "December–March has the best weather and is a good time to see albatross chicks and penguins. To watch wildlife, always go with a licensed guide, keep your distance and do not use flash. The Otago Peninsula road is narrow and winding — drive slowly and watch for oncoming traffic. Inland and the passes have snow in winter — check road conditions.",
  },

  // ── New Zealand batch 2 (2026-09-05) ──
  napier: {
    identity:
      "Napier sits on Hawke's Bay on the east coast of the North Island, with about 66,400 people (June 2025 estimate), and has one of the densest collections of Art Deco buildings anywhere: on 3 February 1931 the Hawke's Bay earthquake flattened the centre and killed 256 people, and over the following years the whole town was rebuilt in the Art Deco style of the day. The Pania of the Reef statue on Marine Parade is the town's emblem. Hawke's Bay is New Zealand's second-largest wine region with more than seventy wineries, and Cape Kidnappers to the south holds one of the world's largest mainland gannet colonies. The local iwi is Ngāti Kahungunu.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Napier (Napier City Council, Hawke's Bay; 105 km²; ~66,400 June 2025; 3 February 1931 earthquake killed 256 and the city was rebuilt in Art Deco; Marine Parade; Pania of the Reef; Napier Port; Hastings ~18 km, the "Twin Cities", combined ~133,240; Hawke's Bay the second-largest NZ wine region; Cape Kidnappers gannets; Art Deco festival February)
    howItWorks:
      "Napier is a city of the Hawke's Bay region of New Zealand, governed by the Napier City Council over about 105 km² with about 66,400 people in June 2025; the council runs waste, roads and planning, while police, schools and hospitals belong to central government. The earthquake of 3 February 1931 destroyed the city and killed 256 people, and the rebuilding fell in the years when Art Deco was in fashion, so the centre became one of the most complete Art Deco quarters in the world, with the Art Deco festival each February as its emblem; Marine Parade and the statue of Pania of the Reef stand by the sea and the port lies north of town. Hastings lies 18 km south, the two known as the Twin Cities, each with a council of its own and about 133,240 people between them; Hawke's Bay is New Zealand's second-largest wine region by vineyard area, the gannet colony of Cape Kidnappers lies to the south-east and the airport north of town. Newcomers most often go wrong by taking Napier and Hastings for one city, when they are two councils with two centres.",
    layout:
      "The centre lies on the flat south of Bluff Hill, with the Art Deco streets densest around Emerson and Tennyson streets; Marine Parade runs south along the shore with gardens, fountains, the aquarium and the Pania statue, and Bluff Hill overlooks the port. The 1931 quake lifted the Ahuriri lagoon, now the wetland and airport site north of town. Hastings is about 20 km south, Te Mata Peak south-east of Hastings, and Cape Kidnappers about 30 km south-east at the tip of the headland. The wineries spread across the plains and the Gimblett Gravels between Napier and Hastings.",
    gettingAround:
      "Hawke's Bay Airport (NPE), about 5 km north-west of the centre, has scheduled domestic flights. Driving from Wellington takes about 4 hours and from Taupō about 2; coaches run. The centre is walkable and Marine Parade suits cycling; the wineries, Cape Kidnappers and Te Mata Peak need a car or a tour. The climate is temperate maritime, sunny and dry, with warm dry summers and mild winters.",
    culture:
      "English is universal and Māori place names are common. The Art Deco Festival each February fills the town with 1930s dress and vintage cars and is the busiest time. Cellar doors mostly charge for tastings — mind the drink-driving limit. The Cape Kidnappers gannet colony lies on private farmland, opens only from September to April, and is reached by guided tour or by walking the beach on the tide. Do not enter marae uninvited. Tipping is optional.",
    seeAndDo:
      "Guided Art Deco walks of the centre (Emerson Street, the Art Deco Centre); Marine Parade, the Pania statue and the National Aquarium; the Bluff Hill lookout; Hawke's Bay wineries (cycle-tasting trails); the Cape Kidnappers gannets (tractor tour or low-tide beach walk); sunrise and paragliding on Te Mata Peak; the Sunday farmers' market in Hastings; birdwatching on the Ahuriri estuary.",
    whenAndTips:
      "Book early for the February Art Deco Festival; November–April has the best weather and the gannet season; winter is quiet but the wineries stay open. A day for the town, half a day to a day each for the wineries and Cape Kidnappers. The beach walk to the cape must follow the tide — leave after low water and return before it rises.",
  },
  taupo: {
    identity:
      "Taupō lies on the northern shore of Lake Taupō in the centre of the North Island, with about 27,000 people (June 2025 estimate). The lake, about 616 km², is New Zealand's largest and fills the caldera of the Taupō volcano — its Oruanui eruption about 26,000 years ago was one of the largest volcanic eruptions on earth in the last 100,000 years. The Waikato River leaves the northern end of the lake and about 4.6 km in a straight line north of town crashes through Huka Falls; geothermal fields such as Craters of the Moon and several geothermal power stations surround the town. Rainbow trout introduced in the 1890s made Taupō a world-known trout fishery. Tongariro National Park lies about 50 km south. The local iwi is Ngāti Tūwharetoa.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Taupō (Taupō District Council, Waikato region; urban area ~27,000 June 2025, second-largest in Waikato; north-eastern edge of Lake Taupō, New Zealand's largest lake, a caldera; Huka Falls; Wairakei geothermal power station 1958 and seven stations in the region; Ngāti Tūwharetoa; Tongariro National Park south; Ironman NZ; trout fishing)
    howItWorks:
      "Taupō is a town of the Waikato region of New Zealand, governed by the Taupō District Council, its urban area holding about 27,000 people in June 2025, the second-largest in the region; the council runs waste, roads and planning, while police, schools and hospitals belong to central government. The town lies at the north-eastern corner of Lake Taupō, the largest lake in New Zealand and the caldera of a great volcano, with geothermal activity still under its floor; the Huka Falls lie on the Waikato River north of town, the Wairakei geothermal station commissioned in 1958 made this the centre of geothermal power with seven stations in the district, and the town's population has grown from that time. The lakebed is owned by the Ngāti Tūwharetoa iwi, Tongariro National Park lies on the southern shore, trout fishing and the Ironman are its two events, and Rotorua lies about 80 km north. Newcomers most often go wrong by taking Lake Taupō for an ordinary lake, when it is a volcanic crater, still steaming beneath and around it.",
    layout:
      "The town spreads along the northern lakeshore, with the marina, parks and hot pools on the waterfront and the main street a block or two inland. The river outlet is at the east of town, and Huka Falls, Craters of the Moon and the Wairakei geothermal field lie in a line north along the river; the Mine Bay rock carvings on the western shore can only be reached by boat or kayak. Across the lake to the south are Tūrangi and Tongariro National Park (the Ruapehu, Ngāuruhoe and Tongariro volcanoes); Rotorua is about 80 km north. The airport is about 8 km south of town.",
    gettingAround:
      "Taupō Airport (TUO), about 8 km south of town, has Air New Zealand flights to Auckland only. Driving from Auckland takes about 3.5 hours, from Wellington about 4.5 and from Rotorua about 1; coaches run. The town is walkable, Huka Falls can be reached on foot or by bicycle along the river track, and Tongariro needs a car or a crossing shuttle. The climate is temperate at about 360 m, with warm summers and cold winters and snow on the mountains.",
    culture:
      "English is universal. Ngāti Tūwharetoa owns much of the lakebed and shore, and the Mine Bay carvings are a Māori artwork of the 1970s — look, don't touch. Trout fishing needs a Taupō-specific licence, separate from the rest of New Zealand. Keep to the boardwalks in geothermal areas — the ground is scalding. The lake is cold for swimming. Tipping is optional.",
    seeAndDo:
      "Huka Falls (on foot, by bicycle or by jet boat to the foot of the falls); a lake cruise to the Mine Bay Māori rock carvings; the Craters of the Moon geothermal walk; the Wairakei Terraces hot pools; skydiving and bungy on the lakeshore (Taupō is a skydiving hub); trout fishing; the Tongariro Alpine Crossing (a day hike from Tūrangi); the Orakei Korako geothermal area about 25 km north.",
    whenAndTips:
      "December–March is most comfortable with plenty on the lake; winter (June–September) pairs with skiing on Ruapehu. The Tongariro crossing depends on weather and needs a guide and gear in winter. Taupō is a common overnight stop on the Auckland–Wellington drive — one or two nights.",
  },
  tauranga: {
    identity:
      "Tauranga lies on the western Bay of Plenty on the North Island, with about 161,000 people (June 2025 estimate) — New Zealand's fifth-largest and one of its fastest-growing cities, and the Port of Tauranga is the country's largest export port. Mount Maunganui (Mauao, 232 m) on the edge of the city is an extinct volcano, and the beach below it is one of the best-known surf beaches in the country; the Te Puke district to the east is the heart of kiwifruit growing. The 1864 Battle of Gate Pā on the city's edge brought the heaviest British losses of the New Zealand Wars. The local iwi are Ngāti Ranginui, Ngāi Te Rangi and Ngāti Pūkenga. The city enjoys more than 2,400 sunshine hours a year.",
    // howItWorks sources: Wikipedia (2026-09): Tauranga (Tauranga City Council ~142 km²; ~161,000 June 2025; Bay of Plenty Regional Council; Mount Maunganui bridge 1988; Port of Tauranga largest export port; Western Bay of Plenty District separate); Local government in New Zealand
    howItWorks:
      "Tauranga is among the fastest-growing cities in New Zealand, and Tauranga City Council governs about 142 km² with about 161,000 people in 2025, the fifth-largest urban area in the country; the Bay of Plenty Regional Council runs public transport and environment, and police, schools and hospitals belong to central government. The city grew around Tauranga Harbour: the centre lies on its peninsula, the beach town at the foot of Mount Maunganui (Mauao) across the harbour bridge of 1988, and Pāpāmoa spreading east along the coast as the main new residential area; the Port of Tauranga is the country's largest export port, and kiwifruit and avocados leave from the orchards of the district. The Western Bay of Plenty District — Te Puke, Ōmokoroa — is another council. Addresses give number, street, suburb and four-digit postcode. There is no passenger rail and little public transport, the car is daily life, and the mild climate has drawn many retirees. Newcomers most often go wrong by taking Mount Maunganui for Tauranga's centre, when it is a suburb across the harbour.",
    layout:
      "The centre sits on a peninsula on the southern shore of Tauranga Harbour, with The Strand on the waterfront as the dining street; the harbour bridge leads to Mount Maunganui — the township at the tip of the peninsula with the harbour on one side, an open beach on the other and the mountain at the very end. The port wharves and container yards lie on the harbour side of the Mount. Gate Pā is in the south-west of the city, McLaren Falls about 20 km west, Te Puke about 30 km south-east and Rotorua about 65 km south. The airport is at Mount Maunganui, about 3 km from the centre.",
    gettingAround:
      "Tauranga Airport (TRG) at Mount Maunganui, about 2.9 km in a straight line from the centre, has scheduled domestic flights. Driving from Auckland takes about 2.5 hours via the Waikato Expressway and from Rotorua about 1; coaches run. Local buses serve the city; the centre and the Mount are each walkable, with a bus or taxi between them; the surrounding district needs a car. The climate is temperate maritime with warm summers and mild wet winters.",
    culture:
      "English is universal. Mauao is a place of deep significance to local Māori — keep to the tracks and leave nothing behind; the beach is patrolled, so swim between the flags. The Gate Pā reserve is a battlefield memorial — keep it quiet. Summer is cruise-ship season, when the centre is busy on port days. Kiwifruit harvest runs April–June. Tipping is optional.",
    seeAndDo:
      "Climb Mauao (about 45 minutes; the base track is gentler); surfing and the hot saltwater pools at Mount Maunganui beach; dining on The Strand; the Gate Pā historic reserve; McLaren Falls Park (glow-worm night walks); kiwifruit orchard tours at Te Puke; dolphin cruises; Pāpāmoa Beach.",
    whenAndTips:
      "December–March is the beach season — book early; April–May and October–November are quieter with good weather. The Mount is the best place to stay. A coastal side-trip on the Auckland–Rotorua–Taupō route — one or two nights.",
  },
  nelson: {
    // howItWorks sources（2026-09-15 核实，add-year）: Stats NZ 2025-06-30 估计（1 级）；下一期约 2026-10
    identity:
      "Nelson sits on Tasman Bay at the top of the South Island, with about 54,300 people (June 2025 estimate); founded in 1841 by the New Zealand Company, it is the oldest city in the South Island. It is known for sunshine (over 2,400 hours a year — 'Sunny Nelson'), is the gateway to three national parks — Abel Tasman, Kahurangi and Nelson Lakes — and has one of the country's densest communities of craftspeople and artists: the World of WearableArt awards began here in 1987, and the goldsmith who made the One Ring for the Lord of the Rings films works here. The marker on Botanical Hill is called the 'Centre of New Zealand' (in fact the origin point of an early survey).",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Nelson (city and unitary authority at the top of the South Island; 422 km²; ~54,300, urban ~50,800; oldest city in the South Island, settled 1841, royal charter 1858; Tasman Bay; over 2,400 sunshine hours, the sunniest in NZ; Abel Tasman National Park in the separate Tasman District; Port Nelson the biggest fishing port in Australasia; World of Wearable Art founded 1987; airport ~1 million passengers)
    // howItWorks sources（2026-09-13 回扫改）：删「全国只有六个」—— 单一制议会数量 5 或 6 取决于是否计入查塔姆群岛议会，地方政府委员会口径也不明确，不写具体数。核实 2026-09-13
    howItWorks:
      "Nelson is a 'unitary authority' in New Zealand's local government system, exercising the powers of both a city and a regional council, one of only a handful of such areas in the country; it covers about 422 km² with about 54,300 people in June 2025 (Stats NZ) and an urban area of about 50,800. European settlers arrived in 1841 and a royal charter followed in 1858, making it the oldest city in the South Island. The city lies on the eastern shore of Tasman Bay with more than 2,400 sunshine hours a year, the sunniest place in New Zealand and 'Sunny Nelson' by its own account; Port Nelson is the largest fishing port in Australasia, and seafood, horticulture, forestry, farming and tourism are the local 'big five', while the World of Wearable Art founded here in 1987 is now held in Wellington. Abel Tasman National Park lies west in the neighbouring Tasman District; the airport handles about a million passengers a year and the Picton ferry terminal is about 110 km east. Newcomers most often go wrong by taking Abel Tasman for Nelson's park, when it lies in another council's area.",
    layout:
      "The centre lies on the flat at the mouth of the Maitai River, with Trafalgar Street as the main street, the cathedral on a knoll at its end and the Saturday market in Montgomery Square. Botanical Hill (the 'Centre of New Zealand') is just east of the centre. Tahunanui Beach is about 5 km south-west, with the airport beside it. West via Richmond and Motueka it is about 65 km to Marahau, the gateway to Abel Tasman National Park; Nelson Lakes National Park is about 90 km south at St Arnaud; the Marlborough wine region about 110 km east.",
    gettingAround:
      "Nelson Airport (NSN), about 6 km south-west of the centre, is one of New Zealand's busiest regional airports with scheduled domestic flights. Driving from the Picton ferry takes about 2 hours and from Christchurch about 5; coaches run. Local buses serve the city and the centre is walkable; the national parks need a car or tour shuttles. The climate is temperate maritime, sunny with mild winters.",
    culture:
      "English is universal. Eight recognised iwi (including Ngāti Kuia and Ngāti Toa Rangatira) have ties to the region. Artists' studios and pottery, glass and woodcarving workshops welcome visitors — ask before photographing. Huts and campsites on the Abel Tasman Coast Track must be booked, and kayak with licensed operators. Tipping is optional.",
    seeAndDo:
      "The Saturday market; the cathedral and Trafalgar Street; the Centre of New Zealand walk on Botanical Hill; Tahunanui Beach; Abel Tasman National Park (water taxi plus a day or multi-day walk on the Coast Track; kayaking to seal colonies); Lake Rotoiti in Nelson Lakes National Park; local wineries and breweries; the WOW and Classic Cars museum.",
    whenAndTips:
      "November–April suits beaches and the parks, with January–February the busiest; winters are clear but cool. Allow at least a day for Abel Tasman and book huts ahead for multi-day walks. The natural first stop westward after arriving in the South Island by the Picton ferry.",
  },
  kaikoura: {
    identity:
      "Kaikōura is a small town on the north-east coast of the South Island about 180 km by road north of Christchurch, with only about 2,350 people (June 2025 estimate), yet it is New Zealand's most famous whale-watching destination: the Kaikōura Canyon offshore plunges from 30 m to 2,000 m, deep-water sperm whales are present year-round, and the whale boats run almost every day; the peninsula has New Zealand fur seal colonies. The name means 'meal of crayfish' in Māori (kai food, kōura crayfish). The magnitude 7.8 earthquake of 14 November 2016 lifted the coastline and cut the road and railway, since rebuilt. The Seaward Kaikōura Range rising straight from the shore gives the town its snow-mountains-by-the-sea setting. The local iwi is Ngāi Tahu.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Kaikōura (Kaikōura District Council; town ~2,350, district ~4,340; peninsula between the Seaward Kaikōura Range and the Pacific; name means "meal of crayfish"; Kaikōura Canyon close inshore supports sperm whales, dusky and Hector's dolphins, fur seals; ~1 million visitors a year, tourism ~40% of district GDP; 2016 magnitude 7.8 earthquake cut all road and rail, NZ$1.1 billion of repairs; Christchurch ~180 km)
    howItWorks:
      "Kaikōura is a small town on the east coast of the South Island, governed by the Kaikōura District Council, with about 2,350 people in the town and about 4,340 in the district; the council runs waste, roads and planning, while police, schools and hospitals belong to central government. The town stands on a peninsula running into the Pacific with the Seaward Kaikōura Range behind it, a narrow strip between mountains and sea; the name means 'a meal of crayfish' in Māori, and roadside crayfish stalls still trade. What sets it apart lies underwater: the Kaikōura Canyon comes close inshore, and its deep water brings sperm whales, dusky and Hector's dolphins and fur seals near the coast, so whale watching followed whaling, farming and fishing as the main trade, with about a million visitors a year and tourism near forty per cent of the district's GDP. The magnitude 7.8 earthquake of 2016 cut every road and railway, and repairs cost about NZ$1.1 billion; Christchurch lies about 180 km south. Newcomers most often go wrong by expecting a long boat ride to the whales, when the canyon lies a few kilometres offshore.",
    layout:
      "The town lies on the coastal flat at the base of the Kaikōura Peninsula, with West End, the main street, facing the bay to the north; the peninsula reaches east into the sea, with the seal colony at Point Kean and a walkway around it; South Bay on the south side of the peninsula is where the whale boats leave. State Highway 1 and the Coastal Pacific railway run through town along the shore, and the Ōhau Point seal area lies about 23 km in a straight line north on the coast. The Seaward Kaikōura Range presses against the coast just west of town.",
    gettingAround:
      "Kaikōura has no scheduled flights — the local airfield serves only whale-watching scenic flights; driving from Christchurch takes about 2.5 hours and from Picton about 2. The Coastal Pacific train between Christchurch and Picton stops here and is a scenic way in (seasonal); coaches run. The town is walkable and cyclable, and the peninsula walkway takes about 3 hours. The climate is temperate maritime with strong sea winds and winter snow on the peaks.",
    culture:
      "English is universal. Whale watching is led by Whale Watch Kaikōura, run by the local iwi; trips depend on sea conditions and are often cancelled by weather, so check the refund rules. Seals are wild — keep at least 10 m away and never block their path to the sea. Crayfish is the local speciality, cooked at roadside stalls. The reefs lifted by the earthquake are good viewing spots — watch the swell. Tipping is optional.",
    seeAndDo:
      "Whale watching (by boat, light aircraft or helicopter); swimming with dolphins and seal viewing; the Kaikōura Peninsula walkway (Point Kean seal colony); seal pups at Ōhau Point (winter); the coastal stretch of the Coastal Pacific train; roadside crayfish stalls; the Mount Fyffe track in the Kaikōura Range; albatross birdwatching trips.",
    whenAndTips:
      "Whales can be seen all year; October–March has the steadiest weather and migrating humpbacks too; winter seas bring more cancellations. Take seasickness remedies before sailing. Plan one night as a stop between Christchurch and Picton.",
  },
  wanaka: {
    identity:
      "Wānaka lies at the southern end of Lake Wānaka in inland Otago on the South Island, at about 290 m, with about 13,200 people (June 2025 estimate). It is the gateway to Mount Aspiring National Park (Tititea in Māori, part of the Te Wāhipounamu World Heritage wilderness of the south-west) and the base for the Cardrona and Treble Cone ski fields — quieter than Queenstown, with the same mountains and lake. The willow standing in the lake shallows, 'That Wānaka Tree', is one of the most photographed trees in New Zealand, and the Roys Peak track looks over the whole lake and range. Ngāi Tahu Māori historically came here seasonally to hunt, fish and gather pounamu (greenstone).",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Wānaka (town in Queenstown-Lakes District, Otago, the council seat being Queenstown; ~13,200 June 2025, population tripled between 2000 and 2020; southern end of Lake Wānaka; gateway to Mount Aspiring National Park; That Wānaka Tree; Roys Peak; Treble Cone, Cardrona, Snow Farm; Warbirds over Wanaka biennial; Queenstown 120 km over the Crown Range; semi-continental climate)
    howItWorks:
      "Wānaka is a town of the Otago region of New Zealand, in the same Queenstown-Lakes District as Queenstown, whose council sits at Queenstown; it had about 13,200 people in June 2025, its population tripling between 2000 and 2020. The town lies at the southern end of Lake Wānaka as the gateway to Mount Aspiring National Park; the willow standing in the lake became famous through social media, and the Roys Peak track climbs from the lakeshore to the ridge; the ski fields of Treble Cone, Cardrona and Snow Farm open in winter, and the biennial Warbirds over Wanaka puts old aircraft in the sky. Its climate is semi-continental, unusual in New Zealand, with four distinct seasons. Queenstown lies about 120 km south over the Crown Range, and the airport takes only small aircraft. Newcomers most often go wrong by taking Wānaka for part of Queenstown, when they are two towns in one district with a mountain pass between them.",
    layout:
      "The town sits on Roys Bay at the southern end of the lake, with the lakefront path a few hundred metres from the centre; 'That Wānaka Tree' stands on the shore west of town. The Roys Peak trailhead is about 6 km along the western shore; the Matukituki valley of Mount Aspiring National Park (Rob Roy Glacier) is about 55 km north-west, the last stretch on gravel; Cardrona ski field is about 35 km south on the Crown Range road and Treble Cone about 20 km west; Lake Hāwea is about 15 km north-east. Queenstown lies south, about 70 km over the Crown Range.",
    gettingAround:
      "Wānaka Airport has no scheduled commercial flights; the nearest airport is Queenstown (ZQN), about 1 hour over the Crown Range road (chains may be required at the pass in winter) or about 1.5 hours via Cromwell, with airport shuttles and coaches. The town is walkable and cyclable; the park and ski fields need a car or the ski-field buses. The climate is temperate continental with warm dry summers and cold winters, with snow on the mountains.",
    culture:
      "English is universal. Photograph 'That Wānaka Tree' from the shore — don't wade out or climb it; the Roys Peak track crosses a private farm and closes each year from early October to mid-November for lambing. Keep to the tracks in the national park and carry out your rubbish. Ski fields charge entry and lift passes. The lake is cool for swimming even in summer. Tipping is optional.",
    seeAndDo:
      "The lakefront and 'That Wānaka Tree'; the Roys Peak track (5–6 hours return); the Rob Roy Glacier track in Mount Aspiring National Park; skiing at Cardrona and Treble Cone (June–September); Diamond Lake and Rocky Mountain; Lake Hāwea; Puzzling World and the town cinema; kayaking and skydiving over the lake.",
    whenAndTips:
      "December–March is best for hiking and the lake, April brings autumn colour, June–September is ski season. Start Roys Peak early and carry plenty of water; mountain weather changes fast. Check the Crown Range road in winter and carry chains. Plan two nights, linked with Queenstown.",
  },
};
