import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "italy-overview": {
    // identity sources: ISTAT《Bilancio demografico mensile gennaio-dicembre 2025》：2025-12-31 常住人口 58,942,828 人。https://www.istat.it/notizia/bilancio-demografico-mensile-gennaio-dicembre-2025/
    //   核实日 2026-09-07，来源级别 1
    identity:
      "Italy is a peninsular country in southern Europe, its mainland shaped like a boot reaching into the Mediterranean, plus the two large islands of Sicily and Sardinia, about 300,000 sq km with a resident population of about 58.9 million at the end of 2025 (ISTAT). The land is mostly mountains and hills: the young, high Alps in the north (bordering France, Switzerland and Austria), the Apennines running like a spine down the whole peninsula, large old hill country in the centre (Tuscany and others), the Po Valley in the north — the country's largest continuous plain — and an active volcanic belt in the south, Sicily and the Campi Flegrei area.",
    layout:
      "It helps to divide Italy into: the centre (Rome, Florence — the core of classical antiquity and the Renaissance), the north-west (Milan, Turin — the financial and industrial centre, near the Alps), the north-east (Venice, Bologna — the Venetian Lagoon and the Dolomites), the south (Naples, Bari — Mount Vesuvius and the olive groves of Puglia), Sicily (Palermo, Catania — Mount Etna, the highest active volcano in Europe outside the Caucasus), and Sardinia (Cagliari — one of the oldest landmasses in the Mediterranean).",
    gettingAround:
      "Italy's high-speed rail (Frecciarossa and others) is extensive — Rome–Milan, Rome–Florence, Rome–Naples and other main lines are convenient, often more comfortable than flying. Domestic flights are mainly for fast links between distant regions or to and from Sicily and Sardinia. Big cities have a metro; Venice's internal transport is on foot and by water bus (no cars). Drive on the right; historic centres often have Limited Traffic Zones (ZTL), and driving in without permission incurs a fine. Restaurant bills often include a bread/service charge (coperto/servizio); tipping is not required, though leaving small change is fine. Tap water is drinkable in most cities. Power is 230V with the European two-round-pin plug.",
    culture:
      "The official language is Italian; English is fairly common in tourist areas and among younger people. Mealtimes run later (lunch after 1 pm, dinner after 8 pm), and many small shops close for a long midday break (riposo). Italians value dressing appropriately and strong family bonds; visiting a church requires covered shoulders and knees. Restaurant bills often already include a bread/service charge, and tipping is not required.",
    seeAndDo:
      "History and art: the Colosseum and the Vatican in Rome, the Renaissance art of Florence, the lagoon city of Venice. Nature: the Dolomites in the Alps, the cliffside terraces of Cinque Terre, Mount Vesuvius and the Amalfi Coast on the Bay of Naples, Mount Etna in Sicily, the beaches of Sardinia. Active-volcano viewing (Etna, Stromboli) should follow safety assessments from INGV (Italy's national geophysics and volcanology institute) and use a licensed guide.",
    whenAndTips:
      "April–June and September–October are the most comfortable with relatively fewer people; July–August is peak season, hot in the south and on the islands, with crowded popular sights — also the Italian summer holiday, when many small shops close. Italy is in the Schengen area; most foreign visitors travel visa-free for short tourism or follow Schengen rules. Historic centres often have restricted traffic zones (ZTL) — check before driving in; book popular museums and monuments online ahead to skip long queues.",
  },

  rome: {
    // identity sources: 意大利统计局（ISTAT）发布 **comune（市镇）常住人口**（Bilancio demografico，月度滚动 + 年度定案，
    //   基准日多为 1 月 1 日，当年临时数约次年 3 月上线）。**`città metropolitana`（大都会市）是行政建制，
    //   不是统计口径** —— 仓库里已经踩过一次。「市区人口」在意大利同样不是 ISTAT 的称谓。2026-09-08 核。
    //   罗马 comune 常住人口 **约 2,745,062（2026-01-01，ISTAT）**（2025-01-01 为 2,746,898，略降）。
    //   原文 identity 写「市区人口约 280 万」、howItWorks 写「2025 年约 270 万」—— 口径名是编的、两段还打架，已一并对齐。
    identity:
      "Rome is the capital of Italy, with a comune population of about 2.745 million (1 January 2026, ISTAT), set on hills along the Tiber — one of the most important founding cities of Western civilisation, the centre of the ancient Roman Empire and later the centre of the Catholic Church (Vatican City sits entirely within the city of Rome as an independent enclave). The city has nearly three thousand years of continuous urban history, with ancient Roman, medieval, Renaissance and Baroque layers stacked on and below the surface.",
    // howItWorks sources: Wikipedia (2026-09): Rome (Roma Capitale 2010; 15 municipi; ~1,287 km²; ~2.7 million 2025; Metropolitan City 121 comuni ~4.2 million 2015; 22 rioni; GRA; 3 metro lines); Comune
    howItWorks:
      "Rome has been a commune of special status since 2010, 'Roma Capitale', governed by a mayor and council, with fifteen boroughs (municipi), each with an elected president and council. It covers about 1,287 km², the largest commune in Italy, with about 2.745 million people at 1 January 2026; since 2015 Rome and 120 neighbouring communes have formed the Metropolitan City of Rome Capital, which replaced the province, with about 4.2 million people. The 22 rioni inside the Aurelian Walls are the ancient city, the twentieth-century quarters lie beyond them, and EUR, planned in the 1930s, is the administrative and business district to the south; the GRA ring road is the edge of the city in local minds, though the commune extends far beyond it. Vatican City is an enclave inside the city. The Tiber runs through the middle. Three metro lines cover only part of it, and buses and cars carry most journeys. Addresses give street, number and postcode. Newcomers most often go wrong by taking the walled city for the whole, when Rome runs for tens of kilometres from the walls to its boundary through suburbs and countryside.",
    layout:
      "Rome's old city is built on seven hills on the east bank of the Tiber, with the ancient sites — the Roman Forum, the Colosseum, the Palatine Hill — concentrated at the centre. Vatican City is on the west bank, an independent enclave, with St Peter's Basilica the highest dome in the city. Trastevere, on the south-west bank, is an old district that keeps more of the everyday street life.",
    gettingAround:
      "Fiumicino Airport (FCO) is south-west of the city, with the Leonardo Express (about 32 minutes) to the central station; Ciampino Airport (CIA, mainly budget carriers) is south-east. The city has a metro (two main lines — not very dense because of archaeological constraints), buses and trams; the historic centre is largely pedestrian and dense with sites, good for walking. The climate is Mediterranean: hot, dry summers and mild, rainy winters.",
    culture:
      "Italian is the main language, with fairly common English in tourist areas. Romans live at a more relaxed pace than northern cities, and meals run later. Visiting St Peter's Basilica and the Sistine Chapel at the Vatican requires covered shoulders and knees — inappropriate dress will be turned away. Restaurant bills often include a bread/service charge; tipping is not required. Watch for pickpockets and unofficial 'guides' touting near the sights.",
    seeAndDo:
      "The Colosseum and the Roman Forum (book ahead; a combined ticket with the Palatine Hill is available); the Vatican Museums, the Sistine Chapel, St Peter's Basilica (book well ahead to skip long queues); the Pantheon; the Trevi Fountain and the Spanish Steps; Piazza Navona; nightlife and small restaurants in Trastevere; the Borghese Gallery (needs a timed booking).",
    whenAndTips:
      "April–June and September–October are the most comfortable; July–August is hot and the most crowded. Always book the Vatican Museums and the Colosseum online ahead — on-the-day queues often run several hours. Dress appropriately for churches (no bare shoulders or knees). Watch for pickpockets, and don't keep valuables in outer pockets. The historic centre has restricted traffic zones (ZTL) — drivers should check the boundaries.",
  },

  florence: {
    // howItWorks sources（2026-09-15 核实，update）: https://demo.istat.it/app/?i=POS · ISTAT · provincia 048 (Firenze) total = 988,494, 1 gennaio 2026 · 1级 · 2026-09-15 核；下一期约 2027-03
    // identity sources（2026-09-15 核实，update）: https://demo.istat.it/app/?i=POS · ISTAT population register (queried directly via its RPCCerca.php POST API) · comune 048017, 1 gennaio 2026 = 361,625 · 1级 · 2026-09-15 核；下一期约 2027-03
    // identity sources: 佛罗伦萨 comune（市镇本身）2024 年 361,705 人（ISTAT 口径，经 urbistat 转引，3 级，2026-09-08 核）
    //   https://ugeo.urbistat.com/adminstat/it/it/demografia/dati-sintesi/firenze/48017/4 。
    //   **意大利要分清三档**：comune（市镇本身）< città metropolitana（大都市市，**是行政建制不是统计口径**）
    //   < 都市连绵区。佛罗伦萨大都会市 41 个市镇约 99 万。
    //   **发布节奏**：ISTAT 人口按月滚动 + 年度定案，基准日多为 1 月 1 日，当年数约次年 3 月上线。
    identity:
      "Florence is in Tuscany in central Italy, on the Arno, with a comune population of about 362,000 (January 2026, ISTAT) — the birthplace of the Renaissance, where 15th-century patronage by the Medici family let masters such as Leonardo, Michelangelo and Botticelli leave a huge body of enduring work, and the whole old town is a World Heritage Site.",
    // howItWorks sources: Wikipedia (2026-09): Florence (5 quartieri; 102 km²; ~362,000; Metropolitan City 41 comuni ~988,000; UNESCO 1982; ZTL; tram); Comune
    howItWorks:
      "Florence is the capital of Tuscany, governed by a mayor and council, with five boroughs (quartieri); the commune covers about 102 km² with about 362,000 people (January 2026), while the Metropolitan City of Florence, which replaced the province in 2015, has 41 communes and about 988,000 people (January 2026), with Scandicci and Fiesole as communes of their own. The Arno divides the city: the north bank holds the historic core inscribed as World Heritage in 1982, with the cathedral, the Palazzo Vecchio and the Uffizi; the south bank, the Oltrarno, is the quarter of artisans and residents, with the Pitti Palace. The old town is a restricted traffic zone (ZTL) closed to vehicles without a permit, a rule residents and visitors alike must remember. Trams run to Scandicci and the airport, and the old town is walked. Addresses give street, number and postcode, and the old town has two numbering series, red for shops and black for homes. Newcomers most often go wrong by taking the old town for the whole city, when most residents live in the quarters beyond the old walls and in the neighbouring communes.",
    layout:
      "Florence's old town is small, and the main sights are all walkable: the red dome of the Cathedral (Santa Maria del Fiore) is the city's landmark; the Ponte Vecchio spans the Arno, still lined with goldsmiths' shops; the Uffizi Gallery and the Piazza della Signoria are just south of the centre. Piazzale Michelangelo, across the river, is the best viewpoint over the whole city.",
    gettingAround:
      "Florence Airport (FLR) is very close to the city, with a tram about 20 minutes to the central station. High-speed rail from Rome is about 1.5 hours, from Milan about 1.7 hours — also very convenient. The old town is entirely walkable, one of the best Italian cities to explore on foot. The climate is temperate, hot summers and mild winters, with a bigger day–night range than coastal cities.",
    culture:
      "Italian is the main language, with widespread English in tourist areas. Florentines are intensely proud of their artistic heritage and keep Tuscan food traditions alive (bistecca alla fiorentina, Tuscan olive oil). The historic centre has a restricted traffic zone (ZTL) — drive in with care. Restaurant bills often include a bread/service charge.",
    seeAndDo:
      "The Cathedral (climb the dome, booking required); the Uffizi Gallery (the core Renaissance painting collection, book ahead); the Accademia Gallery (Michelangelo's original David); the Ponte Vecchio and the Arno riverside; sunset from Piazzale Michelangelo; a day trip south into the Tuscan hills (Siena, San Gimignano and other towns, mostly needing a car or a tour).",
    whenAndTips:
      "April–June and September–October are the most comfortable; July–August is hot with the most visitors. Always book the Uffizi and the Accademia (David) online ahead — on-the-day queues often exceed two hours in peak season. Dome-climbing slots are limited and need a specific time booked ahead. Driving the Tuscan countryside is very scenic but the roads have many bends — mind conditions.",
  },

  milan: {
    // identity sources: 米兰大都会市（Città Metropolitana di Milano，2015 年取代省而设，辖 133 个市镇）
    //   **3,246,455 人（2025-01-01）**，另有 2026-05-31 的月度更新页显示 3,258,021 ——
    //   大都会市自己的统计办公室（2 级，2026-09-08 核）。米兰 comune 本身约 140 万。
    //   **「都会区」不是 ISTAT 的称谓** —— 仓库里都灵/那不勒斯/巴里已经在用「大都会市」这个正确说法，
    //   米兰与博洛尼亚是仅剩的两处旧措辞，本轮统一。
    identity:
      "Milan is on the Po Valley in north-western Italy, where the Metropolitan City of Milan (133 communes) has about 3.25 million people (1 January 2025) — Italy's financial, fashion and design centre, host of international fashion weeks and furniture fairs. The city has a long history (Leonardo's Last Supper is painted on the refectory wall of a monastery here), but overall feels modern and among the most commercially oriented of Italian cities.",
    // howItWorks sources: 米兰有两套并存的官方数：市政府户籍登记（anagrafe）2025-12-31 = 1,399,079
    //   （2024-12-31 = 1,407,044）；ISTAT 官方估计约 1,362,863。
    //   https://www.milanocittastato.it/news/abitanti-a-milano-quanti-siamo-nel-2026/（3 级，转引市政府 anagrafe，2026-09-08 核）。
    //   **两套差约 4 万，只写一个就会被另一个来源打脸** —— 与保定「含/不含定州」、
    //   韩国「住民登录 vs 统计厅推算」、智利「普查计数 vs 调节后」同一类处理：两个都给。
    //   米兰大都会市（Città Metropolitana，**行政建制不是统计口径**）133 个市镇约 325 万。
    //   **下一轮**应直接去 demo.istat.it 或 comune.milano.it 取一手页面，把基准日钉死。
    howItWorks:
      "Milan is governed by a mayor and council, with nine boroughs (municipi), each with its own council; the commune covers about 181 km² with about 1.40 million people on the city's own residence register (end of 2025) or about 1.36 million on the national statistics office's estimate, while the Metropolitan City of Milan, which replaced the province in 2015, has 133 communes and about 3.25 million people, and the wider urban region exceeds 6 million, with Monza as another city with a government of its own. The city grew outward in rings: the line of the medieval canals innermost, then the line of the Spanish walls, then the ring boulevards, with the Duomo at the centre; the new towers at Porta Nuova to the north and CityLife to the west stand on old railway yards and fairgrounds. Italy's stock exchange, fashion and design industries are concentrated here. Five metro lines run by ATM cover the city and inner suburbs. Addresses give street, number and postcode. Newcomers most often go wrong by taking Milan for a city of the cathedral and fashion, when it is Italy's economic centre, whose daily weight lies between the office towers and the suburbs.",
    layout:
      "Milan Cathedral (Gothic, a forest of spires) is the central landmark, and the cathedral square connects to the Galleria Vittorio Emanuele II — a 19th-century glass-roofed shopping arcade, one of Milan's most elegant public spaces. La Scala opera house and the Brera art gallery are just north of the cathedral. Around the city is the flat farmland of the Po Valley.",
    gettingAround:
      "Milan Linate Airport (LIN) is close to the city (about 8 km, with metro and bus links), while Malpensa (MXP, the main international hub) is about 50 km out, with an airport express. High-speed rail from Rome is about 3 hours, from Venice about 2.5 hours. The city has a metro (four lines, one of the densest networks in Italy) and trams. The climate is temperate continental: muggy summers and cold, foggy winters, with the flat Po Valley trapping poor air circulation and haze.",
    culture:
      "Italian is the main language; because of business and fashion, English is relatively common. Milanese life moves faster than other Italian cities, with careful dress and a strong sense of being the fashion capital. Restaurant bills often include a bread/service charge. The historic centre has a congestion charge zone (Area C) — driving in requires payment or a permit.",
    seeAndDo:
      "Milan Cathedral (climb to the roof for the city view); the Galleria Vittorio Emanuele II; La Scala opera house; the Brera art gallery; Santa Maria delle Grazie for Leonardo's Last Supper (book well ahead — one of the hardest tickets in Milan, extremely limited slots); Sforza Castle; shopping in the fashion quarter (the Quadrilatero della Moda).",
    whenAndTips:
      "April–June and September–October are the most comfortable; summer is muggy and winter is foggy and cold. The Last Supper needs booking weeks or even months ahead online — one of Milan's most sought-after tickets. Milan is often a hub for day trips to Lake Como, Lake Garda or the Alps. The historic centre has traffic restrictions — check before driving in.",
  },

  turin: {
    // identity sources（2026-09-15 核实，update）: https://demo.istat.it/app/?i=POS · ISTAT · provincia 001 (Torino) total = 2,204,779, 1 gennaio 2026 · 1级 · 2026-09-15 核；下一期约 2027-03
    // identity sources: 都灵 comune 2026 年约 86 万；**都灵大都会市（2015 年取代省而设，辖 312 个市镇）约 220 万** ——
    //   与同条目 howItWorks 已有的核实一致，2026-09-08 复核。
    //   **「都会区」不是 ISTAT 的称谓**，identity 原本用它配了一个对不上的 180 万；
    //   **同一条口径问题在一个条目里往往出现两次，修的时候要把整个条目搜一遍。**
    identity:
      "Turin is in the upper Po valley in north-western Italy, where the Metropolitan City of Turin (312 communes) has about 2.2 million people (January 2026, ISTAT) — the birthplace of Italian unification and the country's first capital (1861–1865), and the home of Fiat's car industry. The city has regular Baroque streets and extensive arcades, hosted the 2006 Winter Olympics, and backs onto the Alps — on a clear day you can see snow mountains from the centre.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Turin (comune 130 km²; ~855,700 2026; 8 circoscrizioni; Metropolitan City of Turin ~2.2 million; Piedmont capital; Po; Baroque grid; Mole Antonelliana 167 m; Savoy residences UNESCO 1997; Fiat/Lingotto; metro 1 line; 2006 Olympics; first capital of Italy 1861–65)
    howItWorks:
      "Turin is the capital of Piedmont, governed by a mayor and council with eight boroughs (circoscrizioni); the commune covers about 130 km² with about 856,000 people in 2026, while the Metropolitan City of Turin, which replaced the province in 2015, has 312 communes and about 2.2 million people. From 1861 to 1865 it was the first capital of the Kingdom of Italy, and the Baroque grid and palaces left by the House of Savoy were inscribed as World Heritage in 1997, with Piazza Castello as the point of reference and the Mole Antonelliana rising 167 m; the Po runs along the east of the city and the Alps stand on the skyline 50 km west; the Lingotto works and the Mirafiori plant of Fiat lie to the south as the birthplace of the Italian car industry, one metro line serves the city, and the Winter Olympics were held here in 2006. Newcomers most often go wrong by taking Turin for an industrial city, when its centre is a royal capital with more than ten kilometres of arcaded streets.",
    layout:
      "Turin spreads across the plain on the west bank of the Po, laid out on a regular grid with long arcades linking the buildings (you can shop in the rain without an umbrella). Piazza Castello is the heart of the centre, with the Royal Palace and Palazzo Madama. Not far west of the city are the foothills of the Alps, and the Basilica of Superga stands on a hill to the east, overlooking the city and the distant snow peaks.",
    gettingAround:
      "Turin Airport (TRN) is north of the city, with metro and train links. High-speed rail from Milan is about 1 hour, from Rome about 4 hours. The city has a metro (fully automatic, Italy's first such system) and trams; the historic centre is walkable. The climate is temperate continental, hot summers and cold winters, with occasional fog and a bit drier than Milan.",
    culture:
      "Italian is the main language; Turin people are known for being precise and reserved (closer in temperament to Switzerland or France than southern Italy, with historical ties to the nearby French border). It is one of the birthplaces of Italian chocolate (the hazelnut Gianduiotto), with a deep coffee culture. Restaurant bills often include a bread/service charge.",
    seeAndDo:
      "Piazza Castello, the Royal Palace and Palazzo Madama; the Egyptian Museum (Turin's Egyptian collection is one of the most important outside Cairo); the National Cinema Museum (housed in the landmark spire of the Mole Antonelliana, with a lift to the top); the Basilica of Superga for the city and Alpine panorama; 1–2 hours from Turin into the Alps for skiing or hiking.",
    whenAndTips:
      "April–June and September–October are the most comfortable. Winter fog occasionally blocks the Alpine view — choose a clear day for Superga. The Egyptian Museum and the Cinema Museum both deserve half a day or more. Turin is a convenient base for the western Alps, including the area around Gran Paradiso National Park on the Italy–France border.",
  },

  venice: {
    // identity sources: 威尼斯市统计处（Serie storiche，2026-03-06 更新）：市镇（comune，含梅斯特雷/马尔盖拉）
    //   2025-12-31 为 251,294；**岛上历史城区 47,625**（比上一年少 864，-1.7%），2025 年已跌破 5 万。
    //   https://www.comune.venezia.it/it/content/serie-storiche（2 级，2026-09-08 核）。
    //   **威尼斯必须分清两档**：comune 25 万含陆地上的梅斯特雷，水城本身（centro storico）不到 5 万 ——
    //   差五倍，写「威尼斯人口」时不写明哪一档就是错的。历史城区人口是**长期下降**的。
    identity:
      "Venice sits in a lagoon on the Adriatic coast of north-eastern Italy, made up of over a hundred small islands linked by more than 400 bridges, with a historic-centre population of about 47,600 (end of 2025, now below 50,000 and still declining, and the outflow of residents is a long-running local issue). It was one of the great medieval Mediterranean trading powers, and its canals and car-free layout are its most distinctive feature; the whole Venetian Lagoon is a World Heritage Site.",
    // howItWorks sources: Wikipedia (2026-09): Venice (comune = historic city + lagoon + Mestre/Marghera merged 1926; 6 municipalità; ~250,000 2024, historic centre ~48,000; 6 sestieri numbering; ACTV; Ponte della Libertà 1933; UNESCO 1987); Comune
    howItWorks:
      "The Venice people speak of is, administratively, a commune far larger than the water city: it takes in the historic centre in the lagoon, islands such as Murano and Burano, and the mainland districts of Mestre and Marghera merged in 1926, divided into six boroughs (municipalità) and governed by a mayor and council. The commune had about 251,000 people at the end of 2025, of whom only about 47,600 live in the historic centre, a number falling every year; most residents live on the mainland and cross daily by the Ponte della Libertà of 1933, with Piazzale Roma as the last point reachable by car or bus. The historic centre is divided into six sestieri, and house numbers run continuously within each sestiere rather than by street, so one number may be several alleys from the next. The vaporetto water buses run by ACTV are the only public transport on the islands, and the airport is on the mainland. Venice and its lagoon were inscribed as World Heritage in 1987, and since 2024 an access fee has been trialled for day visitors. Newcomers most often go wrong by taking Venice for the water city alone, when its town hall, most of its residents and its airport are on the mainland.",
    layout:
      "Venice's historic centre is built entirely on the islands of the lagoon, with the Grand Canal winding through the city in a reverse-S and serving as the main water thoroughfare. Piazza San Marco is the heart of the city, next to St Mark's Basilica and the Doge's Palace. There are no roads for cars — transport is entirely on foot through narrow lanes, or by water bus (vaporetto) and gondola. The surrounding lagoon has the colourful fishing village of Burano and the glassmaking island of Murano.",
    gettingAround:
      "Venice Marco Polo Airport (VCE) is on the mainland side of the lagoon's north shore, with an airport bus or water bus (about an hour) into the city. High-speed rail from Milan is about 2.5 hours, from Rome about 3.5 hours, and the station (Santa Lucia) is right on the canal. Getting around is entirely on foot and by vaporetto — no cars (and no bike lanes). The climate is Mediterranean/temperate transitional, with an 'acqua alta' (high water) phenomenon in autumn and winter that floods some low squares.",
    culture:
      "Italian is the main language; with so many tourists, English is widespread in tourist areas, and other European languages are often heard too. The resident population keeps falling, and over-tourism is a long-running local debate — some periods charge day-trippers an entry fee (check the latest official rules). Restaurant bills often include a bread/service charge, and canal-side restaurants are generally pricier.",
    seeAndDo:
      "Piazza San Marco, St Mark's Basilica, the Doge's Palace; the Rialto Bridge and the Grand Canal; a gondola or vaporetto ride on the canals; the Accademia Gallery; Burano (the colourful fishing village) and Murano (glassmaking); the Bridge of Sighs; the masked parades of Carnival (February, dates vary by year).",
    whenAndTips:
      "April–June and September–October are the most comfortable and relatively less crowded; July–August is muggy with the most visitors; November to January is the high season for acqua alta — check the tide forecast before heading out, and elevated walkways go up in some areas. Day-trippers may need to pay an entry fee (check the latest official policy). Canal-side restaurants are pricier — a few streets inland usually offers better value.",
  },

  bologna: {
    // identity sources: 博洛尼亚大都会市（Città Metropolitana di Bologna，55 个市镇）**1,024,290 人（2026-01-01 估计，ISTAT）**；
    //   博洛尼亚 comune 本身约 391,473（2026-01-01）——3 级转引 ISTAT，2026-09-08 核。
    //   数字与同条目 howItWorks 一致，**本轮只是把「都会区」统一改成「大都会市（Città Metropolitana）」**，
    //   并补上此前缺的 identity 来源留痕。
    identity:
      "Bologna is on the edge of the Po Valley at the northern foot of the Apennines in north-eastern Italy, where the Metropolitan City of Bologna (55 communes) has about 1.02 million people (1 January 2026 estimate, ISTAT) — the capital of Emilia-Romagna. It is home to the world's oldest continuously operating university (the University of Bologna, founded in 1088), and is widely regarded as one of Italy's gastronomic capitals — Bolognese ragù, Parmesan cheese and Parma ham all come from this area.",
    // howItWorks sources: **意大利的官方人口口径**（ISTAT，2026-09-09 复核）：`comune`（市镇常住人口）是唯一严格意义上的统计口径，逐月滚动、按 1 月 1 日定案，当年临时数约次年 3 月上线；`città metropolitana`（大都会市）**是 2015 年起取代省的行政建制、不是统计口径**，数字为辖内各 comune 相加，会随行政区划改革变动。「市区人口」「都会区」在意大利官方统计里都不存在，已由 `check:claims` 的 `C6k` 拦住。
    //   独立复核：comune 391,473、大都会市（55 市镇）1,024,290，均为 2026-01-01（ISTAT）。数字准确，**缺的是统计时点**。 3 级转引 ISTAT，2026-09-09 独立复核（本批意大利 6 城此前已有 2026-09-08 的核实痕迹，本轮是**复核**，全部与 ISTAT 对上）。
    //   https://www.istat.it/
    howItWorks:
      "Bologna is the capital of Emilia-Romagna, governed by a mayor and council with six boroughs (quartieri); the commune covers about 141 km² with about 391,000 people at 1 January 2026, while the Metropolitan City of Bologna, which replaced the province, has 55 communes and about 1.02 million. The porticoes are the city's form: some 38 km of continuous arcades in the centre were inscribed as World Heritage in 2021, letting one cross half the city in the rain without an umbrella, the Two Towers lean in the middle of the old town and Piazza Maggiore is the point of reference; the University of Bologna, founded in 1088, is the oldest in continuous operation in the world, and its students keep the city younger than its surroundings; Bologna Centrale is the crossing of Italy's north-south and east-west high-speed lines, a monorail runs from Marconi airport to the station, and ragù and ham are the daily fare of the district. Newcomers most often go wrong by taking Bologna for a transfer station, when it is Italy's food capital and its oldest university town.",
    layout:
      "Bologna's old town is marked by two leaning towers (the Asinelli and the Garisenda), and its covered arcades — about 62 km in total (about 42 km within the historic centre) — are its most distinctive streetscape, letting you walk almost the whole city without an umbrella in the rain; in 2021, 12 of the most representative stretches were inscribed as a World Heritage Site. Piazza Maggiore is the heart of the centre, with the Basilica of San Petronio on its south side. Because of its extensive red-brick buildings, the old town is nicknamed 'the Red City'.",
    gettingAround:
      "Bologna Airport (BLQ) is north-west of the city, with a monorail (the Marconi Express) about 7 minutes to the central station. Bologna is a key hub of the Italian high-speed rail network — about 1.5–2 hours from Rome, about 1 hour from Milan, about 35 minutes from Florence — and is often used as a stopover. The city has buses, and walking the arcaded old town is pleasant. The climate is temperate continental, muggy summers and cold, foggy winters.",
    culture:
      "Italian is the main language; the university-town character brings a strong young and student atmosphere, with relatively common English. Bologna people are intensely proud of their food tradition (the authentic local sauce is called ragù, usually served with tagliatelle rather than spaghetti). Restaurant bills often include a bread/service charge.",
    seeAndDo:
      "Climbing the Asinelli Tower for the city view (several hundred steps); walking the arcades; Piazza Maggiore and the Basilica of San Petronio; the old campus and anatomical theatre of the University of Bologna; food markets and delicatessens for local ham and cheese; as a rail hub, easy day trips to Florence or Ravenna (Byzantine mosaics).",
    whenAndTips:
      "April–June and September–October are the most comfortable. Bologna has far fewer visitors than Florence or Venice and is relatively affordable, a good base for experiencing 'everyday Italy'. As a high-speed rail hub, it works well as a base for several day trips.",
  },

  naples: {
    // howItWorks sources（2026-09-15 核实，update）: https://demo.istat.it/app/?i=POS · ISTAT · comune 063049 (Napoli) = 905,050, 1 gennaio 2026 · 1级 · 2026-09-15 核；下一期约 2027-03
    // identity sources: **意大利的官方人口口径**（ISTAT，2026-09-09 复核）：`comune`（市镇常住人口）是唯一严格意义上的统计口径，逐月滚动、按 1 月 1 日定案，当年临时数约次年 3 月上线；`città metropolitana`（大都会市）**是 2015 年起取代省的行政建制、不是统计口径**，数字为辖内各 comune 相加，会随行政区划改革变动。「市区人口」「都会区」在意大利官方统计里都不存在，已由 `check:claims` 的 `C6k` 拦住。
    //   独立复核：大都会市（92 市镇）约 295.1 万、comune 本身 905,050，均为 2026-01-01（ISTAT）。数字准确，缺年份。 3 级转引 ISTAT，2026-09-09 独立复核（本批意大利 6 城此前已有 2026-09-08 的核实痕迹，本轮是**复核**，全部与 ISTAT 对上）。
    //   https://www.istat.it/
    identity:
      "Naples is on the Bay of Naples in southern Italy, where the Metropolitan City of Naples (92 communes) has about 2.95 million people (2026) — the largest city in southern Italy and one of the oldest cities in the Mediterranean (founded by Greeks in the 6th century BC). It is the birthplace of the Margherita pizza, and the city's character is loud, dense and full of everyday street life, in sharp contrast to the order of northern cities. Mount Vesuvius sits across the bay, and its eruption in 79 AD buried the city of Pompeii.",
    // howItWorks sources: Wikipedia (2026-09): Naples (10 municipalità; ~119 km²; ~905,000 2026; Metropolitan City 92 comuni ~2.95 million; centro storico UNESCO 1995; funiculars; metro 1/2/6); Comune
    howItWorks:
      "Naples is the capital of Campania, governed by a mayor and council, with ten boroughs (municipalità); the commune covers about 119 km² with about 905,000 people (January 2026), Italy's third city, while the Metropolitan City of Naples, which replaced the province in 2015, has 92 communes and about 2.95 million people, among the densest areas in Europe. The old town follows the Greek and Roman grid, split down the middle by the straight street of Spaccanapoli, and was inscribed as World Heritage in 1995; the Quartieri Spagnoli lie on its western flank, Vomero on the hill above, Chiaia and Posillipo are the wealthy quarters along the sea, and the Centro Direzionale is the tower cluster of the 1980s. Funiculars join the hill to the lower city, and metro lines 1, 2 and 6 serve the city. Vesuvius stands to the south-east and the Campi Flegrei volcanic field to the west, with the city between them. Addresses give street, number and postcode. Newcomers most often go wrong by taking the din of the old town for the whole city, when the Naples of the hill and the seafront keeps another order.",
    layout:
      "Naples's old town is built on the hills around the bay, with narrow, dense streets, and the historic centre is a World Heritage Site. Via San Biagio dei Librai (Spaccanapoli) is the old town's main axis, lined with Baroque churches and street life. South-east along the bay, the full cone of Mount Vesuvius is visible, and Capri lies out in the bay. To the west, the Campi Flegrei is an active volcanic-geothermal area.",
    gettingAround:
      "Naples Airport (NAP) is very close to the city, with an airport bus. High-speed rail from Rome is about 1–1.5 hours. The city has a metro (some stations decorated with contemporary art, sights in themselves), buses and funiculars (linking hillside districts); the old town is dense and walkable but crowded and noisy, so watch your belongings. Regional trains (the Circumvesuviana) run to Pompeii and Herculaneum. The climate is Mediterranean, hot summers and mild winters, with a mild bay microclimate.",
    culture:
      "Italian is the main language, with a distinct local Neapolitan dialect. Naples people are known for warmth, directness and a strong street life, and traffic and public order are looser than in the north. Authentic Neapolitan pizza has an official certification standard (AVPN), which locals take seriously. Restaurant bills often include a bread/service charge. Pickpocketing is more common near sights and stations — keep a close eye on belongings.",
    seeAndDo:
      "The old town's Spaccanapoli and its many Baroque churches; the National Archaeological Museum of Naples (the core collection of finds from Pompeii); the metro art stations; the Circumvesuviana train to the ruins of Pompeii (a guide or booked tour helps for historical context); hiking to the summit of Vesuvius (official trails, with visitor limits); a boat to Capri or the Amalfi Coast (tickets tight in peak season).",
    whenAndTips:
      "April–June and September–October are the most comfortable; July–August is hot. Pompeii is very large — allow half a day or more, with water and sun protection. The Vesuvius trail has official visitor limits and opening hours — check the website before going. Naples needs more care about safety than most Italian cities — keep valuables out of sight and avoid quiet back streets at night.",
  },

  bari: {
    // identity sources: 意大利统计局（ISTAT）发布 **comune（市镇）常住人口**（Bilancio demografico，月度滚动 + 年度定案，
    //   基准日多为 1 月 1 日，当年临时数约次年 3 月上线）。**`città metropolitana`（大都会市）是行政建制，
    //   不是统计口径** —— 仓库里已经踩过一次。「市区人口」在意大利同样不是 ISTAT 的称谓。2026-09-08 核。
    //   巴里 comune **约 316,248**（2026-01-01）；**Città Metropolitana di Bari 41 个市镇、约 1,218,073**（3 级转引 ISTAT，2026-09-08 核）。
    //   howItWorks 段本来就是对的，identity 的「都会区约 75 万」哪一档都不是，已对齐。
    identity:
      "Bari is on the Adriatic coast of Puglia in south-eastern Italy, with a metropolitan city (città metropolitana) of about 1.22 million (2026, ISTAT) — the capital of Puglia and an important ferry port to Greece, Albania and other Balkan destinations. The city is known for holding the relics of St Nicholas (one basis for the Santa Claus figure), and its old town is a well-preserved maze of white limestone lanes.",
    // howItWorks sources: **意大利的官方人口口径**（ISTAT，2026-09-09 复核）：`comune`（市镇常住人口）是唯一严格意义上的统计口径，逐月滚动、按 1 月 1 日定案，当年临时数约次年 3 月上线；`città metropolitana`（大都会市）**是 2015 年起取代省的行政建制、不是统计口径**，数字为辖内各 comune 相加，会随行政区划改革变动。「市区人口」「都会区」在意大利官方统计里都不存在，已由 `check:claims` 的 `C6k` 拦住。
    //   独立复核：comune 316,248、大都会市（41 市镇）1,218,073，均为 2026-01-01（ISTAT）。数字准确，缺时点。 3 级转引 ISTAT，2026-09-09 独立复核（本批意大利 6 城此前已有 2026-09-08 的核实痕迹，本轮是**复核**，全部与 ISTAT 对上）。
    //   https://www.istat.it/
    howItWorks:
      "Bari is the capital of Apulia, governed by a mayor and council; the commune covers about 117 km² with about 316,000 people at 1 January 2026, while the Metropolitan City of Bari, which replaced the province, has 41 communes and about 1.22 million. The city is in two parts: Bari Vecchia, the old town on the peninsula running into the Adriatic, holds the Basilica of San Nicola and the Norman-Swabian castle, the relics of St Nicholas were brought here from Myra in 1087, and the lanes where women roll orecchiette are its daily life; south of the old town lies the Murat quarter of the nineteenth century, a grid of streets and shopping avenues, with the promenade running along the shore; the port has ferries to Greece, Albania and Montenegro, the airport lies west of town and the Fiera del Levante is held each autumn. Newcomers most often go wrong by taking Bari for a staging post for Alberobello or Matera, when it is among the most important economic centres of mainland southern Italy.",
    layout:
      "Old Bari (Bari Vecchia) is built on a small peninsula reaching into the sea, its streets narrow and maze-like, with the Basilica of San Nicola and the cathedral inside. The new town is a regular grid, built to 19th-century planning ideas, a sharp contrast to the old town. Inland from the city are Puglia's typical olive-grove plains, with the limestone Alta Murgia plateau to the southwest and the Gargano Promontory to the north.",
    gettingAround:
      "Bari Airport (BRI) is about 8 km from the city, with train and airport bus links. High-speed rail from Rome is about 4 hours (many people fly instead). The city has buses and a seafront promenade; the old town is walkable. Ferries run to Greece (Patras, Corfu and others) and Albania. The climate is Mediterranean, hot and dry in summer, mild and rainy in winter, drier than northern Italian cities.",
    culture:
      "Italian is the main language, with distinctive Puglian dialect words. Bari people are proud of their local food (orecchiette, ear-shaped hand-made pasta) and the Feast of St Nicholas (May, with a seaborne procession). Restaurant bills often include a bread/service charge.",
    seeAndDo:
      "The old town's maze of lanes and the Basilica of San Nicola; the cathedral; the everyday street scene of residents hand-making orecchiette outdoors; the seafront promenade; an hour southwest to the limestone Alta Murgia plateau (prehistoric sites and karst landforms), or an hour southeast to 'the town of stone houses', Alberobello (a World Heritage Site of conical-roofed trulli); farther north, the coast and forests of the Gargano Promontory.",
    whenAndTips:
      "April–June and September–October are the most comfortable; July–August is hot but also the season for Puglia's beaches. The old town's lanes are maze-like — explore in daylight first to get your bearings. Day trips to Alberobello and the Alta Murgia suit a car or a tour, as public transport is limited.",
  },

  palermo: {
    // identity sources: **意大利的官方人口口径**（ISTAT，2026-09-09 复核）：`comune`（市镇常住人口）是唯一严格意义上的统计口径，逐月滚动、按 1 月 1 日定案，当年临时数约次年 3 月上线；`città metropolitana`（大都会市）**是 2015 年起取代省的行政建制、不是统计口径**，数字为辖内各 comune 相加，会随行政区划改革变动。「市区人口」「都会区」在意大利官方统计里都不存在，已由 `check:claims` 的 `C6k` 拦住。
    //   独立复核：comune 626,273、大都会市（82 市镇）约 120 万，均为 2026 年（ISTAT）。数字准确，缺年份。 3 级转引 ISTAT，2026-09-09 独立复核（本批意大利 6 城此前已有 2026-09-08 的核实痕迹，本轮是**复核**，全部与 ISTAT 对上）。
    //   https://www.istat.it/
    identity:
      "Palermo is the capital of Sicily, on a bay on the island's north-west coast, where the Metropolitan City of Palermo (82 communes) has about 1.2 million people (2026). It was ruled in turn by Phoenicians, Greeks, Romans, Arabs and Normans, and its architecture and culture blend several Mediterranean traditions — the Norman-Arab palaces and churches are Palermo's most distinctive landmark, listed as a World Heritage Site.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Palermo (comune 161 km²; 626,273 2026; 8 circoscrizioni; Metropolitan City of Palermo ~1.2 million; capital of the autonomous Sicilian Region with its own parliament; Arab-Norman UNESCO 2015 with Monreale and Cefalù in other comuni; Quattro Canti; Ballarò/Vucciria/Capo markets; Mondello in comune; Punta Raisi airport ~35 km)
    howItWorks:
      "Palermo is the capital of Sicily, an autonomous region of Italy with a parliament and legislative powers of its own; the commune is governed by a mayor and council with eight boroughs, covering about 161 km² with about 626,000 people in 2026, and the metropolitan city has 82 communes and about 1.2 million. The city lies in a mountain-ringed basin called the Conca d'Oro, the Quattro Canti marks the crossing of the old town's two main streets, and the markets of Ballarò, Vucciria and Capo still cry their wares in the Arab manner; the 'Arab-Norman Palermo' inscribed as World Heritage in 2015 includes the Palatine Chapel in the royal palace, but the cathedral of Monreale in the same listing stands 8 km away in another commune and Cefalù further along the coast; Mondello beach lies at the northern edge of the commune and the airport 35 km west. Newcomers most often go wrong by expecting Monreale inside Palermo, when it is another commune up the hill.",
    layout:
      "The core of Palermo's old town is the Quattro Canti crossroads, where four main streets meet, dividing four historic quarters. The Norman Palace and the Palatine Chapel (with Byzantine mosaics) are among the city's key monuments. Palermo Cathedral blends architectural styles from several eras. The city backs onto Monte Pellegrino and faces an open bay.",
    gettingAround:
      "Palermo Airport (PMO) is about 35 km from the city, with airport bus and train links. High-speed/long-distance rail to Naples or Rome takes a long time (most people fly or take the ferry). The city has buses and trams; the old town is walkable but narrow and crowded. The climate is Mediterranean, hot and dry in summer, mild and rainy in winter, one of the warmer cities in Italy.",
    culture:
      "Italian is the main language, with distinctive Sicilian dialect words and accent. Palermo's street markets (such as the Ballarò market) are central to local life, intense in sound, smell and colour. Restaurant bills often include a bread/service charge, and street food (fried chickpea fritters, panelle; fried rice balls, arancina) is good value.",
    seeAndDo:
      "The Norman Palace and the Palatine Chapel; Palermo Cathedral; the Quattro Canti and the Teatro Massimo; the Ballarò and Vucciria markets; Monreale Cathedral (out of town, mosaics on a par with Ravenna, worth the trip); along the coast to Mondello for the Norman-era Church of Santa Maria dell'Ammiraglio.",
    whenAndTips:
      "April–June and September–October are the most comfortable; July–August is hot. The old town's narrow streets have somewhat chaotic traffic — watch for cars when crossing. Street markets close relatively early in the evening — go in daylight. Monreale needs a dedicated bus trip or a hired car — allow half a day.",
  },

  catania: {
    // identity sources: 意大利统计局（ISTAT）发布 **comune（市镇）常住人口**（Bilancio demografico，月度滚动 + 年度定案，
    //   基准日多为 1 月 1 日，当年临时数约次年 3 月上线）。**`città metropolitana`（大都会市）是行政建制，
    //   不是统计口径** —— 仓库里已经踩过一次。「市区人口」在意大利同样不是 ISTAT 的称谓。2026-09-08 核。
    //   卡塔尼亚 comune **约 296,984**（2026-01-01）；**Città Metropolitana di Catania 58 个市镇、约 1,067,550**（3 级转引 ISTAT，2026-09-08 核）。
    //   「西西里第二大城市」按 comune 人口成立（巴勒莫 comune 约 62.6 万）。
    identity:
      "Catania is on the east coast of Sicily, right beside Mount Etna, the highest active volcano in Europe outside the Caucasus, with a metropolitan city (città metropolitana) of about 1.07 million (2026, ISTAT). The city has repeatedly been destroyed and rebuilt by Etna's lava flows and earthquakes; the current Baroque old town was built after the great earthquake of 1693, largely using Etna's black volcanic stone, earning it the nickname 'the Black Baroque city' — a World Heritage Site.",
    // howItWorks sources: **意大利的官方人口口径**（ISTAT，2026-09-09 复核）：`comune`（市镇常住人口）是唯一严格意义上的统计口径，逐月滚动、按 1 月 1 日定案，当年临时数约次年 3 月上线；`città metropolitana`（大都会市）**是 2015 年起取代省的行政建制、不是统计口径**，数字为辖内各 comune 相加，会随行政区划改革变动。「市区人口」「都会区」在意大利官方统计里都不存在，已由 `check:claims` 的 `C6k` 拦住。
    //   独立复核：comune 296,984、大都会市（58 市镇）1,067,550，均为 2026-01-01（ISTAT）。数字准确，缺时点。 3 级转引 ISTAT，2026-09-09 独立复核（本批意大利 6 城此前已有 2026-09-08 的核实痕迹，本轮是**复核**，全部与 ISTAT 对上）。
    //   https://www.istat.it/
    howItWorks:
      "Catania is the second city of Sicily, governed by a mayor and council, the commune covering about 183 km² with about 297,000 people at 1 January 2026 and the metropolitan city 58 communes with about 1.07 million; Sicily is an autonomous region with a parliament of its own. The city stands at the south-eastern foot of Etna, its territory reaching up the volcano's slopes, and after the lava of 1669 and the earthquake of 1693 destroyed the old town it was rebuilt in black volcanic stone and white limestone, that Baroque inscribed as World Heritage in 2002 among the Late Baroque Towns of the Val di Noto; the elephant on Piazza Duomo is the city's emblem, via Etnea runs straight north from the square towards the volcano and the fish market lies behind it; one metro line serves the city, Fontanarossa is the busiest airport in Sicily and the university founded in 1434 the oldest on the island. Newcomers most often go wrong by taking Catania for Taormina's airport, when it is a Baroque city of three hundred thousand.",
    layout:
      "Catania's old town centres on the Cathedral square, with the 'Elephant Fountain' (a black basalt Roman-era elephant statue as its base) at the middle, the city's emblem. The old town's streets are paved with black volcanic stone, and building façades often show black-and-white volcanic-stone decoration. Mount Etna is to the north-west of the city, and on a clear day you can see the plume from its summit.",
    gettingAround:
      "Catania Airport (CTA) is very close to the city, with an airport bus. The city has buses and a short metro (built using converted volcanic-rock underground space). Reaching Mount Etna is by tour bus or car/tour (cable car and off-road vehicles carry visitors up to the higher crater area). The climate is Mediterranean, hot and dry in summer, with locally changeable weather influenced by Etna.",
    culture:
      "Italian is the main language, with Sicilian dialect common. Catania people have a strong sense of living alongside the volcano — both wary of and dependent on it (volcanic-ash soil makes the surrounding vineyards and citrus groves very fertile). Restaurant bills often include a bread/service charge.",
    seeAndDo:
      "The Cathedral square and the Elephant Fountain; the Benedictine Monastery (a World Heritage Site with layers of Roman and Byzantine remains inside); La Pescheria (a lively early-morning fish market); climbing Mount Etna (with a licensed guide, following the day's INGV safety notices for how high you can go — the summit crater area is generally off-limits); along the coast to Taormina (a clifftop old town with Greek theatre ruins).",
    whenAndTips:
      "April–June and September–October are the most comfortable; July–August is hot. Etna is an active volcano — always climb with a licensed guide and follow the day's official range, never approaching fumaroles or lava areas on your own. Taormina is a popular day trip and traffic is heavy in peak season — go early or take the train.",
  },

  cagliari: {
    // identity sources: 意大利统计局（ISTAT）发布 **comune（市镇）常住人口**（Bilancio demografico，月度滚动 + 年度定案，
    //   基准日多为 1 月 1 日，当年临时数约次年 3 月上线）。**`città metropolitana`（大都会市）是行政建制，
    //   不是统计口径** —— 仓库里已经踩过一次。「市区人口」在意大利同样不是 ISTAT 的称谓。2026-09-08 核。
    //   卡利亚里 comune 约 **14.6–15.4 万**；**2025-06-01 起撒丁大区改革撤销南撒丁省（Provincia del Sud Sardegna），
    //   把其 53 个市镇并入 Città Metropolitana di Cagliari，市镇数由 17 增至 70**，改革后大都会市约 **53.3–53.4 万**
    //   （2 级，含官方法规引用，2026-09-08 核）。
    //   **行政区划改革会让「有几个市镇」这种看起来最稳的数字过期** —— 与里昂都会区 2024 年两市镇合并同一形状。
    identity:
      "Cagliari is the capital of Sardinia, on a bay on the island's south coast, with a metropolitan city (città metropolitana, enlarged in June 2025 by absorbing the former South Sardinia province) of about 530,000 (2026, ISTAT) — Sardinia's political and economic centre. Sardinia is one of the oldest landmasses in the Mediterranean, and it had a distinct prehistoric Nuragic civilisation — thousands of megalithic tower structures called nuraghi are scattered across the island, some listed as (or part of) World Heritage — giving it a different historical thread from mainland Italy.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Cagliari (comune 85 km²; ~146,000; Metropolitan City of Cagliari ~536,000; capital of the autonomous Sardinian Region; Castello on the hill, Marina, Stampace, Villanova; Poetto ~8 km in comune; port fourth in Italy by cargo; Elmas airport 7 km; Molentargius flamingos)
    howItWorks:
      "Cagliari is the capital of Sardinia, an autonomous region of Italy with a parliament and legislative powers of its own; the commune is governed by a mayor and council, covering about 85 km² with about 146,000 people, and the metropolitan city has held 70 communes and about 530,000 people since it absorbed the 53 communes of the former South Sardinia province in June 2025. The city is built on limestone hills: the Castello district crowns the top within walls and towers raised by the Pisans, and the old quarters of Marina, Stampace and Villanova spread below it towards the port; Poetto beach lies about 8 km east, still within the commune, and flamingos stand in the salt pans of Molentargius; the port is the fourth in Italy by cargo, Elmas airport lies 7 km west, and Sardinian is used alongside Italian. Newcomers most often go wrong by taking Cagliari for the doorstep of Sardinia's resorts, when it is an island capital with an autonomous parliament and the resort coasts lie tens of kilometres away.",
    layout:
      "Cagliari's old town is built on a hill overlooking the bay, known as the 'Castello' district, keeping the walls and towers built during the period of Pisan rule (13th century). Below the city is the Molentargius saltwater lagoon, home to flamingos, and from the high old town you can see the bay, the salt lake and the city all at once.",
    gettingAround:
      "Cagliari Airport (CAG) is about 6.6 km in a straight line from the city, with bus and train links. High-speed rail does not reach Sardinia — travel to and from mainland Italy is mainly by air or ferry (about 8 hours to Civitavecchia near Rome). The city has buses and light rail; the Castello district needs climbing. The climate is Mediterranean, hot, dry and low-rainfall in summer, mild in winter.",
    culture:
      "Italian is the main language; Sardinian (a Romance language quite different from Italian) is still used day to day on the island, with some bilingual signs. Sardinians are proud of the island's distinct history and culture (the Nuragic civilisation, traditional mask festivals), and the food is its own tradition (thin pane carasau bread, porceddu roast suckling pig). Restaurant bills often include a bread/service charge.",
    seeAndDo:
      "The Castello walls and towers for the bay panorama; the Cagliari National Archaeological Museum (the core Nuragic-civilisation collection); Molentargius Lake for flamingos; Poetto Beach (reachable from the city centre); nuraghi sites out of town (such as Su Nuraxi at Barumini, a World Heritage Site, needing a car or a tour); the sand dunes of Piscinas on the 'Green Coast' in the south-west (about 1.5 hours by car).",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August is hot but is also the high season for Sardinia's beaches, with more people and higher prices. Inland transport is limited — driving is recommended for the nuraghi sites and the south-west coast. There is no high-speed rail link between Sardinia and mainland Italy — travel between them is by air or ferry, so plan timing and schedules.",
  },

  // ── Italy batch 2 (2026-09-05) ──
  verona: {
    identity:
      "Verona lies in a bend of the Adige in north-eastern Italy, with about 255,000 people (2025). The Verona Arena, completed in the first century AD, is one of the best-preserved Roman amphitheatres in Italy and has staged an opera festival every summer since 1913; Shakespeare set 'Romeo and Juliet' here, and the balcony at Juliet's House draws crowds every day. The Piazza delle Erbe on the site of the Roman forum, the Scaliger family's Castelvecchio and the Basilica of San Zeno layer the city's history from Rome to the Middle Ages, and the whole old town was inscribed as a World Heritage site in 2000. Lake Garda lies about 30 km west.",
    // howItWorks sources: **意大利的官方人口口径**（ISTAT，2026-09-09 复核）：`comune`（市镇常住人口）是唯一严格意义上的统计口径，逐月滚动、按 1 月 1 日定案，当年临时数约次年 3 月上线；`città metropolitana`（大都会市）**是 2015 年起取代省的行政建制、不是统计口径**，数字为辖内各 comune 相加，会随行政区划改革变动。「市区人口」「都会区」在意大利官方统计里都不存在，已由 `check:claims` 的 `C6k` 拦住。
    //   数字与同条目 identity 一致（约 25.5 万 / 2025 年），**只是 howItWorks 段没写年份 —— 典型的「同一条目两段各写各的」**。未找到更新一期的维罗纳 comune 数（ISTAT 的 2026-01-01 数据要到 2026 年下半年才滚动上线，属正常滞后、不算过期）。 3 级转引 ISTAT，2026-09-09 独立复核（本批意大利 6 城此前已有 2026-09-08 的核实痕迹，本轮是**复核**，全部与 ISTAT 对上）。
    //   https://www.istat.it/
    howItWorks:
      "Verona is the capital of Verona province in the Veneto, governed by a mayor and council with eight boroughs; the commune covers about 206 km² with about 255,000 people in 2025. The old town lies in a great bend of the Adige and was inscribed as World Heritage in 2000: the Roman Arena stands on Piazza Bra in the middle of town and is now the open-air opera house of the summer, Piazza delle Erbe occupies the Roman forum, and the della Scala family ruled here in the thirteenth and fourteenth centuries, leaving Castelvecchio and its bridge; Shakespeare set Romeo and Juliet in this city, and Juliet's balcony is a later invention; the station is the crossing of the Milan-Venice line and the Brenner route with about 68,000 passengers a day, the airport lies south-west at Villafranca, Lake Garda 30 km west and the Valpolicella wineries north of town. Newcomers most often go wrong by taking Verona for a romance attraction, when it is northern Italy's rail junction and a capital of wine.",
    layout:
      "The old town sits in a great loop of the Adige, almost surrounded by the river on three sides: the Piazza Bra and the Arena are the entrance at the southern end, Via Mazzini leads from there to the Piazza delle Erbe and the Piazza dei Signori (Dante's statue, the Scaliger tombs), and Juliet's House is in a side street off the Erbe; the cathedral stands at the northern end of the old town and Castelvecchio and its bridge on the western riverbank. Across the river are the Roman theatre and the Castel San Pietro viewpoint. San Zeno lies about 1 km west of the old town. Porta Nuova station is about 1.5 km south of the old town, the airport about 10 km south-west.",
    gettingAround:
      "Verona Villafranca Airport (VRN), about 10 km from the centre, is about 15 minutes from Porta Nuova by the 199 airport bus, with flights across Europe. Trains take about 1 hour 15 from Milan, 1 hour 10 from Venice and 1 hour from Bologna (high-speed), with international trains to Munich and Innsbruck. The old town is walkable — Porta Nuova to the Piazza Bra is about 20 minutes on foot or a bus ride; for Lake Garda take a train to Peschiera (about 15 minutes) or a summer bus. The climate is humid subtropical with hot summers and foggy, damp winters.",
    culture:
      "Italian is universal. The opera festival (late June to early September) plays in the open-air Arena into the night — bring a cushion and book early; the Arena can be visited by day. Juliet's courtyard is free but packed, and touching the bronze statue is a tourist custom. Dress modestly in churches. Local food includes Verona's horse-meat stew, tortellini, Valpolicella and Amarone wines and Soave whites. Bills usually include a coperto (cover charge); tipping is optional.",
    seeAndDo:
      "The Arena (visit or opera); the Piazza delle Erbe, the Piazza dei Signori and the Lamberti tower; Juliet's House; the Castelvecchio museum and its bridge; the Basilica of San Zeno; the cathedral and Sant'Anastasia; across the river to Castel San Pietro for the whole city (funicular); the Giusti Garden; a day at Lake Garda (Sirmione, Garda); the Valpolicella wineries.",
    whenAndTips:
      "April–June and September–October are most comfortable; July–August brings the opera festival but heat; the April wine fair and the December Christmas market are crowded. A day to a day and a half for the city, a day for Lake Garda. On the Milan–Venice high-speed line, so a day trip works.",
  },
  genoa: {
    identity:
      "Genoa is the capital of Liguria, with about 565,000 people (2025), Italy's busiest port and the birthplace of Christopher Columbus (about 1451). The medieval Republic of Genoa was a Mediterranean sea power, and the old town's web of narrow lanes (caruggi) is one of the largest medieval quarters in Europe; the palaces the nobility built along the Strade Nuove (Via Garibaldi and others) in the sixteenth and seventeenth centuries — the Palazzi dei Rolli — were inscribed as a World Heritage site in 2006. For the 500th anniversary of Columbus's voyage in 1992 Renzo Piano remade the old port and built Italy's largest aquarium. Genoa is the home of pesto and focaccia, nicknamed 'La Superba'.",
    // howItWorks sources: Wikipedia (2026-09): Genoa (9 municipi; 240 km², ~30 km of coast; ~565,000 2025; Metropolitan City 67 comuni ~818,000; Rolli UNESCO 2006; ascensori; 1 metro line; bridge 2018/2020); Comune
    howItWorks:
      "Genoa is the capital of Liguria, governed by a mayor and council, with nine boroughs (municipi); the commune covers about 240 km² stretching some 30 km along the coast, with about 565,000 people in 2025, while the Metropolitan City of Genoa, which replaced the province in 2015, has 67 communes and about 818,000 people. Pressed between the sea and the Apennines, the city could only spread along the shore and climb the valleys: the old town is among the largest medieval quarters in Europe, a maze of narrow caruggi, with the Palazzi dei Rolli inscribed as World Heritage in 2006 on its northern edge; the old port was remade as public space by Renzo Piano, and the elevated road runs above the harbour. Funiculars and public lifts are the city's vertical transport, and one metro line serves the centre. The port is the busiest in Italy. The Morandi Bridge collapsed in 2018 and the San Giorgio Bridge opened in 2020. Addresses give street, number and postcode. Newcomers most often go wrong by picturing Genoa as a flat port city, when daily life moves up and down between sea level and the hillsides.",
    layout:
      "The city is squeezed steep and narrow between the hills and the sea: the old town climbs the slope behind the old port, with the Cathedral of San Lorenzo, the Piazza De Ferrari and the Doge's Palace on its eastern side and the Palazzi dei Rolli of Via Garibaldi on its northern edge; the old port (aquarium, Bigo lift, maritime museum) lies on the waterfront. Piazza Principe station is west of the old town, Brignole east in the newer districts. Funiculars and public lifts link the hillside quarters (the Castelletto viewpoint). The fishing village of Boccadasse lies about 3.5 km in a straight line east on the shore, with the Nervi promenade beyond; the airport is about 7 km west.",
    gettingAround:
      "Genoa Cristoforo Colombo Airport (GOA), about 7 km from the centre, is about 30 minutes from the two stations by the Volabus, with flights across Europe. Trains take about 1.5 hours from Milan, 2 from Turin and 2 from Pisa; the coastal line runs east to the Cinque Terre (about 1.5 hours) and west to Sanremo. The city has a one-line metro, buses, funiculars and lifts, and the old town is walked (steeply); Boccadasse is a bus ride. The climate is Mediterranean with warm summers and wet autumns and winters.",
    culture:
      "Italian is universal and the Genoese dialect survives. The lanes are lively by day but some are lonely at night — keep valuables close. Most Rolli palaces are museums or offices, opened together on the annual 'Rolli Days'. Trofie al pesto, focaccia and farinata (chickpea pancake) are the must-eats. Dress modestly in churches. Bills usually include a cover charge; tipping is optional.",
    seeAndDo:
      "The old port with the aquarium, the Bigo and the maritime museum; the Rolli palaces of Via Garibaldi (Palazzo Rosso, Palazzo Bianco, Palazzo Doria-Tursi); the Cathedral of San Lorenzo and the caruggi; the Piazza De Ferrari and the Doge's Palace; the Castelletto viewpoint (by lift); Boccadasse; the Staglieno monumental cemetery; Columbus's house; day trips to the Cinque Terre, Portofino and Camogli.",
    whenAndTips:
      "April–June and September–October are most comfortable; summers are hot but the coast is lively, winters wet. A day to a day and a half for the city, a day for the Cinque Terre. The gateway to the Ligurian coast (the Cinque Terre, Portofino).",
  },
  pisa: {
    // howItWorks sources（2026-09-15 核实，update）: https://demo.istat.it/app/?i=POS · ISTAT · comune 050026 (Pisa) = 90,146, 1 gennaio 2026 · 1级 · 2026-09-15 核；下一期约 2027-03
    // identity sources（2026-09-15 核实，update）: https://demo.istat.it/app/?i=POS · ISTAT · comune 050026 (Pisa) = 90,146, 1 gennaio 2026 · 1级 · 2026-09-15 核；下一期约 2027-03
    // identity sources: 比萨 comune 2024 年 89,422 人（ISTAT 口径，经 urbistat 转引，3 级，2026-09-08 核）。
    //   比萨近年一直在 8.9—9 万之间，原来 identity 写的 9.9 万不对应任何一期。
    identity:
      "Pisa lies on the lower Arno in Tuscany about 10 km from the sea, with a comune population of about 90,000 (January 2026, ISTAT). The Leaning Tower on the Piazza dei Miracoli (built 1173–1372, tilting because its foundations sank), the cathedral, the baptistery and the Camposanto were inscribed as a World Heritage site in 1987; medieval Pisa was a maritime republic contending with Genoa and Venice. Galileo was born here, and the University of Pisa and the Scuola Normale Superiore founded by Napoleon in 1810 make it an academic centre. Pisa's airport is one of Tuscany's main gateways, through which many visitors enter the region.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Pisa (comune 185 km²; ~90,000; Province of Pisa, Tuscany; Piazza dei Miracoli UNESCO 1987 at the north-west edge of the walled city; Arno lungarni; university 1343, Scuola Normale, Sant'Anna, ~50,000 students; Galileo Galilei airport busiest in Tuscany with PisaMover; maritime republic; Florence ~80 km)
    howItWorks:
      "Pisa is the capital of Pisa province in Tuscany, governed by a mayor and council; the commune covers about 185 km² with about 90,000 people (January 2026, ISTAT). The leaning tower, the cathedral and the baptistery do not stand in the centre but on the Piazza dei Miracoli at the north-west corner of the walled city, inscribed as World Heritage in 1987; the weight of the old town lies on the lungarni along the Arno and on Piazza dei Cavalieri, and in the Middle Ages this was a maritime republic beside Genoa and Venice until the Battle of Meloria in 1284; the University of Pisa founded in 1343, the Scuola Normale and the Sant'Anna school put some 50,000 students in a city of 90,000; Galileo Galilei is the busiest airport in Tuscany with a shuttle rail to the station, and Florence lies about 80 km east. Newcomers most often go wrong by taking Pisa for a town with a leaning tower, when the tower stands in one corner and the city itself is half students.",
    layout:
      "The Piazza dei Miracoli lies in the north-west corner of the old town by the walls, with the tower, the cathedral, the baptistery and the Camposanto on one lawn; from the square walk south through the old town to the Piazza dei Cavalieri and Borgo Stretto, then to the riverside with the little church of Santa Maria della Spina and the Lungarno promenades. Pisa Centrale station is about 1.5 km south of the river, and the airport just about 2 km south of the station, 5 minutes by the Pisamover shuttle. Lucca lies about 20 km north-east and the beach at Marina di Pisa to the west.",
    gettingAround:
      "Pisa Galileo Galilei Airport (PSA), about 2 km south of the city, is a major Ryanair base with flights across Europe, linked to Centrale by the Pisamover in 5 minutes. Trains take about 1 hour from Florence, 30 minutes from Lucca, 2 hours from Genoa and 2.5–3 from Rome. The city is walkable — Centrale to the tower is about 25 minutes on foot or a bus ride; Lucca is a train ride. The climate is Mediterranean with hot summers and mild wet winters.",
    culture:
      "Italian is universal. The tower is climbed in timed, limited slots; children under 8 are not admitted and bags are checked; keep off the lawns. The cathedral is free but needs a ticket, and modest dress. Pisa is a university town with a lively riverside in the evening; on the night of 16 June the Luminara di San Ranieri lines both banks with candles. Local food includes chickpea pancakes, baked salt cod and unsalted Tuscan bread. Bills usually include a cover charge.",
    seeAndDo:
      "The Piazza dei Miracoli: the tower (booked climb), the cathedral, the baptistery (echo demonstration), the Camposanto frescoes; the Piazza dei Cavalieri and the Scuola Normale; the Lungarno and Santa Maria della Spina; Borgo Stretto; the university botanical garden (1544, among the oldest in Europe); the San Matteo national museum; the June Luminara; day trips to the walls of Lucca, the Carrara marble quarries and San Gimignano.",
    whenAndTips:
      "April–June and September–October are most comfortable; July–August the Piazza dei Miracoli is packed and hot. Half a day for the square, half a day for the old town. Most visitors come for the day from Florence or on the way through the airport; an overnight gives the tower at dawn without crowds.",
  },
  siena: {
    // identity sources（2026-09-15 核实，add-year）: https://demo.istat.it/app/?i=POS · ISTAT · comune 052032 (Siena) = 53,180, 1 gennaio 2026 · 1级 · 2026-09-15 核；下一期约 2027-03
    identity:
      "Siena stands on the hills of central Tuscany, with about 53,000 people (2026, ISTAT); its old town, inscribed as a World Heritage site in 1995, is one of the most intact medieval cities in Italy. The shell-shaped Piazza del Campo is the heart of the city, where the Palio horse race is run on 2 July and 16 August by the seventeen city wards (contrade); the Torre del Mangia rises about 88 m, and the cathedral's black-and-white striped marble and inlaid floor are masterpieces of Tuscan Gothic. The Monte dei Paschi di Siena, founded in 1472, is the oldest bank still operating in the world. The old town has been closed to cars since 1966.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Siena (comune 118.5 km²; 53,180 2026; Province of Siena, Tuscany; historic centre UNESCO 1995; Piazza del Campo; Palio 2 July/16 August, 17 contrade; cathedral; Torre del Mangia; ZTL; university 1240 ~16,000 students; Monte dei Paschi 1472; Florence ~70 km)
    howItWorks:
      "Siena is the capital of Siena province in Tuscany, governed by a mayor and council; the commune covers about 118 km² with about 53,000 people in 2026. The old town stands on three ridges and was inscribed as World Heritage in 1995, the shell-shaped Piazza del Campo its heart with the Torre del Mangia of the town hall at one corner; beneath the administrative districts lies another layer: the seventeen contrade are neighbourhood bodies surviving from the Middle Ages, each with its flag, church and museum, and ten of them race horses on the square each 2 July and 16 August in the Palio, a local belonging for life from the contrada of one's birth; the old town is a restricted traffic zone, the university founded in 1240 has about 16,000 students, Monte dei Paschi founded in 1472 is among the oldest banks still trading in the world, and Florence lies about 70 km north. Newcomers most often go wrong by taking the Palio for a show put on for visitors, when it is a serious yearly contest between the city's own neighbourhoods.",
    layout:
      "The old town sits on three ridges, with the Piazza del Campo in the hollow where they meet and the Palazzo Pubblico and the Torre del Mangia on its southern side; the cathedral crowns the western ridge, with the cathedral museum and the Santa Maria della Scala hospital beside it; San Domenico stands on the north-western ridge and the Porta Camollia at the northern end. The main street runs from the Porta Camollia through the Campo to the Porta Romana in the south. The station is about 2 km north below the old town (escalators lead up), and the coach station is on the Piazza Gramsci at the northern edge of the old town. Chianti lies north, and Montalcino, Pienza and the Val d'Orcia south.",
    gettingAround:
      "Siena has no airport with scheduled flights; the nearest are Florence (about 80 km) and Pisa (about 150 km). From Florence the coach takes about 1 hour 15 and arrives at the edge of the old town (more convenient than the train, which takes about 1.5 hours with a change). The old town is entirely on foot (steep, cobbled); Chianti and the Val d'Orcia need a car or a tour. The climate is Mediterranean with hot dry summers and cool winters.",
    culture:
      "Italian is universal. Around the Palio the old town fills with contrada flags and processions; the free standing area in the Campo must be claimed hours ahead and lodging sells out a year in advance; on other days the contrada museums can be visited by appointment. Dress modestly in the cathedral, whose inlaid floor is fully uncovered from mid-August to mid-October. Siena's sweets are panforte and ricciarelli almond biscuits, and Chianti is the local wine. Bills usually include a cover charge.",
    seeAndDo:
      "The Piazza del Campo and the Palazzo Pubblico (the 'Allegory of Good Government' frescoes in the civic museum), the climb up the Torre del Mangia; the cathedral, the Piccolomini Library and the cathedral museum's 'unfinished façade' viewpoint; Santa Maria della Scala; San Domenico (the relics of St Catherine); the contrade and fountains of the old town; the Palio (2 July, 16 August); day trips to the Chianti wineries, San Gimignano, Montalcino and the Val d'Orcia, Pienza.",
    whenAndTips:
      "April–June and September–October are most comfortable; the Palio days are a crush. A day to a day and a half for the old town, one or two for the surroundings. A day trip from Florence works, but an overnight gives the Campo without crowds.",
  },
  matera: {
    // identity sources: 意大利统计局（ISTAT）发布 **comune（市镇）常住人口**（Bilancio demografico，月度滚动 + 年度定案，
    //   基准日多为 1 月 1 日，当年临时数约次年 3 月上线）。**`città metropolitana`（大都会市）是行政建制，
    //   不是统计口径** —— 仓库里已经踩过一次。「市区人口」在意大利同样不是 ISTAT 的称谓。2026-09-08 核。
    //   马泰拉 comune 约 **59,368**（2026 年，3 级转引 ISTAT，2026-09-08 核）。identity 与 howItWorks 两处原本都缺年份，已一并补上。
    identity:
      "Matera lies on the limestone uplands of Basilicata in southern Italy, with about 59,000 people (2026, ISTAT). It is famous for the Sassi — cave dwellings cut into the walls of the Gravina ravine, stacked in tiers and inhabited since prehistory, making it one of the longest continuously inhabited settlements in the world. In the 1950s, because of poverty and sanitation, the government moved the inhabitants out of the Sassi; a law of 1986 allowed restoration and return, the Sassi and the surrounding park of rupestrian churches were inscribed as a World Heritage site in 1993, and Matera was European Capital of Culture in 2019. About 150 rock-cut churches dot the Murgia plateau across the ravine, and films such as 'The Passion of the Christ' were shot here.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Matera (comune 392 km²; ~60,400; Province of Matera, Basilicata; Sassi cave districts UNESCO 1993, evacuated 1950s–70s, reoccupation law 1986; Civita; modern town on the plateau; Gravina ravine, Murgia park; ECoC 2019; Bari ~60 km with airport; FAL narrow-gauge rail)
    howItWorks:
      "Matera is the capital of Matera province in Basilicata, governed by a mayor and council; the commune covers about 392 km² with about 59,000 people (2026, ISTAT). The Matera people picture is the Sassi, two districts of caves cut into the limestone wall of a ravine, inhabited since the eighth millennium BC and among the longest continuously occupied settlements in the world, inscribed as World Heritage in 1993; between the 1950s and the 1970s the government moved the residents out of the Sassi, calling them 'the shame of Italy', and a law of 1986 opened the way to restoration and reoccupation, so that today they hold hotels and restaurants; the city government, the schools and most residents are in the modern town on the plateau above, with the Gravina ravine and the Murgia park facing the Sassi across it; in 2019 it was European Capital of Culture, and Bari with its airport lies about 60 km north-east. Newcomers most often go wrong by taking the Sassi for Matera, when they are half of the old town and daily life goes on in the new town on the plateau.",
    layout:
      "The Sassi divide into the Sasso Barisano to the north and the Sasso Caveoso to the south, with the Civita district and the cathedral on the high ground between them; the dwellings step down the western wall of the ravine to the Gravina stream at the bottom. The post-nineteenth-century town lies on the plateau west of the Sassi, with the Piazza Vittorio Veneto at the boundary between new town and Sassi and the Centrale station (FAL narrow gauge) north of the new town. Across the ravine is the Murgia plateau (viewpoint and rock churches), reached from the Sasso Caveoso by a path and a suspension bridge.",
    gettingAround:
      "Matera has no airport with scheduled flights; the nearest is Bari (about 60 km), with a direct airport bus of about 1 hour 15. The Ferrovie Appulo Lucane narrow-gauge train from Bari Centrale reaches Matera Centrale in about 1.5 hours (few services on Sundays); coaches also arrive from Bari, Naples and Rome. The Sassi are entirely on foot — many steps and slippery stone, so wear good shoes; the Murgia plateau is reached on foot across the ravine or by car around it. The climate is Mediterranean with hot summers and cool winters.",
    culture:
      "Italian is universal and the local dialect survives. The Sassi now hold many homes, hotels and restaurants; visit an open 'typical cave dwelling' to see how people once lived; the frescoes of the rock churches are fragile — no flash, no touching. Matera bread (IGP), peppers and Lucanian sausage are the local tastes. On 2 July the procession of the Madonna della Bruna ends with the traditional tearing apart of the float. Bills usually include a cover charge.",
    seeAndDo:
      "The Sasso Caveoso (the typical cave-house museum, Santa Maria de Idris); the Sasso Barisano; the cathedral and the Civita; San Pietro Caveoso; the Murgia viewpoint (the whole Sassi at sunset) and the rock-church trails; the Palombaro Lungo cistern; the MUSMA sculpture museum (inside caves); the Sassi lit up at night.",
    whenAndTips:
      "April–June and September–October are most comfortable; summers are hot but the evenings pleasant, and the Bruna festival in July is the liveliest. Stay at least one night — the Sassi are at their best at dusk and dawn. Link with Bari and Alberobello on a Puglia route.",
  },
  trieste: {
    identity:
      "Trieste lies on the Adriatic in the north-eastern corner of Italy, the capital of Friuli-Venezia Giulia, with about 199,000 people (2025). From 1382 to 1918 it belonged to the Habsburgs and was the principal port and fourth-largest city of Austria-Hungary; its neoclassical centre, its café culture and the Piazza Unità d'Italia facing the sea (one of the largest sea-facing squares in Europe) carry a Central European air. James Joyce wrote here from 1904 to 1915 and befriended the local writer Italo Svevo. Miramare Castle (1856–1860) stands on a headland north of the city. Trieste is Italy's coffee port, the autumn Barcolana is one of the largest sailing regattas in the world, and the winter bora wind can reach 140 km/h.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Trieste (comune 84 km²; ~198,700 2025; capital of the autonomous Friuli-Venezia Giulia region; Habsburg port until 1918, fourth city of Austria-Hungary; Piazza Unità on the sea; Canal Grande; Miramare ~8 km; Karst plateau; Slovenia ~5 km; Slovene community; bora; largest Italian port by tonnage; free port; ICTP/SISSA; Ronchi airport ~30 km)
    howItWorks:
      "Trieste is the capital of Friuli-Venezia Giulia, one of Italy's five autonomous regions with legislative powers of its own; the commune is governed by a mayor and council, covering about 84 km² with about 199,000 people in 2025. From 1382 to 1918 it belonged to the Habsburgs as the main seaport of Austria-Hungary and its fourth city, and Piazza Unità in the centre stands with imperial palaces on three sides and the sea on the fourth, the canal, the coffee houses and the literary tradition all left from that time; the Karst plateau rises behind the city, the Slovenian border lies 5 km away, the Slovene community is the local minority, and the bora wind can blow past a hundred kilometres an hour in winter; the port is the largest in Italy by tonnage and keeps its free-port status, Miramare castle stands 8 km north-west, research institutes such as the ICTP make it a city of science, and the airport lies about 33 km north-west. Newcomers most often go wrong by imagining Trieste from an idea of Italy, when its buildings, its coffee and its accent all rest on a Central European foundation.",
    // layout sources: 机场距离：注册表坐标算出西北约 30.4 公里，与同条目 howItWorks 段一致；原 layout 段的 40 公里偏大。
    layout:
      "The centre lies on the flat by the sea around the Piazza Unità d'Italia and the Canal Grande (the Borgo Teresiano, with Sant'Antonio and the Serbian Orthodox church), with the hill of San Giusto behind it crowned by the castle, the cathedral and Roman remains. The Centrale station lies north of the centre and the port on both sides. Miramare Castle is about 7 km in a straight line north along the coast, reached by tram or the shore path. The Karst plateau rises behind the city, with the Grotta Gigante about 10 km north and a viewpoint at Opicina. The airport is about 33 km north-west at Ronchi dei Legionari.",
    // gettingAround sources: 约 33 km；同条目另一段原本写「约 30 公里」，本次统一。随机抽样审计（seed=4）抽中。2026-09-13 核。
    gettingAround:
      "Trieste Airport (TRS) at Ronchi, about 33 km from the city, has its own railway station (about 30 minutes to the centre) and scheduled flights. Trains take about 2 hours from Venice and about 2.5 from Ljubljana. City buses run and the centre is walkable; the 6 bus or the shore walk reaches Miramare, and Opicina is reached by the tram (when running) or bus. The climate is humid subtropical with the fierce bora wind in winter.",
    culture:
      "Italian is universal, with a Slovene community and many German traces. Cafés are the heart of local life, with Trieste's own coffee vocabulary (capo in b and so on); historic cafés such as the San Marco keep a quiet reading atmosphere. No flash inside Miramare. The Barcola seafront promenade is where locals swim and sunbathe. The cooking mixes Italian and Austrian — goulash, jota (a bean, sauerkraut and pork soup), seafood. Bills usually include a cover charge.",
    seeAndDo:
      "The Piazza Unità d'Italia and the waterfront; the Canal Grande and Sant'Antonio; San Giusto castle and cathedral and the Roman theatre; the historic cafés (San Marco, Tommaseo, degli Specchi); Miramare Castle and its gardens; the Revoltella Museum; the Grotta Gigante; the Opicina viewpoint; the Barcola seafront; day trips to Muggia, Piran in Slovenia and the ruins of Aquileia.",
    whenAndTips:
      "May–June and September–October are most comfortable, with the Barcolana weekend in October the most crowded; the seafront is lively in summer and the winter bora is bitter. A day for the city, half a day for Miramare and the Karst. A stop east of Venice before Slovenia.",
  },
};
