import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "france-overview": {
    // identity sources: INSEE《Bilan démographique 2025》Insee Première n° 2087：2025-01-01 约 68.6 百万（含本土与五个海外省；INSEE 本身即按百万级公布）。https://www.insee.fr/fr/statistiques/8719824
    //   核实日 2026-09-07，来源级别 1
    identity:
      "Metropolitan France covers about 550,000 sq km with a population of about 68.6 million as of January 2025, including the five overseas departments (INSEE), the largest country by area in Western Europe. The land is very varied: the north-west and west are old, low blocks (the Armorican Massif) and coastal plains; the centre-south is the Massif Central (extinct volcanoes and plateaus); the south-east and south have the young, high Alps and Pyrenees; in between are the two big sedimentary basins, the Paris Basin and the Aquitaine Basin. On the Mediterranean is Corsica — a mountainous island. Travel mode covers only metropolitan France and Corsica, not the overseas departments and territories.",
    layout:
      "It helps to divide France into: the Paris region (the capital and surroundings), the north (the plains around Lille), Alsace (Strasbourg, the Rhine valley, a historically Franco-German border area), Rhône-Alpes (Lyon, Grenoble, toward the high Alps), Provence (Marseille, Nice, the Mediterranean coast), the south-west (Toulouse, Bordeaux, the Pyrenees and wine country), the west (Nantes, the Loire estuary), and the island of Corsica.",
    gettingAround:
      "France's high-speed rail (TGV) network is extensive — Paris to Lyon, Marseille, Strasbourg, Bordeaux and other big cities is all within 2–4 hours, often more convenient than flying (city centre to city centre). Domestic flights are mainly for fast links between distant regions or to Corsica. Big cities have a metro, and suburbs have regional rail (RER/TER). Drive on the right; motorways are mostly tolled. Restaurant bills usually already include a service charge; rounding up is polite but not required. Tap water is drinkable. Power is 230V with the European two-round-pin plug.",
    culture:
      "The official language is French; English is fairly common in tourist areas and among younger people but not universal — a few words of French greeting are well received. The French value dining etiquette and conversational discretion, and it's customary to say bonjour on entering a shop and au revoir on leaving. Many small shops close on Sundays and at midday. Tipping is not required (the bill already includes a service charge; rounding up or leaving small change is fine).",
    seeAndDo:
      "The museums and landmarks of Paris; Mont Blanc, the Barre des Écrins and skiing in the Alps; the Calanques coast and lavender fields of Provence; the chain of extinct volcanoes and gorges of the Massif Central (the Gorges du Tarn, the Gorges de l'Ardèche); the Cirque de Gavarnie in the Pyrenees; the château country of the Loire valley; Mont-Saint-Michel and the chalk cliffs of Normandy; the mountains and sea of Corsica. Wine-region tours (Bordeaux, Burgundy and others) are popular.",
    whenAndTips:
      "May–June and September–October are quieter with good weather; July–August is peak season, hot in the south with crowded beaches and popular sights — also the French summer holiday, when many small shops close. The ski season in the Alps is December–April. France is in the Schengen area; most foreign visitors travel visa-free for short tourism or follow Schengen rules. Book ahead for popular sights and restaurants; the south has strong summer UV, so use sun protection.",
  },

  paris: {
    // identity sources: INSEE 参照人口（populations de référence）现行生效版参照 2023 年、2026-01-01 起生效；下一版参照 2025 年（2024 是空档年，无普查滚动样本参照）。各档 2023 年数：commune de Paris 2,103,778 / unité urbaine 11,013,774 / aire d'attraction des villes（2020 版划定）13,320,752 / région Île-de-France 12,463,067 / Métropole du Grand Paris（2016 年设立的行政建制，131 市镇，**不是统计口径**）7,142,540。级别 1，2026-09-09 核。
    //   https://www.insee.fr/fr/statistiques/2011101?geo=COM-75056
    //   https://www.insee.fr/fr/statistiques/2011101?geo=AAV2020-001
    //   https://www.insee.fr/fr/statistiques/8684539
    //   本条目约定：正文说「都会区 / metropolitan area」一律指 aire d'attraction；行政大区一律用「法兰西岛大区」专名，不套用「都会区」。已停用的 aire urbaine 不再引用（仓库在尼斯条目上踩过一次）。
    identity:
      "Paris is the capital of France, with a city (commune) population of about 2.1 million and a metropolitan area of about 13.3 million on INSEE's aire d'attraction des villes definition, both 2023 reference populations, in a bend of the Seine in the north of the country. For over two thousand years it has been the political and cultural centre of the region, and Baron Haussmann's 19th-century rebuilding shaped the broad boulevards and stone terraces seen today — one of the cities with the densest concentration of museums and art collections in the world.",
    // howItWorks sources: 人口：巴黎「城市吸引区」2023 年参照人口约 1,332 万 —— INSEE，1 级，与 identity 段同源。⚠️ 不要与 2016 年设立的「大巴黎都会区」（131 个市镇、约 714 万）混用，那是行政建制、不是统计口径。
    howItWorks:
      "The Paris people speak of is, administratively, only the city of about 105 km² inside the Périphérique ring road, a commune and department in one since 2019, governed by the Mayor and the Council of Paris; it is divided into twenty arrondissements spiralling clockwise from the centre, each with a mayor and council, the first four merged as 'Paris Centre' since 2020. The city had about 2.1 million people in the 2023 reference population, while the Île-de-France region around it holds about 12.5 million (2023) — an administrative region, not the same thing as a statistical metropolitan area; on INSEE's aire d'attraction des villes definition the metropolitan area holds about 13.3 million (2023), and the Métropole du Grand Paris, an administrative body created in 2016 rather than a statistical caliber, gathers 131 communes and about 7.1 million people (2023); La Défense, the airports and most people's homes lie outside the city line. The Seine divides Left Bank from Right Bank. Addresses give street, number and postcode, and the last two digits after 750 are the arrondissement, which is how locals place things. Metro and RER run on one Navigo pass, and the Grand Paris Express, due around 2030, is linking the suburbs to each other. Newcomers most often go wrong by taking the twenty arrondissements for the whole of Paris, when they are the core of that metropolitan area of about 13.3 million at the 2023 reference date.",
    layout:
      "Paris is organised around the Seine, with the Left Bank (south, traditionally more academic and artistic, the Latin Quarter, Montparnasse) and the Right Bank (north, the commercial and administrative centre, the Louvre, the Champs-Élysées). The city is 20 spiralling arrondissements numbered outward from the centre. The Eiffel Tower is in the south-west and the Sacré-Cœur is on the Montmartre hill in the north, both high points. On the outer ring is the modern tower district of La Défense.",
    gettingAround:
      "Two main airports: Charles de Gaulle (CDG, with the RER B line or an airport express, about 35–50 minutes into town) and Orly (ORY, with rail links). The metro network is extremely dense (14 lines), plus buses and the RER suburban rail, taken with a Navigo pass or paper/phone tickets; the centre is also very walkable. The climate is temperate maritime, four clear but not extreme seasons, occasional summer heatwaves, and winters with little snow but grey and chilly.",
    culture:
      "French is the main language; English is fairly common among the young and in tourist areas. Saying bonjour on entering a shop and au revoir on leaving is basic manners and is better received than starting straight in. Dining is unhurried, with dinner usually starting after 7–8 pm. Restaurant bills already include a service charge, so no extra tip is required. The metro is very crowded at peak times, and pickpocketing occasionally occurs at popular sights and on the metro — watch your belongings.",
    seeAndDo:
      "The Louvre, the Musée d'Orsay, the Centre Pompidou; the Eiffel Tower and the Champ de Mars; Notre-Dame (under restoration/partly reopened — check official announcements); the Arc de Triomphe and the Champs-Élysées; Montmartre and the Sacré-Cœur; a Seine river cruise; the Jardin du Luxembourg; the Palace of Versailles (out of town, needs most of a day).",
    whenAndTips:
      "April–June and September–October are the most comfortable. In August many local shops and restaurants close for holidays; the main sights stay open but the local atmosphere is quieter. Book timed tickets online in advance for popular museums (the Louvre, Orsay) to skip the queues. Be alert for pickpockets on the metro and keep bags to the front.",
  },

  lille: {
    // identity sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Métropole Européenne de Lille（95 个市镇）2023 = 1,195,234 —— **原文数字与口径都对**，只是把年份与口径写明确。
    identity:
      "Lille is at the far north of France, near the Belgian border, with a metro area of about 1.20 million (2023 legal population, 95 communes), historically the textile and industrial centre of French Flanders, its architecture marked by Flemish brick gables quite different from Paris. It is the largest city in northern France and a hub of the London–Paris–Brussels high-speed rail triangle.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Lille (commune 35 km²; ~238,000 2023; Métropole Européenne de Lille 95 communes ~1.2 million, Eurometropolis with Kortrijk/Tournai ~2 million; Hauts-de-France capital; Vieux-Lille Flemish brick; Grand Place; Euralille with Lille-Europe Eurostar; VAL metro 1983, first automated network; Braderie September; Belgium ~15 km; ~110,000 students)
    howItWorks:
      "Lille is the capital of the Hauts-de-France region and the prefecture of the Nord, governed by a mayor and council, the commune covering about 35 km² with about 238,000 people in 2023; the Métropole Européenne de Lille created in 2015 gathers 95 communes and about 1.2 million people, and beyond it the cross-border Eurometropolis with Kortrijk and Tournai in Belgium holds about 2 million, the border 15 km away. Vieux-Lille is a quarter of Flemish red brick with the Grand Place at its centre, Euralille is the district built between the two stations in the 1990s where Eurostar and TGV call at Lille-Europe, an hour from Paris, an hour and a half from London and 38 minutes from Brussels; the VAL opened in 1983 was the world's first automated metro, the Braderie flea market each September draws three million people, and some 110,000 students make it the largest university city in northern France. Newcomers most often go wrong by taking Lille for a French border town, when its daily life straddles France and Belgium and its speech and buildings rest on Flemish foundations.",
    layout:
      "Lille's old town (Vieux-Lille) keeps a well-preserved area of 17th-century Flemish brick streets, with the Grand Place as the central landmark. The city was once a thriving textile-industry area, and many old mills have been converted into cultural spaces. The land is flat, part of the great plain of northern France.",
    gettingAround:
      "Lille Airport (LIL) is south of the city, with an airport bus. Lille is more often reached by high-speed rail: about 1 hour from Paris, about 1.5 hours from London, about 40 minutes from Brussels (Eurostar and Thalys both stop here). The city has a metro (one of the earliest fully automatic metro systems in France) and trams. The climate is temperate maritime, cloudy and rainy, cooler and wetter than Paris.",
    culture:
      "French is the main language; being close to Belgium, Flemish culture and beer culture have a visible influence (a wide range of local beers). Lille people are known for being warm and direct, and the September 'Braderie de Lille' is one of the largest flea markets in Europe, with stalls across the whole city. Restaurant bills already include a service charge.",
    seeAndDo:
      "The Flemish streets and Grand Place of the old town; the Palais des Beaux-Arts (one of France's most important painting collections after the Louvre); the old stock exchange (converted into a book market and cafés); the September Braderie; the local dish carbonnade (beef stewed in beer) with fries. An hour south to Paris, or a day trip north to London or Brussels.",
    whenAndTips:
      "May–September is the most comfortable; during the September Braderie the whole city is packed and lodging should be booked early. Lille is a good stopover between Paris, London and Brussels, with high-speed rail far more convenient than flying. It rains a lot — carry an umbrella.",
  },

  strasbourg: {
    // identity sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Eurométropole de Strasbourg（33 个市镇）2023 = 522,596；unité urbaine = 494,536；aire d'attraction（268 个市镇）= 875,163。**原文的「约78万」三个口径都对不上。**
    identity:
      "Strasbourg is in north-eastern France on the Ill river, a tributary of the Rhine, right on the German border, with a Eurométropole of about 523,000 (2023 legal population, 33 communes), the centre of the Alsace region. Historically it changed hands between France and Germany several times, so its architecture, language (Alsatian, close to a German dialect) and food all show a clear Franco-German blend. It is one of the seats of the European Parliament and the headquarters of the Council of Europe.",
    // howItWorks sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   **这是典型的口径混用**：原文把「33 个市镇」（Eurométropole 的建制规模）和「87.5 万」（其实是 268 个市镇的吸引区人口）拼进了同一句话。
    howItWorks:
      "Strasbourg is the capital of the Grand Est region and the prefecture of the Bas-Rhin, governed by a mayor and council, the commune covering about 78 km² with about 295,000 people in 2023; the Eurométropole created in 2015 gathers 33 communes and the métropole itself holds about 523,000, and the wider aire d'attraction of 268 communes about 875,000. It is one of Europe's three 'capitals': the European Parliament, the Council of Europe and the European Court of Human Rights all stand in the European quarter north of the centre, and the hotels fill when parliament sits. The old town lies on the Grande Île in a loop of the Ill, inscribed as World Heritage in 1988, with the Neustadt planned under German rule added in 2017, the sandstone cathedral and the timber-framed houses of Petite France on the island; Kehl in Germany lies just across the Rhine, reached by tram since 2017, Alsatian survives in the countryside, the Christmas market is among the oldest in France and the TGV reaches Paris in about an hour and three quarters. Newcomers most often go wrong by taking Strasbourg for a French provincial city, when its institutions, its buildings and its daily life straddle France and Germany.",
    layout:
      "The core of Strasbourg's old town, the Grande Île, is wrapped by two branches of the Ill and was the first entire old town to be listed as a World Heritage Site. The cathedral (pink sandstone, one tower) is the old town's high point. La Petite France, with its half-timbered houses along the canals, is the most photographed corner. The European district (the European Parliament and other institutions) is east of the old town.",
    gettingAround:
      "Strasbourg Airport (SXB) is south of the city, with a train link. High-speed rail from Paris is about 1.8 hours, and Zürich is also easily reached. The city has one of the largest tram networks in France and extensive cycle lanes (local cycling rates are among the highest in France). The climate is continental, cold winters and hot summers, with a bigger seasonal range than other French cities.",
    culture:
      "French is the main language; Alsatian (a German dialect) is still used by older generations and in some contexts, and German often appears on restaurant menus and signs. The food has a German character (choucroute with sausage, onion tart, Alsace white wine). The Christmas market (December) is one of the most famous in France, said to date back to 1570. Restaurant bills already include a service charge.",
    seeAndDo:
      "Strasbourg Cathedral (climb the tower for the old town and Rhine plain); a walk or boat trip along the canals of La Petite France; the European district for the European Parliament building (viewable from outside, open days allow entry); the Alsatian Museum; the December Christmas market; day trips to Alsace wine-route towns (such as Colmar).",
    whenAndTips:
      "May–October is good for sightseeing; December's Christmas market is the busiest and most crowded time of year, so book lodging early. Winters are cold and summers hot — pack for the season. Cycling is a normal way to get around locally — consider renting a bike for the old town.",
  },

  lyon: {
    // howItWorks sources（2026-09-15 核实，update）: https://www.insee.fr/fr/statistiques/2011101?geo=COM-69266 · INSEE population légale, millésime 2023（2026-01-01生效版）= 163,684 · 1级 · 2026-09-15 核；下一期约 2026-12（INSEE次一版millésime 2024通常年底以政令公布）
    // identity sources: 里昂城市吸引区 2,339,329、市镇法定人口 519,127（均为 2023 年参照人口，2026-01-01 生效版）；
    //   里昂大都会 1,436,354（58 个市镇）——INSEE
    //   https://www.insee.fr/fr/statistiques/2011101?geo=COM-69123 与 .../2011101?geo=AAV2020-002
    //   （均 1 级，2026-09-08 核）。
    //   **法国排名必须写明口径**：aire d'attraction 与 commune 两套口径下里昂的名次分别是第二和第三，
    //   写成「第二或第三」会被读成数据不确定，其实是口径不同。
    //   注意 aire d'attraction des villes 是 2020 年起的口径，取代了已停用的 aire urbaine ——
    //   尼斯条目此前就是引了停用口径的旧数。
    identity:
      "Lyon is in south-eastern France, where the Saône meets the Rhône, with an aire d'attraction of about 2.34 million (2023 legal population) — France's second-largest city by aire d'attraction and its third-largest by commune population, behind Marseille, an important city of Roman Gaul. It is widely regarded as the gastronomic capital of France, was a centre of the Renaissance silk trade, and its old town is a UNESCO World Heritage Site as a whole.",
    // howItWorks sources: Wikipedia (2026-09): Lyon (9 arrondissements; 47.9 km²; 2023 pop 519,127; Métropole de Lyon 58 communes ~1.4 million since 2015; Villeurbanne separate; UNESCO 1998); Communes of France
    howItWorks:
      "Lyon has two administrative layers: the city, with nine arrondissements, each with a mayor and council, covering about 48 km² with about 519,000 people in 2023; and, since 2015, the Métropole de Lyon, which joins the city with its neighbouring communes — 58 in total including Lyon, after two of them merged in 2024 — into a local government unique in France — it replaces the department within its area, its council is directly elected, and it runs transport, waste, roads and social services for about 1.4 million people. Villeurbanne, pressed against Lyon with about 164,000 people (2023, INSEE), is a separate city. Two rivers define the layout: the Presqu'île between the Saône and the Rhône is the old centre with Place Bellecour; Vieux Lyon and the Fourvière hill lie west of the Saône; the Croix-Rousse to the north is the old silk-weavers' quarter; and Part-Dieu east of the Rhône is the business district and high-speed rail station — the whole inscribed as World Heritage in 1998. Addresses give street, number and postcode, and the last digit after 6900 is the arrondissement. Newcomers most often go wrong by taking the city of Lyon for the whole, when it is the core of a metropolis of 1.4 million.",
    layout:
      "Lyon sits between two rivers (the Saône and the Rhône) and the surrounding hills. The old town (Vieux Lyon) is on the west bank of the Saône at the foot of Fourvière hill, a Renaissance ensemble; the Basilica of Notre-Dame de Fourvière is on the hilltop, overlooking the whole city. Between the two rivers is the 'Presqu'île' (peninsula), the main commercial district. The old town has unique 'traboules' — hidden passages linking building courtyards, historically used to carry silk.",
    gettingAround:
      "Lyon–Saint-Exupéry Airport (LYS) is east of the city, with a rail express (Rhônexpress) about 30 minutes into town. High-speed rail from Paris is about 2 hours. The city has a dense metro, tram and bus network; the old town and the Presqu'île are walkable. The climate is temperate continental, hot summers and cooler winters, with more sun than Paris.",
    culture:
      "French is the main language. Lyon people are intensely proud of their culinary tradition — a 'bouchon' (a traditional Lyon bistro) serves hearty dishes like offal and sausage, with Beaujolais wine. The 'Fête des Lumières' in early December is one of France's grandest light-art festivals. Restaurant bills already include a service charge.",
    seeAndDo:
      "The Basilica of Notre-Dame de Fourvière and its funicular; the Renaissance buildings and traboules of the old town; the Roman theatre ruins; the Musée des Beaux-Arts; the central square and shopping streets of the Presqu'île; a meal at a traditional bouchon; the early-December light festival; from Lyon, 1–1.5 hours to Grenoble, the Alps or the Beaujolais wine region.",
    whenAndTips:
      "May–June and September–October are the most comfortable; during the early-December light festival the whole city is packed and lodging is tight. Bouchon portions are large and rich (be selective about offal dishes) — check the menu ahead. Lyon is a hub for onward travel to the Alps and Provence, with excellent high-speed rail connections.",
  },

  grenoble: {
    // identity sources: 人口：Grenoble-Alpes Métropole（49 个市镇）2023 年参照人口 450,608 —— INSEE，1 级（2026-09-08 核，与 howItWorks 段同源）。⚠️ 不要与「城市吸引区」（aire d'attraction des villes，204 个市镇、727,380）混用，那是另一套口径。INSEE 的参照人口按法律滞后三年，2026-01-01 生效版参照 2023 年 —— 不是过期。下一版参照 2025 年，2026 年底公布。
    identity:
      "Grenoble is in south-eastern France in the Isère valley, ringed by three mountain ranges (the Vercors, the Chartreuse and the Belledonne), with a metropolitan area of 49 communes and about 450,000 people at the 2023 reference date (INSEE) — the research and high-tech centre of the French Alps (sometimes called 'France's Silicon Valley') and host of the 1968 Winter Olympics. The city itself is flat, and looking up to see snow mountains all around is its most distinctive impression.",
    // howItWorks sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   同样的口径混用：Grenoble-Alpes Métropole（49 个市镇）2023 = 450,608，而 72.7 万是 **204 个市镇**的吸引区人口（727,380）。identity 段的「约45万」本身是对的。
    howItWorks:
      "Grenoble is the prefecture of the Isère, governed by a mayor and council, the commune covering only about 18 km², among the densest in France, with about 156,000 people in 2023; the Grenoble-Alpes Métropole created in 2015 gathers 49 communes and the métropole itself holds about 451,000, and the wider aire d'attraction of 204 communes about 727,000, the largest metropolis in the Alps. The city stands on flat ground where the Drac meets the Isère, ringed on three sides by the Chartreuse, Vercors and Belledonne ranges, and the Bastille cable car of 1934 carries people from the centre up the northern cliff in a string of spherical cabins; some 70,000 students and the French atomic energy commission, STMicroelectronics and Schneider Electric make it France's centre of research and microelectronics, the Winter Olympics were held here in 1968, five tram lines serve the metropolis, the ski resorts lie thirty to sixty kilometres away and Lyon about 100 km west. Newcomers most often go wrong by taking Grenoble for a mountain town, when the city is as flat as a table and the mountains stand around it.",
    layout:
      "Grenoble is built on the flat valley floor where the Isère and Drac rivers meet, with a narrow-streeted old town inside the old walls. In the north of the city a cable car (the iconic 'bubble' spherical cars) rises from the site of the old Bastille fortress, a few minutes to a viewpoint over the city and the mountains on three sides. University campuses and research institutes are scattered around the city.",
    gettingAround:
      "Grenoble–Isère Airport (GNB) is about 40 km from the city, mainly served by winter ski charter flights; day-to-day access is more often by high-speed rail (about 3 hours from Paris) or a bus transfer from Lyon airport (about 1 hour). The city has an extensive tram network, and the old town is walkable. The climate is mountain: cold, snowy winters and hot summers with cool evenings; being ringed by mountains, air circulation is poorer, and winter temperature inversions can bring haze.",
    culture:
      "French is the main language; because of the universities and research institutes, English is relatively common. Grenoble people live an outdoor-oriented lifestyle — skiing, climbing and mountaineering are everyday activities. Walnuts are a local speciality with a protected designation of origin. Restaurant bills already include a service charge.",
    seeAndDo:
      "The Bastille fortress and the 'bubble' cable car for the city-and-mountains panorama; the old town's Musée Dauphinois and Musée de Grenoble; a day trip to hike the Vercors plateau or the Chartreuse range; skiing in the Alps in winter (resorts such as Alpe d'Huez and Les Deux Alpes are about 1–1.5 hours by car); the Écrins National Park to the south for summer mountaineering.",
    whenAndTips:
      "June–September suits hiking, December–April is ski season. Winter can bring temperature-inversion haze in the valley, while the mountains above are often clearer. Grenoble's own airport has few, seasonal flights — most visitors come via high-speed rail to Paris or a transfer from Lyon airport. Check mountain weather and avalanche warnings for hiking and skiing nearby.",
  },

  marseille: {
    // identity sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Aix-Marseille-Provence（92 个市镇）2023 = 1,939,077。原文的 190 万在「约」的容差内，顺手改精确。
    identity:
      "Marseille is on the Mediterranean coast of south-eastern France, with a metro area of about 1.94 million (2023 legal population, 92 communes) — France's oldest city (founded by Greeks around 600 BC) and its largest commercial port. The city is known for the Old Port, Mediterranean food (bouillabaisse fish soup) and a limestone fjord-like coastline called the Calanques, and is an important gateway to Corsica and North Africa.",
    // howItWorks sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   同上。
    howItWorks:
      "Marseille is among the largest communes in France at about 241 km², with part of the Calanques National Park inside its boundary; it is divided into sixteen arrondissements paired into eight sectors, each with a mayor and council. With about 886,000 people in 2023 it is France's second city, and since 2016 it has formed the Aix-Marseille-Provence metropolis with 92 communes and about 1.94 million people, Aix among them as a city with a government of its own. The Vieux-Port is the centre and point of reference; the 'quartiers nord' are the working-class districts, the southern coast holds the beaches and the wealthier residential quarters, and the Euroméditerranée project at La Joliette has turned the old docks into a business district. Addresses give street, number and postcode, and the last two digits after 130 are the arrondissement. Two metro lines and trams join the city. Newcomers most often go wrong by picturing Marseille as a compact port town, when it runs for tens of kilometres from north to south, from the hills to the sea, all inside one commune.",
    layout:
      "Marseille is built around the Old Port (Vieux-Port), the historic core, with yachts and fishing boats moored and cafés and a fish market around it. The Basilica of Notre-Dame de la Garde stands on a hill to the south, the city's high point, with a view over the whole bay and the islands offshore (the Frioul archipelago, home to the Château d'If). South-east along the coast is the Calanques National Park — a limestone fjord coastline between Marseille and Cassis.",
    gettingAround:
      "Marseille Provence Airport (MRS) is north-west of the city, with an airport bus. High-speed rail from Paris is about 3.2 hours. The city has a metro, trams and buses; the Old Port and main sights are walkable. The climate is Mediterranean: hot, dry summers and mild winters, often with a dry, cold north wind called the Mistral.",
    culture:
      "French is the main language; because of successive waves of migration (from Italy, North Africa, the Comoros and elsewhere), Marseille is one of the most ethnically diverse cities in France, with a correspondingly rich food and neighbourhood culture. Marseille people are known for being direct, warm and strongly locally identified. Restaurant bills already include a service charge.",
    seeAndDo:
      "The Old Port and Notre-Dame de la Garde; a boat to the Château d'If (the setting of Dumas's 'The Count of Monte Cristo'); hiking or a boat trip in the Calanques National Park (strong summer UV and no shade on the trails); the Museum of European and Mediterranean Civilisations (MuCEM); the narrow lanes of Le Panier old quarter; an authentic bouillabaisse (a proper one is usually booked ahead and served in two courses).",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August is very hot — avoid midday for Calanques hikes and carry plenty of water. The Mistral is dry and cold and can affect boat trips — check the forecast ahead. Some Calanques trails are restricted or closed in summer for fire risk — check official notices before setting out.",
  },

  nice: {
    // identity sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   **原文的「约100万」对不上任何现行口径**：Métropole Nice Côte d'Azur（约 49 个市镇）2023 = 574,287；aire d'attraction des villes（100 个市镇）= 641,721。100 万很可能引的是 **2020 年已被取代的旧口径 aire urbaine**，那套划法覆盖范围大得多，现已废弃。
    identity:
      "Nice is on the Mediterranean coast of south-eastern France, close to the Italian border, with a metro area of about 574,000 (2023 legal population, Métropole Nice Côte d'Azur) — the centre of the Côte d'Azur. Since the 19th century it has been a winter resort for European high society, and the seafront 'Promenade des Anglais', built by the English, is still the city's emblem.",
    // howItWorks sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   同上。
    howItWorks:
      "Nice is the prefecture of the Alpes-Maritimes, governed by a mayor and council, with about 358,000 people in 2023, France's fifth city; since 2012 it has formed the Métropole Nice Côte d'Azur with 48 neighbouring communes, stretching from the coast to ski villages in the Alps, and the aire d'attraction of 100 communes holds about 642,000. The city spreads along the Baie des Anges: the Promenade des Anglais is the shoreline itself, the old town lies at the eastern end below Castle Hill, the nineteenth-century grid is today's commercial centre, and the Paillon river has been covered to make a green belt and tram corridor. Nice passed from the Kingdom of Savoy to France only in 1860, and Italy remains in its buildings, dialect and food; Monaco lies 20 km east and the Italian border about 30 km. Three tram lines join airport, centre and port. Addresses give street, number and postcode. In 2021 Nice was inscribed as World Heritage as the 'Winter Resort Town of the Riviera'. Newcomers most often go wrong by taking Nice for a beach resort, when it is the administrative centre of a metropolis half of whose communes lie in the mountains.",
    layout:
      "Nice is built along a broad bay, with the Promenade des Anglais running the length of the seafront and a pebble beach behind it. The old town (Vieux Nice) is to the east, narrow Italian-style lanes and coloured buildings (the area was historically under Savoyard/Italian rule, joining France only in 1860). Castle Hill (no castle, now a ruined park) is at the eastern end of the old town, overlooking the whole bay.",
    gettingAround:
      "Nice Côte d'Azur Airport (NCE) is west of the city, right on the coast, France's third-busiest airport by passengers, with a tram about 30 minutes to the centre. High-speed rail from Paris is about 5.5 hours (most people fly). The city has trams and buses; the seafront and old town are walkable. The climate is Mediterranean: mild, humid winters and hot, dry summers — one of the sunniest regions of France.",
    culture:
      "French is the main language; because of its history and many visitors, Italian and English are also often heard. Nice people are proud of their local identity ('Niçois') and dishes like salade niçoise and pissaladière (onion tart). The Nice Carnival each February is one of the largest in France. Restaurant bills already include a service charge.",
    seeAndDo:
      "The Promenade des Anglais and the pebble beach; the old town's narrow lanes and the Cours Saleya market; Castle Hill for the panorama; the Matisse Museum and the Chagall Museum; the coastal train to Monaco, the clifftop village of Èze, or Cannes (each about 30–40 minutes); the February carnival.",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August is hot with crowded beaches and sights; lodging is tight during the February carnival. The coastal train line (toward Monaco and Menton) is very scenic and inexpensive — a popular experience. UV is strong in summer, and the beaches are mostly pebble rather than sand — water shoes help.",
  },

  toulouse: {
    // identity sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Toulouse unité urbaine 2023 = 1,093,783；aire d'attraction = 1,529,112；Toulouse Métropole（37 个市镇）= 841,524。原文没说是哪个口径，按数值最接近的建成区标明。
    identity:
      "Toulouse is in south-western France on the Garonne, with a built-up area of about 1.09 million (2023 legal population) — the centre of France's aerospace industry (Airbus's headquarters is here) and an important European Space Agency base. Because of the widespread use of locally fired pink brick and tile, it is called 'la Ville Rose' (the Pink City).",
    // howItWorks sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Toulouse Métropole（37 个市镇）2023 = 841,524。
    howItWorks:
      "Toulouse is the prefecture of the Haute-Garonne and capital of the Occitanie region, governed by a mayor and council, with about 515,000 people, France's fourth city; since 2015 it has formed Toulouse Métropole with 36 neighbouring communes and about 842,000 people, among them Blagnac, home of Airbus, a commune with a government of its own. The core is the pink-brick old town on the east bank of the Garonne, with the Capitole square and city hall as point of reference; in 1963 the state placed the aerospace industry here, and Airbus and the European space sector have made it one of the fastest-growing big cities, while some 130,000 students make it a university town at the same time. Two metro lines and trams serve the city, and the Canal du Midi, World Heritage since 1996, runs through it. Addresses give street, number and postcode. Occitan survives in street names and culture. Newcomers most often go wrong by taking Toulouse for a quiet old southern town, when it is one of the centres of the European aircraft industry.",
    layout:
      "Toulouse's old town spreads along the east bank of the Garonne, with the town hall (the Capitole) fronting the main square, pink-brick buildings throughout the city. The Canal du Midi (a historic canal linking the Atlantic and the Mediterranean, a World Heritage Site) passes the edge of the city, lined with tree-shaded paths. Around the city are Airbus's final-assembly plants and aerospace industrial parks.",
    gettingAround:
      "Toulouse–Blagnac Airport (TLS) is west of the city; the T2 tram that used to serve it stopped running in June 2023, and a bus now links the airport with the city — check Tisséo, the operator, for the current service. High-speed rail from Paris is about 4.5 hours (many people fly instead). The city has a metro (two fully automatic lines), trams and buses. The climate is temperate, influenced by both the Atlantic and the Mediterranean, hot and dry in summer, mild in winter.",
    culture:
      "French is the main language, with a south-western accent and Occitan/Gascon cultural roots (some signs pair French with Occitan). Toulouse is one of France's largest student cities, young and lively. Local food is known for cassoulet (a white-bean-and-meat stew) and violet-flavoured sweets. Restaurant bills already include a service charge.",
    seeAndDo:
      "Capitole square and the pink-brick old town; the Basilica of Saint-Sernin (one of the largest surviving Romanesque churches); the Musée des Augustins; the Cité de l'Espace (a space-themed park) and an Airbus factory tour (book ahead); a walk or cycle along the Canal du Midi; an hour south to the northern foothills of the Pyrenees.",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August is hot and dry. Airbus factory tours need booking well ahead online, with ID required. Toulouse is a common starting point for driving or touring to the Pyrenees (such as the Cirque de Gavarnie).",
  },

  bordeaux: {
    // identity sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Bordeaux unité urbaine（73 个市镇）2023 = 1,034,027；Bordeaux Métropole（28 个市镇）= 854,334（howItWorks 段用的是这个，对）；aire d'attraction（275 个市镇）= 1,426,278。**两段中文都叫「都会区」却指两个不同东西**，已各自标明口径。
    identity:
      "Bordeaux is in south-western France on the lower Garonne, with a built-up area of about 1.03 million (2023 legal population, 73 communes) — the centre of one of the world's most prestigious wine regions. Its 18th-century stone terraces are well preserved and the whole old town is a World Heritage Site; over the last decade or two, extensive riverfront redevelopment has turned it from an industrial port into a popular tourist city.",
    // howItWorks sources: Wikipedia (2026-09): Bordeaux (49 km²; 2023 pop ~268,000; Bordeaux Métropole 28 communes 854,334; Mérignac airport; UNESCO 2007 ~40% of area; LGV 2017); Communes of France
    howItWorks:
      "Bordeaux is the prefecture of the Gironde and capital of Nouvelle-Aquitaine, governed by a mayor and council, yet the city covers only about 49 km² with about 268,000 people in 2023; since 2015 it has formed Bordeaux Métropole with 27 neighbouring communes and about 854,000 people, with Mérignac, home of the airport, Pessac and Talence as separate communes. The city lies on the crescent bend of the Garonne, the 'Port of the Moon' of its old name: the left bank holds the eighteenth-century stone city and the Chartrons quarter of the wine merchants, and about forty per cent of the city's area was inscribed as World Heritage in 2007; the right bank, La Bastide, was marsh and industry and is now new development. Four tram lines serve the metropolis, and since the high-speed line opened in 2017 Paris is about two hours away. Addresses give street, number and postcode. Some 10,000 wine estates around the city are its economy and its identity. Newcomers most often go wrong by taking the city of Bordeaux for the whole, when it is the core of a metropolis of 854,000.",
    layout:
      "Bordeaux is built along a crescent-shaped bend of the Garonne (hence 'the Port of the Moon'), with the old town on the west bank, a continuous run of 18th-century classical stone buildings. The riverside Miroir d'Eau (Water Mirror) is a landmark shallow reflecting pool. Around the city are the vineyards of the Bordeaux region (the Médoc on the left bank, Saint-Émilion on the right, among others), 30–60 minutes by car.",
    gettingAround:
      "Bordeaux–Mérignac Airport (BOD) is west of the city, with a rail express (about 30 minutes) to the centre. High-speed rail from Paris is about 2 hours (much shorter since the TGV Atlantic line opened). The city has an extensive tram network and buses; the old town is walkable. The climate is temperate maritime, moderated by the Atlantic, mild and humid.",
    culture:
      "French is the main language. Bordeaux's city life is closely tied to the wine industry, and many locals work at or with an estate. The city has an elegant, unhurried feel. Restaurant bills already include a service charge, and sommelier recommendations when ordering wine are usually reliable.",
    seeAndDo:
      "The Miroir d'Eau and the Saint-Pierre old quarter; La Cité du Vin (an interactive wine museum); Bordeaux Cathedral; out of town, Saint-Émilion (a medieval stone village, itself a World Heritage Site) or a Médoc estate visit and tasting (mostly by appointment); the Dune du Pilat (Europe's tallest sand dune, about an hour by car).",
    whenAndTips:
      "May–June and September–October are the most comfortable; September–October is the grape harvest, with related events at some estates. Book estate visits and tastings ahead; if driving between tastings, arrange a designated driver or drink little or nothing. The sand at the Dune du Pilat gets very hot — avoid walking barefoot for long at midday in summer.",
  },

  nantes: {
    // identity sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Nantes Métropole 2023 = 689,456；unité urbaine = 689,036；aire d'attraction（116 个市镇）= 1,050,815。**原文的「约96万」三个口径都对不上**，是个无来源的旧数。已与同条目 howItWorks 的 68 万统一。
    identity:
      "Nantes is in western France near the mouth of the Loire, with a metro area of about 689,000 (2023 legal population, 24 communes), historically an important Atlantic port and shipbuilding centre (also once a port in the transatlantic slave trade, a history now presented candidly at a dedicated memorial). Its 18th-century stone buildings and bold recent contemporary public art (such as a giant mechanical elephant) give the city a distinctive character, and it has repeatedly been rated one of France's most liveable cities.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Nantes (commune 65 km²; 327,734 2023, sixth in France; Nantes Métropole 24 communes ~680,000; prefecture of Loire-Atlantique and capital of Pays de la Loire, historically Brittany; Loire, Île de Nantes with the Machines; Château des ducs de Bretagne; Passage Pommeraye; trams since 1985; European Green Capital 2013; Atlantic ~50 km)
    howItWorks:
      "Nantes is the prefecture of the Loire-Atlantique and the capital of the Pays de la Loire region, governed by a mayor and council, the commune covering about 65 km² with about 328,000 people in 2023, France's sixth city; Nantes Métropole gathers 24 communes and about 680,000 people. Historically and culturally it belongs to Brittany, the Château des ducs de Bretagne stands in the centre and the treaty joining Brittany to France was signed here in 1532, yet today's administrative map places it in the Pays de la Loire, and the local argument for 'returning' it to Brittany continues. The Loire runs along the south of the city, the Machines de l'île on the Île de Nantes include a walking elephant, and the Passage Pommeraye is a nineteenth-century shopping arcade; France's first modern tramway was revived here in 1985, in 2013 it was European Green Capital, the Atlantic lies 50 km west and the shipyards of Saint-Nazaire at the river mouth. Newcomers most often go wrong by taking Nantes for an inland city, when it was France's largest slave-trading port and the river and the sea are its history.",
    layout:
      "Nantes is built where the Loire meets several tributaries, its old town centred on the Château des Ducs de Bretagne. The Île de Nantes (the former shipyard district) has been redeveloped for contemporary art and creative industries, and the giant mechanical elephant and carousel of Les Machines de l'île are here. West along the Loire, the river leads to the Atlantic.",
    gettingAround:
      "Nantes Atlantique Airport (NTE) is south-west of the city, with an airport bus. High-speed rail from Paris is about 2 hours. The city has an extensive tram network (a pioneer of the modern French tram revival) and buses; the old town is walkable. The climate is temperate maritime, mild and humid, moderated by the Atlantic, rarely extreme.",
    culture:
      "French is the main language. Nantes shows traces of both Breton and Anjou/Loire culture (it was historically the capital of the Duchy of Brittany). The city invests heavily in contemporary art and creative industries, and the mechanical elephant is its signature cultural symbol. Restaurant bills already include a service charge.",
    seeAndDo:
      "The Château des Ducs de Bretagne and its moat; the giant mechanical elephant (you can ride it) and carousel on the Île de Nantes; the Cathedral of St Peter and St Paul; the contemporary-art walking route (Le Voyage à Nantes, with a green line in summer); west along the Loire to Saint-Nazaire for the Atlantic, or a day trip east to the Loire valley châteaux (Amboise, Chambord and others, mostly near Tours).",
    whenAndTips:
      "May–September is the most comfortable; the mechanical elephant runs longer hours in summer — book online ahead to skip queues. The Loire château cluster is a fair drive from Nantes; if châteaux are the sole focus, Tours or Blois make a closer base. The transatlantic-slave-trade memorial site is a place for quiet, respectful visiting.",
  },

  ajaccio: {
    // identity sources: 阿雅克肖市镇法定人口 76,320（2023 年参照人口，2026-01-01 生效版）——
    //   INSEE https://www.insee.fr/fr/statistiques/8643952?geo=COM-2A004（1 级，2026-09-08 核）。
    //   正文的 7.6 万与之一致。（这条注释此前一直写着「identity 的『约7万』偏低」，
    //   而正文早已改对 —— 注释滞后于正文，2026-09-08 重写。）
    //   科西嘉红线复核：howItWorks 里 2018 年两省与大区合并为「单一地方行政区」是行政建制沿革事实，
    //   不涉现代自治/独立议题，符合项目红线。
    identity:
      "Ajaccio is on the west coast of Corsica, the island's capital, with a city population of about 76,000 (2023 legal population), and the birthplace of Napoleon Bonaparte (his childhood home is now a national museum). Corsica is mountainous, with a central spine of granite peaks over 2,000 m and a very indented coastline combining beaches, fjord-like inlets and cliffs; historically influenced by several Mediterranean powers in turn, it joined France in 1768.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Ajaccio (commune 82 km²; ~76,300 2023; prefecture of Corse-du-Sud and seat of the Collectivité de Corse, the single territorial collectivity since 2018 with its own assembly; Maison Bonaparte, Napoleon born 1769; citadel; Sanguinaires; airport 5 km; ferries Marseille/Nice/Toulon; Corsican language; Bastia ~150 km; first French city liberated 1943)
    howItWorks:
      "Ajaccio is the prefecture of Corse-du-Sud and the seat of the Collectivité de Corse — since 2018 Corsica's two departments and its region have been merged into a single territorial collectivity with an assembly and executive council of its own, holding wider powers than an ordinary region; the commune is governed by a mayor and council, about 82 km² with about 76,000 people in 2023. The city lies on a west-facing gulf, rebuilt by the Genoese in 1492, and Napoleon was born in the Maison Bonaparte in the old town in 1769, with the citadel and the old port beside it and the Sanguinaires islands at the mouth of the gulf; in September 1943 it was the first French city liberated. Corsican stands beside French in schools and on road signs, the airport lies 5 km east, ferries sail to Marseille, Nice and Toulon, and Bastia lies about 150 km north-east. Newcomers most often go wrong by taking Corsica for an ordinary French region, when it has an assembly, a language and an identity of its own, and Ajaccio is its administrative centre.",
    layout:
      "Ajaccio is built around a broad bay, the old town at its north-eastern corner, with Napoleon's childhood home and the cathedral at its core. The western side of the bay has a breakwater and marina, with beaches along the shore. Not far behind the city, Corsica's mountainous terrain begins, and on a clear day the inland high peaks are visible.",
    // gettingAround sources: 机场方位与距离：注册表坐标算出**城东约 5.3 公里**，与同条目 howItWorks 段一致；原 gettingAround 段的「城南约 8 公里」方位与距离都不对。
    gettingAround:
      "Ajaccio Airport (AJA) is about 5 km east of the city, with a bus link. There are also ferries to mainland France (Marseille, Nice, Toulon) and Italy. Getting around the island is mostly by car (mountain roads with many bends), and there is also a scenic railway linking Ajaccio, Corte and Bastia. The climate is Mediterranean: hot, dry summers and mild, rainy winters, with snow in the inland mountains in winter.",
    culture:
      "French is the main language; Corsican (a Romance language close to Italian) is still used day to day on the island, and signs are often bilingual French/Corsican. Islanders have a strong Corsican identity, and the food (Corsican charcuterie, chestnut products, AOC cheeses) forms its own tradition. Restaurant bills already include a service charge.",
    seeAndDo:
      "Napoleon's childhood home museum and the cathedral; the old town's narrow lanes and market; a drive along the coast to the Sanguinaires Islands reserve or Pointe de la Parata for the Genoese towers; a summer boat trip to the Scandola Nature Reserve (a World Heritage coastline); a day trip inland to Corte (the old capital, a mountain town) or the red-granite coast of Piana north of Ajaccio (a World Heritage Site).",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August is peak season, with crowded beaches and ferries. Inland mountain roads have many bends — bring motion-sickness medication if needed. Book boat tickets to reserves like Scandola ahead in peak season. Inland mountains have a large day–night temperature range — a jacket for evenings is worth carrying even in summer.",
  },

  // ── France batch 2 (2026-09-05) ──
  annecy: {
    // identity sources: 安纳西市镇法定人口 132,117（2023 年参照人口，2026-01-01 生效版）——
    //   INSEE https://www.insee.fr/fr/statistiques/2011101?geo=COM-74010（1 级，2026-09-08 核）。
    //   **这个三年滞后是法律定义，不是数据过期**：populations de référence 每年 12 月下旬由法令签署、
    //   次年 1 月 1 日生效；参照年份原为生效年的前三年，2026 年底那一版起压到前两年，**下一版参照 2025 年**（2024 是「空档年」），预计 2026-12 公布。
    //   安纳西是 2017 年由 6 个市镇合并成的新市镇，合并前后的人口数不可比。
    identity:
      "Annecy lies at the northern tip of Lake Annecy at the foot of the French Alps, the capital of Haute-Savoie, with about 132,000 people (2023 commune legal population, after a 2017 merger of six communes), only 45 km from Geneva. The Thiou river and several canals run through the old town, and the twelfth-century Palais de l'Isle in the middle of the river — once a prison and courthouse — is the town's emblem, with the château on the slope above, hence the name 'Venice of the Alps'. Lake Annecy is known for its clear water and ringed by a cycle path; the Semnoz and the Tournette nearby are hiking and paragliding country, and the Annecy International Animation Film Festival each June is the world animation industry's annual gathering.",
    // howItWorks sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Grand Annecy 2023 = 213,415。原文「约30万」高估约 41%。
    howItWorks:
      "Annecy is the prefecture of Haute-Savoie, governed by a mayor and council; in 2017 it merged with five neighbouring communes to about 67 km², with about 132,000 people in 2023, while the Grand Annecy agglomeration gathers 34 communes and about 213,000. The city lies at the northern end of Lake Annecy, the Thiou and its canals flowing out of the lake through the old town with the Palais de l'Isle standing midstream, which earns it the name 'Venice of the Alps', and the château on the slope behind; the lake is among the cleanest in Europe and a cycle path runs round it; Geneva lies about 35 km north and many residents cross the border to work in Switzerland each day, outdoor firms such as Salomon are headquartered here, the international animation festival has been held each June since 1963, and the local airport has no regular scheduled passenger flights, Geneva serving. Newcomers most often go wrong by taking Annecy for a lakeside resort, when it is a departmental capital and a town of cross-border commuters.",
    layout:
      "The old town sits where the Thiou leaves the lake at its northern end, with the Palais de l'Isle in the river, coloured houses, arcades and market streets along the canals, and the château on the slope south-west of the old town. The Jardins de l'Europe and the Pont des Amours are on the lakeshore east of the old town, with the Pâquier lawns stretching east along the lake. The station is about 500 m north of the old town. The Semnoz rises south of town, Talloires on the eastern shore and Doussard at the southern end are the usual lakeside villages, and the lake circuit by bicycle is about 40 km.",
    gettingAround:
      "Annecy's own airport serves mainly business and general aviation, with no regular scheduled passenger flights; the nearest major airports are Geneva (about 45 km, direct coaches in about 1 hour) and Lyon (about 125 km). Trains take about 2 hours from Lyon, 3.5–4 from Paris (by TGV) and about 1.5 from Geneva (usually with a change). The old town is walkable and a hire bicycle along the lake is the best way to get around; boats and buses circle the lake for the lakeside villages. The climate is temperate with warm summers and cold winters, with snow on the mountains.",
    culture:
      "French is universal, with English in the tourist quarters. Old-town markets are held on Tuesdays, Fridays and Sundays. The lake is clean for swimming at designated beaches; boats, paddleboards and paragliding (launching from the Col de la Forclaz) are the usual activities. Savoyard food is built on cheese — tartiflette, fondue, Reblochon. Service is included in restaurant bills; tipping is optional. Lodging is tight during the June animation festival.",
    seeAndDo:
      "The old-town canals and the Palais de l'Isle; the Château d'Annecy (museum); the lakeshore, the Jardins de l'Europe and the Pont des Amours; cycling round the lake; boats to Talloires or Doussard; the Semnoz for the lake and Mont Blanc; paragliding from the Col de la Forclaz; the old-town markets; skiing nearby in winter (La Clusaz, Le Grand-Bornand).",
    whenAndTips:
      "June–September is best, with swimming in the lake and July–August the most crowded; autumn is quiet, winter cold but with a Christmas market and skiing nearby. A day for the town, a day round the lake. A stop on a Lyon–Geneva–Chamonix route.",
  },
  avignon: {
    // identity sources: 阿维尼翁市镇法定人口 92,188（2023 年参照人口，2026-01-01 生效版）——
    //   INSEE https://www.insee.fr/fr/statistiques/2011101?geo=COM-84007（1 级，2026-09-08 核）。
    //   **上一轮欠的那个数已补上（2026-09-08）**：大阿维尼翁聚合区 2023 年参照人口 199,932，
    //   16 个市镇（含阿维尼翁，跨沃克吕兹与加尔两省）—— INSEE EPCI-248400251
    //   https://www.insee.fr/fr/statistiques/2011101?geo=EPCI-248400251（1 级）。正文的「约 20 万」本来就对。
    identity:
      "Avignon lies on the left bank of the Rhône in Provence, with about 92,000 people (2023 commune legal population). From 1309 to 1377 seven popes resided here, and the fourteenth-century Palais des Papes is one of the largest Gothic palaces in Europe; the 'Pont d'Avignon' of the song (the Pont Saint-Bénézet, built 1171–1185) now has only four piers reaching into the river; and the 4.3 km medieval wall still fully encloses the old town. The palace, the episcopal ensemble and the bridge were inscribed as a World Heritage site in 1995. The Avignon Festival, founded in 1947, turns the whole city into a stage every July.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Avignon (commune 64.8 km²; 92,188 2023; Grand Avignon 16 communes ~200,000, straddling Vaucluse and Gard; prefecture of Vaucluse; 4,330 m of ramparts; Palais des Papes, popes 1309–1377, papal territory until 1791; Pont Saint-Bénézet; UNESCO 1995; festival July ~100,000; TGV station 3 km, ~2 h 40 Paris; mistral 120–160 days)
    howItWorks:
      "Avignon is the prefecture of the Vaucluse, governed by a mayor and council, the commune covering about 65 km² with about 92,000 people in 2023; the Grand Avignon agglomeration gathers 16 communes and about 200,000 people, straddling the Vaucluse and the Gard across the Rhône, with the town on the far bank in another department. Seven popes lived here from 1309 to 1377, the papacy bought the city in 1348, and it passed to France only with the Revolution in 1791; 4,330 m of medieval ramparts still stand complete, and the Palais des Papes and the Pont Saint-Bénézet were inscribed as World Heritage in 1995; the theatre festival each July draws about a hundred thousand people and turns the whole city into a stage; the TGV station lies 3 km outside town, about two hours forty from Paris, and the mistral blows on a hundred and twenty to a hundred and sixty days a year. Newcomers most often go wrong by assuming the walls hold everything, when the commune reaches beyond them and another department's towns lie across the river.",
    layout:
      "The walled old town lies on the east bank of the Rhône: the Palais des Papes and the cathedral stand on the rock at the northern end, the Rocher des Doms park behind the palace looks over the river and the bridge, and the Pont Saint-Bénézet reaches into the river from the walls; the Place de l'Horloge (town hall, opera) lies south of the palace, and the Rue de la République runs from the square to the station (Avignon Centre) just outside the southern wall. The TGV station is about 4 km south in the Courtine district, with a shuttle train. Villeneuve-lès-Avignon with its tower and fort lies across the river.",
    gettingAround:
      "Avignon's local airport has very few flights; the nearest major airport is Marseille Provence (about 85 km, coaches in about 1 hour). The TGV reaches Avignon TGV in about 2 hours 40 minutes from Paris, about 1 hour from Lyon and about 30 minutes from Marseille, with a shuttle train of about 6 minutes to Avignon Centre. The old town is walkable and largely closed to cars, with parking outside the walls; the surroundings (the Châteauneuf-du-Pape wineries, the Pont du Gard, the Luberon villages) need a car or a tour. The climate is Mediterranean with hot dry summers and the mistral wind in winter.",
    culture:
      "French is universal, with an international crowd during the festival. The papal palace is mostly bare halls, visited with the Histopad tablet guide; the cathedral is a working church. The July festival has an official programme (IN) and more than a thousand fringe shows (OFF), with flyers and performers on every street — book lodging months ahead. Provençal food and Rhône wines (Châteauneuf-du-Pape lies about 15 km north) are the local tastes. Service is included in restaurant bills.",
    seeAndDo:
      "The Palais des Papes; the Pont Saint-Bénézet; the Rocher des Doms for the Rhône; the Place de l'Horloge and the Rue de la République; the Petit Palais museum (early Italian painting); Les Halles market; the walls; the Philippe le Bel tower at Villeneuve across the river; day trips to the Pont du Gard (about 25 km), Châteauneuf-du-Pape, Gordes and Roussillon in the Luberon, and Saint-Rémy.",
    whenAndTips:
      "April–June and September–October are most comfortable; the July festival is the liveliest but crowded and hot; lavender blooms from late June to mid-July (the Luberon, Sénanque Abbey). A day for the old town, one or two for the surroundings. The natural base for driving Provence.",
  },
  montpellier: {
    // identity sources: 蒙彼利埃市镇法定人口 310,240（2023 年参照人口，2026-01-01 生效版）；
    //   蒙彼利埃地中海都会区 522,542（31 个市镇）——
    //   INSEE https://www.insee.fr/fr/statistiques/2011101?geo=COM-34172（1 级，2026-09-08 核）。
    //   **排名必须写明口径**：按市镇人口计，蒙彼利埃在巴黎/马赛/里昂/图卢兹/尼斯/南特之后排第七；
    //   换成城市吸引区口径这个名次就不成立。
    identity:
      "Montpellier lies about 10 km inland from the Mediterranean in southern France, the capital of the Occitanie region, with about 310,000 people (2023 commune legal population) — the seventh-largest French city by commune population and one of its fastest-growing, with about 70,000 students making up a quarter of the population. The university was founded around 1160, and its medical faculty (1220) is the oldest medical school still in operation in the world; the old town, the Écusson, keeps medieval lanes and seventeenth- and eighteenth-century mansions, the Place de la Comédie with the 1888 opera house is the city's living room, and Antigone is a neoclassical quarter designed by Ricardo Bofill in the 1980s. The city enjoys about 2,700 sunshine hours a year.",
    // howItWorks sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Montpellier Méditerranée Métropole 2023 = 522,542。
    howItWorks:
      "Montpellier is the prefecture of the Hérault, governed by a mayor and council, with about 310,000 people in 2023, France's seventh city and the fastest-growing big city since 2000; since 2015 it has formed Montpellier Méditerranée Métropole with 30 neighbouring communes and about 523,000 people. The old town, the Écusson, is an oval of medieval streets with the Place de la Comédie as point of reference; from there the neoclassical Antigone quarter of the 1980s and the new Port Marianne districts run south-east towards the sea, which lies 10 km away. Some 70,000 students make up nearly a quarter of the population, and the faculty of medicine founded in 1220 is among the oldest in Europe. Five tram lines serve the metropolis, and since December 2023 public transport has been free for residents. Addresses give street, number and postcode. Newcomers most often go wrong by taking Montpellier for a seaside city, when it lies inland and the beaches belong to the neighbouring communes.",
    layout:
      "The Écusson old town sits on a low hill in the centre, with the Place de la Comédie at its south-east corner as the hub of trams and pedestrian streets; the Promenade du Peyrou, the Saint-Clément aqueduct and the triumphal arch stand at the highest western end, with the Saint-Pierre cathedral and the medical faculty to the north-west. Antigone runs east from the Polygone shopping centre beside the Comédie to the Lez river, with the town hall and new districts further south-east. Saint-Roch station lies south of the Comédie. The beaches are about 10 km south (Palavas-les-Flots, Carnon), reached by tram plus bus or cycle path. The airport is about 7 km south-east.",
    gettingAround:
      "Montpellier–Méditerranée Airport (MPL), about 7 km from the centre, has scheduled domestic and international flights, with an airport bus linking to the tram. The TGV reaches Saint-Roch in about 3.5 hours from Paris, about 1.5 from Marseille and about 3 from Barcelona; the newer Montpellier Sud de France station also takes some TGVs. The city has five tram lines (free for residents since December 2023; visitors buy tickets) and buses, and the old town is walkable; for the beach take the tram to the end and change to a bus or cycle. The climate is Mediterranean with hot dry summers and autumn downpours.",
    culture:
      "French is universal, and English is relatively common in this student city. Nightlife centres on the Saint-Roch quarter at a relaxed pace, and street performers fill the Comédie at weekends. The Musée Fabre is a major gallery of southern France. Local food includes Montpellier's brandade (salt-cod purée), Pic Saint-Loup wines and oysters from Sète and the Étang de Thau. Service is included in restaurant bills; tipping is optional.",
    seeAndDo:
      "The Place de la Comédie and the opera; the lanes and mansions of the Écusson; the Promenade du Peyrou, the aqueduct and the arch; the Saint-Pierre cathedral and the medical faculty's anatomy museum; the Musée Fabre; Antigone; the botanical garden (1593, the oldest in France); cycling along the Lez to the sea; day trips to Sète and the Étang de Thau, Aigues-Mortes, the Nîmes arena and the Pont du Gard.",
    whenAndTips:
      "May–June and September–October are most comfortable; summers are hot but the beaches are lively; winters are mild. A day for the city, half a day for the beach, a day for the surroundings. A stop on the Paris–Barcelona high-speed line, linked with Nîmes and Sète.",
  },
  reims: {
    // identity sources: 兰斯市镇法定人口 177,674（2023 年参照人口，2026-01-01 生效版）；
    //   大兰斯共同体 298,037（143 个市镇）——
    //   INSEE https://www.insee.fr/fr/statistiques/2011101?geo=COM-51454（1 级，2026-09-08 核）。
    identity:
      "Reims lies in the Champagne region of north-eastern France, with about 178,000 people (2023 commune legal population) — the largest city of Champagne. From the baptism of Clovis in 496, the kings of France were traditionally crowned in Reims Cathedral, anointed with the Holy Ampulla, hence the title 'city of coronations'; the cathedral, the Palais du Tau and the Abbey of Saint-Remi were inscribed as a World Heritage site in 1991, and the Champagne hillsides, houses and chalk cellars followed in 2015. Beneath the city run tens of kilometres of chalk galleries (some dating to Roman times) storing the wines of Taittinger, Veuve Clicquot, Pommery and other great houses. On 7 May 1945 the German unconditional surrender was signed in Reims.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Reims (commune 47 km²; 177,674 2023, largest in Marne though Châlons-en-Champagne is the prefecture; Grand Reims 143 communes ~300,000; cathedral of coronations with Palais du Tau and Saint-Remi UNESCO 1991; champagne houses and chalk cellars UNESCO 2015; Art Deco rebuild after WWI; German surrender signed 1945; TGV ~45 min Paris; trams; Épernay ~25 km)
    howItWorks:
      "Reims is the most populous city of the Marne with about 178,000 people in 2023, yet not its prefecture — that is the smaller Châlons-en-Champagne; it is governed by a mayor and council, and the Grand Reims community gathers 143 communes and about 300,000 people. The kings of France were crowned in Reims Cathedral, and the cathedral with the Palais du Tau and the Abbey of Saint-Remi were inscribed as World Heritage in 1991; the First World War all but flattened the city, and the rebuilding left a body of Art Deco architecture; the cellars cut into the chalk belong to the champagne houses of Veuve Clicquot, Taittinger and Pommery, and the 'Champagne hillsides, houses and cellars' were inscribed as World Heritage in 2015; Germany's unconditional surrender was signed here in May 1945, the TGV reaches Paris in about 45 minutes and Épernay lies about 25 km south. Newcomers most often go wrong by assuming Reims is the prefecture, when the Marne's prefecture is Châlons-en-Champagne and Reims is only its largest city.",
    layout:
      "The centre sits on the flat by the Vesle river, with the cathedral and the Palais du Tau in the middle, the town hall and the Place Drouet-d'Erlon (the dining quarter) to the north and the station to the north-west. The Basilica of Saint-Remi lies about 1.5 km south of the centre, and the cellars of Taittinger, Pommery, Veuve Clicquot and Ruinart cluster on the Saint-Nicaise hill around it. The surrender museum is north of the station. The Champagne-Ardenne TGV station is about 5 km south of the city. Épernay (Moët and others) lies about 30 km south, with the Champagne hillside villages between the two towns.",
    gettingAround:
      "Reims has no airport with scheduled flights; the nearest is Paris Charles de Gaulle (about 136 km, about 30 minutes by direct TGV to the Champagne-Ardenne station). The TGV from Paris Est reaches the city-centre station in about 45 minutes, making Reims one of the easiest day trips from Paris. The city has trams and buses; the centre is walkable, and Saint-Remi and the cellars are a tram ride or a 20-minute walk away; Épernay is about 30 minutes by train, and the hillside villages need a car or a tour. The climate is temperate maritime, cool and cloudy.",
    culture:
      "French is universal. The cathedral is a working church, closed to visitors during services; the 'smiling angel' on the façade and the Chagall windows are the highlights. Cellar visits must be booked and are mostly guided tours with a tasting; the cellars stay at about 10°C, so bring a jacket, and mind the drink-driving limit if you drive to the houses. The pink biscuit of Reims with Champagne is the local tradition. Service is included in restaurant bills.",
    seeAndDo:
      "Reims Cathedral (the façade sculpture, the Chagall windows) and the Palais du Tau; the Basilica and museum of Saint-Remi; cellar tours (Taittinger, Pommery, Veuve Clicquot, Ruinart); the Surrender Museum; the fine-arts museum; the Carnegie Library (Art Deco); the restaurants of the Place Drouet-d'Erlon; day trips to the Avenue de Champagne and Moët in Épernay, the hillside villages and Hautvillers (the abbey of Dom Pérignon).",
    whenAndTips:
      "May–October is best, with the houses busiest in the September harvest; the Christmas market runs in December. A day for the city, half a day for the cellars, half a day for Épernay. A day trip from Paris or an overnight.",
  },
  colmar: {
    // identity sources: 科尔马市镇法定人口 66,970（2023 年参照人口，2026-01-01 生效版）——
    //   INSEE https://www.insee.fr/fr/statistiques/2011101?geo=COM-68066（1 级，2026-09-08 核）。
    identity:
      "Colmar lies on the Rhine plain of Alsace at the foot of the Vosges, with about 67,000 people (2023 commune legal population), the capital of the Haut-Rhin department. Its old town keeps its medieval and Renaissance half-timbered houses almost intact, and the 'Petite Venise' quarter on the Lauch is a famous corner; the Unterlinden Museum holds Grünewald's Isenheim Altarpiece (1512–1516), and Bartholdi, the sculptor of the Statue of Liberty, was born here. Colmar calls itself the capital of Alsatian wine, sitting halfway along the Alsace Wine Route, and its Christmas market is among the best known in Europe.",
    // howItWorks sources: en.wikipedia (2026-09, Tier B short): Colmar (commune 66.6 km²; ~67,000 2023, third in Alsace; Colmar Agglomération; prefecture of Haut-Rhin, in the European Collectivity of Alsace; free imperial city 1226; Little Venice; Unterlinden with the Isenheim altarpiece; Bartholdi birthplace; Alsace wine route; ~595 mm rain, among the driest in France; Strasbourg ~64 km)
    howItWorks:
      "Colmar is the prefecture of the Haut-Rhin and part of the European Collectivity of Alsace created in 2021, which merged the two Rhine departments while remaining inside the Grand Est region; the commune is governed by a mayor and council, about 67 km² with about 67,000 people in 2023, the third city of Alsace. The old town is a maze of timber-framed houses, a free imperial city from 1226, 'Little Venice' a stretch of quarter along the canal, the Unterlinden museum holding the Isenheim altarpiece, and Bartholdi, sculptor of the Statue of Liberty, born here; it calls itself the capital of the Alsace wine route, and with about 595 mm of rain a year it is among the driest cities in France; Strasbourg lies about 64 km north, the German border 20 km east and the nearest airport is Mulhouse-Basel. Newcomers most often go wrong by taking Colmar for a Christmas market, when it is a departmental capital with a year of days beyond the winter.",
    layout:
      "The old town is compact: the Unterlinden Museum is at the northern end, the Rue des Marchands, the Maison des Têtes and the Pfister House line the streets towards Saint-Martin's church, the Bartholdi Museum is in the middle, and the Petite Venise lies on the Lauch at the southern end, with flat-bottomed boats. The station is about 1 km south-west of the old town. Vineyards and wine villages surround the town: Riquewihr, Ribeauvillé and Kaysersberg about 10–15 km north-west, Eguisheim about 7 km south-west, and the Haut-Koenigsbourg castle about 25 km north.",
    gettingAround:
      "Colmar has no airport with scheduled flights; the nearest are the Basel-Mulhouse EuroAirport (about 52 km, about 1 hour by train via Mulhouse) and Strasbourg (about 68 km). Trains take about 30 minutes from Strasbourg, about 2.5 hours from Paris (TGV) and about 45 minutes from Basel. The old town is walkable, with a tourist train; the wine villages are reached by bus, bicycle (there is a cycle path) or tour, with shuttle buses in the Christmas season. The climate is semi-continental — Colmar is one of the driest cities in France — with warm summers and cold winters.",
    culture:
      "French is universal, the Alsatian dialect is still spoken, and German usually works. The Christmas markets (late November to late December) fill several old-town squares — very crowded, so book lodging six months ahead. Winery tastings (Riesling, Gewürztraminer, Pinot Gris) are mostly free or nominal; mind the drink-driving limit. Alsatian food includes choucroute, tarte flambée and kougelhopf. Service is included in restaurant bills.",
    seeAndDo:
      "The Petite Venise (by boat); the Unterlinden Museum (the Isenheim Altarpiece); the Bartholdi Museum; the Maison des Têtes, the Pfister House and the Rue des Marchands; Saint-Martin's and the Dominican church ('Madonna of the Rose Bower'); the covered market; the Alsace Wine Route (Riquewihr, Ribeauvillé, Kaysersberg, Eguisheim); the Haut-Koenigsbourg castle; the Christmas markets in December.",
    whenAndTips:
      "May–June and September–October are most comfortable, with the harvest in September–October; the December Christmas markets are the liveliest and most crowded; the old town is busy in summer. A day for the town, a day for the wine villages. An easy day trip from Strasbourg and the base for the Wine Route.",
  },
  rouen: {
    // identity sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   Métropole Rouen Normandie（71 个市镇）2023 ≈ 50 万；aire d'attraction（316 个市镇）= 715,234。原文「都会区约71万」数字凑巧接近吸引区、但标成了都会区，有歧义。
    identity:
      "Rouen lies on the lower Seine in Normandy, the capital of the Normandy region, with about 118,000 people in the city (2023 legal population) and about 715,000 in the wider aire d'attraction of 316 communes. It was one of the largest and richest cities of medieval Europe; the Gothic façade of Rouen Cathedral (painted more than thirty times by Monet) and its 151 m cast-iron spire are the city's emblem, the centre holds more than a thousand half-timbered houses and the fourteenth-century Gros-Horloge clock, and on 30 May 1431 Joan of Arc was burned at the stake in the Place du Vieux-Marché. Flaubert was born here, and the Seine port is one of France's major river ports.",
    // howItWorks sources: 法国国家统计与经济研究所（INSEE）dossier complet / comparateur de territoires，参照 2023 年、2026-01-01 生效的 populations de référence（原 populations légales，由法令 n° 2025-1362 于 2025-12-26 确认）。**级别 1**。https://www.insee.fr/fr/statistiques/2011101
    //   **这套口径按法律就滞后三年**：2026 年生效版参照 2023 年 —— 这不是过期，是定义。下一版**参照 2025 年**（不是 2024 —— INSEE 把发布滞后从三年压到两年，2024 那一档虽同期发布，官方称为「空档年」année blanche、不具规制效力），预计 2026 年底公布、2027-01-01 生效。
    //   法国有三套并行口径不能混：commune（市镇）/ unité urbaine（建成区）/ aire d'attraction des villes（城市吸引区，2020 年起取代旧的 aire urbaine）；另有 Métropole、communauté urbaine 是**行政建制**，与统计口径不是一回事。
    //   第三处口径混用：「71 个市镇」是都会区建制规模，「71.5 万」却是 316 个市镇的吸引区人口。
    howItWorks:
      "Rouen is the prefecture of the Seine-Maritime and the capital of the Normandy region, governed by a mayor and council, the commune covering only about 21 km² with about 118,000 people in 2023; the Métropole Rouen Normandie gathers 71 communes and about 500,000 people, while the wider aire d'attraction of 316 communes holds about 715,000. The Seine divides the city: the right bank holds the old town with the cathedral, the Gros-Horloge and streets of timber-framed houses, Joan of Arc was burned on the Vieux-Marché in 1431 and a modern church now stands on the square; Monet painted the cathedral more than thirty times from a window opposite; the left bank is the industrial and residential city of the nineteenth century onward. The port of Rouen runs far inland along the Seine as France's fifth port, shipping grain to sea; the train reaches Paris in about an hour and twenty minutes with no direct TGV, and Le Havre lies about 90 km north-west. Newcomers most often go wrong by taking Rouen for an outer suburb of Paris, when it is the capital of Normandy and a seaport on the Seine.",
    layout:
      "The old town lies on the right bank of the Seine: the cathedral is in the centre, the Rue du Gros-Horloge runs west from it through the clock to the Place du Vieux-Marché (the Joan of Arc church and memorial), the churches of Saint-Maclou and Saint-Ouen lie east, and the fine-arts museum to the north near the station (Rive-Droite). The left bank holds the newer districts. The Côte Sainte-Catherine to the east looks over the city and the river bend. Downstream lie the Norman abbeys, upstream Giverny (Monet's garden, about 60 km).",
    gettingAround:
      "Rouen has no airport with scheduled flights; the nearest are Paris Charles de Gaulle (about 160 km) and Beauvais. Trains from Paris Saint-Lazare reach Rouen-Rive-Droite in about 1.5 hours, with frequent services. The city has a metro (light rail) and buses, and the old town is walkable; Giverny and the Normandy landing beaches need a car or a tour. The climate is temperate maritime, mild and wet.",
    culture:
      "French is universal. The cathedral is a working church, with a light show on the façade on summer nights; the Historial Jeanne d'Arc tells the story of the trial with multimedia, and the modern church on the Place du Vieux-Marché stands beside the site of the pyre — keep quiet there. Norman food includes Rouen duck, Camembert, cider and Calvados, with plenty of restaurants around the Vieux-Marché. Service is included in restaurant bills.",
    seeAndDo:
      "Rouen Cathedral; the Gros-Horloge and its street; the Place du Vieux-Marché with the Joan of Arc church and the Historial; Saint-Maclou and its cloister-ossuary; the Abbey of Saint-Ouen; the fine-arts museum (Impressionist collection); the ceramics museum; the view from the Côte Sainte-Catherine; day trips to Monet's garden at Giverny, the Norman abbeys route (Jumièges), Honfleur and Étretat.",
    whenAndTips:
      "May–September is best, with the cathedral light show in summer; winters are wet. A day for the city. An easy day trip from Paris and a stop on the way to the Normandy coast.",
  },
};
