import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "romania-overview": {
    // 全七段 sources: 同中文侧（INS press release 2026-08-28 tier 1; INS TEMPO ADM101A tier 1; Constitution via official-text mirror tier 2; European Commission / Council press releases tier 1; UK FCDO travel advice tier 1; ANAF tier 1; CFR Călători booking site tier 1; airport websites tier 1, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Romania lies in south-eastern Europe, with the arc of the Carpathians filling the middle of the country, the Black Sea to the south-east, and the Danube flowing across the south before forming a delta at the south-eastern tip. On 1 January 2026 its resident population was about 19.04 million (National Institute of Statistics). The land is roughly three concentric rings: the Transylvanian Plateau enclosed by mountains in the middle, a ring of Carpathian mountains and Subcarpathian hills around it, and plains, the Dobrogea Plateau and the Danube Delta beyond.",
    howItWorks:
      "Under the constitution, Romania's territory is divided into communes (comună), towns (oraș) and counties (județ), with some larger towns designated as municipalities (municipiu); there are 41 counties plus the city of Bucharest, which has county status, and in 2025 the country had 103 municipalities, 216 towns and 2,862 communes. Communes, towns and municipalities each have an elected local council and a directly elected mayor, and counties have an elected county council and council president. In addition, the central government appoints a prefect in each county and in Bucharest as its representative; the prefect has no authority over local councils or mayors but can challenge unlawful local decisions in the administrative courts. Locals give locations by town and county. Railways, roads and domestic flights set the radius of life: from Bucharest, trains to the big cities of the west and Transylvania often take anywhere from five to more than ten hours. Newcomers most often go wrong by assuming Romania uses the euro — it is an EU member but uses its own currency, the leu.",
    layout:
      "The capital, Bucharest, lies on the Romanian Plain in the south; the Black Sea coast and Constanța are in the south-east; in the middle, ringed by the Carpathian arc, is Transylvania, with Brașov, Sibiu, Sighișoara and Cluj-Napoca at the foot of the mountains and in its basins; Timișoara and Oradea stand on the Western Plain; and the Danube Delta is at the country's south-eastern tip.",
    gettingAround:
      "Bucharest Henri Coandă International Airport is the main gateway, and cities such as Cluj-Napoca, Timișoara and Oradea have scheduled domestic flights to Bucharest. Trains are run by the national passenger rail company CFR Călători: from Bucharest North station it takes a little over 2 hours to Brașov or Constanța, about 5½ to 6½ hours to Sibiu, about 9 to 10 hours to Cluj-Napoca and about 11 hours to Timișoara. Drivers must buy an electronic road vignette (rovinietă) in advance to use national roads and motorways, and dipped headlights or daytime running lights are required during the day. Romania uses the leu; internal Schengen air and sea border controls were lifted on 31 March 2024, and land border checks on 1 January 2025.",
    culture:
      "The official language is Romanian, a Romance language, and English is widely spoken in the big cities and in tourism. Traditional foods include polenta (mămăligă), grilled minced-meat rolls (mici) and sour soup (ciorbă). Tipping is voluntary; since 2023, tips left in restaurants have been printed as a separate line on the till receipt. Electricity is 230 V with European two-pin round plugs.",
    seeAndDo:
      "Cities: the old town and Palace of the Parliament in Bucharest, Brașov's old town and Black Church, the upper and lower towns of Sibiu, the citadel of Sighișoara, the squares of Timișoara, the Art Nouveau streets of Oradea and the peninsula old town of Constanța. Nature: the national parks of the Carpathians, the Danube Delta and the Black Sea coast. World Heritage sites include the Historic Centre of Sighișoara, the Villages with Fortified Churches in Transylvania and the Danube Delta.",
    whenAndTips:
      "May–June and September–October are mild and suit cities and mountains; July–August is peak season on the Black Sea beaches and hot on the plains; in winter the mountains offer skiing. Trains between cities are slow, so for long distances consider domestic flights. Drivers should buy the road vignette before setting off.",
  },
  bucharest: {
    // 全七段 sources: 同中文侧（RPL2021 tier 1; INS TEMPO tier 1; Administrative Code via mirror tier 2; Palace of the Parliament International Conference Centre site tier 1; CFR Călători tier 1; en.wikipedia / OSM tier 3, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Bucharest, the capital of Romania, lies on the southern plain on both banks of the Dâmbovița, with a resident population of about 1.717 million in the 2021 census (National Institute of Statistics). First mentioned in documents in 1459, it became the capital in 1862. The city combines the old-town lanes around Lipscani with broad boulevards and monumental buildings; the Palace of the Parliament, home to the Chamber of Deputies, the Senate and the Constitutional Court, has a built area of about 365,000 m².",
    howItWorks:
      "Bucharest is a municipality with county status and a two-tier administration: the whole city has an elected General Mayor and the General Council of Bucharest, and each of its 6 sectors has an elected sector mayor and sector council; under the Administrative Code, decisions of the General Council and normative orders of the General Mayor are binding on the sectors too. The 6 sectors fan out from the centre, so each includes a corner of the city centre as well as outer residential districts — the old town is in Sector 3 and the Palace of the Parliament in Sector 5. Addresses give the sector number (Sector) instead of a county, while in daily speech people use neighbourhood names. The metro, buses and trams set the radius of daily life, and suburban population growth in recent years has been mainly in Ilfov County, which surrounds the capital. Newcomers most often go wrong by assuming the main airport is in the city — Henri Coandă Airport is at Otopeni in Ilfov County, about 15.5 km in a straight line from the old town and a little over 20 minutes by train from the North station.",
    layout:
      "The old town lies on the north bank of the Dâmbovița, with Lipscani Street and Stavropoleos Monastery; south-west of the old town is the Palace of the Parliament; north of the old town, Calea Victoriei links the National Museum of Art and the Romanian Athenaeum; further north are the Arcul de Triumf and King Michael I Park, with the Village Museum by the park's lake; the North station is north-west of the old town; and the airport is north of the city in Ilfov County.",
    gettingAround:
      "Henri Coandă International Airport is about 15.5 km in a straight line from the old town; direct trains from Bucharest North take about 20 to 25 minutes, and there is also an airport bus (route 100 since December 2023). The city has a metro, buses, trams and trolleybuses, and the old town is best on foot. For Brașov, Constanța, Sibiu and other cities take CFR trains from the North station; for the big western cities such as Cluj-Napoca and Timișoara, domestic flights are also an option.",
    culture:
      "Romanian is spoken, and English is widespread. The Romanian Athenaeum is home to the George Enescu Philharmonic; the Village Museum brings together traditional farmhouses from all over the country. Old-town restaurants and taverns cluster around Lipscani. Visits to the Palace of the Parliament must be booked in advance and require an identity document.",
    seeAndDo:
      "Old town: Lipscani Street and Stavropoleos Monastery. The Palace of the Parliament (booked tours). Along Calea Victoriei: the National Museum of Art and the Romanian Athenaeum. In the north: the Arcul de Triumf, King Michael I Park and the Village Museum. Cișmigiu Gardens in the centre.",
    whenAndTips:
      "May–June and September–October are the most comfortable; July–August is hot; winter is cold. Palace of the Parliament tours have limited places, so book ahead. Taking the train from the airport avoids road congestion at rush hour.",
  },
  "cluj-napoca": {
    // 全七段 sources: 同中文侧（RPL2021 tier 1; Cluj Airport website tier 1; CFR Călători tier 1; en.wikipedia tier 3 for history, districts and the UNESCO Creative City title, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Cluj-Napoca, a city in Transylvania in north-western Romania and the seat of Cluj County, lies in the valley of the Someșul Mic, with a resident population of about 287,000 in the 2021 census (National Institute of Statistics). The \"Napoca\" in its name comes from the Roman settlement here. It is a university city, and the students of Babeș-Bolyai University give it a young, lively feel.",
    howItWorks:
      "Cluj-Napoca is run by an elected local council and a directly elected mayor and is also the seat of Cluj County; the city is divided into neighbourhoods (cartier), which have no administrative role and serve only as the language locals use for directions. The centre is Union Square, with St Michael's Church standing in its middle and the Bánffy Palace and old-town lanes around it, and the city spreads east and west along the Someșul Mic valley from there. Buses, trolleybuses and walking set the radius of daily life, with university buildings spread inside and outside the old town. Newcomers most often go wrong by assuming the well-known Turda Salt Mine is in Cluj — it is in the separate city of Turda, about 25 km in a straight line from central Cluj-Napoca.",
    layout:
      "The old town lies south of the Someșul Mic, with Union Square in the middle and the Romanian National Opera east of the square; Cetățuia Hill on the north bank looks over the old town; the botanical garden is south of the old town; and the city stretches east and west along the valley, with the airport to the east.",
    gettingAround:
      "Cluj International Airport is about 7.5 km in a straight line from the centre, with scheduled domestic flights to Bucharest as well as international routes. A direct train from Bucharest takes about 9 to 10 hours, so many people fly. The city has buses and trolleybuses, and the old town is walkable.",
    culture:
      "Cluj-Napoca is a university city and one of the cultural centres of Transylvania, with a National Theatre and the Romanian National Opera; in 2021 it joined the UNESCO Creative Cities Network as a City of Film. The Bánffy Palace is now the Cluj Art Museum.",
    seeAndDo:
      "Union Square and St Michael's Church, the Bánffy Palace (Cluj Art Museum), the old-town lanes, the Romanian National Opera, the botanical garden and the Cetățuia Hill viewpoint. Day trips: the Turda Salt Mine and Turda Gorge in Turda.",
    whenAndTips:
      "May–June and September–October are the most comfortable; summer brings music and film festivals, when accommodation is tight; winter is cold. From Bucharest, flying saves a great deal of time over the train.",
  },
  timisoara: {
    // 全七段 sources: 同中文侧（RPL2021 tier 1; European Commission culture page tier 1; Timișoara Airport flight board tier 1; CFR Călători tier 1; en.wikipedia / OSM tier 3 for urban history and districts, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Timișoara, a city on Romania's Western Plain and the seat of Timiș County, is crossed by the Bega Canal and had a resident population of about 251,000 in the 2021 census (National Institute of Statistics). Its old town is a chain of squares lined with Baroque and Art Nouveau buildings, often nicknamed \"Little Vienna\", and in 2023 it was one of the European Capitals of Culture.",
    howItWorks:
      "Timișoara is run by an elected local council and a directly elected mayor and is also the seat of Timiș County. The city's layout comes from its fortress: from the 18th century the city grew inside and outside the fortress, and when the walls were demolished at the end of the 19th century the old bastion belt became boulevards and new districts, so the old town, the Citadel (Cetate), is ringed by historic districts such as Fabric, Iosefin and Elisabetin — names locals still use for directions, though they have no administrative role. The old town's axis is a chain of three squares — Union, Liberty and Victory — with the opera house and the Metropolitan Cathedral at either end of Victory Square. Trams, buses and walking set the radius of daily life, and the banks of the Bega Canal are a route for walking and cycling. Newcomers most often go wrong by assuming the train to Bucharest is convenient — a direct train takes about 11 hours, and domestic flights are more common between the two cities.",
    layout:
      "The old town lies north of the Bega Canal, with Union Square in the north, Liberty Square in the middle and Victory Square running south to the Metropolitan Cathedral by the canal; the opera house stands at the northern end of Victory Square; the Maria Theresia Bastion is a surviving section of the fortifications; the Rose Park lies along the canal; and the airport is to the north-east.",
    gettingAround:
      "Timișoara International Airport is about 10 km in a straight line from the centre, with scheduled domestic flights to Bucharest. A direct train from Bucharest takes about 11 hours. The city has trams and buses, the old-town squares are within walking distance of one another, and paths run along the Bega Canal.",
    culture:
      "The old town's Baroque and Art Nouveau buildings cluster around the three squares, and the opera and the National Theatre share the building at the northern end of Victory Square. The Bega Canal was dug in the 18th century and is now lined with parks and paths. The city is known for its parks, including the Rose Park, and is also called \"the City of Roses\".",
    seeAndDo:
      "Union Square, Liberty Square, Victory Square and the opera house, the Metropolitan Cathedral, Huniade Castle (Banat Museum), the Maria Theresia Bastion, and the Bega Canal paths and Rose Park.",
    whenAndTips:
      "May–June and September–October are the most comfortable, with roses in bloom in early summer; July–August is hot. From Bucharest, flying is recommended.",
  },
  brasov: {
    // culture sources（2026-09-15 核实，fix）: https://en.wikipedia.org/wiki/Biserica_Neagr%C4%83 (3级) + https://www.monitorulexpres.ro/2026/04/22/incendiul-din-21-aprilie-1689-noaptea-care-a-transformat-pentru-totdeauna-biserica-neagra-din-brasov/ (3级)
    // identity sources（2026-09-15 核实，fix）: https://en.wikipedia.org/wiki/Biserica_Neagr%C4%83 (3级，引 Judit Petki 2019 年研究) + https://www.monitorulexpres.ro/2026/04/22/incendiul-din-21-aprilie-1689-noaptea-care-a-transformat-pentru-totdeauna-biserica-neagra-din-brasov/ (3级本地媒体，2026-04 复核同一结论)
    // 全七段 sources: 同中文侧（RPL2021 tier 1; Bran Castle operator website tier 1; UNESCO 596 tier 1; CFR Călători tier 1; en.wikipedia / ro.wikipedia / OSM tier 3 for districts and the Black Church, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，黑教堂「1689 年大火熏黑得名」是流传说法，改正为 19 世纪污染、名称 19 世纪末见于文献；其余 ok）。
    identity:
      "Brașov, a city in south-eastern Transylvania and the seat of Brașov County, is ringed by the Carpathians, with the forested Mount Tâmpa rising right beside its old town, and had a resident population of about 238,000 in the 2021 census (National Institute of Statistics). The old town centres on Council Square and the Black Church, whose blackened walls gave it its name; Bucharest is just over two hours away by train.",
    howItWorks:
      "Brașov is run by an elected local council and a directly elected mayor and is also the seat of Brașov County. The city has three parts: the walled old town, with Council Square, the Black Church and Catherine's Gate; the old Șchei district outside the walls to the south-west; and the new town to the north, centred on the railway station. Mount Tâmpa rises immediately east of the old town, and sections of the fortifications such as the White Tower can still be seen on the slopes. Locals give directions by old town, Șchei and new town. Buses and walking set the radius of daily life, and the city limits reach up into the mountains to the Poiana Brașov ski area. Newcomers most often go wrong by assuming Bran Castle is in Brașov — it is in the commune of Bran, about 22 km in a straight line from the old town, and needs a bus or car.",
    layout:
      "The old town sits at the foot of the western side of Mount Tâmpa, with Council Square in the middle and the Black Church to its south-west; Catherine's Gate is at the south-western corner of the old town, with the Șchei district beyond; the White Tower stands on the slope north-west of the old town; the new town and railway station are north-east of the old town; Poiana Brașov is up in the mountains to the south; and Bran Castle guards a mountain pass to the south-west.",
    gettingAround:
      "Direct trains from Bucharest North take about 2 hours 15 minutes to 2 hours 46 minutes, with frequent departures. Brașov-Ghimbav Airport is about 8.7 km in a straight line from the old town and handles mainly international routes and charters. Buses are the main transport in town, and the old town is walkable; a cable car and footpaths climb Mount Tâmpa; take a bus or drive to Bran Castle.",
    culture:
      "The Black Church is the old town's great Gothic landmark; a fire did strike it in 1689, but research now attributes its blackened walls to 19th-century industrial pollution rather than the fire, and the name Black Church is not recorded until the late 19th century. Council Square is lined with brightly coloured old houses. Bran Castle traces its history to a fortress the king authorised the city of Brașov to build in 1377; today it is a popular attraction thanks to its association with the novel Dracula.",
    seeAndDo:
      "Council Square, the Black Church, Catherine's Gate, the White Tower viewpoint, Mount Tâmpa (by cable car or on foot) and the old Șchei district. Around the city: Bran Castle in the commune of Bran, the fortified church of Prejmer (part of the World Heritage Villages with Fortified Churches in Transylvania), and skiing at Poiana Brașov in winter.",
    whenAndTips:
      "May to October suits walking in the old town and the mountains; December to March is ski season at Poiana Brașov. Bran Castle is crowded on summer weekends, so go early. Mountain weather changes quickly, so bring a jacket for Mount Tâmpa.",
  },
  sibiu: {
    // 全七段 sources: 同中文侧（RPL2021 tier 1; European Commission culture page tier 1; ASTRA Museum website tier 1; CFR Călători tier 1; en.wikipedia / OSM tier 3 for the upper and lower towns, guilds and Păltiniș, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Sibiu, a city in southern Transylvania and the seat of Sibiu County, lies in a basin on the northern side of the Southern Carpathians, with a resident population of about 134,000 in the 2021 census (National Institute of Statistics). A medieval trading city with thriving craft guilds, its old town is divided into an upper and a lower town; in 2007 Sibiu was one of the European Capitals of Culture.",
    howItWorks:
      "Sibiu is run by an elected local council and a directly elected mayor and is also the seat of Sibiu County. The old town has two levels: the upper town is the terrace with the Great Square, the Small Square and the churches, and the lower town is the old quarter below the slope along the river, linked to the upper town by steps, passageways and the Bridge of Lies. Locals give directions by upper town, lower town and square names. The city covers more than its urban area: the ASTRA Open-Air Museum in the Dumbrava forest on the southern edge and the Păltiniș ski area in the mountains are both administered by the city of Sibiu. Buses and walking set the radius of daily life. Newcomers most often go wrong by assuming Sibiu is close to Bucharest — a direct train takes five and a half to six and a half hours.",
    layout:
      "In the upper town the Great Square and the Small Square adjoin each other, with the Brukenthal National Museum on the west side of the Great Square and the Council Tower between the two squares; the Bridge of Lies leads from the Small Square towards the lower town; the lower town lies below the slope to the north of the upper town; the ASTRA Open-Air Museum is in the forest south of the city; and the airport is to the west.",
    gettingAround:
      "Sibiu International Airport is about 5.2 km in a straight line from the Great Square and serves mainly international routes, with no scheduled domestic flights. A direct train from Bucharest takes about 5½ to 6½ hours. The city has buses, and the old town is walkable; take a bus or taxi to the ASTRA Open-Air Museum.",
    culture:
      "In the Middle Ages Sibiu was a city of flourishing craft guilds, with 19 guilds already recorded in 1376. The Brukenthal National Museum has been open to the public since 1817. The ASTRA Open-Air Museum covers about 96 ha, with about 10 km of paths and more than 400 traditional buildings from across the country. The city holds an international theatre festival every year.",
    seeAndDo:
      "The Great and Small Squares, the view from the Council Tower, the Bridge of Lies, the Brukenthal National Museum, the lanes of the lower town and the ASTRA Open-Air Museum. Around the city: Păltiniș in the Southern Carpathians and the Villages with Fortified Churches in Transylvania.",
    whenAndTips:
      "May to October is best, with plenty of outdoor events and festivals in summer; the Great Square hosts a Christmas market in December; winter is cold. The ASTRA Open-Air Museum is large, so allow half a day.",
  },
  constanta: {
    // 全七段 sources: 同中文侧（RPL2021 tier 1; CFR Călători tier 1; en.wikipedia / OSM / Nominatim tier 3 for Tomis, Ovid, the Casino building and Mamaia, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Constanța, Romania's Black Sea port city in the south-east and the seat of Constanța County, had a resident population of about 264,000 in the 2021 census (National Institute of Statistics). It grew from the ancient Greek colony of Tomis, and the Roman poet Ovid was exiled here. The old town sits on a peninsula reaching into the sea, and to the north lies the beach resort of Mamaia.",
    howItWorks:
      "Constanța is run by an elected local council and a directly elected mayor and is also the seat of Constanța County. The city stretches along the coast: the peninsula jutting into the sea in the south is the old town, where Ovid Square, the History and Archaeology Museum, the Roman Mosaic Edifice, the Genoese Lighthouse and the seafront Casino are all within a few hundred metres of one another; the port lies to the south and west of the old town; and to the north, on the narrow strip between Lake Siutghiol and the Black Sea, is the Mamaia resort, also within the city limits. Locals give directions by peninsula old town, city centre and Mamaia. Buses and walking set the radius of daily life, and in summer the crowds concentrate along the coastal resorts. Newcomers most often go wrong by assuming Constanța's airport is on the edge of the city — Mihail Kogălniceanu Airport is in another commune, about 24 km in a straight line from the centre.",
    layout:
      "The old town is on the peninsula in the south, with Ovid Square in the middle and the Casino and Genoese Lighthouse on the seaward side; the port lies to the south and west of the peninsula; newer districts spread north and west; Mamaia lies between the lake and the sea north of the city, about 8 km from the centre in a straight line; and the airport is to the north-west.",
    gettingAround:
      "Mihail Kogălniceanu International Airport is about 24 km in a straight line from the centre and has no scheduled domestic flights. Direct trains from Bucharest North take about 2 hours, with frequent departures and more in summer. The city has buses, the peninsula old town is walkable, and buses run to Mamaia.",
    culture:
      "The peninsula old town preserves remains from the days of Tomis onwards: the Roman Mosaic Edifice and the ancient finds in the History and Archaeology Museum. The seafront Casino, an Art Nouveau building completed in 1910, is the city's landmark. In summer the coast around Mamaia is a popular holiday destination for Romanians.",
    seeAndDo:
      "Ovid Square, the National History and Archaeology Museum, the Roman Mosaic Edifice, the Genoese Lighthouse, the seafront promenade and the Casino building; the beach resort of Mamaia; Lake Siutghiol.",
    whenAndTips:
      "June to September is beach season, with Mamaia busiest and accommodation tight in July–August; May and October are quieter and mild; winter brings strong sea winds.",
  },
  oradea: {
    // 全七段 sources: 同中文侧（RPL2021 tier 1; Oradea Airport flight table tier 1; CFR Călători tier 1; en.wikipedia / OSM / Nominatim tier 3 for layout and architecture, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Oradea, a city in north-western Romania and the seat of Bihor County, is crossed by the Crișul Repede and had a resident population of about 183,000 in the 2021 census (National Institute of Statistics). The city is known for its early-20th-century Art Nouveau buildings and its 18th-century Baroque architecture, and Union Square with the Black Eagle Palace is its most familiar image.",
    howItWorks:
      "Oradea is run by an elected local council and a directly elected mayor and is also the seat of Bihor County. The Crișul Repede divides the city into two banks: the south bank is the \"New Town\" centred on Union Square, where the Black Eagle Palace and the Art Nouveau streets are concentrated, and the pentagonal fortress east of the centre is also on this bank; the north bank has the Baroque cathedral and 18th-century districts. Locals give directions by the district names on either bank. Trams, buses and walking set the radius of daily life. Newcomers most often go wrong by assuming the train to Bucharest is convenient — there is only one direct train, an overnight service of about 14 hours, and domestic flights are more common between the two cities.",
    layout:
      "The Crișul Repede flows east to west through the centre; on the south bank are Union Square, the Black Eagle Palace and the Art Nouveau streets, with Oradea Fortress east of Union Square; the north bank is the area around the Baroque cathedral; the airport is a short way south of the city; and Băile Felix is in the commune of Sânmartin to the south.",
    gettingAround:
      "Oradea International Airport is about 3.8 km in a straight line from Union Square, with scheduled domestic flights to Bucharest. The only direct train to Bucharest is an overnight service of about 14 hours; the train to Cluj-Napoca takes about 4 hours. The city has trams and buses, and the centre is walkable.",
    culture:
      "Oradea was rebuilt in Baroque style in the 18th century, and in the early 20th century a wave of Art Nouveau buildings influenced by the Vienna Secession and other styles went up; the city is a member of the European network of Art Nouveau cities. The Black Eagle Palace is an Art Nouveau complex with a glass-roofed arcade. Băile Felix, south of the city, is a thermal spa resort.",
    seeAndDo:
      "Union Square and the Black Eagle Palace, the Art Nouveau streets, Oradea Fortress, the Crișul Repede riverside promenade and the Baroque cathedral. Around the city: the thermal spa of Băile Felix in the commune of Sânmartin.",
    whenAndTips:
      "May to October is best for walking and looking at the architecture; winter is cold, and the thermal spas are a good option. From Bucharest, flying is recommended.",
  },
  sighisoara: {
    // 全七段 sources: 同中文侧（RPL2021 tier 1; UNESCO whc 902 and 596 tier 1; CFR Călători tier 1; en.wikipedia tier 3 for the citadel, Clock Tower and festival, 2026-09-15）。 核实 2026-09-15 当批（content-verifier 独立检索，全部 ok）。
    identity:
      "Sighișoara is a small town in the Târnava Mare valley in central Transylvania, in Mureș County, with a resident population of about 24,000 in the 2021 census (National Institute of Statistics). Its hilltop citadel keeps its towers, walls and medieval lanes, and was inscribed on the World Heritage List in 1999 as the Historic Centre of Sighișoara, which UNESCO describes as an example of a small fortified medieval town.",
    howItWorks:
      "Sighișoara is a municipality (municipiu) run by an elected local council and a directly elected mayor, but it is not the county seat; the seat of Mureș County is Târgu Mureș. The town has two levels: on the hilltop is the walled citadel, with the Clock Tower, Citadel Square and the Church on the Hill, and people still live inside the citadel; below it, along the Târnava Mare valley, is the lower town with the railway station, shops and newer housing. Locals simply say \"the citadel\" and \"the lower town\". Daily life is compact, and the citadel can be walked end to end in a quarter of an hour. Newcomers most often go wrong by thinking the World Heritage site is just the Clock Tower — the whole hilltop citadel, with its lanes and walls, is within the inscribed area.",
    layout:
      "The citadel is on the hilltop, and the Clock Tower is the main gate tower leading up from the lower town; Citadel Square lies west of the Clock Tower; a covered wooden staircase climbs on from the citadel to the Church on the Hill; the lower town is in the river valley north of the hill, with the railway station across the river; and the fortified church of Biertan lies to the south-west.",
    gettingAround:
      "Sighișoara has no airport with scheduled flights; the nearest is Târgu Mureș, about 40 km away in a straight line. Direct trains from Bucharest North take about 6 hours 10 minutes to 6 hours 50 minutes, and from Brașov about 3½ to 4½ hours. The citadel can only be explored on foot, with plenty of slopes. Biertan requires a car or hired driver.",
    culture:
      "The Clock Tower is 64 m high and now houses a history museum, with views from the top over the citadel and the valley. The covered wooden staircase leads up to the church and school on the hill. Every July the citadel hosts a medieval festival, with costumed performances and markets in the lanes.",
    seeAndDo:
      "The Clock Tower and history museum, Citadel Square, the walls and towers, the covered staircase and Church on the Hill, and the medieval lanes of the citadel. Nearby: the fortified church of Biertan, one of the World Heritage Villages with Fortified Churches in Transylvania.",
    whenAndTips:
      "May to October is best, with the most visitors during the medieval festival in July; the citadel's cobbled lanes are steep and slippery, so wear non-slip shoes. Sighișoara combines well with Brașov and Sibiu on a Transylvania itinerary.",
  },
  craiova: {
    // 全七段 sources: 同中文侧（INS RPL2021 table 1.3.2, tier 1; ADR South-West Oltenia, tier 1; Craiova Airport website, tier 1; Craiova city hall history page, tier 1; Oltenia Museum, tier 1; Eco Urbis, tier 1; Craiova Art Museum, tier 1; clubferoviar.ro, tier 2; distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Craiova is the seat of Dolj County in south-western Romania, on the plain on the left bank of the Jiu River, with about 234,000 residents in the 2021 census (National Institute of Statistics) — the most populous of the five county seats in the South-West Oltenia development region. It first appears in documents in 1475, its historic centre keeps the Casa Băniei begun in the late 15th century, and the sculptor Brâncuși studied at its school of arts and crafts as a young man.",
    howItWorks:
      "Craiova is run by an elected mayor and local council and is also the seat of Dolj County; the 'Oltenia' people talk about is not a tier of government but a historical region name, and although the South-West Oltenia regional development agency has its headquarters here, the development region is only a planning and statistical unit. One division of responsibility is easy to miss: Craiova International Airport on the edge of town belongs to the county, as a county-owned autonomous company, not to the city. The historic centre is around Mihai Viteazul Square, with the art museum, the national theatre, the metropolitan cathedral and the Casa Băniei all within a few hundred metres on foot, and the railway station about 2 km to the north-east. Addresses use six-digit postcodes, Craiova's beginning with 200. The most common misunderstanding is that you can fly from here to Bucharest: the airport currently has only international scheduled flights, and the train to the capital takes about 4 hours, so flying abroad from Craiova is easier than flying to the capital.",
    layout:
      "The historic centre is around Mihai Viteazul Square: the art museum (the Jean Mihail Palace) is on the square, the national theatre to the east, and the Casa Băniei and the metropolitan cathedral a few hundred metres to the south-west; the railway station is about 2 km to the north-east; Nicolae Romanescu Park is about 2.6 km to the south; the airport is about 7.5 km east of town in a straight line.",
    gettingAround:
      "Craiova International Airport (CRA) is about 7.5 km from the historic centre in a straight line and has only international scheduled flights; city bus route 9 serves the airport (as of September 2026). Craiova station is a rail hub, about 4 hours from Bucharest North. The city has buses, and the historic centre is walkable.",
    culture:
      "Romanian is spoken locally. Churches are in use, so dress modestly when visiting. The art museum has a Brâncuși room holding several of his early works. The Oltenia Museum has several sections, its ethnography section housed in the Casa Băniei.",
    seeAndDo:
      "Mihai Viteazul Square and the historic centre; the Brâncuși room at the Craiova Art Museum; the Casa Băniei (the Oltenia Museum's ethnography section); the Marin Sorescu National Theatre; Nicolae Romanescu Park (opened in 1903, with a lake, islands and a suspension bridge).",
    whenAndTips:
      "Spring and autumn are the most comfortable; summers are hot and winters cold. It is a starting point for Brâncuși's ensemble in Târgu Jiu — the two cities are linked through the sculptor.",
  },
  "targu-jiu": {
    // 全七段 sources: 同中文侧（INS RPL2021 table 1.3.2, tier 1; ADR South-West Oltenia, tier 1; UNESCO 1473, tier 1; clubferoviar.ro, tier 2; CNAIR notices, tier 1; Romsilva via search summary, tier 2; distances computed）。 核实 2026-09-15 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Târgu Jiu is the seat of Gorj County in south-western Romania, on the Jiu River, with about 73,500 residents in the 2021 census (National Institute of Statistics). The memorial ensemble the sculptor Constantin Brâncuși created here in 1937–1938 was inscribed as a World Heritage site in 2024 as the 'Brâncuși Monumental Ensemble of Târgu Jiu', commemorating those who died defending the city in the First World War.",
    howItWorks:
      "Târgu Jiu is run by an elected mayor and local council and is the seat of Gorj County; the South-West Oltenia development region has only a regional office here, its headquarters being in Craiova. The city's central axis is Brâncuși's work itself: an axis about 1.5 km long runs across town along the Avenue of the Heroes, with the Table of Silence, the Gate of the Kiss and the Alley of Chairs in the Brâncuși Park by the Jiu River at the western end, the long-standing Church of the Holy Apostles Peter and Paul in the middle, and the Endless Column in the park at the eastern end. Addresses use six-digit postcodes beginning with 210. Daily life is shaped by roads and rail: the nearest airport with scheduled flights is in Craiova, about 90 km away in a straight line, and the railway heads north through the Jiu Gorge. The most common misunderstanding is to think the Brâncuși ensemble is a single sculpture park, when it is a memorial axis crossing the city with its two ends 1.5 km apart in a straight line and streets and a church in between, walked from one end to the other.",
    layout:
      "Brâncuși Park is by the Jiu River on the west side of town, with the Table of Silence and the Gate of the Kiss inside it; from the park the Avenue of the Heroes runs east past the Gorj County Museum area and the Church of the Holy Apostles Peter and Paul to the park at the eastern end with the Endless Column; the railway station lies south of the axis; Brâncuși's childhood home is in the village of Hobița, about 17 km west of town in a straight line.",
    gettingAround:
      "Târgu Jiu has no airport with scheduled flights; the nearest is Craiova International (CRA, about 93 km in a straight line), with Sibiu (SBZ) about 105 km. The railway runs on the Bucharest–Craiova–Petroșani line. North of town the road enters the mountains through Jiu Gorge National Park, whose southern entrance is about 18 km from town in a straight line; the high section of the Transalpina mountain road is closed in winter, with opening dates as announced by the national road company. In town you can walk the whole ensemble along the Avenue of the Heroes.",
    culture:
      "Romanian is spoken locally. The Church of the Holy Apostles Peter and Paul is in use, so dress modestly when visiting. The Brâncuși ensemble is a memorial, so don't climb on the sculptures.",
    seeAndDo:
      "A walk from the Table of Silence and the Gate of the Kiss along the Avenue of the Heroes to the Endless Column; the Alley of Chairs in Brâncuși Park; the Gorj County Museum; Brâncuși's childhood home in Hobița outside town; the Jiu Gorge to the north.",
    whenAndTips:
      "Late spring to early autumn is best for walking the ensemble; winters are cold and the high mountain road is closed. The two ends of the ensemble are 1.5 km apart in a straight line, so allow half a day.",
  },

  sinaia: {
    // 全七段 sources: 同中文侧（INS RPL2021 table 1.3.2, tier 1; Transport Urban Sinaia official site, tier 1; peles.ro, tier 1; Sinaia town hall geography and history pages, tier 1; ANAF on tips, tier 1; distances computed）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（content-verifier 独立检索，正文 ok；市属公司统管公交与索道一项未取到第二来源，记 unknown）。
    identity:
      "Sinaia is a mountain town in Romania's Prahova valley, with a resident population of 9,071 at the 2021 census (INS), lying between 798 and 1,055 m above sea level on the south-eastern slope of the Bucegi massif. The town takes its name from Sinaia Monastery, founded in 1695 and itself named after Mount Sinai; Peleș Castle, built in the late 19th century for King Carol I, stands on the hillside north-west of town.",
    howItWorks:
      "Sinaia is a town (oraș) with an elected mayor and local council, but it is not a county seat — that is Ploiești, for Prahova County. The municipal company runs both the town buses and every cableway on the mountain, with two cable-car sections, two gondola sections and several chairlifts and tows on one ticket card; Peleș and Pelișor castles, by contrast, belong to the Peleș National Museum and not to the town. The built-up area is stretched north to south along the national road and railway in the Prahova valley, climbing from 798 m to 1,055 m: the station, Ghica Park, the casino building and the monastery are all within a few hundred metres of one another, the castles are on the hillside to the north-west, and the cable-car base station is to the south. The railway to Bucharest, opened in 1879, the roads built earlier, and the castles together turned this into a resort. Newcomers often place Peleș Castle in Brașov or on the edge of Bucharest, when it is about 1.1 km north-west of the town centre; many also expect to walk straight in, when tickets have to be bought in advance through official channels for a set time slot.",
    layout:
      "The town centre is around Bulevardul Carol I and Ghica Park: the railway station is about 200 m east, the casino building about 400 m north-east, and Sinaia Monastery about 300 m north-west. Peleș Castle is about 1.1 km north-west on the hillside, with Pelișor and Foișor further north-west again; the cable-car base station is about 500 m south-west.",
    gettingAround:
      "Sinaia has no airport with scheduled flights; the nearest is Brașov, about 39 km away in a straight line, and Bucharest's airport is about 97 km away in a straight line. The town is on the Bucharest–Brașov main railway line and the national road, with the station about 200 m from the centre. The mountain is reached by cable car and gondola on a single ticket card. The climate is a mountain one: the weather station has been running since 1888, the mean annual temperature is about 6°C and annual precipitation more than 800 mm (town hall), with snow in winter.",
    culture:
      "The official language is Romanian. Sinaia Monastery is a working monastery, so dress modestly when visiting. Tipping is voluntary; since 2023, tips left in restaurants are itemised separately on the receipt.",
    seeAndDo:
      "Peleș Castle (timed tickets must be bought in advance through official channels, and there are annual closures for cleaning and preventive conservation — check with the museum); Pelișor Castle; Sinaia Monastery; the casino building, completed in 1912 according to its operator and now a conference centre; Dimitrie Ghica Park; and the cable car up to the stations at 1,400 m and 2,000 m.",
    whenAndTips:
      "June–September suits walking in the mountains, and December to March is the snow season; opening hours for the castles and the cableways change with the season, so check before you go. It is high enough that summer nights are cool.",
  },

  "curtea-de-arges": {
    // 全七段 sources: 同中文侧（INS RPL2021 table 1.3.2, tier 1; Curtea de Argeș town hall geography, history and station pages, tier 1; CNAIR via media on the DN7C mountain section, tier 2; Hidroelectrica via media on Vidraru, tier 2; ANAF on tips, tier 1; distances computed）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Curtea de Argeș is a city in the north of Argeș County in Romania, with a resident population of 25,977 at the 2021 census (INS), set in the upper valley of the Argeș river on the southern flank of the Făgăraș mountains at an average altitude of about 450 m. In the 14th century it was the first capital of the principality of Wallachia, and its Princely Church of St Nicholas holds the earliest burials of the principality's rulers; a kilometre north of the centre stands the monastery church of Curtea de Argeș, built in the first decades of the 16th century.",
    howItWorks:
      "This is a city (municipiu) with an elected mayor and local council, but it is not the county seat — that is Pitești, about 36 km south in a straight line. The city runs north to south along the Argeș valley, and its two cores are about 1.1 km apart: at the south end the 14th-century Princely Court ruins and the Princely Church of St Nicholas, with the municipal museum right beside them; at the north end the monastery and its gardens, where an episcopal palace was built between 1886 and 1890. The city's name is its history: in 1247 this was the seat of a Wallachian ruler, in 1359 the principality's first metropolitan see was established at Argeș, the principality's first mint opened here late in the 14th century, and only in the first decade of the 16th century was the settlement renamed after the princely court, as \"the court of Argeș\". The railway station is about 1.3 km south, its building commissioned from an Italian architect in 1898. Newcomers often take the monastery and the princely church for one place, when they are a kilometre and two centuries apart; many also assume the 151-km road over the Făgăraș mountains starts here, when it begins near Pitești and this city is a gateway along it.",
    layout:
      "The centre lies in the middle of the built-up area: the Princely Church of St Nicholas and the Princely Court ruins are about 600 m south, with the municipal museum next to them; the monastery is about 1.1 km north; and the railway station is about 1.3 km south. The Vidraru reservoir and dam are about 25 km north in a straight line, along the road over the mountains.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest are Sibiu, about 85 km away in a straight line, and Brașov, about 91 km away in a straight line. The railway is the end of a branch line from Pitești, and reaching Bucharest means changing there. North of the city the DN7C crosses the Făgăraș mountains towards the road between Sibiu and Brașov; its high section opens only in summer and has daily time restrictions, with the dates set by the national roads company. The climate is that of a valley, with a mean annual temperature close to 8°C and frequent fog in spring and autumn (town hall).",
    culture:
      "The official language is Romanian. Both the monastery and the Princely Church of St Nicholas are working churches, so dress modestly and keep quiet inside. Tipping is voluntary; since 2023, tips left in restaurants are itemised separately on the receipt.",
    seeAndDo:
      "The monastery church and the episcopal palace in its gardens; the Princely Church of St Nicholas and the Princely Court ruins; the municipal museum; the railway station building designed in 1898; and a drive north along the mountain road to the Vidraru dam (the reservoir has been drawn down since August 2025 for refurbishment and refilling since April 2026, so as of September 2026 check the water level with the operator).",
    whenAndTips:
      "May–September is comfortable and covers the season when the high section of the mountain road is open; in winter that section is closed. Whether you may photograph church interiors is set locally.",
  },
};
