import type { TravelGuide } from "@/lib/travel-lesson";

export const TRAVEL_EN: Record<string, TravelGuide> = {
  "estonia-overview": {
    // 全七段 sources: 同中文侧。Population 1,360,745 on 1 Jan 2026 (Statistics Estonia, revised release 2026-04-21, tier 1); euro since 2011-01-01; Schengen 2007-12-21; 79 local governments = 15 cities + 64 rural municipalities after the 2017 reform; county governments abolished 2018-01-01; Type F/C 230 V, dipped headlights required at all times, tipping ~10% for excellent service (visitestonia.com); NyxAir operates Tallinn–Kuressaare and Tallinn–Kärdla under state contract (ERR); Virtsu–Kuivastu ~27 min, Rohuküla–Heltermaa ~1 h 15 min (praamid.ee). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；岛屿数「一千多个」改为两千多个，其余 ok）。
    identity:
      "Estonia lies on the eastern shore of the Baltic Sea, facing Finland across the Gulf of Finland, with a population of about 1.36 million on 1 January 2026 (Statistics Estonia). Most of the country is low and flat: the north coast is a limestone escarpment, the south is a landscape of glacial hills and lakes, and off the west coast lie Saaremaa, Hiiumaa and more than two thousand islands in all; bogs and forests cover much of the land.",
    howItWorks:
      "Local government in Estonia has a single tier: the 2017 reform merged 213 local governments into 79, of which 15 are cities (linn) and 64 are rural municipalities (vald), each run by an elected council; county governments were abolished in 2018, and the 15 counties remain only as territorial units. Since the mergers many towns belong to a surrounding rural municipality: the town of Kuressaare on Saaremaa is part of Saaremaa Parish, and the town of Otepää is part of Otepää Parish, so a population figure may refer to the town itself or to the whole municipality. The capital, Tallinn, is the political and transport centre, where ferries, the main airport and railways begin. Locals give directions by county and island names. Daily range is shaped by distance and season: the country is small, but winter days are short and snowy, and trips to the islands depend on ferry and flight schedules. The most common misunderstanding for newcomers is to take Pärnu as the \"summer capital\" and Otepää as the \"winter capital\" in any legal sense — both are ceremonial titles handed over from Tallinn each year.",
    layout:
      "Along the Gulf of Finland in the north are the capital Tallinn, the Lahemaa coast and the limestone escarpment, with Ida-Viru County further east; the centre is a belt of forest and bog with the Pandivere Upland; the south is the hill-and-lake country of Tartu, Viljandi, Otepää and the Haanja Upland; Lake Peipus lies in the east; the west has Pärnu, Haapsalu and Matsalu Bay, with the West Estonian Archipelago of Saaremaa, Hiiumaa and other islands offshore.",
    gettingAround:
      "Lennart Meri Tallinn Airport is the main international gateway. Scheduled domestic flights link Tallinn with Kuressaare on Saaremaa and Kärdla on Hiiumaa, operated by NyxAir under a state contract. Saaremaa can also be reached by ferry from Virtsu on the mainland to Kuivastu on Muhu, a crossing of about 27 minutes, then by road onto the island; Hiiumaa is reached by ferry from Rohuküla to Heltermaa, about 1 hour 15 minutes. Long-distance buses and Elron regional trains link the main towns. Traffic drives on the right, and headlights must be on at all times. Estonia has used the euro since 1 January 2011 and joined the Schengen Area in 2007.",
    culture:
      "The official language is Estonian, and English is widely spoken among younger people and in tourism. The sauna, Midsummer and the choral tradition are important parts of Estonian life, and bonfires are lit across the country on Midsummer Eve. Rye bread, smoked fish and dairy products are everyday food. The tourism board says a tip of around 10% is usual for excellent service but not obligatory. The supply is 230 V with European two-pin plugs.",
    seeAndDo:
      "Historic towns: Tallinn Old Town, the university town of Tartu, the episcopal castles of Kuressaare and Haapsalu, and the Order castle ruins of Viljandi and Rakvere. Nature: the coast and erratic boulders of Lahemaa National Park, the bogs and \"fifth season\" floods of Soomaa National Park, Kaali crater and Panga Cliff on Saaremaa, Suur Munamägi in the Haanja Upland, and Jägala Waterfall.",
    whenAndTips:
      "June to August has the longest days and the liveliest coast and islands; May and September are quieter and cool; winter is cold with very short days, and the Otepää area in the south is cross-country skiing country. Ferries to the islands have long queues on summer weekends, so drivers should book a place in advance. In the bogs, stay on the boardwalks; during the spring floods in Soomaa some roads are under water.",
  },
  tallinn: {
    // 全七段 sources: 同中文侧。Population 452,563 on 1 Jan 2026 (Statistics Estonia RV0240, tier 1); Old Town UNESCO 1997; Toompea Castle seat of parliament; 8 city districts each with a district government; free public transport for registered residents since 2013 (tallinn.ee); airport tram restored 2026-08-01 on lines T2/T4 (ERR); Rail Baltica Ülemiste terminal target 2030 (ERR). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；全部 ok）。
    identity:
      "Tallinn, the capital of Estonia, lies on the southern shore of the Gulf of Finland, with a population of about 453,000 on 1 January 2026 (Statistics Estonia). Its Old Town keeps the layout of a medieval Hanseatic town, with well-preserved walls, towers and Town Hall Square, and was inscribed on the World Heritage List in 1997; on Toompea hill above the Old Town stands the seat of today's parliament.",
    howItWorks:
      "Tallinn is run by an elected city council and city government, and the city is divided into eight districts, each with a district government headed by an elder responsible for community-level matters. The heart of the city is the Old Town: the Lower Town around Town Hall Square and its merchant streets, and the Upper Town with the castle and government buildings on Toompea hill. Locals give directions by district, and large residential districts such as Lasnamäe and Mustamäe, together with the Old Town, the port and the airport, make up the city's reference points. Daily range is shaped by public transport: since 2013, residents registered in Tallinn have ridden buses and trams free with a personal travel card, while visitors buy tickets. The most common misunderstanding for newcomers is that Tallinn is just the small Old Town — most residents live in the districts outside it, which is where the city's work and daily life are centred.",
    layout:
      "The Old Town sits on a low hill south of the port, divided into the upper town of Toompea and the lower town around Town Hall Square; east of the Old Town are Kadriorg Park and Palace, and further east the seafront of Pirita; to the north is the port and the North Tallinn area around the Seaplane Harbour museum; to the south and south-west are residential districts such as Mustamäe; the airport lies to the south-east, about 5.6 km in a straight line from the centre.",
    gettingAround:
      "Lennart Meri Tallinn Airport is about 5.6 km in a straight line from the centre; the airport tram, suspended for several years, returned on 1 August 2026, and buses also serve the airport. Buses and trams are the main city transport, and the Old Town is best on foot. Ferries sail from the port to Helsinki; Elron trains and long-distance buses go to Tartu, Pärnu and other towns; Saaremaa and Hiiumaa can be reached by domestic flight or ferry. Rail Baltica, which will connect to the European rail network, is under construction with a target of 2030.",
    culture:
      "Estonian is spoken and English is widespread. The medieval streets and walls of the Old Town are the city's calling card, and a Christmas market fills Town Hall Square in winter. The Seaplane Harbour and the Kadriorg Art Museum present maritime and art history. The tourism board says a tip of around 10% is usual for excellent service but not obligatory.",
    seeAndDo:
      "The Old Town: Town Hall Square, the walls and towers, Toompea Castle and its viewing platforms; Kadriorg Palace and Park; the Seaplane Harbour museum; the Pirita seafront; and day trips from Tallinn to Lahemaa National Park and Jägala Waterfall.",
    whenAndTips:
      "June to August has long days and the busiest Old Town and port; December brings the Christmas market; winter is cold with short days. On cruise-ship days the Old Town is crowded, and early morning and evening are quieter. The Old Town's cobbles are uneven, so wear comfortable shoes.",
  },
  tartu: {
    // 全七段 sources: 同中文侧。Population 99,900 (municipality) / 96,506 (city proper) on 1 Jan 2026 (Statistics Estonia RV0240); University of Tartu founded 1632 by King Gustav II Adolf of Sweden (ut.ee); Old Observatory part of the Struve Geodetic Arc, World Heritage 2005; Estonian National Museum new building opened 2016; Finnair Tartu–Helsinki under city contract 2024-03-31 to 2027-12-31 (tartu.ee). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；全部 ok）。
    identity:
      "Tartu is Estonia's second-largest city, on the banks of the Emajõgi River, with a population of about 99,900 in the city municipality on 1 January 2026 (Statistics Estonia). It is a university town: the University of Tartu was founded in 1632 by order of King Gustav II Adolf of Sweden, and its campus is woven into the old town; the Old Observatory on Toome Hill is one of the stations of the Struve Geodetic Arc, inscribed in 2005 as part of that World Heritage site.",
    howItWorks:
      "Tartu is run by an elected city council and city government, and in the 2017 reform it absorbed a neighbouring rural municipality, and at the start of 2026 the city municipality had about 99,900 people, of whom about 96,500 lived in the city of Tartu itself. The centre is the old town on the left bank of the Emajõgi: Town Hall Square, the university main building and the park and Old Observatory on Toome Hill are all within walking distance. Locals find their way by the river, Town Hall Square and Toome Hill. Daily rhythm follows the university: during term the town is full of students and lively, and noticeably quieter in the holidays. The most common misunderstanding for newcomers is to see Tartu as just an ordinary town outside Tallinn — the university, the Estonian National Museum and many research institutions make it one of Estonia's academic and cultural centres.",
    layout:
      "The old town lies on the left bank of the Emajõgi: Town Hall Square opens towards the river where the old stone bridge once stood, the university main building is behind the square, and above rises Toome Hill with the Old Observatory, the cathedral ruins and a park. The right bank is residential and commercial; Raadi, north of the centre, is home to the new building of the Estonian National Museum; the airport is south of the city, about 8 km in a straight line from the centre.",
    gettingAround:
      "Tartu Airport is about 8 km in a straight line from the centre and currently has scheduled Finnair flights to Helsinki (the city's contract runs to the end of 2027). Elron trains and long-distance buses from Tallinn are both convenient. Within the city, buses and bicycles are the main options, and the old town and Toome Hill are easy on foot.",
    culture:
      "Estonian is spoken and English is widespread, and the university gives the town a young, academic atmosphere. The \"Kissing Students\" sculpture on Town Hall Square is one of the town's symbols; the start of the academic year in autumn and student festivities in spring make the old town especially lively. The Estonian National Museum is the place to learn about Estonian folk culture and everyday history. The tourism board says a tip of around 10% is usual for excellent service.",
    seeAndDo:
      "Town Hall Square and the Town Hall; the University of Tartu main building and university museum; Toome Hill and the Old Observatory; the Estonian National Museum; St John's Church; the Emajõgi riverside walk; and trips from Tartu to Otepää and Lake Võrtsjärv.",
    whenAndTips:
      "May to June and September are the most pleasant, and the town is liveliest during term; in July and August the students are away and the town is quiet; winter is cold. Toome Hill has many slopes, and evening walks by the river and in the parks are the most comfortable.",
  },
  parnu: {
    // 全七段 sources: 同中文侧。Population 52,198 (municipality) / 40,934 (city proper) on 1 Jan 2026 (Statistics Estonia RV0240); 2017 merger with Audru, Paikuse, Tõstamaa; "summer capital" a ceremonial title handed over from Tallinn (ERR); Red Tower 15th century, Tallinn Gate 17th century, Mud Baths building 1927 (visitestonia); Pärnu airport EPU winter flights to Ruhnu only (airport.ee); passenger trains to Pärnu suspended since Dec 2018 (ERR). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；全部 ok）。
    identity:
      "Pärnu is a seaside town in south-western Estonia, where the Pärnu River flows into Pärnu Bay, with a population of about 52,200 in the city municipality on 1 January 2026 (Statistics Estonia). It is known for its long sandy beach, seaside spa tradition and summer events, and each summer it takes over the ceremonial title of \"summer capital\" from Tallinn. The old town keeps the 15th-century Red Tower and the 17th-century Tallinn Gate.",
    howItWorks:
      "Pärnu is run by an elected council, and in 2017 it merged with the neighbouring municipalities of Audru, Paikuse and Tõstamaa, and at the start of 2026 the city municipality had about 52,200 people, of whom about 40,900 lived in the town of Pärnu itself. The centre is the old town and seafront on the south bank of the river mouth: the old town has shopping streets and remains of the town gates, and a short walk south brings you to the beach park and the beach. Locals find their way by the river, the old town and the seafront. Daily life changes with the seasons: the seafront is packed in summer, and in winter the town returns to a small-town pace. The most common misunderstanding for newcomers is that \"summer capital\" means the government moves here for the summer — it is only a ceremonial title handed over from Tallinn each year.",
    layout:
      "The Pärnu River flows from east to west into Pärnu Bay, with jetties reaching into the bay on both sides of the mouth; the old town is on the south bank, where the Red Tower and Tallinn Gate stand; south of the old town are the beach park, the Mud Baths and the long beach; the north bank is residential and industrial.",
    gettingAround:
      "Pärnu's local airport has only small winter flights to the island of Ruhnu; the nearest airport with scheduled international flights is Tallinn, about 116 km in a straight line. Passenger trains to Pärnu have been suspended since the end of 2018, so long-distance buses are the main link with Tallinn and Tartu; the planned Rail Baltica line will pass through Pärnu. In town, walking, cycling and buses are the main options, and the old town and seafront are within walking distance.",
    culture:
      "Estonian is spoken and English is widespread. Pärnu has a long seaside spa tradition, and the Mud Baths building is one of its landmarks. Summer brings music festivals and beach events, while winter is much quieter. The tourism board says a tip of around 10% is usual for excellent service.",
    seeAndDo:
      "Pärnu Beach and the beach park; the Red Tower; Tallinn Gate and the remains of the town walls; the former Mud Baths; the jetties at the mouth of the Pärnu River; and trips from Pärnu to Soomaa National Park for its bogs and \"fifth season\" floods.",
    whenAndTips:
      "June to August is beach season, and accommodation is tight at weekends; May and September are quieter and cool; winter is windy by the sea. The bay is shallow and warms quickly, making summer swimming suitable for families.",
  },
  kuressaare: {
    // 全七段 sources: 同中文侧。Kuressaare town 12,729, Saaremaa Parish 29,869 on 1 Jan 2026 (Statistics Estonia RV0240; the parish's own register figure 31,506 is a different caliber); town part of Saaremaa Parish since 2017, seat of Saare County and the parish (saaremaavald.ee); URE year-round flights to Tallinn ~40 min (airport.ee); Virtsu–Kuivastu ~27 min (praamid.ee); episcopal castle 14th century, now Saaremaa Museum (visitestonia); Kaali crater ~17 km NE in a straight line by coordinates (earlier draft said 19 km). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；卡利陨石坑距离 19→17 km（按坐标），其余 ok）。
    identity:
      "Kuressaare is the main town on the south coast of Saaremaa and the seat of Saare County, with a population of about 12,700 in the town and about 29,900 in Saaremaa Parish on 1 January 2026 (Statistics Estonia). The town keeps a castle built by the bishops in the 14th century, now home to the Saaremaa Museum; outside the town are natural sights of the island such as Kaali crater and Panga Cliff.",
    howItWorks:
      "Kuressaare is no longer a separate local government: after the 2017 reform it merged with the rural areas of Saaremaa into Saaremaa Parish, and the town is the seat of the parish and the county. At the start of 2026 the town itself had about 12,700 people and the whole of Saaremaa Parish about 29,900. The centre is the square around the town hall and the streets leading to the castle, while the castle and moat park lie by the sea at the southern edge of town. When locals say \"going to town\" they mean Kuressaare, where most public services for the island's villages are concentrated. Daily range is shaped by island transport: reaching the mainland means a flight or a ferry, and in strong winter winds both can be disrupted. The most common misunderstanding for newcomers is that Saaremaa is small enough to see in a day — the island covers about 2,673 km², its sights are scattered, and it needs a car or several days.",
    layout:
      "The town centre is around Town Hall Square, with the episcopal castle and castle park to the south, right beside the bay; the airport is south-east of town, about 3 km in a straight line from the centre; Kaali crater is about 17 km north-east of town in a straight line, Panga Cliff is on the island's north coast, and the ferry harbour for the mainland is on Muhu, east of Saaremaa.",
    gettingAround:
      "Kuressaare Airport has scheduled domestic flights to Tallinn all year round, with a flight time of about 40 minutes. Alternatively, take the ferry from Virtsu on the mainland to Kuivastu on Muhu, about 27 minutes, and drive across Muhu onto Saaremaa. There are buses on the island, but services are infrequent, so a car or a rented bicycle is more convenient.",
    culture:
      "Estonian is spoken, and English is widely used when summer visitors are around. Saaremaa's windmills, stone walls, farmhouses and juniper meadows are part of the traditional rural landscape; smoked fish and rye bread are common local foods. The tourism board says a tip of around 10% is usual for excellent service.",
    seeAndDo:
      "Kuressaare Episcopal Castle and the Saaremaa Museum; the castle park and seafront; Kaali crater; Panga Cliff; rural landscapes such as the Angla windmills; and a drive around the island to see the coast of the West Estonian Archipelago.",
    whenAndTips:
      "June to August is the most pleasant and the busiest time for ferries, so book a place for your car if crossing on a weekend; May and September are quieter; in winter strong winds can delay ferries and flights. Distances on the island are long, and petrol stations and shops are concentrated in town.",
  },
  haapsalu: {
    // 全七段 sources: 同中文侧。Population 13,033 (municipality) / 9,338 (town proper) on 1 Jan 2026 (Statistics Estonia RV0240); seat of Lääne County; episcopal castle begun 13th century, centre of power until late 17th century, now a museum; first mud-cure establishment opened 1825 by Dr Carl Abraham Hunnius (visitestonia); railway currently ends at Turba, extension to Haapsalu designed but unfunded as of 2026-01-30 (ERR). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；全部 ok）。
    identity:
      "Haapsalu is a small town on Estonia's west coast and the seat of Lääne County, with a population of about 13,000 in the city municipality on 1 January 2026 (Statistics Estonia). It sits on a peninsula between shallow bays, with an episcopal castle begun in the 13th century; the first mud-cure establishment opened here in 1825, and the town has been a seaside resort ever since.",
    howItWorks:
      "Haapsalu is run by an elected council, and after the 2017 reform its territory grew, and at the start of 2026 the municipality had about 13,000 people, of whom about 9,300 lived in the town itself. The centre is the episcopal castle and the old streets around it; the castle was the seat of power in the area until the end of the 17th century. Locals find their way by the castle, the seaside promenade and the old railway station. Daily range is small: the town can be walked end to end, and the bay surrounds the peninsula on three sides. The most common misunderstanding for newcomers is that trains run all the way here — the railway currently ends at Turba, and the extension to Haapsalu has been designed but, as of early 2026, has no funding.",
    layout:
      "The town lies on a peninsula reaching into shallow bays: the episcopal castle and old streets are in the centre, the Kuursaal and seaside promenade from the resort era are on the northern shore, and the old railway station, now a railway museum, is to the south; the town is surrounded by water on three sides, and the bays are shallow and full of reeds.",
    gettingAround:
      "Haapsalu has no airport with scheduled flights; the nearest with international flights is Tallinn, about 90 km in a straight line. Long-distance buses are the main link with Tallinn, as trains currently run only as far as Turba. Ferries to the island of Vormsi leave from nearby Rohuküla. The town is small enough for walking and cycling.",
    culture:
      "Estonian is spoken. Seaside cures and mud treatments are Haapsalu's tradition, and the wooden houses of the old town and the seaside promenade keep the atmosphere of the resort era. In summer the castle hosts music and cultural events. The tourism board says a tip of around 10% is usual for excellent service.",
    seeAndDo:
      "Haapsalu Episcopal Castle and museum; the seaside promenade and Kuursaal; the old railway station and railway museum; the wooden-house streets of the old town; and birdwatching in nearby Matsalu National Park.",
    whenAndTips:
      "June to August is the most pleasant, with the most events; spring and autumn are good for migrating birds at Matsalu; winter winds off the sea are cold. The bay is shallow, so the water warms quickly in summer.",
  },
  viljandi: {
    // 全七段 sources: 同中文侧。Population 17,000 on 1 Jan 2026 (Statistics Estonia RV0240); seat of Viljandi County; not merged in 2017, surrounded by Viljandi Parish; Order castle begun 1224, park since early 20th century, suspension bridge 1931 (visitestonia); Estonian Traditional Music Centre in new building on Castle Hill since 2008; Viljandi Folk Music Festival in late July (folk.ee); UT Viljandi Culture Academy (viljandi.ut.ee). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；全部 ok）。
    identity:
      "Viljandi is a small town in southern Estonia and the seat of Viljandi County, with a population of about 17,000 on 1 January 2026 (Statistics Estonia). It stands on the edge of an ancient valley in the Sakala Upland, and on its Castle Hill are the ruins of an Order castle begun in 1224, looking down on Lake Viljandi in the valley floor; each year in late July the town hosts the Viljandi Folk Music Festival.",
    howItWorks:
      "Viljandi is run by an elected council, and in the 2017 reform it did not merge with its neighbours, so the city is surrounded by a separate local government, Viljandi Parish. The centre is the Castle Hill and old town area: the Order castle ruins, the Estonian Traditional Music Centre and the old streets are all within walking distance. Locals find their way by the Castle Hill, the lake and the old town. Daily range is small, and cultural life revolves around the Traditional Music Centre and the University of Tartu Viljandi Culture Academy. The most common misunderstanding for newcomers is to treat Viljandi Parish and the city of Viljandi as the same place — the city is an independent local government surrounded by the parish.",
    layout:
      "The old town sits high on the edge of the ancient valley, with the Castle Hill on its southern side, where a suspension bridge links two parts of the hill; below the Castle Hill is Lake Viljandi, with lakeside paths and a beach; the railway station is north of the old town.",
    gettingAround:
      "Viljandi has no airport with scheduled flights; the nearest with international flights is Tallinn, about 125 km in a straight line, while Tartu Airport is about 64 km away but flies only to Helsinki. Elron trains and long-distance buses run from Tallinn. The town is small enough to walk.",
    culture:
      "Estonian is spoken. Viljandi is an important centre of Estonian traditional music, with performances at the Traditional Music Centre throughout the year, and the town fills with visitors during the folk music festival. The tourism board says a tip of around 10% is usual for excellent service.",
    seeAndDo:
      "The Order castle ruins and suspension bridge; the Estonian Traditional Music Centre; Lake Viljandi and its lakeside path; the old town streets; and trips from Viljandi to Soomaa National Park.",
    whenAndTips:
      "June to August is the most pleasant, and accommodation is tight during the folk music festival in late July; the trees on the Castle Hill change colour in autumn; winter is cold. The slopes between the Castle Hill and the lake are steep, so wear comfortable shoes.",
  },
  rakvere: {
    // 全七段 sources: 同中文侧。Population 15,345 on 1 Jan 2026 (Statistics Estonia RV0240); seat of Lääne-Viru County; Rakvere city and Rakvere Parish are separate local governments; stone castle on Vallimägi begun under Danish rule in the mid-13th century, passed to the Livonian Order in 1347, now an interactive museum (visitestonia); aurochs statue "Tarvas" on the hill; Elron trains (visitestonia). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；「没有机场」改为没有定期航班机场，其余 ok）。
    identity:
      "Rakvere is a small town in northern Estonia and the seat of Lääne-Viru County, with a population of about 15,300 on 1 January 2026 (Statistics Estonia). On the castle hill at the edge of town stand the ruins of a medieval castle, now an interactive castle museum, together with a huge bronze statue of an aurochs.",
    howItWorks:
      "Rakvere is run by an elected council, and it is surrounded by a separate local government, Rakvere Parish — the same name but a different administrative unit. The centre is the old streets and central square at the foot of the castle hill, where county offices, the theatre and shops are concentrated. Locals find their way by the castle hill and the old town. Daily range is small and the town can be walked end to end; it is also a gateway town for Lahemaa National Park and the Pandivere Upland. The most common misunderstanding for newcomers is to confuse Rakvere city with Rakvere Parish — for addresses and public services, check which one is meant.",
    layout:
      "The castle hill is on the western side of the centre, with the castle ruins and the aurochs statue on top and the old streets and town centre below; the railway and bus stations are at the edge of town; to the north runs the road towards Lahemaa National Park.",
    gettingAround:
      "Rakvere has no airport with scheduled flights; the nearest with international flights is Tallinn, about 87 km in a straight line. Elron trains and long-distance buses link it with Tallinn. The town is small enough to walk; reaching the Lahemaa coast requires a car or a tour.",
    culture:
      "Estonian is spoken. The castle museum presents medieval life in an interactive way, with costumed events and festivities often held in summer. Rakvere Theatre is a regional cultural centre. The tourism board says a tip of around 10% is usual for excellent service.",
    seeAndDo:
      "Rakvere Castle and its castle museum; the aurochs statue on the castle hill; the old streets and central square; and trips from Rakvere to the boulder-strewn coast and manor houses of Lahemaa National Park.",
    whenAndTips:
      "June to August is the most pleasant, with the most castle events; winter is cold. The castle hill slopes are short but steep and slippery in the rain.",
  },
  otepaa: {
    // 全七段 sources: 同中文侧。Otepää Parish 6,125 and Otepää town 2,052 on 1 Jan 2026 (Statistics Estonia RV0240); Otepää is a rural municipality, not a county seat (Valga County's seat is Valga); "winter capital" a ceremonial title handed over each December (ERR); Tehvandi Sports Centre ski jump and cross-country trails, FIS World Cup venue (fis-ski.com); Lake Pühajärv (visitestonia); Otepää Nature Park protected since 1957 (kaitsealad.ee). 核实 2026-09-13 当批（content-verifier 独立检索，人口经统计局 API 直查；「没有机场」改为没有定期航班机场，其余 ok）。
    identity:
      "Otepää is a small town on the Otepää Upland in south-eastern Estonia, with about 2,050 people in the town and about 6,130 in Otepää Parish on 1 January 2026 (Statistics Estonia). It is Estonia's winter sports centre: the Tehvandi Sports Centre has a ski jump and cross-country ski trails, and each December the town takes over the ceremonial title of \"winter capital\"; Lake Pühajärv and the hills outside town are places for summer hiking and swimming.",
    howItWorks:
      "The town of Otepää belongs to Otepää Parish, run by the parish council, with the town as the parish seat; it is not a county seat — the seat of Valga County is Valga. At the start of 2026 the town itself had about 2,050 people and the whole parish about 6,130. The town centre is around the church and square, the castle hill is at the edge of town, and the Tehvandi Sports Centre is to the south. Locals find their way by the castle hill, Lake Pühajärv and Tehvandi. Daily life changes with the seasons: in winter skiers and race spectators pour in, and in summer it is a lakeside holiday area. The most common misunderstanding for newcomers is that \"winter capital\" means a city — it is a town of just over two thousand people, and accommodation and services are very tight in high season.",
    layout:
      "The town sits among the hills in the middle of the Otepää Upland: the church and square are in the centre, the castle hill is at the edge of town, the Tehvandi Sports Centre is on the slopes to the south, and Lake Pühajärv lies to the south-west with paths and a beach on its shore; all around are the hills, lakes and forests of Otepää Nature Park.",
    gettingAround:
      "Otepää has no airport with scheduled flights; Tartu Airport is about 30 km in a straight line but flies only to Helsinki, and other routes go through Tallinn. Long-distance buses from Tartu take around an hour; from the Tallinn direction you usually change in Tartu, so driving is more convenient. The town can be walked, and a bicycle is handy for the lakes and trails.",
    culture:
      "Estonian is spoken. Cross-country skiing is at the heart of life in Otepää in winter, and the town is buzzing on race weekends; in summer the focus shifts to lakeside holidays and hiking. The tourism board says a tip of around 10% is usual for excellent service.",
    seeAndDo:
      "The Tehvandi Sports Centre and its ski jump viewpoint; Lake Pühajärv and its lakeside path; Otepää castle hill; hiking in the hill-and-lake country of Otepää Nature Park; and cross-country skiing in winter.",
    whenAndTips:
      "December to March is ski season, and accommodation is tight on race weekends; June to August is good for lakeside holidays and hiking; spring and autumn are quiet. Hill roads ice over in winter, so drivers need winter tyres.",
  },
  kardla: {
    // 全七段 sources: 同中文侧（Statistics Estonia RV0240 2026-01-01, tier 1; vald.hiiumaa.ee, tier 1; Local Government Organisation Act; airport.ee and praamid.ee, tier 1; Estonian Geological Survey crater story map, tier 1; Transport Administration lighthouse pages, tier 1; UNESCO MAB, tier 1; distances computed）。 核实 2026-09-16 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Kärdla is the town on Hiiumaa, Estonia's second-largest island, and the seat of Hiiu County; on 1 January 2026 the town itself had about 2,900 people and Hiiumaa Parish, which covers the whole island, about 8,300 (Statistics Estonia). The town grew up around a 19th-century cloth mill, and beneath it lies a meteorite crater about 4 km across, formed some 455 million years ago but buried under sedimentary rock, so no crater shape is visible on the ground.",
    howItWorks:
      "Kärdla has no town government of its own: since 2017 the whole island has been a single parish, Hiiumaa, governed by an elected parish council that appoints the parish mayor, with Kärdla as the seat of the parish and the county. The parish is divided into five sub-parishes, Kärdla among them, each with a council representing its residents. The centre is around the central square, with the parish offices, shops and church within a few hundred metres, and the small harbour and seafront to the north. Locals say 'going to town' and mean Kärdla, where most of the island's schools, health care and offices are. Daily life is shaped by the island: reaching the mainland means flying to Tallinn or driving to the east coast for the ferry. Newcomers often expect to see the crater, when it is buried underground and what you can see is the model in town and the museum's explanation; they also underestimate the island, whose Kõpu lighthouse in the far west is more than 30 km from town in a straight line.",
    layout:
      "The town lies on Hiiumaa's north coast, with the central square and parish offices in the middle, the church north of the square and the harbour and seafront further north on the shore. Heltermaa on the island's east coast is the ferry port, and the airport is about 5 km east of town. About 14 km north-west along the coast is Tahkuna lighthouse, and Kõpu lighthouse stands on the Kõpu peninsula in the west of the island.",
    gettingAround:
      "Kärdla Airport (KDL), about 5 km from the centre in a straight line, has scheduled domestic flights to Tallinn operated by NyxAir under a state contract. By sea, take the ferry from Rohuküla on the mainland to Heltermaa on the island's east coast, about 1 hour 15 minutes, then drive to Kärdla. There is no railway on the island and buses are infrequent, so driving or cycling is easier.",
    culture:
      "Estonian is spoken, with English usable in tourism in summer. The Long House of the Hiiumaa Museum was the cloth mill's management building and tells the story of the town and the mill. The whole West Estonian Archipelago was designated a UNESCO biosphere reserve in 1990, and the island's coastal meadows, juniper woods and stone walls are part of its traditional rural landscape.",
    seeAndDo:
      "The central square and the Hiiumaa Museum's Long House; the harbour and seafront; learning about the buried Kärdla crater; the cast-iron Tahkuna lighthouse at the northern tip; Kõpu lighthouse in the west; and cycling the coast and juniper woods.",
    whenAndTips:
      "June–August is the most comfortable, with the longest days; winter is windy and both flights and ferries can change with the weather, so check the operators' notices. Ferry car spaces are tight on summer weekends, so book ahead.",
  },
  voru: {
    // 全七段 sources: 同中文侧（Statistics Estonia RV0240 2026-01-01, tier 1; Estonian Encyclopaedia, tier 2; Vana-Võrumaa museum, tier 1; tartu.ee on TAY, tier 1; distances computed）。 核实 2026-09-16 当批（content-verifier 独立检索，本条全部 ok）。
    identity:
      "Võru is the seat of Võru County in south-eastern Estonia, built on the north shore of Lake Tamula, with about 11,800 people in the town on 1 January 2026 (Statistics Estonia). It is a county town laid out to a plan at the end of the 18th century, its old town a neat grid of streets; the writer Friedrich Reinhold Kreutzwald practised medicine here for more than forty years and compiled the Estonian epic Kalevipoeg.",
    howItWorks:
      "Two local governments with the same name sit in one town: the town of Võru is governed by an elected town council that appoints the mayor and covers only the town, while Võru Parish around it is a separate local government of about 10,000 people whose offices are also in town, as are the county's institutions. The town was made a county seat in 1784 and planned on paper the following year, and the old town is still a regular grid, with the central square and St Catherine's Church in the middle and Lake Tamula to the south-west, its shore lined with a park, bathing area and paths. Locals divide the town into the centre, the industrial Võrusoo to the north and the largely wooded Kubija to the south. Daily life runs on the roads: there are no passenger trains, so trips to Tartu or Tallinn are by bus or car, and south of town lie the hills and lakes of the Haanja Upland. Newcomers often assume a southern county seat must have trains, when Võru has had no regular passenger trains since 2001; they also tend to count the town and the parish as one population.",
    layout:
      "The old town sits on the north shore of Lake Tamula, its grid of streets around the central square, with St Catherine's Church beside the square and the Kreutzwald Memorial Museum a few hundred metres south of it; along the lake are Kreutzwald Park and a lakeside path, with a footbridge out to Rose Island. Võrusoo's industrial area lies to the north, the woods of Kubija to the south, and the hills of the Haanja Upland beyond.",
    gettingAround:
      "There is no airport with scheduled flights here; the nearest, Tartu (TAY), about 54 km away in a straight line, flies only to Helsinki, and other flights go through Tallinn. As of September 2026 Võru has no passenger trains, so travel to Tartu or Tallinn by bus or car. The town is walkable, while the Haanja Upland and the surrounding lakes need a car.",
    culture:
      "Estonian is spoken, with English usable among younger people. The Kreutzwald Memorial Museum is his former home in Võru and shows the life of the doctor-writer and the making of the epic. In summer the bathing area and lakeside path on Lake Tamula are where locals spend warm days.",
    seeAndDo:
      "The Kreutzwald Memorial Museum; the central square and St Catherine's Church of 1793; the Lake Tamula shore path and Rose Island; the Võru County Museum; and a drive south into the hills, lakes and observation towers of the Haanja Upland.",
    whenAndTips:
      "June–September is the most comfortable, with swimming in the lake; winters are cold and the days short. There is no train, so check bus times before you travel.",
  },

  toila: {
    // 全七段 sources: 同中文侧（Statistics Estonia RV0240 at 1 January 2026, tier 1; Ministry of Regional Affairs and Agriculture on the 2025 merger of Toila into Jõhvi — the first municipal merger since the 2017 reform, tier 1; Jõhvi municipality on the service centres, tier 1; Oru Park history tier 2; waterfall and klint figures reused from this library's terrain entries）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧）。
    identity:
      "Toila lies on Estonia's north-eastern coast around the mouth of the Pühajõgi, a summer resort that grew with the railway in the late 19th century. The coast to its west carries the highest stretch of the North Estonian klint, about 55 m at Ontika, and the Valaste waterfall is some 10 km away in a straight line, its drop varying with the flow. Beside the town is Oru Park, a protected landscape.",
    howItWorks:
      "Start with what has already changed: the municipality of Toila no longer exists. A government decree in 2025 merged Toila with Jõhvi into a new Jõhvi municipality, effective after that year's local elections — according to the ministry responsible, the first municipal merger in Estonia since the 2017 reform. The statistics show it: Toila municipality has no figures in the January 2026 release, while Jõhvi rose from about 12,000 to about 16,000 in the same period. So the answer to who runs Toila today is Jõhvi municipality, with its offices in Jõhvi and a service centre left in Toila handling residence registration, civil registry matters, nurseries and schools; counties have not been a tier of government since 2018 and serve as statistical and regional units. The town itself is a small stretch along the river and the shore, with the park, the spa and the harbour all in it. What sets this place apart is the coast to the west: the North Estonian klint is at its highest at Ontika, and both the waterfall and the cliff-top paths are along that stretch. Newcomers working from older material go looking for a Toila municipal office, and that address no longer has a government behind it.",
    layout:
      "The centre is around the mouth of the Pühajõgi, with Oru Park along the right bank about 1 km away and the marina about 1 km to the north-east. The Valaste waterfall is about 10 km west in a straight line, and the Ontika klint about 14 km west, with the Saka stretch of the same cliff further west again.",
    gettingAround:
      "Toila has no airport with scheduled flights; the nearest with them is Tallinn, about 152 km away in a straight line. The nearest railway station is at Jõhvi, about 9 km from town in a straight line, and getting around town or out to the cliffs means a car or a bus. The climate is maritime-continental, with cold snowy winters and cool summers.",
    culture:
      "Estonian is spoken here. The town has been a summer resort since the late 19th century, and its park and spa tradition go back to that. Tipping in restaurants is not compulsory, with around ten per cent usual for exceptional service. Tap water is safe to drink. The supply is 230 V with two-round-pin continental sockets.",
    seeAndDo:
      "The paths and river valley in Oru Park; the Valaste waterfall and the stairway below the cliff (check on-site notices for the state of the facilities); the klint at Ontika; a stretch of the cliff-top woodland path; and the sea from around the harbour in summer.",
    whenAndTips:
      "June–August is the most comfortable, with long days; in winter the cliff paths ice over. The waterfall's flow varies a lot with the season, with the most water during the spring melt; keep back from the cliff edge where there is no railing.",
  },

  vosu: {
    // 全七段 sources: 同中文侧（Statistics Estonia RV0240 at 1 January 2026, tier 1; haljala.ee on the municipality's area, settlements and share within the national park, tier 1; Environmental Board / kaitsealad.ee on Lahemaa's 1971 designation and 74,784 ha across three municipalities, tier 1; Käsmu boulders reused from this library's lahemaa-coast entry）。 核实 2026-09-16 当批。 核实 2026-09-16 当批（同中文侧）。
    identity:
      "Võsu sits on Estonia's north coast inside Lahemaa National Park, one of the two small towns of Haljala municipality, whose population was 3,909 at the start of 2026 (Statistics Estonia). The park, designated in 1971, is the country's oldest and largest at 74,784 hectares — about 48,000 on land and 27,000 at sea — and spans three municipalities; both the beach at Võsu and the Käsmu peninsula to its west lie within it.",
    howItWorks:
      "Who runs this place and where people actually are come apart into three points. Administratively Võsu belongs to Haljala municipality — 550 km², two small towns and more than seventy villages, with the municipal offices at Haljala rather than Võsu; counties have not been a tier of government since 2018. In conservation terms about four tenths of the municipality lies inside Lahemaa National Park, whose rules are set by the environmental authorities, while the park's visitor centre is in yet another village, Palmse, run by the state forest management centre. And the place visitors actually gather is the beach at Võsu. The park itself spans three municipalities, so a good many \"Lahemaa sights\" are not in this one — worth keeping straight when planning. The coast here was shaped by ice: the Käsmu peninsula is strewn with boulders, most carried here by glaciers around 12,500 years ago. Newcomers treat a national park as a gated attraction, when this one is a large protected area with villages and farmland inside it.",
    layout:
      "The town spreads along its bay, with the beach immediately north. Käsmu village is about 4.5 km north-west on its peninsula, with the boulder field just north of the village. Palmse Manor and the park visitor centre are about 7 km south, Sagadi Manor and its forest museum about 8.4 km south-east, and the fishing village of Altja about 9 km east.",
    gettingAround:
      "Võsu has no airport with scheduled flights; the nearest with them is Tallinn, about 66 km away in a straight line. Getting here and moving around the park is mostly by car, with intercity buses passing through; villages within the park are well apart, so allow driving time when planning a day. The climate is maritime-continental, with cold snowy winters and cool summers.",
    culture:
      "Estonian is spoken here. Käsmu was known as the captains' village, with a ship's master or mate in almost every house. Tipping in restaurants is not compulsory, with around ten per cent usual for exceptional service. Tap water is safe to drink. The supply is 230 V with two-round-pin continental sockets.",
    seeAndDo:
      "The beach at Võsu; the Käsmu peninsula and the boulder field north of the village; Palmse Manor and the park visitor centre; Sagadi Manor and its forest museum; the net sheds of the fishing village at Altja; and the forest paths through the park.",
    whenAndTips:
      "June–August is the most comfortable and the busiest by the sea; outside that season many privately run museums and manors keep shorter hours, so check first. Phone coverage is patchy in places within the park, so read the trail markings before heading into the forest.",
  },
};
