import type { TerrainLesson } from "@/types/terrain";

export const TERRAIN_EN: Record<string, TerrainLesson> = {
  "namib-desert": {
    // sources: 见 terrain.zh.ts 同条目注释（中英同源，数字逐项对齐；check:zhen 比对同单位数字）
    seeing:
      "The Namib is a coastal desert running along the south-western edge of Africa, with its main body inside Namibia. Its aridity is produced by the South Atlantic subtropical high and amplified by cold upwelling in the Benguela Current: a hot desert pressed directly against a cold ocean surface, a combination that is uncommon worldwide. According to planning documents submitted with the UNESCO nomination, the desert-and-coast protected belt along the Namibian coastline runs about 1,570 km, and its inland width ranges from about 25 km at the narrowest to about 180 km at the widest.",
    formation:
      "The origin of the aridity is tied to the break-up of Gondwana: about 130 million years ago the Southern Ocean gateway opened, Antarctica moved towards the pole, and the Benguela Current was set going. The nomination dossier states that the sand sea and the underlying Tsondab Sandstone have not been wetter than semi-arid for roughly 130 million years, and that the modern Namib was firmly established at least 32 million years ago. The sand here is not local: it comes from exorheic river systems far inland to the south-east, relayed by three conveyor belts — river transport, a northward longshore current, and onshore wind — over a distance of more than 1,000 km.",
    observation:
      "Extreme aridity leaves almost no water vapour or dust in the air, so landform outlines are unusually sharp by day. The sand has a clear spatial colour gradient: yellowish brown near the coast, turning to a strong yellow-red further inland. A coastal fog belt often blankets the shore — the Swakopmund area records more than 100 fog days a year and about 34 mm of annual fog condensation, against only 10 to 20 mm of rainfall, which rises above 200 mm only at the foot of the Great Escarpment. The Kuiseb River is a boundary you can see with the naked eye: sand sea to its south, gravel plains to its north.",
    distinguish:
      "Compared with the inland deserts already in this library, such as the Taklamakan and the Simpson, the Namib differs fundamentally in being a cold-current coastal desert whose moisture comes from fog rather than rain. The nomination dossier offers its own comparison: the Namib is not unique in its aridity, and the Atacama has been dry since at least the Miocene. Further east, the Kalahari is grass-covered semi-fixed sand, whereas the Namib combines mobile sand with stony gravel desert.",
    concept:
      "A sand sea is not the same thing as a desert — it is only one landform unit within one, and the several dune fields inside the Namib differ in character. The most common claim attached to this desert is that it is the oldest in the world, but the nomination dossier itself writes that it is one of the oldest deserts on earth, and notes that the question of desert antiquity is continuously debated. The widely circulated figure of 55 million years of aridity does not appear once in authoritative sources, and the several dates that can actually be found each refer to a different thing, so any date has to be written together with what it measures.",
    history:
      "The geological history is described above. Stone Age remains along the Kuiseb River date back roughly 200,000 years. As for protection, the Namib Desert Park was proclaimed in 1907 and Naukluft in 1968; in 1979 the two were merged with adjoining state land into the Namib-Naukluft Park, which now covers 49,768 km². The Namib Sand Sea was inscribed on the World Heritage List in 2013 and is Namibia's only natural World Heritage property.",
  },
  "namib-sand-sea": {
    // sources: 见 terrain.zh.ts 同条目注释（含「世界最高沙丘」的 1 级反证与政府内部冲突的处理）
    seeing:
      "The Namib Sand Sea is the wind-built sand sea within the Namib Desert, inscribed on the World Heritage List in 2013 under four natural criteria and Namibia's only natural World Heritage property. The inscribed property covers 3,077,700 hectares, with a further buffer zone of 899,500 hectares; the sand sea extends nearly 300 km along the coast and about 100 km inland. Note that a separate management figure records dunes and sandy plains at about 4 million hectares, a larger area than the inscribed property — the two numbers are not the same measure.",
    formation:
      "Two generations of sand sea are stacked here: below lies the deep red, semi-consolidated Tsondab Sandstone Formation, and above it the pale yellow to cream, still unconsolidated Sossus Sand Formation. The sand arrives from river systems 1,000 km inland, relayed to the central Namib by rivers, a northward longshore current and onshore wind. Beneath the sand the bedrock is a peneplain, rising from sea level to between 800 and 1,000 m at the eastern edge of the dunes; isolated hills outcrop only in the southern half of the dune field and are conspicuously absent from the northern half. Accumulation has continued for at least 21 million years and is still going on.",
    observation:
      "Dune form is zoned by wind regime, which makes it legible from the air at a glance: the coastal belt carries crescent dunes under a single wind direction; the core of the sand sea carries linear dunes under two, parallel ridges combing away inland; and near the Great Escarpment on the eastern edge these give way to star dunes under multi-directional winds — a pyramidal body with radiating sinuous arms, where dunes stand highest and are spaced widest, some reaching 200 to 300 m. The palaeo-valley of the Tsauchab River carries no dunes along its whole length, forming a grey-white corridor through the red sand all the way to Sossusvlei.",
    distinguish:
      "The difference from the Taklamakan lies in where the sand comes from: the Taklamakan draws its sand from surrounding mountains, whereas the sand of the Namib Sand Sea comes from exorheic rivers a thousand kilometres away, enters the sea, is carried north by the longshore current, and is finally blown back onto the land — that the sand is not local is one of its most counter-intuitive features. Its relationship with the Namib Desert entry is one of containment: the sand sea is only one unit of the Namib, bounded to the north by the Kuiseb River.",
    concept:
      "Sossusvlei and Deadvlei are terminal basins of rivers, not lakes: normally they are a white crust of calcareous clay, and they hold water only in rare flood years. One claim here needs correcting specifically — that these are the highest dunes in the world. Namibia's own nomination dossier calls this a marketing claim, states plainly that the dunes are not the highest in absolute terms, tabulates taller dunes in other countries for comparison, and records that cross-regional comparisons of dune height do not appear in the geomorphological literature.",
    history:
      "The ostrich eggshell fossil record spans about 21 million years, covering the entire history of the two sand seas, and is the main material for reconstructing this sand sea's history. Radiocarbon dating of the dead camel thorn trees at Deadvlei shows that the water supply to that spot was cut off abruptly about 600 years ago. In modern times the Kuiseb River has reached the sea only twice, in 1934 and 2011. Topnaar people have lived along the Kuiseb River since ancient times and still live within the park. Protection was established in three steps, in 1907, 1968 and 1979, forming today's Namib-Naukluft Park, while the sand sea itself was inscribed on the World Heritage List in 2013.",
  },
  "skeleton-coast": {
    // sources: 见 terrain.zh.ts 同条目注释（公园口径来自 MEFT；沉船数量等 3 级说法未采用）
    seeing:
      "The Skeleton Coast is a stretch of open coast in northern Namibia. On the park definition used by the Ministry of Environment, Forestry and Tourism, it runs 500 km north from the Ugab River to the Kunene River, extends about 40 km inland, and covers 16,390 km². More than 100 lichen species and 306 bird species are recorded within the park. Its name comes from the whale and seal bones scattered along the shore.",
    formation:
      "Dense coastal fog and cold sea breezes are produced by the Benguela Current and are the dominant climatic control on this coast. The dune fields of the northern section are built by a zig-zag relay: sand is first flushed into the sea at the mouth of the Swakop River, carried north by the longshore current for more than 230 km, and comes ashore again around the mouth of the Huab, building triangular dune fields whose apex sits at the river mouth and which open out inland and to the north; when the sand reaches the next river it is returned to the sea, and so it relays northward stage by stage. The rivers involved, from south to north, are the Huab, Koigab, Unjab, Hoanib and Hoarusib.",
    observation:
      "Under its persistent fog belt, this coast is often reduced from the air to a white tongue of fog lying against the land's edge. The dry riverbeds are grey-green lines running from the interior across the desert to the Atlantic, in strong contrast with the sand and gravel on either side. The apex of each triangular dune field points at a river mouth, which is the key geometric cue for identifying the northern section. The southern section is mainly gravel plain, turning to tall dunes only north of Terrace Bay.",
    distinguish:
      "Unlike the two lagoon coasts of Walvis Bay and Sandwich Harbour, the Skeleton Coast is an open, high-energy shore with year-round heavy surf and no shelter, so it has neither tidal flats nor large flocks of waders. It also differs from the Namib Sand Sea: the sand sea's sand comes from the south and piles into enormous mobile dunes, whereas the sand of the northern Skeleton Coast is redistributed locally between rivers and the longshore current, and its mobile dunes stand under 100 m.",
    concept:
      "The word skeleton does not refer to shipwrecks — the name comes from whale and seal bones along the shore, and the wrecks are a meaning layered on afterwards. Wreck counts are a second common misconception: the widely repeated figure of more than a thousand has no verifiable source, and the responsible ministry itself writes only of a number of wrecks. The other counter-intuitive thing about a coastal desert is that with almost no rain, moisture comes mainly from fog, so biomass is concentrated in lichens and fog-tolerant plants.",
    history:
      "The geological and climatic origins are described above. The reserve was first proclaimed in 1971 and took its present form in 1973, covering 16,390 km². The Kunene River mouth at the northern end of the park is an important wetland, and this stretch also shelters desert-adapted elephant, rhino and lion.",
  },
  "central-namib-gravel-plains": {
    // sources: 见 terrain.zh.ts 同条目注释（准平原与阻沙北侵取申报文本；多罗布公园取 MEFT）
    seeing:
      "Of the Namib's three landform units, the central Namib gravel plains are the one that is neither sand sea nor coast: a grey-black gravel-covered surface spread north of the Kuiseb River, running from the coast inland to the foot of the Great Escarpment. Its essential character is that of a peneplain — a planed-off bedrock erosion surface that rises from sea level at the coast to between 800 and 1,000 m inland. Dorob National Park, on these plains, was proclaimed in 2010 and covers 7,800 km².",
    formation:
      "Gravel plains are the product of long erosion: once the bedrock has been planed off, the surface retains only a thin layer of gravel and calcrete, while the fine sand is carried away by wind and the remaining coarse gravel armours and stabilises the ground. The Kuiseb River crosses this belt, and its almost annual floods sweep the sand out of the channel, preventing the dunes to the south from crossing the river northward — which is why the river forms the northern boundary of the sand sea. Isolated rock hills are scattered across the plain.",
    observation:
      "From the air this belt reads as three colour bands: red sand sea on one side, grey-black gravel plain on the other, and a green river corridor between them. Broad lichen fields cover parts of the gravel surface and darken after fog; welwitschia plants are scattered among the stones. Around the Swakop River valley the surface is eroded into a maze of gullies known locally as the Moon Landscape.",
    distinguish:
      "The difference from the sand sea is in surface material: the sand sea is mobile sand that wind can push, while this is gravel and calcrete that wind cannot move, so the surface form stays essentially stable. It also differs from the grass-covered semi-fixed sand of the Kalahari — that is sand, this is gravel.",
    concept:
      "Stony gravel desert counts as desert too: whether a place is a desert is judged by aridity, not by whether dunes cover the ground. The surface of a gravel plain is stable, yet it lies in a hyper-arid zone where moisture comes mainly from coastal fog, which is also why lichens can grow here in continuous fields.",
    history:
      "The geological history is the erosion of this peneplain and the gravel layer resting on it. Dorob National Park was proclaimed in 2010 and covers 7,800 km²; it adjoins the Skeleton Coast to the north and Namib-Naukluft to the south, linking the protected areas along this stretch of coast into a continuous chain. The nomination dossier also records that the strong contrast between red sand and grey gravel on either side of the Kuiseb River inspired some of the earliest hand-held photographs of Earth taken from space.",
  },
  "sandwich-harbour": {
    // sources: 见 terrain.zh.ts 同条目注释（Ramsar 743 与申报文本；名字来源按红线不写）
    seeing:
      "Sandwich Harbour lies on the north-western shore of the Namib Sand Sea property and is a coastal lagoon; the nomination dossier states plainly that it is no longer a functioning harbour. It is a Ramsar Wetland of International Importance, site number 743, covering 16,500 hectares and designated on 23 August 1995. In Ramsar's own wording it is one of Namibia's most important coastal wetlands.",
    formation:
      "The lagoon sits at the palaeomouth of the Kuiseb River. Fresh water still seeps out of the old channel, creating dense reedbeds and brackish conditions along the lagoon margin, supporting large numbers of aquatic invertebrates and in turn drawing migratory birds from the Palaearctic and from Africa. The nomination dossier lists the site as a clear example of dunes, coastal lagoon and salt flats interacting and evolving together.",
    observation:
      "Its signature image is dunes standing directly at the water: the foot of the tall dune slope is the shore of the lagoon, with almost no transition between sand and water. At low tide the mud flats are broadly exposed, and flamingos are often present in large flocks — a January 2008 census recorded about 45,000 lesser flamingos and about 10,000 greater flamingos here, with waterbird numbers averaging about 75,000 and having reached 400,000.",
    distinguish:
      "Sandwich Harbour and Walvis Bay Lagoon are both lagoons and were both designated on 23 August 1995, but their mechanisms differ: Sandwich is a palaeomouth fed by freshwater seepage, so its water is brackish and reeds grow at the edge, whereas Walvis Bay is tide-dominated and immediately adjoins a city. Sandwich, by contrast, lies inside the World Heritage property with no town nearby.",
    concept:
      "A lagoon is not a lake: it connects to the ocean and rises and falls with the tide, and its salinity shifts accordingly. Coastal lagoons also have an evolutionary path that is easy to overlook — the lagoon mouth can be sealed naturally by longshore sand transport, and once it closes, exchange with the open sea stops and the character of the water body changes with it. This opening and closing is normal for a coastal lagoon, not an anomaly.",
    history:
      "The geological origin of the palaeomouth is described above. About 1,600 years ago people were already using the marine resources of this place. On 23 August 1995 it was listed as a Ramsar Wetland of International Importance, and in 2013 it was inscribed on the World Heritage List as part of the Namib Sand Sea.",
  },
  "walvis-bay-lagoon": {
    // sources: 见 terrain.zh.ts 同条目注释（Ramsar 742，1995 年口径；沙嘴成因用谨慎措辞）
    seeing:
      "Walvis Bay Lagoon is a tidal lagoon sheltered by the Pelican Point sand spit, in the Erongo Region administratively. It is a Ramsar Wetland of International Importance, site number 742, covering 12,600 hectares and designated on 23 August 1995. On the 1995 edition of the Ramsar information, waterbird numbers at this wetland range between 37,000 and 79,000, with 11 threatened bird species regularly present — figures that have not been updated for thirty years and should be read as that year's measure.",
    formation:
      "The lagoon depends on its spit, built from sand carried by the longshore current and belonging to the downstream end of the same longshore transport system that moves the Namib Sand Sea's sand from south to north. The spit encloses an open bay from the ocean, making the water inside a low-energy environment where fine sediment settles out into broad tidal flats. The Ramsar information also notes that natural silting may eventually fill the lagoon in.",
    observation:
      "From the air a slender spit reaches north and rings off a bay of still water from the ocean. The shape of the tidal flats changes with the tide, at low water the mud flats are exposed over a wide area, and sandbanks serve as night roosts for birds. Salt works stand on one side of the lagoon, and parts of the water surface run towards pink.",
    distinguish:
      "The contrast with Sandwich Harbour is what makes this pair worth reading together: this lagoon is tide-dominated and sits beside a city, while Sandwich is a palaeomouth fed by freshwater seepage and lies inside the World Heritage property. It also differs from an open, high-energy shore like the Skeleton Coast — the inside of a lagoon is sheltered by its spit and therefore low-energy, and it is precisely that shelter that produces tidal flats and flocks of waders.",
    concept:
      "What separates a lagoon from a lake is its connection to the ocean. The spit is the precondition for the lagoon: if the spit is breached by storms, or conversely silted flat, the lagoon disappears either way. A coastal lagoon is therefore a landform with a limited lifespan, and its existence depends on a balance being maintained between longshore sand supply and the tide.",
    history:
      "Both the spit and the lagoon are young landforms shaped by longshore sand transport since the Holocene, geologically far younger than the sand sea and gravel plains to the east. On 23 August 1995 the site was listed as a Ramsar Wetland of International Importance.",
  },
  brandberg: {
    // sources: 见 terrain.zh.ts 同条目注释（含 1904 年事件与本山无关的实测结论、「白夫人」的安全写法边界）
    seeing:
      "Brandberg is an almost circular granite inselberg standing on the central Namib gravel plains. Its central peak, Königstein, reaches 2,573 m above sea level and is the highest point in Namibia. The massif is nearly circular and roughly 30 km across, rises more than 1,800 m above the surrounding plains, and lies about 30 km north-west of the town of Uis.",
    formation:
      "It belongs to the Cretaceous ring complexes of the Damaraland intrusive suite, the same family as Spitzkoppe and Erongo, emplaced in several pulses about 130 million years ago, contemporary with the break-up of Gondwana and the opening of the South Atlantic. The manner of emplacement is distinctive: the magma pushed aside a block bounded by a ring fracture, so that remnants of Karoo sediments about 220 million years old are still preserved as a collar around the western and southern margins, while an 800 m wide marginal breccia within the granite records vertical movement of a few hundred metres along that fault zone.",
    observation:
      "The near-circular topographic outline is easily recognised from the air and on satellite images, and is the first cue for identifying it. The weathered granite takes on a reddish tone, and the mountain's local-language name means burning mountain. The collar of Karoo sediments reads from the air as a band of colour running right around the massif. More interesting still is the contrast with the neighbouring Messum complex of the same family: Messum is deeply weathered gabbro and reads as a shallow dark ring, while Brandberg is unweathered granite standing clear of the plain and reads as a raised pale disc — one concave, one convex, on the same satellite image.",
    distinguish:
      "Spitzkoppe, of the same family, is also granite, but it rises only 600 to 700 m above the plain as a cluster of sharp peaks, whereas Brandberg stands more than 1,800 m above it as a single plateau-like massif with its own summit climate and biological zone. The difference from Erongo lies in rock assemblage and scale: Erongo is about 35 km across, comprises both intrusive and extrusive rocks, and is ringed by a dolerite dyke.",
    concept:
      "A granite inselberg is not a volcano. The granite here is plutonic rock that cooled underground rather than a cone built up by eruption, and its near-circular outline comes from the plan shape of an intrusion controlled by a ring fracture, not from a crater. Three things let it stand isolated above the plain: the body formed at depth and was exposed only after its country rock was stripped away; the granite weathers along concentric joints formed as the magma cooled, peeling off layer by layer rather than shattering, which preserves its rounded form; and the summits of granite inselbergs in the central Namib have been measured by cosmogenic nuclides to be lowering at about 5 m per million years — five metres in a million years, which is why a Cretaceous intrusion is still here.",
    history:
      "The geological history is described above. Excavation shows dense and repeated human occupation of the higher parts of the mountain from about 5,000 years ago; the region was becoming arid at the time, and water together with rock shelter may have made this a gathering place for dispersed hunter-gatherers and herders. More than 900 rock art sites and more than 120 recorded archaeological sites are known here, including both paintings and engravings. Among them, a frieze known as the White Lady, in the Tsisab Gorge, is widely known, and its authors and meaning have long been a subject of research. The area is a gazetted national monument of more than 450 km², and was added to the UNESCO World Heritage Tentative List in 2002.",
  },
  spitzkoppe: {
    // sources: 见 terrain.zh.ts 同条目注释（GSN 单页经 Wayback 取得；绝对海拔仅 3 级，正文只写相对高差）
    seeing:
      "Spitzkoppe is a cluster of granite peaks on the Namib gravel plains, made up of Gross Spitzkoppe, Klein Spitzkoppe and the Pontok Mountains, standing 600 to 700 m above the plain as a group. The sheer granite wall of Gross Spitzkoppe draws climbers, which earned it the nickname Matterhorn of Africa.",
    formation:
      "It belongs to the same family as Brandberg and Erongo: a tectono-magmatic episode about 135 million years ago intruded granite into schists and marbles of the Damara Supergroup around 650 million years old, and into the younger Karoo sediments above them. That intrusion was preceded by an intensified phase of basaltic to rhyolitic magmatism, which left behind a dense swarm of north-north-east trending dykes. Several million years of erosion then stripped the Karoo and Damara country rock away layer by layer, carving the granite into what stands today.",
    observation:
      "The first cue for identifying it is not the mountain but the dykes: a set of dark, straight north-north-east trending ridges crosses the gravel plain and is conspicuous on aerial photographs and satellite images, and following them leads straight to this cluster of granite peaks. The three groups of peaks are spread across several kilometres of gravel plain with flat ground between them, and the rock carries the same reddish tone.",
    distinguish:
      "The difference from Brandberg is one of bulk and form: Brandberg stands more than 1,800 m above the plain as a single massif with its own summit climate zone, while this rises only 600 to 700 m as a cluster of peaks. The difference from Erongo is one of rock assemblage: Erongo combines intrusive and extrusive rocks, is about 35 km across and is ringed by a dyke, whereas Spitzkoppe is a small, purely plutonic body.",
    concept:
      "These rounded peaks were not carved by wind. Granite develops concentric joints as the magma cools and solidifies, and weathering then peels it away along those joints layer after layer, producing rounded boulders and smooth rock faces — a process known as onion-skin weathering, or exfoliation. Wind and the extreme day-night temperature range only finish the work; they are not the cause. The natural rock bridge, weathering pits and boulder fields here all come from the same mechanism.",
    history:
      "Klein Spitzkoppe is one of Namibia's well-known mineral localities: for more than a century local people have won topaz, aquamarine and green fluorite and other semi-precious stones from small workings in the pegmatites and their weathering products. The rock art site known as Bushman's Paradise, at the eastern end of the Pontok Mountains, holds national monument status. The name Pontok comes from the thatched huts built by local people — their rounded roof shape is exactly what early visitors were reminded of on seeing these hills.",
  },
  "erongo-mountains": {
    // sources: 见 terrain.zh.ts 同条目注释（法定地位：非国家公园、非国家级保护区，1 级否证；只写国家纪念地那一条）
    seeing:
      "The Erongo Mountains lie about 25 km south-west of Omaruru and form a Cretaceous granite ring complex about 35 km in diameter, rising more than 1,000 m above the deeply weathered Damara peneplain around it and walled on its eastern, southern and western sides by high granite cliffs. Its highest peak, Hohenstein, stands at about 2,319 m, although that figure so far appears only in unofficial sources.",
    formation:
      "In the Geological Survey of Namibia's description, the Erongo Mountains are the eroded core of an ancient volcano, with both peripheral and central granite intrusions. They belong with Brandberg and Spitzkoppe to the Damaraland suite, formed by events between about 137 and 124 million years ago and likewise linked to the break-up of Gondwana and the opening of the South Atlantic. The family divides into two types: Brandberg and Spitzkoppe consist mostly of plutonic rocks, while Messum and Erongo comprise an assemblage of both intrusive and extrusive rocks. The core of the complex is a layered volcanic sequence running from dark, silica-poor to pale, silica-rich rocks, later intruded in several phases by granitic to granodioritic magma, and the main body is encircled by a dolerite ring dyke up to 200 m thick.",
    observation:
      "That ring dyke, though deeply weathered, still forms a pronounced feature on aerial photographs and satellite images — from the air it reads as a dark ring about 35 km across enclosing a bright granite mass at the centre. On the south-eastern side, a bastion of Triassic conglomerate about 220 million years old presents a completely different texture from the granite cliffs. Fields of weathered granite boulders are scattered through the range.",
    distinguish:
      "The key difference from Brandberg and Spitzkoppe is the rock assemblage: those two are almost entirely plutonic, while Erongo carries both intrusive and extrusive rocks. The three also differ in form — Brandberg is a solid mass standing more than 1,800 m above the plain, Spitzkoppe is a handful of sharp peaks, and Erongo is a ring structure about 35 km in diameter.",
    concept:
      "This is a good place to understand what a ring complex is: magma rises along a ring fracture while the central block subsides, and later erosion strips away the softer extrusive rocks, leaving the resistant plutonic core and the ring dyke behind — which is why what stands out in the landscape today is a rise rather than a hollow. Two misconceptions are common: taking such a ring structure for an impact crater, or for a surviving volcanic crater. It is neither; it is the underground part of a volcano, exposed after the volcano itself was stripped away.",
    history:
      "The range is varied in mineralisation — tungsten, tin, fluorite and beryllium are the most common, with gold and uranium also present; mineral specimens such as aquamarine, schorl, smoky quartz and fluorite are prized by collectors and are worked from many small diggings, while large-scale mining was abandoned decades ago as uneconomic. Caves in the weathered granite gave rock shelter to early hunter-gatherers, who left finely detailed hunting and ceremonial scenes on the walls; three of these — Phillip's Cave, Etemba and Paula's Cave — have been declared national monuments.",
  },
  "fish-river-canyon": {
    // sources: 见 terrain.zh.ts 同条目注释（长度只写有口径的 56 km；世界第二大 / 非洲最大均不写）
    seeing:
      "The Fish River Canyon is a deeply incised canyon in southern Namibia that cuts in one stroke through the horizontal sedimentary cover and into the ancient metamorphic basement beneath. On the measure given in the Tentative List submission it is 56 km long — measured along the river course, from the first waterfall north of the northernmost viewpoint to a point opposite the Chudaub beacon. Its two halves differ markedly in form: the northern section is about 8 km wide and 160 to 190 m deep, the southern section about 5 km wide and 460 to 550 m deep.",
    formation:
      "The two sections did not form the same way. The northern section is a tectonic trough that subsided along fault lines, bounded on the west by a sharp monoclinal fold and on the east by a linear reverse fault; only the southern section is mostly the work of river incision. There is an earlier chapter as well: during the Dwyka glaciation, about 300 to 350 million years ago, south-flowing ice gouged out a valley ancestral to the Fish River, which was then filled with glacial sediments, sandstones and shales of the Karoo Supergroup. By about 130 million years ago, continental uplift following the break-up of Gondwana steepened the gradient, and the river cut down along these pre-existing lines of weakness to its present level.",
    observation:
      "The contact between the two rock packages is visible to the naked eye in the canyon walls: pale, horizontally bedded sediments above, and structurally grained metamorphic gneiss below, the two eroding in quite different patterns. Dark linear dolerite dykes about 770 million years old cut through the pale gneiss and read from the air as dark straight lines. The most telling change in the picture is the transition between the two sections — broad and shallow in the north, narrow and deep with tight meanders in the south, a shift from wide-and-shallow to narrow-and-deep that is obvious from the air in a single glance. The steeply inclined bounding faults of the southern section are clearly visible from the main lookout point as well.",
    distinguish:
      "Compared with the entrenched-meander canyons already in this library, the meanders of the Fish River Canyon formed on a low-gradient surface before the incision and were then preserved vertically as the river cut down, rather than swinging their way into hard rock on their own. Nor is it a glacial valley: ice did gouge its ancestral valley, but that valley was filled in first and only then re-incised, so the deep canyon seen today is the joint work of the river and of tectonics.",
    concept:
      "The most common misconception is that a single river cut the whole canyon over a few million years. That is not the position the authoritative descriptions take: the northern section is a tectonic trough that subsided along faults, and only the southern section is chiefly river incision; nor did the river open its own line from nothing — it followed pre-existing weaknesses, the palaeo-valley gouged by ice during the Dwyka glaciation and the fault belt. The Tentative List text also leaves one admirably honest sentence: the canyon without doubt formed in a rift valley, yet some of the faults actually indicate compressional tectonics — which is to say the structural picture here is still under discussion.",
    history:
      "The geological history is described above; the exposed metamorphic basement was metamorphosed more than a billion years ago, and the horizontal sediments above it are about 550 million years old. The canyon is a national monument, and was added to the UNESCO World Heritage Tentative List in 2002 as Fishriver Canyon. The hot springs game park it sits in was proclaimed in 1968, greatly enlarged in 1988 by the addition of the Huns Mountains, covers 4,611 km², and in August 2003 a treaty established a transfrontier park. Groundwater rising along the bounding fault belt feeds the springs: the spring in the canyon runs at 60 °C and the sulphur spring upstream at 56 °C, and the Nama name of the springs means burning water. Within the park, the Apollo 11 Cave holds animal images more than 25,000 years old; that cave lies in the Huns Mountains and is not inside the canyon itself.",
  },
};
